/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/cinematics/coldcinemaelement.c
 * Functions: 9
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_001899B0_1COldCinemaElement_QAE_XZ
 * Symbol: ??1COldCinemaElement@@QAE@XZ
 * Original: 0x001899B0 - 0x001899B1 (1 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001899B0_1COldCinemaElement_QAE_XZ(void)
{

loc_001899B0:
    esp += 4; return; /* ret */

}

/**
 * fn_001899C0_0COldCinemaElement_QAE_PADW4TWildcard_CAIVOSubscriber_PAVCAISoldier_00HMW4TBlock_0_NVCRC_4MM_Z
 * Symbol: ??0COldCinemaElement@@QAE@PADW4TWildcard@CAIVOSubscriber@@PAVCAISoldier@@00HMW4TBlock@0@_NVCRC@@4MM@Z
 * Original: 0x001899C0 - 0x001899EA (42 bytes, 16 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001899C0_0COldCinemaElement_QAE_PADW4TWildcard_CAIVOSubscriber_PAVCAISoldier_00HMW4TBlock_0_NVCRC_4MM_Z(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_001899C0:
    PUSH32(esp, ebp);
    ebp = MEM32(esp + 8);
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    edi = 0x53B054;
    esi = eax;
    ecx = 5;
    edx = 0; /* xor self */
    /* repe cmpsb - string compare, ecx iterations */
    if (1 /* strings matched (repe cmpsb) */) { sub_001899EA(); return; } /* je: equal / zero */

loc_001899D9:
    PUSH32(esp, 0x80);
    PUSH32(esp, eax);
    PUSH32(esp, ebp);
    PUSH32(esp, 0); fn_0009B7F0_strncpy(); /* call 0x0009B7F0 */

loc_001899E5:
    esp = esp + 0xC;
    g_seh_ebp = ebp; sub_001899EE(); return; /* tail jmp 0x001899EE */

}

/**
 * sub_001899EA
 * Original: 0x001899EA - 0x001899EE (4 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_001899EA(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_001899EA:
    MEM8(ebp) = 0;

}

/**
 * sub_001899EE
 * Original: 0x001899EE - 0x00189A9D (175 bytes, 44 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_001899EE(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_001899EE:
    eax = MEM32(esp + 0x14);
    ecx = MEM32(esp + 0x18);
    edx = MEM32(esp + 0x30);
    xmm0 = MEMF(esp + 0x38); /* movss */
    MEM32(ebp + 0x80) = eax;
    eax = 0; /* xor self */
    esi = ebp + 0x108;
    MEM32(ebp + 0x1A0) = eax;
    MEM32(ebp + 0x1A4) = eax;
    edi = ebp + 0x1A8;
    MEM8(edi) = LO8(eax);
    SET_LO8(eax, MEM8(esp + 0x34));
    MEM32(ebp + 0x84) = ecx;
    MEM8(esi) = 0;
    MEM32(ebp + 0x198) = edx;
    MEMF(ebp + 0x228) = xmm0; /* movss */
    xmm0 = MEMF(esp + 0x3C); /* movss */
    PUSH32(esp, 0x55E7EC);
    PUSH32(esp, ebx);
    MEM8(ebp + 0x19C) = LO8(eax);
    MEMF(ebp + 0x22C) = xmm0; /* movss */
    PUSH32(esp, 0); fn_0009B920_strstr(); /* call 0x0009B920 */

loc_00189A5C:
    esp = esp + 8;
    if (TEST_Z(eax, eax)) goto loc_00189A76; /* je: equal / zero */

loc_00189A63:
    eax = 0; /* xor self */
    if (TEST_Z(ebx, ebx)) goto loc_00189A70; /* je: equal / zero */

loc_00189A69:
    ecx = ebx;
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_00189A70:
    MEM32(ebp + 0x1A0) = eax;

loc_00189A76:
    PUSH32(esp, 0x55E7E4);
    PUSH32(esp, ebx);
    PUSH32(esp, 0); fn_0009B920_strstr(); /* call 0x0009B920 */

loc_00189A81:
    esp = esp + 8;
    if (TEST_Z(eax, eax)) { sub_00189AD7(); return; } /* je: equal / zero */

loc_00189A88:
    PUSH32(esp, 0x55E7E0);
    PUSH32(esp, ebx);
    PUSH32(esp, 0); fn_0009CD90_strcspn(); /* call 0x0009CD90 */

loc_00189A93:
    ecx = ebx;
    esp = esp + 8;
    esi = ecx + 1;
    g_seh_ebp = ebp; sub_00189AA0(); return; /* tail jmp 0x00189AA0 */

}

/**
 * sub_00189AA0
 * Original: 0x00189AA0 - 0x00189AD7 (55 bytes, 23 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00189AA0(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00189AA0:
    SET_LO8(edx, MEM8(ecx));
    ecx++;
    if (TEST_NZ(LO8(edx), LO8(edx))) goto loc_00189AA0; /* jne: not equal / not zero */

loc_00189AA7:
    ecx = ecx - esi;
    if (CMP_AE(eax, ecx)) goto loc_00189AC2; /* jae: above or equal (unsigned >=) */

loc_00189AAD:
    ecx = eax + ebx + 3;
    esi = edi;
    esi = esi - ecx;

loc_00189AB5:
    SET_LO8(edx, MEM8(ecx));
    MEM8(esi + ecx) = LO8(edx);
    ecx++;
    if (TEST_NZ(LO8(edx), LO8(edx))) goto loc_00189AB5; /* jne: not equal / not zero */

loc_00189ABF:
    MEM8(eax + ebx) = LO8(edx);

loc_00189AC2:
    eax = 0; /* xor self */
    if (TEST_Z(ebx, ebx)) goto loc_00189ACF; /* je: equal / zero */

loc_00189AC8:
    ecx = ebx;
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_00189ACF:
    MEM32(ebp + 0x1A4) = eax;
    g_seh_ebp = ebp; sub_00189AF8(); return; /* tail jmp 0x00189AF8 */

}

/**
 * sub_00189AD7
 * Original: 0x00189AD7 - 0x00189AF8 (33 bytes, 11 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00189AD7(void)
{
    int _flags = 0; /* fallback flag var */

loc_00189AD7:
    PUSH32(esp, 0x53B054);
    PUSH32(esp, ebx);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_00189AE2:
    esp = esp + 8;
    if (TEST_Z(eax, eax)) { sub_00189AF8(); return; } /* je: equal / zero */

loc_00189AE9:
    PUSH32(esp, 0x80);
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_0009B7F0_strncpy(); /* call 0x0009B7F0 */

loc_00189AF5:
    esp = esp + 0xC;

}

/**
 * sub_00189AF8
 * Original: 0x00189AF8 - 0x00189B17 (31 bytes, 10 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00189AF8(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00189AF8:
    eax = MEM32(esp + 0x1C);
    if (TEST_Z(eax, eax)) { sub_00189B17(); return; } /* je: equal / zero */

loc_00189B00:
    PUSH32(esp, 0x80);
    PUSH32(esp, eax);
    ecx = ebp + 0x88;
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_0009B7F0_strncpy(); /* call 0x0009B7F0 */

loc_00189B12:
    esp = esp + 0xC;
    g_seh_ebp = ebp; sub_00189B1E(); return; /* tail jmp 0x00189B1E */

}

/**
 * sub_00189B17
 * Original: 0x00189B17 - 0x00189B1E (7 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00189B17(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00189B17:
    MEM8(ebp + 0x88) = 0;

}

/**
 * sub_00189B1E
 * Original: 0x00189B1E - 0x00189B52 (52 bytes, 13 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00189B1E(void)
{
    uint32_t ebp;
    float xmm0;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00189B1E:
    eax = MEM32(esp + 0x28);
    edx = MEM32(esp + 0x20);
    SET_LO8(ecx, MEM8(esp + 0x2C));
    xmm0 = MEMF(esp + 0x24); /* movss */
    POP32(esp, edi);
    MEM32(ebp + 0x190) = eax;
    POP32(esp, esi);
    MEM32(ebp + 0x188) = edx;
    MEMF(ebp + 0x18C) = xmm0; /* movss */
    MEM8(ebp + 0x194) = LO8(ecx);
    eax = ebp;
    POP32(esp, ebp);
    esp += 52; return; /* ret 48 */

}
