/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: xboxfre-dec03/private/sdktools/crt/crtw32/startup/crt0.c
 * Functions: 1
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_0009F0E5_amsg_exit
 * Symbol: __amsg_exit
 * Original: 0x0009F0E5 - 0x0009F101 (28 bytes, 8 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0009F0E5_amsg_exit(void)
{

loc_0009F0E5:
    PUSH32(esp, 0); fn_000A34FD_FF_MSGBANNER(); /* call 0x000A34FD */

loc_0009F0EA:
    PUSH32(esp, MEM32(esp + 4));
    PUSH32(esp, 0); fn_000A34D1_NMSG_WRITE(); /* call 0x000A34D1 */

loc_0009F0F3:
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0xFF);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(0x57DA14), _icall_esp); /* indirect call */
    }

loc_0009F0FE:
    POP32(esp, ecx);
    POP32(esp, ecx);
    esp += 4; return; /* ret */

}
