/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/network/cnetlag.c
 * Functions: 12
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_0027B180_CNetLag_GetLagTime
 * Symbol: ?GetLagTime@CNetLag@@SAKXZ
 * Original: 0x0027B180 - 0x0027B186 (6 bytes, 2 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B180_CNetLag_GetLagTime(void)
{

loc_0027B180:
    eax = MEM32(0x57F6EC);
    esp += 4; return; /* ret */

}

/**
 * fn_0027B190_CNetLag_UpdateOGotTime
 * Symbol: ?UpdateOGotTime@CNetLag@@QAEXABVCNetTimeStamp@@@Z
 * Original: 0x0027B190 - 0x0027B19B (11 bytes, 5 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B190_CNetLag_UpdateOGotTime(void)
{

loc_0027B190:
    edx = MEM32(eax);
    MEM32(ecx + 4) = edx;
    eax = MEM32(eax);
    MEM32(ecx + 8) = eax;
    esp += 4; return; /* ret */

}

/**
 * fn_0027B1A0_CNetLag_ShouldResend
 * Symbol: ?ShouldResend@CNetLag@@QBE_NXZ
 * Original: 0x0027B1A0 - 0x0027B1A3 (3 bytes, 2 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B1A0_CNetLag_ShouldResend(void)
{

loc_0027B1A0:
    SET_LO8(eax, 1);
    esp += 4; return; /* ret */

}

/**
 * fn_0027B1B0_CNetLag_GetOGotTime
 * Symbol: ?GetOGotTime@CNetLag@@QBE?AVCNetTimeStamp@@XZ
 * Original: 0x0027B1B0 - 0x0027B1B6 (6 bytes, 3 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B1B0_CNetLag_GetOGotTime(void)
{

loc_0027B1B0:
    edx = MEM32(ecx + 4);
    MEM32(eax) = edx;
    esp += 4; return; /* ret */

}

/**
 * fn_0027B1C0_CNetLag_GetOOnTime
 * Symbol: ?GetOOnTime@CNetLag@@QBE?AVCNetTimeStamp@@XZ
 * Original: 0x0027B1C0 - 0x0027B1C6 (6 bytes, 3 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B1C0_CNetLag_GetOOnTime(void)
{

loc_0027B1C0:
    edx = MEM32(ecx + 8);
    MEM32(eax) = edx;
    esp += 4; return; /* ret */

}

/**
 * fn_0027B1D0_CNetLag_GetGotTime
 * Symbol: ?GetGotTime@CNetLag@@QBE?AVCNetTimeStamp@@XZ
 * Original: 0x0027B1D0 - 0x0027B1D5 (5 bytes, 3 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B1D0_CNetLag_GetGotTime(void)
{

loc_0027B1D0:
    edx = MEM32(ecx);
    MEM32(eax) = edx;
    esp += 4; return; /* ret */

}

/**
 * fn_0027B1E0_CNetLag_Update
 * Symbol: ?Update@CNetLag@@QAEXABVCNetCommandSet@@@Z
 * Original: 0x0027B1E0 - 0x0027B1E1 (1 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B1E0_CNetLag_Update(void)
{

loc_0027B1E0:
    esp += 4; return; /* ret */

}

/**
 * fn_0027B1F0_CNetLag_Reset
 * Symbol: ?Reset@CNetLag@@QAEXXZ
 * Original: 0x0027B1F0 - 0x0027B20C (28 bytes, 7 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B1F0_CNetLag_Reset(void)
{

loc_0027B1F0:
    ecx = 0; /* xor self */
    MEM32(eax) = ecx;
    MEM32(eax + 4) = ecx;
    MEM32(eax + 8) = ecx;
    MEM32(0x57F6EC) = 2;
    MEM8(0x57F6F0) = 1;
    esp += 4; return; /* ret */

}

/**
 * fn_0027B210_0CNetLag_QAE_XZ
 * Symbol: ??0CNetLag@@QAE@XZ
 * Original: 0x0027B210 - 0x0027B235 (37 bytes, 10 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B210_0CNetLag_QAE_XZ(void)
{

loc_0027B210:
    ecx = ecx | 0xFFFFFFFFu;
    MEM32(eax + 4) = ecx;
    MEM32(eax + 8) = ecx;
    ecx = 0; /* xor self */
    MEM32(eax) = ecx;
    MEM32(eax + 4) = ecx;
    MEM32(eax + 8) = ecx;
    MEM32(0x57F6EC) = 2;
    MEM8(0x57F6F0) = 1;
    esp += 4; return; /* ret */

}

/**
 * fn_0027B240_CNetLag_UpdateGotTime
 * Symbol: ?UpdateGotTime@CNetLag@@QAEXABVCNetTimeStamp@@@Z
 * Original: 0x0027B240 - 0x0027B26E (46 bytes, 16 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B240_CNetLag_UpdateGotTime(void)
{
    int _flags = 0; /* fallback flag var */

loc_0027B240:
    ecx = MEM32(eax);
    edx = MEM32(esi);
    if (CMP_AE(edx, ecx)) goto loc_0027B26D; /* jae: above or equal (unsigned >=) */

loc_0027B248:
    eax = ecx;
    eax = eax - edx;
    edx = ((int32_t)eax < 0) ? 0xFFFFFFFF : 0; /* cdq */
    eax = eax ^ edx;
    eax = eax - edx;
    if (CMP_NE(eax, 1)) goto loc_0027B263; /* jne: not equal / not zero */

loc_0027B256:
    MEM32(esi) = ecx;
    MEM32(0x57F6EC) = 2;
    esp += 4; return; /* ret */

loc_0027B263:
    MEM32(0x57F6EC) = 1;

loc_0027B26D:
    esp += 4; return; /* ret */

}

/**
 * fn_0027B270_CNetLag_ShouldWait
 * Symbol: ?ShouldWait@CNetLag@@QBE_NXZ
 * Original: 0x0027B270 - 0x0027B29B (43 bytes, 14 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B270_CNetLag_ShouldWait(void)
{
    int _cf = 0; /* carry flag */

loc_0027B270:
    PUSH32(esp, 0); fn_00118880_ZeroTime_GetSimTime(); /* call 0x00118880 */

loc_0027B275:
    ecx = eax;
    eax = 0x3E0F83E1;
    { uint64_t _r = (uint64_t)eax * (uint64_t)MEM32(ecx + 0x14);
      eax = (uint32_t)_r; edx = (uint32_t)(_r >> 32); }
    edx = edx >> 3;
    eax = 0xCCCCCCCDu;
    { uint64_t _r = (uint64_t)eax * (uint64_t)edx;
      eax = (uint32_t)_r; edx = (uint32_t)(_r >> 32); }
    eax = MEM32(esp + 4);
    ecx = MEM32(eax);
    edx = edx >> 3;
    (void)0; /* cmp edx, ecx - flags set for next jcc */
    SET_LO8(eax, _cf ? 0xFFFFFFFF : 0); /* sbb self (CF extend) */
    SET_LO8(eax, LO8(eax) + 1);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0027B2A0_CNetLag_GetCmdTime
 * Symbol: ?GetCmdTime@CNetLag@@QBE?AVCNetTimeStamp@@XZ
 * Original: 0x0027B2A0 - 0x0027B2C4 (36 bytes, 12 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0027B2A0_CNetLag_GetCmdTime(void)
{

loc_0027B2A0:
    PUSH32(esp, 0); fn_00118880_ZeroTime_GetSimTime(); /* call 0x00118880 */

loc_0027B2A5:
    ecx = eax;
    eax = 0x3E0F83E1;
    { uint64_t _r = (uint64_t)eax * (uint64_t)MEM32(ecx + 0x14);
      eax = (uint32_t)_r; edx = (uint32_t)(_r >> 32); }
    edx = edx >> 3;
    eax = 0xCCCCCCCDu;
    { uint64_t _r = (uint64_t)eax * (uint64_t)edx;
      eax = (uint32_t)_r; edx = (uint32_t)(_r >> 32); }
    edx = edx >> 3;
    edx = edx + 2;
    MEM32(esi) = edx;
    eax = esi;
    esp += 4; return; /* ret */

}
