/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/ui/menueffects/cbackgroundanim.c
 * Functions: 9
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

static int cmenubganim_va_is_valid(uint32_t va)
{
    return va >= 0x00010000u && va < 0x04000000u;
}

static int cmenubganim_va_range_is_valid(uint32_t va, uint32_t size)
{
    return va >= 0x00010000u && va < 0x04000000u && size <= 0x04000000u - va;
}

/**
 * fn_0019AA10_CMenuAnimation_GetSoundKeys
 * Symbol: ?GetSoundKeys@CMenuAnimation@@QAEXMMAAPBUCSoundKey@@AAH@Z
 * Original: 0x0019AA10 - 0x0019AA58 (72 bytes, 24 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0019AA10_CMenuAnimation_GetSoundKeys(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_0019AA10:
    xmm2 = MEMF(0x561490); /* movss */
    MEM32(esi) = 0;
    ecx = MEM32(edx);
    ecx = MEM32(ecx + 0xC);
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    ebp = MEM32(esp + 0xC);
    eax = 0; /* xor self */
    (void)0; /* test ecx, ecx - flags set for next jcc */
    PUSH32(esp, edi);
    xmm0 = xmm0 * xmm2; /* mulss */
    xmm1 = xmm1 * xmm2; /* mulss */
    if (CMP_LE(ecx & ecx, 0)) goto loc_0019AA51; /* jle: less or equal (signed <=) */

loc_0019AA38:
    ebx = MEM32(edx + 0xC);
    edi = ebx;
    /* nop */

loc_0019AA40:
    xmm2 = (float)(int32_t)MEM32(edi); /* cvtsi2ss */
    /* comiss xmm2, xmm0 - sets EFLAGS */
    if ((xmm2 >= xmm0)) { sub_0019AA5E(); return; } /* jae: above or equal (unsigned >=) */

loc_0019AA49:
    eax++;
    edi = edi + 0xC;
    if (CMP_L(eax, ecx)) goto loc_0019AA40; /* jl: less (signed <) */

loc_0019AA51:
    MEM32(ebp) = 0;

}

/**
 * sub_0019AA58
 * Original: 0x0019AA58 - 0x0019AA5E (6 bytes, 4 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0019AA58(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_0019AA58:
    POP32(esp, edi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp += 8; return; /* ret 4 */

}

/**
 * sub_0019AA5E
 * Original: 0x0019AA5E - 0x0019AA93 (53 bytes, 23 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0019AA5E(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_0019AA5E:
    ecx = eax + eax * 2;
    ecx = ecx << 2;
    ebx = ebx + ecx;
    MEM32(ebp) = ebx;
    edi = MEM32(edx);
    if (CMP_GE(eax, MEM32(edi + 0xC))) { sub_0019AA58(); return; } /* jge: greater or equal (signed >=) */

loc_0019AA70:
    edi = MEM32(edx + 0xC);
    xmm0 = (float)(int32_t)MEM32(edi + ecx); /* cvtsi2ss */
    /* comiss xmm0, xmm1 - sets EFLAGS */
    if ((xmm0 >= xmm1)) { sub_0019AA58(); return; } /* jae: above or equal (unsigned >=) */

loc_0019AA7D:
    ebp = MEM32(esi);
    eax++;
    ecx = ecx + 0xC;
    ebp++;
    MEM32(esi) = ebp;
    edi = MEM32(edx);
    if (CMP_L(eax, MEM32(edi + 0xC))) goto loc_0019AA70; /* jl: less (signed <) */

loc_0019AA8D:
    POP32(esp, edi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0019AAA0_CMenuAnimation_GetDurationInMs
 * Symbol: ?GetDurationInMs@CMenuAnimation@@QAEHXZ
 * Original: 0x0019AAA0 - 0x0019AAB3 (19 bytes, 5 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0019AAA0_CMenuAnimation_GetDurationInMs(void)
{
    float xmm0;

loc_0019AAA0:
    ecx = MEM32(eax);
    xmm0 = (float)(int32_t)MEM32(ecx); /* cvtsi2ss */
    xmm0 = xmm0 * MEMF(0x5D1D44); /* mulss */
    eax = (int32_t)xmm0; /* cvttss2si */
    esp += 4; return; /* ret */

}

/**
 * fn_0019AAC0_CMenuAnimation_InitEmpty
 * Symbol: ?InitEmpty@CMenuAnimation@@QAEXXZ
 * Original: 0x0019AAC0 - 0x0019AADE (30 bytes, 8 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0019AAC0_CMenuAnimation_InitEmpty(void)
{
    float xmm0;

loc_0019AAC0:
    xmm0 = 0.0f; /* xorps self = zero */
    ecx = 0; /* xor self */
    MEM32(eax) = 0x582D1C;
    MEM32(eax + 4) = 0x612ACC;
    MEM32(eax + 8) = ecx;
    MEM32(eax + 0xC) = ecx;
    MEMF(eax + 0x10) = xmm0; /* movss */
    esp += 4; return; /* ret */

}

/**
 * fn_0019AAE0_CMenuAnimation_Init
 * Symbol: ?Init@CMenuAnimation@@QAEXPAX@Z
 * Original: 0x0019AAE0 - 0x0019AB35 (85 bytes, 38 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0019AAE0_CMenuAnimation_Init(void)
{
    uint32_t ebp;
    uint32_t animation_count;
    uint32_t image_count;
    uint32_t table_size;
    int _flags = 0; /* fallback flag var */
    float xmm0;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_0019AAE0:
    xmm0 = 0.0f; /* xorps self = zero */
    animation_count = cmenubganim_va_range_is_valid(eax, 0x10) ? MEM32(eax + 4) : 0xFFFFFFFFu;
    image_count = cmenubganim_va_range_is_valid(eax, 0x10) ? MEM32(eax + 8) : 0xFFFFFFFFu;
    table_size = (animation_count <= 0x400u) ? animation_count * 0x10u : 0xFFFFFFFFu;
    if (!cmenubganim_va_range_is_valid(ecx, 0x14) ||
        !cmenubganim_va_range_is_valid(eax, 0x10) ||
        animation_count > 0x400u ||
        image_count > 0x4000u ||
        !cmenubganim_va_range_is_valid(eax + 0x10, table_size)) {
        static uint32_t invalid_animation_count = 0;
        if (invalid_animation_count < 8) {
            fprintf(stderr,
                    "[FSW/Menu] using empty menu animation object=%08X data=%08X animations=%08X images=%08X\n",
                    (unsigned)ecx,
                    (unsigned)eax,
                    (unsigned)animation_count,
                    (unsigned)image_count);
        }
        invalid_animation_count++;
        eax = ecx;
        fn_0019AAC0_CMenuAnimation_InitEmpty();
        return;
    }
    MEM32(ecx) = eax;
    PUSH32(esp, ebx);
    MEMF(ecx + 0x10) = xmm0; /* movss */
    edx = MEM32(eax + 4);
    ebx = eax + 0x10;
    eax = edx;
    eax = eax << 4;
    PUSH32(esp, edi);
    eax = eax + ebx;
    edi = 0; /* xor self */
    if (CMP_LE(edx & edx, 0)) goto loc_0019AB1E; /* jle: less or equal (signed <=) */

loc_0019AAFF:
    PUSH32(esp, ebp);
    edx = ebx + 8;
    PUSH32(esp, esi);

loc_0019AB04:
    esi = MEM32(edx);
    if (esi > 0x4000u || !cmenubganim_va_range_is_valid(eax, esi * 0x18u)) {
        static uint32_t invalid_animation_table_count = 0;
        if (invalid_animation_table_count < 8) {
            fprintf(stderr,
                    "[FSW/Menu] truncating corrupt menu animation table object=%08X data=%08X item=%u frames=%08X table=%08X\n",
                    (unsigned)ecx,
                    (unsigned)MEM32(ecx),
                    (unsigned)edi,
                    (unsigned)esi,
                    (unsigned)eax);
        }
        invalid_animation_table_count++;
        POP32(esp, esi);
        POP32(esp, ebp);
        POP32(esp, edi);
        POP32(esp, ebx);
        eax = ecx;
        fn_0019AAC0_CMenuAnimation_InitEmpty();
        return;
    }
    MEM32(edx + 4) = eax;
    esi = esi + esi * 2;
    eax = eax + esi * 8;
    esi = MEM32(ecx);
    ebp = MEM32(esi + 4);
    edi++;
    edx = edx + 0x10;
    if (CMP_L(edi, ebp)) goto loc_0019AB04; /* jl: less (signed <) */

loc_0019AB1C:
    POP32(esp, esi);
    POP32(esp, ebp);

loc_0019AB1E:
    edx = MEM32(ecx);
    edx = MEM32(edx + 8);
    edx = edx + edx * 4;
    edx = eax + edx * 4;
    POP32(esp, edi);
    MEM32(ecx + 4) = ebx;
    MEM32(ecx + 8) = eax;
    MEM32(ecx + 0xC) = edx;
    POP32(esp, ebx);
    esp += 4; return; /* ret */

}

/**
 * fn_0019AB40_CImageItem_GetData
 * Symbol: ?GetData@CImageItem@@QBEXMAAM0000@Z
 * Original: 0x0019AB40 - 0x0019ABA4 (100 bytes, 34 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0019AB40_CImageItem_GetData(void)
{
    uint32_t item = edx;
    uint32_t out0 = MEM32(esp + 4);
    uint32_t out1 = MEM32(esp + 8);
    uint32_t out2 = MEM32(esp + 0xC);
    uint32_t out3 = MEM32(esp + 0x10);
    uint32_t out4 = MEM32(esp + 0x14);
    uint32_t count;
    uint32_t table;
    float t;

    if (!cmenubganim_va_range_is_valid(item, 0x10)) {
        esp += 24; return; /* ret 20 */
    }

    count = MEM32(item + 8);
    table = MEM32(item + 0xC);
    t = MEMF(0x5F33F8) * MEMF(0x561490);
    if (!isfinite(t) || t < 0.0f) {
        t = 0.0f;
    }

#ifdef XBOXRECOMP_VULKAN_GRAPHICS
    if (getenv("FSW_TH_BG_KEYS") != NULL) {
        static uint32_t key_log_count;
        if (key_log_count < 96 && count > 0 && count <= 0x4000u &&
            cmenubganim_va_range_is_valid(table, count * 0x18u)) {
            uint32_t first = table;
            uint32_t last = table + (count - 1) * 0x18u;
            fprintf(stderr,
                    "[FSW/BG/KEYS] item=%08X crc=%08X count=%u t=%.3f first=%d %.3f %.3f %.3f %.3f %.3f last=%d %.3f %.3f %.3f %.3f %.3f\n",
                    (unsigned)item, (unsigned)MEM32(item), (unsigned)count, t,
                    (int32_t)MEM32(first), MEMF(first + 4), MEMF(first + 8),
                    MEMF(first + 0xC), MEMF(first + 0x10), MEMF(first + 0x14),
                    (int32_t)MEM32(last), MEMF(last + 4), MEMF(last + 8),
                    MEMF(last + 0xC), MEMF(last + 0x10), MEMF(last + 0x14));
            key_log_count++;
        }
    }
#endif

    if (count == 0 || count > 0x4000u || !cmenubganim_va_range_is_valid(table, count * 0x18u)) {
        if (cmenubganim_va_is_valid(out0)) MEMF(out0) = 0.0f;
        if (cmenubganim_va_is_valid(out1)) MEMF(out1) = 0.0f;
        if (cmenubganim_va_is_valid(out2)) MEMF(out2) = MEMF(0x561418);
        if (cmenubganim_va_is_valid(out3)) MEMF(out3) = MEMF(0x561418);
        if (cmenubganim_va_is_valid(out4)) MEMF(out4) = 0.0f;
        esp += 24; return; /* ret 20 */
    }

    uint32_t index = 0;
    while (index < count && (float)(int32_t)MEM32(table + index * 0x18u) < t) {
        index++;
    }

    if (index >= count) {
        index = count - 1;
    }

    if (index == 0) {
        uint32_t frame = table;
        if (cmenubganim_va_is_valid(out0)) MEMF(out0) = MEMF(frame + 4);
        if (cmenubganim_va_is_valid(out1)) MEMF(out1) = MEMF(frame + 8);
        if (cmenubganim_va_is_valid(out2)) MEMF(out2) = MEMF(frame + 0xC);
        if (cmenubganim_va_is_valid(out3)) MEMF(out3) = MEMF(frame + 0x10);
        if (cmenubganim_va_is_valid(out4)) MEMF(out4) = MEMF(frame + 0x14);
        esp += 24; return; /* ret 20 */
    }

    {
        uint32_t prev = table + (index - 1) * 0x18u;
        uint32_t next = table + index * 0x18u;
        float prev_t = (float)(int32_t)MEM32(prev);
        float next_t = (float)(int32_t)MEM32(next);
        float amount = 0.0f;
        float inv_amount;
        if (next_t > prev_t) {
            amount = (t - prev_t) / (next_t - prev_t);
        }
        if (!isfinite(amount) || amount < 0.0f) amount = 0.0f;
        if (amount > 1.0f) amount = 1.0f;
        inv_amount = 1.0f - amount;
        if (cmenubganim_va_is_valid(out0)) MEMF(out0) = MEMF(prev + 4) * inv_amount + MEMF(next + 4) * amount;
        if (cmenubganim_va_is_valid(out1)) MEMF(out1) = MEMF(prev + 8) * inv_amount + MEMF(next + 8) * amount;
        if (cmenubganim_va_is_valid(out2)) MEMF(out2) = MEMF(prev + 0xC) * inv_amount + MEMF(next + 0xC) * amount;
        if (cmenubganim_va_is_valid(out3)) MEMF(out3) = MEMF(prev + 0x10) * inv_amount + MEMF(next + 0x10) * amount;
        if (cmenubganim_va_is_valid(out4)) MEMF(out4) = MEMF(prev + 0x14) * inv_amount + MEMF(next + 0x14) * amount;
    }
    esp += 24; return; /* ret 20 */
}

/**
 * sub_0019ABA4
 * Original: 0x0019ABA4 - 0x0019ABF2 (78 bytes, 29 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0019ABA4(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_0019ABA4:
    eax = ecx + -1;
    if (TEST_S(eax, eax)) goto loc_0019ABAF; /* jl: less (signed <) */

loc_0019ABAB:
    if (CMP_NE(ecx, eax)) { sub_0019ABF2(); return; } /* jne: not equal / not zero */

loc_0019ABAF:
    esi = MEM32(esp + 0x14);
    eax = ecx + ecx * 2;
    ecx = MEM32(edx + 0xC);
    eax = eax << 3;
    ecx = MEM32(ecx + eax + 4);
    MEM32(esi) = ecx;
    ecx = MEM32(edx + 0xC);
    ecx = MEM32(ecx + eax + 8);
    esi = MEM32(esp + 0x18);
    MEM32(esi) = ecx;
    ecx = MEM32(edx + 0xC);
    ecx = MEM32(ecx + eax + 0xC);
    MEM32(ebp) = ecx;
    ecx = MEM32(edx + 0xC);
    ecx = MEM32(ecx + eax + 0x10);
    MEM32(edi) = ecx;
    edx = MEM32(edx + 0xC);
    eax = MEM32(edx + eax + 0x14);
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    MEM32(ebx) = eax;
    POP32(esp, ebx);
    esp += 24; return; /* ret 20 */

}

/**
 * sub_0019ABF2
 * Original: 0x0019ABF2 - 0x0019ACD4 (226 bytes, 57 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0019ABF2(void)
{
    uint32_t ebp;
    float xmm0, xmm1, xmm2, xmm3;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_0019ABF2:
    esi = MEM32(edx + 0xC);
    eax = eax + eax * 2;
    eax = eax << 3;
    edi = MEM32(esi + eax);
    xmm2 = MEMF(esi + eax + 4); /* movss */
    ecx = ecx + ecx * 2;
    ecx = ecx << 3;
    ebp = MEM32(esi + ecx);
    xmm3 = MEMF(esi + ecx + 4); /* movss */
    esi = MEM32(esp + 0x14);
    xmm0 = (float)(int32_t)edi; /* cvtsi2ss */
    xmm1 = xmm1 - xmm0; /* subss */
    ebp = ebp - edi;
    xmm0 = (float)(int32_t)ebp; /* cvtsi2ss */
    xmm1 = xmm1 / xmm0; /* divss */
    xmm0 = MEMF(0x561418); /* movss */
    xmm3 = xmm3 * xmm1; /* mulss */
    xmm0 = xmm0 - xmm1; /* subss */
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 + xmm3; /* addss */
    MEMF(esi) = xmm2; /* movss */
    esi = MEM32(edx + 0xC);
    xmm2 = MEMF(esi + ecx + 8); /* movss */
    xmm3 = MEMF(esi + eax + 8); /* movss */
    esi = MEM32(esp + 0x18);
    xmm2 = xmm2 * xmm1; /* mulss */
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm2 = xmm2 + xmm3; /* addss */
    MEMF(esi) = xmm2; /* movss */
    esi = MEM32(edx + 0xC);
    xmm2 = MEMF(esi + ecx + 0xC); /* movss */
    xmm3 = MEMF(esi + eax + 0xC); /* movss */
    esi = MEM32(esp + 0x1C);
    xmm2 = xmm2 * xmm1; /* mulss */
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm2 = xmm2 + xmm3; /* addss */
    MEMF(esi) = xmm2; /* movss */
    esi = MEM32(edx + 0xC);
    xmm2 = MEMF(esi + ecx + 0x10); /* movss */
    xmm3 = MEMF(esi + eax + 0x10); /* movss */
    esi = MEM32(esp + 0x20);
    xmm2 = xmm2 * xmm1; /* mulss */
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm2 = xmm2 + xmm3; /* addss */
    MEMF(esi) = xmm2; /* movss */
    edx = MEM32(edx + 0xC);
    xmm2 = MEMF(edx + ecx + 0x14); /* movss */
    POP32(esp, edi);
    xmm2 = xmm2 * xmm1; /* mulss */
    xmm1 = MEMF(edx + eax + 0x14); /* movss */
    POP32(esp, esi);
    xmm1 = xmm1 * xmm0; /* mulss */
    xmm2 = xmm2 + xmm1; /* addss */
    POP32(esp, ebp);
    MEMF(ebx) = xmm2; /* movss */
    POP32(esp, ebx);
    esp += 24; return; /* ret 20 */

}
