/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: libraries/source/zero/zerocrc.c
 * Functions: 8
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_00128D90_CalcLowerCRC
 * Symbol: ?CalcLowerCRC@@YAIPBDI@Z
 * Original: 0x00128D90 - 0x00128DCA (58 bytes, 24 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00128D90_CalcLowerCRC(void)
{
    int _flags = 0; /* fallback flag var */

loc_00128D90:
    PUSH32(esp, esi);
    esi = ecx;
    if (TEST_Z(esi, esi)) goto loc_00128DC8; /* je: equal / zero */

loc_00128D97:
    SET_LO8(ecx, MEM8(esi));
    (void)0; /* test LO8(ecx), LO8(ecx) - flags set for next jcc */
    eax = ~eax;
    edx = esi;
    if (TEST_Z(LO8(ecx), LO8(ecx))) goto loc_00128DC6; /* je: equal / zero */

loc_00128DA1:
    ecx = ZX8(LO8(ecx));
    ecx = ZX8(MEM8(ecx + 0x5CE110));
    esi = eax;
    esi = esi >> 0x18;
    ecx = ecx ^ esi;
    esi = MEM32(ecx * 4 + 0x5CDD10);
    SET_LO8(ecx, MEM8(edx + 1));
    eax = eax << 8;
    eax = eax ^ esi;
    edx++;
    if (TEST_NZ(LO8(ecx), LO8(ecx))) goto loc_00128DA1; /* jne: not equal / not zero */

loc_00128DC6:
    eax = ~eax;

loc_00128DC8:
    POP32(esp, esi);
    esp += 4; return; /* ret */

}

/**
 * fn_00128DD0_CalcCRC
 * Symbol: ?CalcCRC@@YAIPBXII@Z
 * Original: 0x00128DD0 - 0x00128DFF (47 bytes, 22 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00128DD0_CalcCRC(void)
{
    int _flags = 0; /* fallback flag var */

loc_00128DD0:
    if (TEST_Z(ecx, ecx)) goto loc_00128DFE; /* je: equal / zero */

loc_00128DD4:
    (void)0; /* test edx, edx - flags set for next jcc */
    eax = ~eax;
    if (CMP_BE(edx & edx, 0)) goto loc_00128DFC; /* jbe: below or equal (unsigned <=) */

loc_00128DDA:
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    /* nop */

loc_00128DE0:
    edi = ZX8(MEM8(ecx));
    esi = eax;
    esi = esi >> 0x18;
    esi = esi ^ edi;
    edi = MEM32(esi * 4 + 0x5CDD10);
    eax = eax << 8;
    eax = eax ^ edi;
    ecx++;
    edx--;
    if ((edx != 0)) goto loc_00128DE0; /* jne: not equal / not zero */

loc_00128DFA:
    POP32(esp, edi);
    POP32(esp, esi);

loc_00128DFC:
    eax = ~eax;

loc_00128DFE:
    esp += 4; return; /* ret */

}

/**
 * fn_00128E00_CRC_Append
 * Symbol: ?Append@CRC@@QAEXPBXH@Z
 * Original: 0x00128E00 - 0x00128E01 (1 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00128E00_CRC_Append(void)
{

loc_00128E00:
    esp += 4; return; /* ret */

}

/**
 * fn_00128E10_CRC_Append
 * Symbol: ?Append@CRC@@QAEXPBD@Z
 * Original: 0x00128E10 - 0x00128E1A (10 bytes, 4 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00128E10_CRC_Append(void)
{

loc_00128E10:
    eax = MEM32(esi);
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_00128E17:
    MEM32(esi) = eax;
    esp += 4; return; /* ret */

}

/**
 * fn_00128E20_0CRC_QAE_PBXH_Z
 * Symbol: ??0CRC@@QAE@PBXH@Z
 * Original: 0x00128E20 - 0x00128E2D (13 bytes, 8 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00128E20_0CRC_QAE_PBXH_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_00128E20:
    (void)0; /* test edx, edx - flags set for next jcc */
    PUSH32(esp, esi);
    esi = ecx;
    if (TEST_NZ(edx, edx)) { sub_00128E2D(); return; } /* jne: not equal / not zero */

loc_00128E27:
    ecx = 0; /* xor self */
    MEM32(eax) = ecx;
    POP32(esp, esi);
    esp += 4; return; /* ret */

}

/**
 * sub_00128E2D
 * Original: 0x00128E2D - 0x00128E58 (43 bytes, 21 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00128E2D(void)
{
    int _flags = 0; /* fallback flag var */

loc_00128E2D:
    ecx = ecx | 0xFFFFFFFFu;
    if (CMP_BE(esi & esi, 0)) goto loc_00128E52; /* jbe: below or equal (unsigned <=) */

loc_00128E34:
    PUSH32(esp, ebx);
    PUSH32(esp, edi);

loc_00128E36:
    ebx = ZX8(MEM8(edx));
    edi = ecx;
    edi = edi >> 0x18;
    edi = edi ^ ebx;
    ebx = MEM32(edi * 4 + 0x5CDD10);
    ecx = ecx << 8;
    ecx = ecx ^ ebx;
    edx++;
    esi--;
    if ((esi != 0)) goto loc_00128E36; /* jne: not equal / not zero */

loc_00128E50:
    POP32(esp, edi);
    POP32(esp, ebx);

loc_00128E52:
    ecx = ~ecx;
    MEM32(eax) = ecx;
    POP32(esp, esi);
    esp += 4; return; /* ret */

}

/**
 * fn_00128E60_0CRC_QAE_PBD_Z
 * Symbol: ??0CRC@@QAE@PBD@Z
 * Original: 0x00128E60 - 0x00128E69 (9 bytes, 5 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00128E60_0CRC_QAE_PBD_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_00128E60:
    if (TEST_NZ(ecx, ecx)) { sub_00128E69(); return; } /* jne: not equal / not zero */

loc_00128E64:
    MEM32(esi) = ecx;
    eax = esi;
    esp += 4; return; /* ret */

}

/**
 * sub_00128E69
 * Original: 0x00128E69 - 0x00128E75 (12 bytes, 5 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00128E69(void)
{

loc_00128E69:
    eax = 0; /* xor self */
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_00128E70:
    MEM32(esi) = eax;
    eax = esi;
    esp += 4; return; /* ret */

}
