/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: libraries/source/zero/zeromathtypes.c
 * Functions: 19
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_00052AF0_ZeroVector3_NormalizeFastest
 * Symbol: ?NormalizeFastest@ZeroVector3@@QAEAAV1@XZ
 * Original: 0x00052AF0 - 0x00052B4A (90 bytes, 26 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00052AF0_ZeroVector3_NormalizeFastest(void)
{
    float xmm0, xmm1, xmm2, xmm3, xmm4, xmm5;

loc_00052AF0:
    PUSH32(esp, ecx);
    eax = ecx;
    MEM32(esp) = eax;
    PUSH32(esp, ecx);
    ecx = MEM32(esp + 4);
    xmm0 = MEMF(ecx); /* movss */
    xmm1 = MEMF(ecx + 4); /* movss */
    xmm2 = MEMF(ecx + 8); /* movss */
    xmm3 = xmm0; /* movss */
    xmm4 = xmm1; /* movss */
    xmm5 = xmm2; /* movss */
    xmm0 = xmm0 * xmm3; /* mulss */
    xmm1 = xmm1 * xmm4; /* mulss */
    xmm2 = xmm2 * xmm5; /* mulss */
    xmm0 = xmm0 + xmm1; /* addss */
    xmm0 = xmm0 + xmm2; /* addss */
    xmm1 = 1.0f / sqrtf(xmm0); /* rsqrtss */
    xmm3 = xmm3 * xmm1; /* mulss */
    xmm4 = xmm4 * xmm1; /* mulss */
    xmm5 = xmm5 * xmm1; /* mulss */
    MEMF(ecx) = xmm3; /* movss */
    MEMF(ecx + 4) = xmm4; /* movss */
    MEMF(ecx + 8) = xmm5; /* movss */
    POP32(esp, ecx);
    POP32(esp, ecx);
    esp += 4; return; /* ret */

}

/**
 * fn_00129920_a_mod
 * Symbol: ?a_mod@@YAMMM@Z
 * Original: 0x00129920 - 0x00129939 (25 bytes, 7 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129920_a_mod(void)
{
    float xmm0;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_00129920:
    fp_push(MEMF(esp + 8)); /* fld float */
    fp_push(MEMF(esp + 4)); /* fld float */
    /* FPU: fprem1  */
    MEMF(esp + 4) = (float)fp_top(); fp_popp(); /* fstp */
    MEMF(esp + 8) = (float)fp_top(); fp_popp(); /* fstp */
    xmm0 = MEMF(esp + 4); /* movss */
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_00129940_ZeroSetFloatExceptionsMask
 * Symbol: ?ZeroSetFloatExceptionsMask@@YAII@Z
 * Original: 0x00129940 - 0x00129966 (38 bytes, 19 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129940_ZeroSetFloatExceptionsMask(void)
{
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_00129940:
    PUSH32(esp, edx);
    PUSH32(esp, ecx);
    PUSH32(esp, eax);
    /* wait - FPU sync */
    /* fnstcw word ptr [esp] - store FPU control word */
    eax = MEM32(esp);
    edx = MEM32(esp + 0x10);
    edx = ~edx;
    ecx = eax;
    edx = edx & 0x3F;
    ecx = ecx & 0xFFFFFFC0u;
    edx = edx | ecx;
    MEM32(esp) = edx;
    /* fldcw word ptr [esp] - load FPU control word */
    eax = ~eax;
    POP32(esp, edx);
    POP32(esp, ecx);
    POP32(esp, edx);
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_00129970_ZeroSetCtrlWord
 * Symbol: ?ZeroSetCtrlWord@@YAXI@Z
 * Original: 0x00129970 - 0x00129977 (7 bytes, 4 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129970_ZeroSetCtrlWord(void)
{
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_00129970:
    PUSH32(esp, ecx);
    /* fldcw word ptr [esp + 8] - load FPU control word */
    POP32(esp, ecx);
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_00129980_ZeroGetCtrlWord
 * Symbol: ?ZeroGetCtrlWord@@YAHXZ
 * Original: 0x00129980 - 0x0012998C (12 bytes, 6 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129980_ZeroGetCtrlWord(void)
{
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_00129980:
    PUSH32(esp, eax);
    /* wait - FPU sync */
    /* fnstcw word ptr [esp] - store FPU control word */
    POP32(esp, eax);
    eax = eax & 0xFFFF;
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_00129990_ZeroSetPrecision
 * Symbol: ?ZeroSetPrecision@@YAHI@Z
 * Original: 0x00129990 - 0x001299BA (42 bytes, 18 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129990_ZeroSetPrecision(void)
{
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_00129990:
    PUSH32(esp, ecx);
    PUSH32(esp, edx);
    eax = 0; /* xor self */
    PUSH32(esp, eax);
    /* wait - FPU sync */
    /* fnstcw word ptr [esp] - store FPU control word */
    edx = MEM32(esp);
    ecx = MEM32(esp + 0x10);
    eax = edx;
    ecx = ecx & 0x300;
    edx = edx & 0xFFFFFCFFu;
    ecx = ecx | edx;
    MEM32(esp) = ecx;
    /* fldcw word ptr [esp] - load FPU control word */
    POP32(esp, ecx);
    POP32(esp, edx);
    POP32(esp, ecx);
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_001299C0_ZeroSetRounding
 * Symbol: ?ZeroSetRounding@@YAHI@Z
 * Original: 0x001299C0 - 0x001299EA (42 bytes, 18 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001299C0_ZeroSetRounding(void)
{
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_001299C0:
    PUSH32(esp, ecx);
    PUSH32(esp, edx);
    eax = 0; /* xor self */
    PUSH32(esp, eax);
    /* wait - FPU sync */
    /* fnstcw word ptr [esp] - store FPU control word */
    edx = MEM32(esp);
    ecx = MEM32(esp + 0x10);
    eax = edx;
    ecx = ecx & 0xC00;
    edx = edx & 0xFFFFF3FFu;
    ecx = ecx | edx;
    MEM32(esp) = ecx;
    /* fldcw word ptr [esp] - load FPU control word */
    POP32(esp, ecx);
    POP32(esp, edx);
    POP32(esp, ecx);
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_001299F0_ZeroCpuTimeStamp
 * Symbol: ?ZeroCpuTimeStamp@@YA_JXZ
 * Original: 0x001299F0 - 0x00129A07 (23 bytes, 8 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001299F0_ZeroCpuTimeStamp(void)
{

loc_001299F0:
    esp = esp - 8;
    /* TODO: rdtsc  */
    MEM32(esp + 4) = edx;
    MEM32(esp) = eax;
    eax = MEM32(esp);
    edx = MEM32(esp + 4);
    esp = esp + 8;
    esp += 4; return; /* ret */

}

/**
 * fn_00129A10_SatisfyStickConstraint
 * Symbol: ?SatisfyStickConstraint@@YAXAAVZeroVector3@@0M@Z
 * Original: 0x00129A10 - 0x00129ADD (205 bytes, 51 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129A10_SatisfyStickConstraint(void)
{
    float xmm0, xmm1, xmm2, xmm3, xmm4, xmm5, xmm6, xmm7;

loc_00129A10:
    PUSH32(esp, edx);
    edx = MEM32(esp + 0xC);
    PUSH32(esp, ecx);
    ecx = MEM32(esp + 0xC);
    xmm3 = MEMF(edx); /* movss */
    xmm4 = MEMF(edx + 4); /* movss */
    xmm5 = MEMF(edx + 8); /* movss */
    xmm0 = MEMF(ecx); /* movss */
    xmm1 = MEMF(ecx + 4); /* movss */
    xmm2 = MEMF(ecx + 8); /* movss */
    xmm3 = xmm3 - xmm0; /* subss */
    xmm4 = xmm4 - xmm1; /* subss */
    xmm5 = xmm5 - xmm2; /* subss */
    xmm6 = xmm3; /* movss */
    xmm7 = xmm4; /* movss */
    xmm6 = xmm6 * xmm6; /* mulss */
    xmm7 = xmm7 * xmm7; /* mulss */
    xmm6 = xmm6 + xmm7; /* addss */
    xmm7 = xmm5; /* movss */
    xmm7 = xmm7 * xmm7; /* mulss */
    xmm6 = xmm6 + xmm7; /* addss */
    xmm7 = 1.0f / sqrtf(xmm6); /* rsqrtss */
    xmm6 = xmm6 * xmm7; /* mulss */
    xmm3 = xmm3 * xmm7; /* mulss */
    xmm4 = xmm4 * xmm7; /* mulss */
    xmm5 = xmm5 * xmm7; /* mulss */
    xmm7 = MEMF(esp + 0x14); /* movss */
    xmm7 = xmm7 - xmm6; /* subss */
    xmm6 = MEMF(0x561458); /* movss */
    xmm7 = xmm7 * xmm6; /* mulss */
    xmm3 = xmm3 * xmm7; /* mulss */
    xmm4 = xmm4 * xmm7; /* mulss */
    xmm5 = xmm5 * xmm7; /* mulss */
    xmm0 = xmm0 + xmm3; /* addss */
    xmm1 = xmm1 + xmm4; /* addss */
    xmm2 = xmm2 + xmm5; /* addss */
    xmm6 = MEMF(edx); /* movss */
    xmm7 = MEMF(edx + 4); /* movss */
    MEMF(ecx) = xmm0; /* movss */
    MEMF(ecx + 4) = xmm1; /* movss */
    MEMF(ecx + 8) = xmm2; /* movss */
    xmm6 = xmm6 - xmm3; /* subss */
    xmm3 = MEMF(edx + 8); /* movss */
    xmm7 = xmm7 - xmm4; /* subss */
    xmm3 = xmm3 - xmm5; /* subss */
    MEMF(edx) = xmm6; /* movss */
    MEMF(edx + 4) = xmm7; /* movss */
    MEMF(edx + 8) = xmm3; /* movss */
    POP32(esp, ecx);
    POP32(esp, edx);
    esp += 4; return; /* ret */

}

/**
 * fn_00129AE0_Zero_acos
 * Symbol: ?Zero_acos@@YAMM@Z
 * Original: 0x00129AE0 - 0x00129AF1 (17 bytes, 8 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129AE0_Zero_acos(void)
{
    uint32_t ebp;

loc_00129AE0:
    PUSH32(esp, ebp);
    ebp = esp;
    eax = MEM32(ebp + 8);
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_00022F10_acosf(); /* call 0x00022F10 */

loc_00129AEC:
    esp = esp + 4;
    POP32(esp, ebp);
    esp += 4; return; /* ret */

}

/**
 * fn_00129B00_Zero_asin
 * Symbol: ?Zero_asin@@YAMM@Z
 * Original: 0x00129B00 - 0x00129B11 (17 bytes, 8 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129B00_Zero_asin(void)
{
    uint32_t ebp;

loc_00129B00:
    PUSH32(esp, ebp);
    ebp = esp;
    eax = MEM32(ebp + 8);
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_00034DA0_asinf(); /* call 0x00034DA0 */

loc_00129B0C:
    esp = esp + 4;
    POP32(esp, ebp);
    esp += 4; return; /* ret */

}

/**
 * fn_00129B20_Zero_atan2
 * Symbol: ?Zero_atan2@@YAMMM@Z
 * Original: 0x00129B20 - 0x00129B35 (21 bytes, 10 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129B20_Zero_atan2(void)
{
    uint32_t ebp;

loc_00129B20:
    PUSH32(esp, ebp);
    ebp = esp;
    eax = MEM32(ebp + 0xC);
    PUSH32(esp, eax);
    ecx = MEM32(ebp + 8);
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_0002B000_atan2f(); /* call 0x0002B000 */

loc_00129B30:
    esp = esp + 8;
    POP32(esp, ebp);
    esp += 4; return; /* ret */

}

/**
 * fn_00129B40_GetMinMax
 * Symbol: ?GetMinMax@@YAXAAVZeroVector3@@0PBMHH@Z
 * Original: 0x00129B40 - 0x00129DC0 (640 bytes, 207 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129B40_GetMinMax(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00129B40:
    esp = esp - 0xC;
    xmm0 = MEMF(eax); /* movss */
    ecx = MEM32(esp + 0x10);
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x20);
    MEMF(esp + 0xC) = xmm0; /* movss */
    xmm0 = MEMF(eax + 4); /* movss */
    PUSH32(esp, edi);
    edi = MEM32(esp + 0x10);
    MEMF(esp + 0x14) = xmm0; /* movss */
    xmm0 = MEMF(eax + 8); /* movss */
    ebx = MEM32(esp + 0x14);
    ebp = edx;
    MEM32(ebp) = edi;
    MEM32(ebp + 4) = ebx;
    MEMF(esp + 0x18) = xmm0; /* movss */
    ebx = MEM32(esp + 0x18);
    MEM32(ebp + 8) = ebx;
    ebp = ecx;
    MEM32(ebp) = edi;
    edi = MEM32(esp + 0x14);
    MEM32(ebp + 4) = edi;
    edi = MEM32(esp + 0x28);
    esi = (uint32_t)((int32_t)esi >> 2);
    MEM32(ebp + 8) = ebx;
    esi = esi << 2;
    ebp = edi + -1;
    eax = eax + esi;
    (void)0; /* cmp ebp, 4 - flags set for next jcc */
    ebx = 1;
    if (CMP_L(ebp, 4)) goto loc_00129D4F; /* jl: less (signed <) */

loc_00129BB2:
    ebx = edi + -5;
    ebx = ebx >> 2;
    ebx++;
    ebp = ebx * 4 + 1;
    MEM32(esp + 0x24) = ebp;

loc_00129BC4:
    xmm0 = MEMF(ecx); /* movss */
    /* comiss xmm0, MEMF(eax) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax))) goto loc_00129BD1; /* jbe: below or equal (unsigned <=) */

loc_00129BCD:
    ebp = MEM32(eax);
    MEM32(ecx) = ebp;

loc_00129BD1:
    xmm0 = MEMF(ecx + 4); /* movss */
    /* comiss xmm0, MEMF(eax + 4) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax + 4))) goto loc_00129BE2; /* jbe: below or equal (unsigned <=) */

loc_00129BDC:
    ebp = MEM32(eax + 4);
    MEM32(ecx + 4) = ebp;

loc_00129BE2:
    xmm0 = MEMF(ecx + 8); /* movss */
    /* comiss xmm0, MEMF(eax + 8) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax + 8))) goto loc_00129BF3; /* jbe: below or equal (unsigned <=) */

loc_00129BED:
    ebp = MEM32(eax + 8);
    MEM32(ecx + 8) = ebp;

loc_00129BF3:
    xmm0 = MEMF(eax); /* movss */
    /* comiss xmm0, MEMF(edx) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx))) goto loc_00129C00; /* jbe: below or equal (unsigned <=) */

loc_00129BFC:
    ebp = MEM32(eax);
    MEM32(edx) = ebp;

loc_00129C00:
    xmm0 = MEMF(eax + 4); /* movss */
    /* comiss xmm0, MEMF(edx + 4) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx + 4))) goto loc_00129C11; /* jbe: below or equal (unsigned <=) */

loc_00129C0B:
    ebp = MEM32(eax + 4);
    MEM32(edx + 4) = ebp;

loc_00129C11:
    xmm0 = MEMF(eax + 8); /* movss */
    /* comiss xmm0, MEMF(edx + 8) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx + 8))) goto loc_00129C22; /* jbe: below or equal (unsigned <=) */

loc_00129C1C:
    ebp = MEM32(eax + 8);
    MEM32(edx + 8) = ebp;

loc_00129C22:
    xmm0 = MEMF(ecx); /* movss */
    eax = eax + esi;
    /* comiss xmm0, MEMF(eax) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax))) goto loc_00129C31; /* jbe: below or equal (unsigned <=) */

loc_00129C2D:
    ebp = MEM32(eax);
    MEM32(ecx) = ebp;

loc_00129C31:
    xmm0 = MEMF(ecx + 4); /* movss */
    /* comiss xmm0, MEMF(eax + 4) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax + 4))) goto loc_00129C42; /* jbe: below or equal (unsigned <=) */

loc_00129C3C:
    ebp = MEM32(eax + 4);
    MEM32(ecx + 4) = ebp;

loc_00129C42:
    xmm0 = MEMF(ecx + 8); /* movss */
    /* comiss xmm0, MEMF(eax + 8) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax + 8))) goto loc_00129C53; /* jbe: below or equal (unsigned <=) */

loc_00129C4D:
    ebp = MEM32(eax + 8);
    MEM32(ecx + 8) = ebp;

loc_00129C53:
    xmm0 = MEMF(eax); /* movss */
    /* comiss xmm0, MEMF(edx) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx))) goto loc_00129C60; /* jbe: below or equal (unsigned <=) */

loc_00129C5C:
    ebp = MEM32(eax);
    MEM32(edx) = ebp;

loc_00129C60:
    xmm0 = MEMF(eax + 4); /* movss */
    /* comiss xmm0, MEMF(edx + 4) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx + 4))) goto loc_00129C71; /* jbe: below or equal (unsigned <=) */

loc_00129C6B:
    ebp = MEM32(eax + 4);
    MEM32(edx + 4) = ebp;

loc_00129C71:
    xmm0 = MEMF(eax + 8); /* movss */
    /* comiss xmm0, MEMF(edx + 8) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx + 8))) goto loc_00129C82; /* jbe: below or equal (unsigned <=) */

loc_00129C7C:
    ebp = MEM32(eax + 8);
    MEM32(edx + 8) = ebp;

loc_00129C82:
    xmm0 = MEMF(ecx); /* movss */
    eax = eax + esi;
    /* comiss xmm0, MEMF(eax) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax))) goto loc_00129C91; /* jbe: below or equal (unsigned <=) */

loc_00129C8D:
    ebp = MEM32(eax);
    MEM32(ecx) = ebp;

loc_00129C91:
    xmm0 = MEMF(ecx + 4); /* movss */
    /* comiss xmm0, MEMF(eax + 4) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax + 4))) goto loc_00129CA2; /* jbe: below or equal (unsigned <=) */

loc_00129C9C:
    ebp = MEM32(eax + 4);
    MEM32(ecx + 4) = ebp;

loc_00129CA2:
    xmm0 = MEMF(ecx + 8); /* movss */
    /* comiss xmm0, MEMF(eax + 8) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax + 8))) goto loc_00129CB3; /* jbe: below or equal (unsigned <=) */

loc_00129CAD:
    ebp = MEM32(eax + 8);
    MEM32(ecx + 8) = ebp;

loc_00129CB3:
    xmm0 = MEMF(eax); /* movss */
    /* comiss xmm0, MEMF(edx) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx))) goto loc_00129CC0; /* jbe: below or equal (unsigned <=) */

loc_00129CBC:
    ebp = MEM32(eax);
    MEM32(edx) = ebp;

loc_00129CC0:
    xmm0 = MEMF(eax + 4); /* movss */
    /* comiss xmm0, MEMF(edx + 4) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx + 4))) goto loc_00129CD1; /* jbe: below or equal (unsigned <=) */

loc_00129CCB:
    ebp = MEM32(eax + 4);
    MEM32(edx + 4) = ebp;

loc_00129CD1:
    xmm0 = MEMF(eax + 8); /* movss */
    /* comiss xmm0, MEMF(edx + 8) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx + 8))) goto loc_00129CE2; /* jbe: below or equal (unsigned <=) */

loc_00129CDC:
    ebp = MEM32(eax + 8);
    MEM32(edx + 8) = ebp;

loc_00129CE2:
    xmm0 = MEMF(ecx); /* movss */
    eax = eax + esi;
    /* comiss xmm0, MEMF(eax) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax))) goto loc_00129CF1; /* jbe: below or equal (unsigned <=) */

loc_00129CED:
    ebp = MEM32(eax);
    MEM32(ecx) = ebp;

loc_00129CF1:
    xmm0 = MEMF(ecx + 4); /* movss */
    /* comiss xmm0, MEMF(eax + 4) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax + 4))) goto loc_00129D02; /* jbe: below or equal (unsigned <=) */

loc_00129CFC:
    ebp = MEM32(eax + 4);
    MEM32(ecx + 4) = ebp;

loc_00129D02:
    xmm0 = MEMF(ecx + 8); /* movss */
    /* comiss xmm0, MEMF(eax + 8) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax + 8))) goto loc_00129D13; /* jbe: below or equal (unsigned <=) */

loc_00129D0D:
    ebp = MEM32(eax + 8);
    MEM32(ecx + 8) = ebp;

loc_00129D13:
    xmm0 = MEMF(eax); /* movss */
    /* comiss xmm0, MEMF(edx) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx))) goto loc_00129D20; /* jbe: below or equal (unsigned <=) */

loc_00129D1C:
    ebp = MEM32(eax);
    MEM32(edx) = ebp;

loc_00129D20:
    xmm0 = MEMF(eax + 4); /* movss */
    /* comiss xmm0, MEMF(edx + 4) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx + 4))) goto loc_00129D31; /* jbe: below or equal (unsigned <=) */

loc_00129D2B:
    ebp = MEM32(eax + 4);
    MEM32(edx + 4) = ebp;

loc_00129D31:
    xmm0 = MEMF(eax + 8); /* movss */
    /* comiss xmm0, MEMF(edx + 8) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx + 8))) goto loc_00129D42; /* jbe: below or equal (unsigned <=) */

loc_00129D3C:
    ebp = MEM32(eax + 8);
    MEM32(edx + 8) = ebp;

loc_00129D42:
    eax = eax + esi;
    ebx--;
    if ((ebx != 0)) goto loc_00129BC4; /* jne: not equal / not zero */

loc_00129D4B:
    ebx = MEM32(esp + 0x24);

loc_00129D4F:
    if (CMP_GE(ebx, edi)) goto loc_00129DB8; /* jge: greater or equal (signed >=) */

loc_00129D53:
    edi = edi - ebx;

loc_00129D55:
    xmm0 = MEMF(ecx); /* movss */
    /* comiss xmm0, MEMF(eax) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax))) goto loc_00129D62; /* jbe: below or equal (unsigned <=) */

loc_00129D5E:
    ebx = MEM32(eax);
    MEM32(ecx) = ebx;

loc_00129D62:
    xmm0 = MEMF(ecx + 4); /* movss */
    /* comiss xmm0, MEMF(eax + 4) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax + 4))) goto loc_00129D73; /* jbe: below or equal (unsigned <=) */

loc_00129D6D:
    ebx = MEM32(eax + 4);
    MEM32(ecx + 4) = ebx;

loc_00129D73:
    xmm0 = MEMF(ecx + 8); /* movss */
    /* comiss xmm0, MEMF(eax + 8) - sets EFLAGS */
    if ((xmm0 <= MEMF(eax + 8))) goto loc_00129D84; /* jbe: below or equal (unsigned <=) */

loc_00129D7E:
    ebx = MEM32(eax + 8);
    MEM32(ecx + 8) = ebx;

loc_00129D84:
    xmm0 = MEMF(eax); /* movss */
    /* comiss xmm0, MEMF(edx) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx))) goto loc_00129D91; /* jbe: below or equal (unsigned <=) */

loc_00129D8D:
    ebx = MEM32(eax);
    MEM32(edx) = ebx;

loc_00129D91:
    xmm0 = MEMF(eax + 4); /* movss */
    /* comiss xmm0, MEMF(edx + 4) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx + 4))) goto loc_00129DA2; /* jbe: below or equal (unsigned <=) */

loc_00129D9C:
    ebx = MEM32(eax + 4);
    MEM32(edx + 4) = ebx;

loc_00129DA2:
    xmm0 = MEMF(eax + 8); /* movss */
    /* comiss xmm0, MEMF(edx + 8) - sets EFLAGS */
    if ((xmm0 <= MEMF(edx + 8))) goto loc_00129DB3; /* jbe: below or equal (unsigned <=) */

loc_00129DAD:
    ebx = MEM32(eax + 8);
    MEM32(edx + 8) = ebx;

loc_00129DB3:
    eax = eax + esi;
    edi--;
    if ((edi != 0)) goto loc_00129D55; /* jne: not equal / not zero */

loc_00129DB8:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp = esp + 0xC;
    esp += 4; return; /* ret */

}

/**
 * fn_00129DC0_Zero_cos
 * Symbol: ?Zero_cos@@YAMM@Z
 * Original: 0x00129DC0 - 0x00129DC7 (7 bytes, 3 insns)
 * Category: crt
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129DC0_Zero_cos(void)
{
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_00129DC0:
    fp_push(MEMF(esp + 4)); /* fld float */
    /* FPU: fcos  */
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_00129DD0_Zero_sin
 * Symbol: ?Zero_sin@@YAMM@Z
 * Original: 0x00129DD0 - 0x00129DD7 (7 bytes, 3 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129DD0_Zero_sin(void)
{
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_00129DD0:
    fp_push(MEMF(esp + 4)); /* fld float */
    /* FPU: fsin  */
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_00129DE0_CircularInterpolation
 * Symbol: ?CircularInterpolation@@YAMMMMM@Z
 * Original: 0x00129DE0 - 0x00129EB9 (217 bytes, 49 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129DE0_CircularInterpolation(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2, xmm3;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00129DE0:
    esp = esp - 0xC;
    xmm0 = MEMF(0x5369AC); /* movss */
    xmm0 = xmm0 / MEMF(esp + 0x18); /* divss */
    xmm1 = xmm0; /* movaps */
    xmm1 = xmm1 * MEMF(esp + 0x10); /* mulss */
    MEMF(esp + 0x18) = xmm1; /* movss */
    fp_push(MEMF(esp + 0x18)); /* fld float */
    MEMF(esp + 8) = xmm0; /* movss */
    /* FPU: fcos  */
    xmm0 = xmm0 * MEMF(esp + 0x14); /* mulss */
    MEMF(esp + 0x10) = xmm0; /* movss */
    MEMF(esp) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp + 0x18)); /* fld float */
    /* FPU: fsin  */
    MEMF(esp + 4) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp + 0x10)); /* fld float */
    /* FPU: fcos  */
    MEMF(esp + 0x18) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp + 0x10)); /* fld float */
    xmm1 = MEMF(esp + 0x18); /* movss */
    /* FPU: fsin  */
    xmm3 = xmm1; /* movaps */
    xmm3 = xmm3 * MEMF(esp); /* mulss */
    MEMF(esp + 0x10) = (float)fp_top(); fp_popp(); /* fstp */
    xmm2 = MEMF(esp + 0x10); /* movss */
    xmm0 = xmm2; /* movaps */
    xmm0 = xmm0 * MEMF(esp + 4); /* mulss */
    xmm0 = xmm0 + xmm3; /* addss */
    xmm3 = 0.0f; /* xorps self = zero */
    /* comiss xmm3, xmm0 - sets EFLAGS */
    MEMF(esp + 0x14) = xmm0; /* movss */
    if ((xmm3 <= xmm0)) goto loc_00129E91; /* jbe: below or equal (unsigned <=) */

loc_00129E68:
    xmm3 = xmm1; /* movaps */
    xmm1 = MEMF(0x56149C); /* movss */
    xmm3 = xmm3 * xmm1; /* mulss */
    xmm2 = xmm2 * xmm1; /* mulss */
    xmm0 = xmm0 * xmm1; /* mulss */
    MEMF(esp + 0x18) = xmm3; /* movss */
    MEMF(esp + 0x10) = xmm2; /* movss */
    MEMF(esp + 0x14) = xmm0; /* movss */

loc_00129E91:
    xmm1 = MEMF(0x561418); /* movss */
    xmm2 = xmm1; /* movaps */
    xmm2 = xmm2 - xmm0; /* subss */
    xmm0 = MEMF(0x561454); /* movss */
    /* comiss xmm0, xmm2 - sets EFLAGS */
    if ((xmm0 <= xmm2)) { sub_00129EB9(); return; } /* jbe: below or equal (unsigned <=) */

loc_00129EAD:
    xmm0 = MEMF(esp + 0x1C); /* movss */
    xmm1 = xmm1 - xmm0; /* subss */
    g_seh_ebp = ebp; sub_00129F00(); return; /* tail jmp 0x00129F00 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_00129EB9
 * Original: 0x00129EB9 - 0x00129F00 (71 bytes, 21 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00129EB9(void)
{
    float xmm0, xmm1;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_00129EB9:
    eax = MEM32(esp + 0x14);
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_00129AE0_Zero_acos(); /* call 0x00129AE0 */

loc_00129EC3:
    /* fld st(0) */
    /* FPU: fsin  */
    esp = esp + 4;
    /* FPU: fdivr dword ptr [0x561418] */
    fp_push(MEMF(0x561418)); /* fld float */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    /* FPU: fsin  */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    MEMF(esp + 0x14) = (float)fp_top(); fp_popp(); /* fstp */
    { double _t = fp_top(); fp_top() = fp_st1(); fp_st1() = _t; } /* fxch */
    xmm1 = MEMF(esp + 0x14); /* movss */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    /* FPU: fsin  */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    MEMF(esp + 0x1C) = (float)fp_top(); fp_popp(); /* fstp */
    xmm0 = MEMF(esp + 0x1C); /* movss */
    /* fstp st(0) */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_00129F00
 * Original: 0x00129F00 - 0x00129F40 (64 bytes, 15 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00129F00(void)
{
    float xmm0, xmm1, xmm2, xmm3;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_00129F00:
    xmm2 = xmm0; /* movaps */
    xmm2 = xmm2 * MEMF(esp + 0x18); /* mulss */
    xmm0 = xmm0 * MEMF(esp + 0x10); /* mulss */
    xmm3 = xmm1; /* movaps */
    xmm3 = xmm3 * MEMF(esp); /* mulss */
    xmm1 = xmm1 * MEMF(esp + 4); /* mulss */
    esp = esp - 8;
    xmm2 = xmm2 + xmm3; /* addss */
    MEMF(esp + 4) = xmm2; /* movss */
    xmm0 = xmm0 + xmm1; /* addss */
    MEMF(esp) = xmm0; /* movss */
    PUSH32(esp, 0); fn_00129B20_Zero_atan2(); /* call 0x00129B20 */

loc_00129F38:
    fp_st1() /= fp_top(); fp_pop(); /* fdiv */
    esp = esp + 0x14;
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_00129F40_CalcNormal
 * Symbol: ?CalcNormal@@YAXAAVZeroVector3@@ABV1@11@Z
 * Original: 0x00129F40 - 0x00129FD6 (150 bytes, 37 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00129F40_CalcNormal(void)
{
    uint32_t ebp;
    float xmm0, xmm1, xmm2, xmm3, xmm4, xmm5, xmm6, xmm7;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00129F40:
    esp = esp - 0xC;
    xmm2 = MEMF(eax + 4); /* movss */
    xmm2 = xmm2 - MEMF(edx + 4); /* subss */
    xmm1 = MEMF(eax + 8); /* movss */
    xmm1 = xmm1 - MEMF(edx + 8); /* subss */
    xmm4 = MEMF(esi + 4); /* movss */
    xmm4 = xmm4 - MEMF(eax + 4); /* subss */
    xmm5 = MEMF(esi + 8); /* movss */
    xmm5 = xmm5 - MEMF(eax + 8); /* subss */
    xmm0 = MEMF(eax); /* movss */
    xmm0 = xmm0 - MEMF(edx); /* subss */
    xmm3 = MEMF(esi); /* movss */
    xmm3 = xmm3 - MEMF(eax); /* subss */
    xmm7 = xmm1; /* movaps */
    xmm6 = xmm2; /* movaps */
    xmm6 = xmm6 * xmm5; /* mulss */
    xmm7 = xmm7 * xmm4; /* mulss */
    xmm6 = xmm6 - xmm7; /* subss */
    MEMF(esp) = xmm6; /* movss */
    edx = MEM32(esp);
    xmm6 = xmm0; /* movaps */
    xmm1 = xmm1 * xmm3; /* mulss */
    xmm6 = xmm6 * xmm5; /* mulss */
    eax = ecx;
    MEM32(eax) = edx;
    xmm1 = xmm1 - xmm6; /* subss */
    MEMF(esp + 4) = xmm1; /* movss */
    edx = MEM32(esp + 4);
    xmm0 = xmm0 * xmm4; /* mulss */
    xmm2 = xmm2 * xmm3; /* mulss */
    xmm0 = xmm0 - xmm2; /* subss */
    MEM32(eax + 4) = edx;
    MEMF(esp + 8) = xmm0; /* movss */
    edx = MEM32(esp + 8);
    MEM32(eax + 8) = edx;
    esp = esp + 0xC;
    g_seh_ebp = ebp; fn_00052AF0_ZeroVector3_NormalizeFastest(); return; /* tail jmp 0x00052AF0 */

}
