/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/script/cbehavior.c
 * Functions: 25
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_000371F0_CScriptInstanceCallback_GetFuncCRC
 * Symbol: ?GetFuncCRC@CScriptInstanceCallback@@UBE?AVCRC@@XZ
 * Original: 0x000371F0 - 0x000371FF (15 bytes, 5 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_000371F0_CScriptInstanceCallback_GetFuncCRC(void)
{

loc_000371F0:
    eax = MEM32(ecx + 4);
    ecx = MEM32(eax + 4);
    eax = MEM32(esp + 4);
    MEM32(eax) = ecx;
    esp += 8; return; /* ret 4 */

}

/**
 * fn_00037200_1CCondition_QAE_XZ
 * Symbol: ??1CCondition@@QAE@XZ
 * Original: 0x00037200 - 0x0003720B (11 bytes, 5 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00037200_1CCondition_QAE_XZ(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00037200:
    ecx = MEM32(eax);
    if (TEST_Z(ecx, ecx)) { sub_0003720B(); return; } /* je: equal / zero */

loc_00037206:
    edx = MEM32(ecx);
    g_seh_ebp = ebp; RECOMP_ITAIL(MEM32(edx + 0x38)); return; /* indirect tail jmp */

}

/**
 * sub_0003720B
 * Original: 0x0003720B - 0x0003720C (1 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0003720B(void)
{

loc_0003720B:
    esp += 4; return; /* ret */

}

/**
 * fn_00037210_CScriptManager_GetCallback
 * Symbol: ?GetCallback@CScriptManager@@QAEPAVCScriptCallback@@VCRC@@@Z
 * Original: 0x00037210 - 0x00037241 (49 bytes, 19 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00037210_CScriptManager_GetCallback(void)
{
    int _flags = 0; /* fallback flag var */

loc_00037210:
    eax = MEM32(eax + 0x168);
    if (TEST_Z(eax, eax)) goto loc_0003723C; /* je: equal / zero */

loc_0003721A:
    edx = MEM32(esp + 4);
    edi = edi;

loc_00037220:
    ecx = MEM32(eax + 0x14);
    if (CMP_A(ecx, edx)) goto loc_00037233; /* ja: above (unsigned >) */

loc_00037227:
    if (CMP_AE(ecx, edx)) goto loc_00037238; /* jae: above or equal (unsigned >=) */

loc_00037229:
    eax = MEM32(eax + 0xC);

loc_0003722C:
    if (TEST_NZ(eax, eax)) goto loc_00037220; /* jne: not equal / not zero */

loc_00037230:
    esp += 8; return; /* ret 4 */

loc_00037233:
    eax = MEM32(eax + 8);
    goto loc_0003722C;

loc_00037238:
    if (TEST_NZ(eax, eax)) { sub_00037241(); return; } /* jne: not equal / not zero */

loc_0003723C:
    eax = 0; /* xor self */
    esp += 8; return; /* ret 4 */

}

/**
 * sub_00037241
 * Original: 0x00037241 - 0x00037247 (6 bytes, 2 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00037241(void)
{

loc_00037241:
    eax = MEM32(eax + 0x18);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_00037250_CSpawnEncounter_GetDebugName
 * Symbol: ?GetDebugName@CSpawnEncounter@@UBEPBDXZ
 * Original: 0x00037250 - 0x00037256 (6 bytes, 2 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00037250_CSpawnEncounter_GetDebugName(void)
{

loc_00037250:
    eax = 0x54A1E0;
    esp += 4; return; /* ret */

}

/**
 * fn_00037260_GCBehavior_UAEPAXI_Z
 * Symbol: ??_GCBehavior@@UAEPAXI@Z
 * Original: 0x00037260 - 0x00037298 (56 bytes, 24 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00037260_GCBehavior_UAEPAXI_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_00037260:
    PUSH32(esp, esi);
    esi = ecx;
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_002144E0_1CBehavior_UAE_XZ(); /* call 0x002144E0 */

loc_00037269:
    if (TEST_Z(MEM8(esp + 8), 1)) goto loc_00037292; /* je: equal / zero */

loc_00037270:
    if (TEST_Z(esi, esi)) goto loc_00037289; /* je: equal / zero */

loc_00037274:
    eax = MEM32(esi + 4);
    if (TEST_Z(eax, eax)) goto loc_00037289; /* je: equal / zero */

loc_0003727B:
    ecx = eax;
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, esi);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 4), _icall_esp); /* indirect call */
    }

loc_00037283:
    eax = esi;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

loc_00037289:
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_001293F0_3_YAXPAX_Z(); /* call 0x001293F0 */

loc_0003728F:
    esp = esp + 4;

loc_00037292:
    eax = esi;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_000372A0_RegisterScriptAction_VCBehavior_YA_AVCRC_P8CBehavior_AE_NXZV0_Z
 * Symbol: ??$RegisterScriptAction@VCBehavior@@@@YA?AVCRC@@P8CBehavior@@AE_NXZV0@@Z
 * Original: 0x000372A0 - 0x00037334 (148 bytes, 51 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_000372A0_RegisterScriptAction_VCBehavior_YA_AVCRC_P8CBehavior_AE_NXZV0_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_000372A0:
    PUSH32(esp, ecx);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x14);
    PUSH32(esp, ecx);
    eax = esp;
    MEM32(esp + 8) = esp;
    MEM32(eax) = esi;
    PUSH32(esp, 0); fn_002047A0_CScriptManager_Get(); /* call 0x002047A0 */

loc_000372B4:
    PUSH32(esp, 0); fn_00037210_CScriptManager_GetCallback(); /* call 0x00037210 */

loc_000372B9:
    if (TEST_NZ(eax, eax)) goto loc_0003732D; /* jne: not equal / not zero */

loc_000372BD:
    eax = MEM32(0x5F9E40);
    if (TEST_NZ(eax, eax)) goto loc_000372D2; /* jne: not equal / not zero */

loc_000372C6:
    PUSH32(esp, 0x10);
    PUSH32(esp, 0); fn_0009E3F2_malloc(); /* call 0x0009E3F2 */

loc_000372CD:
    esp = esp + 4;
    goto loc_000372EC;

loc_000372D2:
    eax = MEM32(0x6135C8);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, 0x10);
    ecx = 0x6135C8;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax), _icall_esp); /* indirect call */
    }

loc_000372E2:
    if (TEST_NZ(eax, eax)) goto loc_000372F0; /* jne: not equal / not zero */

loc_000372E6:
    MEM32(eax) = 0x12345678;

loc_000372EC:
    if (TEST_Z(eax, eax)) goto loc_00037309; /* je: equal / zero */

loc_000372F0:
    ecx = MEM32(esp + 0xC);
    edx = MEM32(esp + 0x10);
    MEM32(eax + 4) = esi;
    MEM32(eax) = 0x54BF40;
    MEM32(eax + 8) = ecx;
    MEM32(eax + 0xC) = edx;
    goto loc_0003730B;

loc_00037309:
    eax = 0; /* xor self */

loc_0003730B:
    MEM32(esp + 0x14) = esi;
    MEM32(esp + 4) = eax;
    PUSH32(esp, 0); fn_002047A0_CScriptManager_Get(); /* call 0x002047A0 */

loc_00037318:
    ecx = esp + 0x14;
    PUSH32(esp, ecx);
    edx = esp + 8;
    PUSH32(esp, edx);
    eax = eax + 0x160;
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_000366F0_PAVCUITexture_ZeroTree_Insert(); /* call 0x000366F0 */

loc_0003732D:
    MEM32(edi) = esi;
    eax = edi;
    POP32(esp, esi);
    POP32(esp, ecx);
    esp += 4; return; /* ret */

}

/**
 * fn_00037340_ECBehavior_WBA_AEPAXI_Z
 * Symbol: ??_ECBehavior@@WBA@AEPAXI@Z
 * Original: 0x00037340 - 0x00037348 (8 bytes, 2 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00037340_ECBehavior_WBA_AEPAXI_Z(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00037340:
    ecx = ecx - 0x10;
    g_seh_ebp = ebp; fn_00037260_GCBehavior_UAEPAXI_Z(); return; /* tail jmp 0x00037260 */

}

/**
 * fn_00037350_CScript_GetPosition
 * Symbol: ?GetPosition@CScript@@UAE?AVZeroVector3@@XZ
 * Original: 0x00037350 - 0x00037373 (35 bytes, 11 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00037350_CScript_GetPosition(void)
{

loc_00037350:
    eax = MEM32(esp + 4);
    edx = MEM32(esp + -12);
    ecx = eax;
    MEM32(ecx) = edx;
    edx = MEM32(esp + -8);
    MEM32(ecx + 4) = edx;
    edx = MEM32(esp + -4);
    esp = esp - 0xC;
    MEM32(ecx + 8) = edx;
    esp = esp + 0xC;
    esp += 8; return; /* ret 4 */

}

/**
 * fn_00037380_CScript_SetActive
 * Symbol: ?SetActive@CScript@@UAEX_N@Z
 * Original: 0x00037380 - 0x00037395 (21 bytes, 7 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00037380_CScript_SetActive(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00037380:
    eax = MEM32(esp + 4);
    if (CMP_EQ(MEM8(ecx + 0x31), LO8(eax))) { sub_00037395(); return; } /* je: equal / zero */

loc_00037389:
    edx = MEM32(ecx);
    MEM8(ecx + 0x31) = LO8(eax);
    MEM32(esp + 4) = eax;
    g_seh_ebp = ebp; RECOMP_ITAIL(MEM32(edx + 0x48)); return; /* indirect tail jmp */

}

/**
 * sub_00037395
 * Original: 0x00037395 - 0x00037398 (3 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00037395(void)
{

loc_00037395:
    esp += 8; return; /* ret 4 */

}

/**
 * fn_000373A0_CScript_IsActive
 * Symbol: ?IsActive@CScript@@UAE_NXZ
 * Original: 0x000373A0 - 0x000373A4 (4 bytes, 2 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_000373A0_CScript_IsActive(void)
{

loc_000373A0:
    SET_LO8(eax, MEM8(ecx + 0x31));
    esp += 4; return; /* ret */

}

/**
 * fn_00214290_CBehavior_LoadSave
 * Symbol: ?LoadSave@CBehavior@@UAEXPAVCBitStream@@W4TLoadSavePass@@@Z
 * Original: 0x00214290 - 0x002142FE (110 bytes, 47 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00214290_CBehavior_LoadSave(void)
{
    int _flags = 0; /* fallback flag var */

loc_00214290:
    PUSH32(esp, ebx);
    ebx = MEM32(esp + 0xC);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0xC);
    PUSH32(esp, edi);
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    edi = ecx;
    PUSH32(esp, 0); fn_00204DC0_CScript_LoadSave(); /* call 0x00204DC0 */

loc_002142A4:
    eax = ebx;
    eax = eax - 4;
    if ((eax == 0)) goto loc_002142EB; /* je: equal / zero */

loc_002142AB:
    eax--;
    if ((eax != 0)) goto loc_002142F8; /* jne: not equal / not zero */

loc_002142AE:
    eax = MEM32(esi);
    ecx = esp + 0x14;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ecx);
    PUSH32(esp, 1);
    ecx = esi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x10), _icall_esp); /* indirect call */
    }

loc_002142BC:
    ecx = MEM32(esi + 8);
    edx = eax;
    eax = eax & 7;
    SET_LO8(ebx, MEM8(eax + 0x55DA24));
    edx = edx >> 3;
    SET_LO8(edx, MEM8(edx + ecx));
    (void)0; /* test LO8(ebx), LO8(edx) - flags set for next jcc */
    SET_LO8(eax, (TEST_NZ(LO8(ebx), LO8(edx))) ? 1 : 0); /* setne */
    (void)0; /* test LO8(eax), LO8(eax) - flags set for next jcc */
    MEM8(edi + 0x24) = LO8(eax);
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_002142F8; /* je: equal / zero */

loc_002142DC:
    eax = MEM32(edi + -16);
    ecx = edi + -16;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x60), _icall_esp); /* indirect call */
    }

loc_002142E5:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp += 12; return; /* ret 8 */

loc_002142EB:
    ecx = 0; /* xor self */
    SET_LO8(ecx, MEM8(edi + 0x24));
    eax = esi;
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_001941B0_CBitStream_WriteBit(); /* call 0x001941B0 */

loc_002142F8:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp += 12; return; /* ret 8 */

}

/**
 * fn_00214300_CBehavior_OnActivate
 * Symbol: ?OnActivate@CBehavior@@UAEX_N@Z
 * Original: 0x00214300 - 0x00214313 (19 bytes, 7 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00214300_CBehavior_OnActivate(void)
{
    int _flags = 0; /* fallback flag var */

loc_00214300:
    SET_LO8(eax, MEM8(esp + 4));
    (void)0; /* test LO8(eax), LO8(eax) - flags set for next jcc */
    MEM8(ecx + 0x34) = LO8(eax);
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_00214310; /* je: equal / zero */

loc_0021430B:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x60), _icall_esp); /* indirect call */
    }

loc_00214310:
    esp += 8; return; /* ret 4 */

}

/**
 * fn_00214320_CBehavior_OnActivateCallback
 * Symbol: ?OnActivateCallback@CBehavior@@QAE_NXZ
 * Original: 0x00214320 - 0x0021432A (10 bytes, 5 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00214320_CBehavior_OnActivateCallback(void)
{

loc_00214320:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 1);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x44), _icall_esp); /* indirect call */
    }

loc_00214327:
    SET_LO8(eax, 0); /* xor self */
    esp += 4; return; /* ret */

}

/**
 * fn_00214330_CBehavior_Setup
 * Symbol: ?Setup@CBehavior@@UAE_NXZ
 * Original: 0x00214330 - 0x00214333 (3 bytes, 2 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00214330_CBehavior_Setup(void)
{

loc_00214330:
    SET_LO8(eax, 1);
    esp += 4; return; /* ret */

}

/**
 * fn_00214340_CBehavior_ParseLine
 * Symbol: ?ParseLine@CBehavior@@UAEXPBDPAD@Z
 * Original: 0x00214340 - 0x0021437B (59 bytes, 23 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00214340_CBehavior_ParseLine(void)
{
    int _flags = 0; /* fallback flag var */
    int _cf = 0; /* carry flag */

loc_00214340:
    PUSH32(esp, esi);
    esi = MEM32(esp + 8);
    PUSH32(esp, edi);
    PUSH32(esp, esi);
    PUSH32(esp, 0x54A180);
    edi = ecx;
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_00214353:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) { sub_0021437B(); return; } /* jne: not equal / not zero */

loc_0021435A:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_00214363:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB68_atol(); /* call 0x0009BB68 */

loc_00214369:
    esp = esp + 4;
    eax--;
    eax = (uint32_t)(-(int32_t)eax);
    SET_LO8(eax, _cf ? 0xFFFFFFFF : 0); /* sbb self (CF extend) */
    SET_LO8(eax, LO8(eax) + 1);
    MEM8(edi + 0x35) = LO8(eax);
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

}

/**
 * sub_0021437B
 * Original: 0x0021437B - 0x002144DC (353 bytes, 120 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0021437B(void)
{
    int _flags = 0; /* fallback flag var */
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_0021437B:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54A178);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_00214386:
    esp = esp + 8;
    if (TEST_Z(eax, eax)) goto loc_002144C3; /* je: equal / zero */

loc_00214391:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54A16C);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_0021439C:
    esp = esp + 8;
    if (TEST_Z(eax, eax)) goto loc_002144C3; /* je: equal / zero */

loc_002143A7:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54A15C);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_002143B2:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) goto loc_002143D3; /* jne: not equal / not zero */

loc_002143B9:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_002143C2:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB16_atof(); /* call 0x0009BB16 */

loc_002143C8:
    MEMF(edi + 0x38) = (float)fp_top(); fp_popp(); /* fstp */
    esp = esp + 4;
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

loc_002143D3:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54A154);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_002143DE:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) goto loc_00214404; /* jne: not equal / not zero */

loc_002143E5:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_002143EE:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB68_atol(); /* call 0x0009BB68 */

loc_002143F4:
    esp = esp + 4;
    (void)0; /* test eax, eax - flags set for next jcc */
    SET_LO8(eax, (TEST_NZ(eax, eax)) ? 1 : 0); /* setne */
    MEM8(edi + 0x54) = LO8(eax);
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

loc_00214404:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54A14C);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_0021440F:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) goto loc_00214435; /* jne: not equal / not zero */

loc_00214416:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_0021441F:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB68_atol(); /* call 0x0009BB68 */

loc_00214425:
    esp = esp + 4;
    (void)0; /* test eax, eax - flags set for next jcc */
    SET_LO8(ecx, (TEST_NZ(eax, eax)) ? 1 : 0); /* setne */
    MEM8(edi + 0x55) = LO8(ecx);
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

loc_00214435:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54A144);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_00214440:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) goto loc_00214466; /* jne: not equal / not zero */

loc_00214447:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_00214450:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB68_atol(); /* call 0x0009BB68 */

loc_00214456:
    esp = esp + 4;
    (void)0; /* test eax, eax - flags set for next jcc */
    SET_LO8(edx, (TEST_NZ(eax, eax)) ? 1 : 0); /* setne */
    MEM8(edi + 0x56) = LO8(edx);
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

loc_00214466:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54A138);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_00214471:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) goto loc_00214497; /* jne: not equal / not zero */

loc_00214478:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_00214481:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB68_atol(); /* call 0x0009BB68 */

loc_00214487:
    esp = esp + 4;
    (void)0; /* test eax, eax - flags set for next jcc */
    SET_LO8(eax, (TEST_NZ(eax, eax)) ? 1 : 0); /* setne */
    MEM8(edi + 0x57) = LO8(eax);
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

loc_00214497:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54A128);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_002144A2:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) goto loc_002144D7; /* jne: not equal / not zero */

loc_002144A9:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_002144B2:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB16_atof(); /* call 0x0009BB16 */

loc_002144B8:
    MEMF(edi + 0x58) = (float)fp_top(); fp_popp(); /* fstp */
    esp = esp + 4;
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

loc_002144C3:
    ecx = edi + 0x48;
    PUSH32(esp, ecx);
    edi = edi + 0x3C;
    PUSH32(esp, edi);
    edi = esp + 0x18;
    PUSH32(esp, 0); fn_00205220_CScript_ParseTriggerItem(); /* call 0x00205220 */

loc_002144D4:
    esp = esp + 8;

loc_002144D7:
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_002144E0_1CBehavior_UAE_XZ
 * Symbol: ??1CBehavior@@UAE@XZ
 * Original: 0x002144E0 - 0x00214546 (102 bytes, 25 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002144E0_1CBehavior_UAE_XZ(void)
{

loc_002144E0:
    eax = MEM32(0);
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x4067C2);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    edi = MEM32(esp + 0x18);
    MEM32(edi) = 0x54A0C0;
    MEM32(edi + 0x10) = 0x54A0AC;
    esi = edi + 0x48;
    MEM32(esp + 0x10) = 1;
    PUSH32(esp, 0); fn_0004FF90_PAVCUIMenu_ZeroList_RemoveAll(); /* call 0x0004FF90 */

loc_00214518:
    esi = edi + 0x3C;
    MEM8(esp + 0x10) = 0;
    PUSH32(esp, 0); fn_0004FF90_PAVCUIMenu_ZeroList_RemoveAll(); /* call 0x0004FF90 */

loc_00214525:
    PUSH32(esp, edi);
    MEM32(esp + 0x14) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_00205890_1CScript_UAE_XZ(); /* call 0x00205890 */

loc_00214533:
    ecx = MEM32(esp + 8);
    POP32(esp, edi);
    MEM32(0) = ecx;
    POP32(esp, esi);
    esp = esp + 0xC;
    esp += 8; return; /* ret 4 */

}

/**
 * fn_00214550_0CBehavior_QAE_XZ
 * Symbol: ??0CBehavior@@QAE@XZ
 * Original: 0x00214550 - 0x002145A1 (81 bytes, 26 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00214550_0CBehavior_QAE_XZ(void)
{
    float xmm0;

loc_00214550:
    PUSH32(esp, esi);
    esi = eax;
    PUSH32(esp, 0); fn_00205360_0CScript_QAE_XZ(); /* call 0x00205360 */

loc_00214558:
    xmm0 = 0.0f; /* xorps self = zero */
    eax = 0; /* xor self */
    MEM32(esi) = 0x54A0C0;
    MEM32(esi + 0x10) = 0x54A0AC;
    MEM32(esi + 0x3C) = eax;
    MEM32(esi + 0x40) = eax;
    MEM32(esi + 0x44) = eax;
    MEM32(esi + 0x48) = eax;
    MEM32(esi + 0x4C) = eax;
    MEM32(esi + 0x50) = eax;
    SET_LO8(ecx, 1);
    MEM8(esi + 0x34) = LO8(eax);
    MEM8(esi + 0x35) = LO8(eax);
    MEM8(esi + 0x56) = LO8(eax);
    MEM8(esi + 0x57) = LO8(eax);
    MEM8(esi + 0x5C) = LO8(eax);
    MEMF(esi + 0x38) = xmm0; /* movss */
    MEM8(esi + 0x54) = LO8(ecx);
    MEM8(esi + 0x55) = LO8(ecx);
    MEMF(esi + 0x58) = xmm0; /* movss */
    eax = esi;
    POP32(esp, esi);
    esp += 4; return; /* ret */

}

/**
 * fn_002145B0_CBehavior_OnReactivate
 * Symbol: ?OnReactivate@CBehavior@@QAE_NXZ
 * Original: 0x002145B0 - 0x0021464E (158 bytes, 52 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002145B0_CBehavior_OnReactivate(void)
{
    int _flags = 0; /* fallback flag var */

loc_002145B0:
    eax = MEM32(0);
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x409F1C);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x18;
    PUSH32(esp, esi);
    esi = ecx;
    SET_LO8(eax, MEM8(esi + 0x5C));
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_002145D9; /* je: equal / zero */

loc_002145D2:
    eax = MEM32(esi);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x44), _icall_esp); /* indirect call */
    }

loc_002145D9:
    ecx = esi + 0x48;
    PUSH32(esp, ecx);
    edx = esp + 0xC;
    PUSH32(esp, edx);
    ecx = esi + 0x3C;
    edx = 0; /* xor self */
    PUSH32(esp, 0); fn_00206470_CScript_SetupTriggerFromParsed(); /* call 0x00206470 */

loc_002145EC:
    MEM32(esp + 0x24) = 0;
    eax = MEM32(esi + 0x38);
    PUSH32(esp, eax);
    PUSH32(esp, ecx);
    ecx = MEM32(esp + 0x20);
    eax = esp;
    MEM32(eax) = ecx;
    ecx = MEM32(esp + 0x20);
    (void)0; /* test ecx, ecx - flags set for next jcc */
    MEM32(esp + 0xC) = esp;
    if (TEST_Z(ecx, ecx)) goto loc_00214612; /* je: equal / zero */

loc_0021460D:
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x34), _icall_esp); /* indirect call */
    }

loc_00214612:
    PUSH32(esp, ecx);
    ecx = MEM32(0x60BA04);
    eax = esp;
    MEM32(esp + 0x10) = esp;
    PUSH32(esp, esi);
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_00041FC0_CreateScriptAction_VCNPCScript_YAPAVCScriptAction_PAVCNPCScript_VCRC_VCCondition_M_Z(); /* call 0x00041FC0 */

loc_00214627:
    esp = esp + 0x10;
    edx = esp + 8;
    PUSH32(esp, edx);
    MEM32(esp + 0x28) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_0002F150_1CTrigger_UAE_XZ(); /* call 0x0002F150 */

loc_0021463C:
    ecx = MEM32(esp + 0x1C);
    SET_LO8(eax, 0); /* xor self */
    MEM32(0) = ecx;
    POP32(esp, esi);
    esp = esp + 0x24;
    esp += 4; return; /* ret */

}

/**
 * fn_00214650_CBehavior_OnDoneWaiting
 * Symbol: ?OnDoneWaiting@CBehavior@@QAE_NXZ
 * Original: 0x00214650 - 0x002146D7 (135 bytes, 43 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00214650_CBehavior_OnDoneWaiting(void)
{

loc_00214650:
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x409F30);
    eax = MEM32(0);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x18;
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    edi = ecx;
    eax = edi + 0x48;
    PUSH32(esp, eax);
    edx = esp + 0x10;
    PUSH32(esp, edx);
    ecx = edi + 0x3C;
    edx = 0; /* xor self */
    PUSH32(esp, 0); fn_00206470_CScript_SetupTriggerFromParsed(); /* call 0x00206470 */

loc_0021467F:
    PUSH32(esp, 0);
    PUSH32(esp, ecx);
    eax = esp + 0x14;
    esi = esp;
    MEM32(esp + 0x10) = esp;
    PUSH32(esp, eax);
    MEM32(esp + 0x34) = 0;
    PUSH32(esp, 0); fn_002019C0_7CTrigger_QAE_AVCCondition_XZ(); /* call 0x002019C0 */

loc_0021469A:
    PUSH32(esp, ecx);
    ecx = MEM32(0x60BA0C);
    eax = esp;
    MEM32(esp + 0x14) = esp;
    PUSH32(esp, edi);
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_00041FC0_CreateScriptAction_VCNPCScript_YAPAVCScriptAction_PAVCNPCScript_VCRC_VCCondition_M_Z(); /* call 0x00041FC0 */

loc_002146AF:
    esp = esp + 0x10;
    edx = esp + 0xC;
    PUSH32(esp, edx);
    MEM32(esp + 0x2C) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_0002F150_1CTrigger_UAE_XZ(); /* call 0x0002F150 */

loc_002146C4:
    ecx = MEM32(esp + 0x20);
    POP32(esp, edi);
    SET_LO8(eax, 0); /* xor self */
    MEM32(0) = ecx;
    POP32(esp, esi);
    esp = esp + 0x24;
    esp += 4; return; /* ret */

}

/**
 * fn_002146E0_CBehavior_Finished
 * Symbol: ?Finished@CBehavior@@UAE_NXZ
 * Original: 0x002146E0 - 0x002147B6 (214 bytes, 67 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002146E0_CBehavior_Finished(void)
{
    int _flags = 0; /* fallback flag var */
    float xmm0;

loc_002146E0:
    eax = MEM32(0);
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x409F44);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x18;
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    edi = ecx;
    SET_LO8(eax, MEM8(edi + 0x57));
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_002147A3; /* je: equal / zero */

loc_00214707:
    SET_LO8(eax, MEM8(edi + 0x35));
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_002147A3; /* je: equal / zero */

loc_00214712:
    eax = MEM32(edi + 0x3C);
    if (TEST_Z(eax, eax)) goto loc_002147A3; /* je: equal / zero */

loc_0021471D:
    xmm0 = MEMF(edi + 0x58); /* movss */
    /* ucomiss xmm0, MEMF(0x561408) - sets EFLAGS */
    /* lahf - load AH from flags (used in FPU compare idiom) */
    if (1 /* jp after test - parity */) goto loc_00214747; /* jp: parity */

loc_0021472F:
    PUSH32(esp, 0); fn_00214650_CBehavior_OnDoneWaiting(); /* call 0x00214650 */

loc_00214734:
    SET_LO8(eax, 1);
    ecx = MEM32(esp + 0x20);
    MEM32(0) = ecx;
    POP32(esp, edi);
    POP32(esp, esi);
    esp = esp + 0x24;
    esp += 4; return; /* ret */

loc_00214747:
    eax = MEM32(edi + 0x58);
    PUSH32(esp, 0);
    PUSH32(esp, 1);
    PUSH32(esp, 0);
    PUSH32(esp, eax);
    ecx = esp + 0x1C;
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_001EEBE0_CTimerTrigger_CreateTrigger(); /* call 0x001EEBE0 */

loc_0021475B:
    esp = esp + 0x14;
    PUSH32(esp, 0);
    PUSH32(esp, ecx);
    edx = esp + 0x14;
    esi = esp;
    MEM32(esp + 0x10) = esp;
    PUSH32(esp, edx);
    MEM32(esp + 0x34) = 0;
    PUSH32(esp, 0); fn_002019C0_7CTrigger_QAE_AVCCondition_XZ(); /* call 0x002019C0 */

loc_00214779:
    PUSH32(esp, ecx);
    ecx = MEM32(0x60BA08);
    eax = esp;
    MEM32(esp + 0x14) = esp;
    PUSH32(esp, edi);
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_00041FC0_CreateScriptAction_VCNPCScript_YAPAVCScriptAction_PAVCNPCScript_VCRC_VCCondition_M_Z(); /* call 0x00041FC0 */

loc_0021478E:
    esp = esp + 0x10;
    edx = esp + 0xC;
    PUSH32(esp, edx);
    MEM32(esp + 0x2C) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_0002F150_1CTrigger_UAE_XZ(); /* call 0x0002F150 */

loc_002147A3:
    ecx = MEM32(esp + 0x20);
    POP32(esp, edi);
    SET_LO8(eax, 1);
    MEM32(0) = ecx;
    POP32(esp, esi);
    esp = esp + 0x24;
    esp += 4; return; /* ret */

}

/**
 * fn_002147C0_CBehavior_OnPreActivate
 * Symbol: ?OnPreActivate@CBehavior@@UAEX_N@Z
 * Original: 0x002147C0 - 0x00214900 (320 bytes, 99 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002147C0_CBehavior_OnPreActivate(void)
{
    int _flags = 0; /* fallback flag var */

loc_002147C0:
    eax = MEM32(0);
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x409F62);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x28;
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    esi = ecx;
    SET_LO8(eax, MEM8(esi + 0x54));
    if (TEST_NZ(LO8(eax), LO8(eax))) goto loc_002147F3; /* jne: not equal / not zero */

loc_002147E3:
    PUSH32(esp, 0); fn_00291240_CRulesManager_Get(); /* call 0x00291240 */

loc_002147E8:
    ecx = MEM32(eax + 0xC);
    if (TEST_Z(ecx, ecx)) goto loc_002148ED; /* je: equal / zero */

loc_002147F3:
    SET_LO8(eax, MEM8(esi + 0x55));
    if (TEST_NZ(LO8(eax), LO8(eax))) goto loc_00214818; /* jne: not equal / not zero */

loc_002147FA:
    PUSH32(esp, 0); fn_00291240_CRulesManager_Get(); /* call 0x00291240 */

loc_002147FF:
    if (CMP_EQ(MEM32(eax + 0xC), 1)) goto loc_002148ED; /* je: equal / zero */

loc_00214809:
    PUSH32(esp, 0); fn_00291240_CRulesManager_Get(); /* call 0x00291240 */

loc_0021480E:
    if (CMP_EQ(MEM32(eax + 0xC), 2)) goto loc_002148ED; /* je: equal / zero */

loc_00214818:
    SET_LO8(eax, MEM8(esi + 0x56));
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_00214832; /* je: equal / zero */

loc_0021481F:
    PUSH32(esp, 0); fn_002047A0_CScriptManager_Get(); /* call 0x002047A0 */

loc_00214824:
    SET_LO8(ecx, MEM8(eax + 0x189));
    if (TEST_Z(LO8(ecx), LO8(ecx))) goto loc_002148ED; /* je: equal / zero */

loc_00214832:
    SET_LO8(eax, MEM8(esp + 0x40));
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_002148ED; /* je: equal / zero */

loc_0021483E:
    SET_LO8(eax, MEM8(esi + 0x35));
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_00214899; /* je: equal / zero */

loc_00214845:
    eax = esi + 0x48;
    PUSH32(esp, eax);
    edx = esp + 0xC;
    PUSH32(esp, edx);
    ecx = esi + 0x3C;
    edx = 0; /* xor self */
    PUSH32(esp, 0); fn_00206470_CScript_SetupTriggerFromParsed(); /* call 0x00206470 */

loc_00214858:
    MEM32(esp + 0x38) = 0;
    eax = MEM32(esi + 0x38);
    PUSH32(esp, eax);
    PUSH32(esp, ecx);
    ecx = MEM32(esp + 0x20);
    eax = esp;
    MEM32(eax) = ecx;
    ecx = MEM32(esp + 0x20);
    (void)0; /* test ecx, ecx - flags set for next jcc */
    MEM32(esp + 0x48) = esp;
    if (TEST_Z(ecx, ecx)) goto loc_0021487E; /* je: equal / zero */

loc_00214879:
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x34), _icall_esp); /* indirect call */
    }

loc_0021487E:
    PUSH32(esp, ecx);
    ecx = MEM32(0x60BA04);
    eax = esp;
    MEM32(esp + 0x4C) = esp;
    PUSH32(esp, esi);
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_00041FC0_CreateScriptAction_VCNPCScript_YAPAVCScriptAction_PAVCNPCScript_VCRC_VCCondition_M_Z(); /* call 0x00041FC0 */

loc_00214893:
    edx = esp + 0x18;
    goto loc_002148DC;

loc_00214899:
    eax = MEM32(esi + 0x38);
    PUSH32(esp, eax);
    ebx = esp + 0x20;
    PUSH32(esp, 0); fn_001EFAE0_CManualTrigger_GetTrueTrigger(); /* call 0x001EFAE0 */

loc_002148A6:
    PUSH32(esp, ecx);
    MEM32(esp + 0x40) = 1;
    ecx = MEM32(eax + 0x10);
    (void)0; /* test ecx, ecx - flags set for next jcc */
    edx = esp;
    MEM32(esp + 0x48) = esp;
    MEM32(edx) = ecx;
    if (TEST_Z(ecx, ecx)) goto loc_002148C3; /* je: equal / zero */

loc_002148BE:
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x34), _icall_esp); /* indirect call */
    }

loc_002148C3:
    PUSH32(esp, ecx);
    ecx = MEM32(0x60BA04);
    eax = esp;
    MEM32(esp + 0x4C) = esp;
    PUSH32(esp, esi);
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_00041FC0_CreateScriptAction_VCNPCScript_YAPAVCScriptAction_PAVCNPCScript_VCRC_VCCondition_M_Z(); /* call 0x00041FC0 */

loc_002148D8:
    edx = esp + 0x2C;

loc_002148DC:
    esp = esp + 0x10;
    PUSH32(esp, edx);
    MEM32(esp + 0x3C) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_0002F150_1CTrigger_UAE_XZ(); /* call 0x0002F150 */

loc_002148ED:
    ecx = MEM32(esp + 0x30);
    POP32(esp, esi);
    MEM32(0) = ecx;
    POP32(esp, ebx);
    esp = esp + 0x34;
    esp += 8; return; /* ret 4 */

}
