/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/script/groupai/membergoals/cmg_search.c
 * Functions: 26
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_0004ABD0_GCMG_Search_UAEPAXI_Z
 * Symbol: ??_GCMG_Search@@UAEPAXI@Z
 * Original: 0x0004ABD0 - 0x0004ABEE (30 bytes, 11 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0004ABD0_GCMG_Search_UAEPAXI_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_0004ABD0:
    PUSH32(esp, esi);
    esi = ecx;
    PUSH32(esp, 0); fn_003C5FC0_1CMG_Search_UAE_XZ(); /* call 0x003C5FC0 */

loc_0004ABD8:
    if (TEST_Z(MEM8(esp + 8), 1)) goto loc_0004ABE8; /* je: equal / zero */

loc_0004ABDF:
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_001293F0_3_YAXPAX_Z(); /* call 0x001293F0 */

loc_0004ABE5:
    esp = esp + 4;

loc_0004ABE8:
    eax = esi;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0004ABF0_GCMG_SearchAimAtLast_UAEPAXI_Z
 * Symbol: ??_GCMG_SearchAimAtLast@@UAEPAXI@Z
 * Original: 0x0004ABF0 - 0x0004AC0E (30 bytes, 11 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0004ABF0_GCMG_SearchAimAtLast_UAEPAXI_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_0004ABF0:
    PUSH32(esp, esi);
    esi = ecx;
    PUSH32(esp, 0); fn_003C5EE0_1CMG_SearchAimAtLast_UAE_XZ(); /* call 0x003C5EE0 */

loc_0004ABF8:
    if (TEST_Z(MEM8(esp + 8), 1)) goto loc_0004AC08; /* je: equal / zero */

loc_0004ABFF:
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_001293F0_3_YAXPAX_Z(); /* call 0x001293F0 */

loc_0004AC05:
    esp = esp + 4;

loc_0004AC08:
    eax = esi;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0004AC10_GCMG_SearchFactionThreat_UAEPAXI_Z
 * Symbol: ??_GCMG_SearchFactionThreat@@UAEPAXI@Z
 * Original: 0x0004AC10 - 0x0004AC2E (30 bytes, 11 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0004AC10_GCMG_SearchFactionThreat_UAEPAXI_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_0004AC10:
    PUSH32(esp, esi);
    esi = ecx;
    PUSH32(esp, 0); fn_003C5E80_1CMG_SearchFactionThreat_UAE_XZ(); /* call 0x003C5E80 */

loc_0004AC18:
    if (TEST_Z(MEM8(esp + 8), 1)) goto loc_0004AC28; /* je: equal / zero */

loc_0004AC1F:
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_001293F0_3_YAXPAX_Z(); /* call 0x001293F0 */

loc_0004AC25:
    esp = esp + 4;

loc_0004AC28:
    eax = esi;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_003C5E80_1CMG_SearchFactionThreat_UAE_XZ
 * Symbol: ??1CMG_SearchFactionThreat@@UAE@XZ
 * Original: 0x003C5E80 - 0x003C5E8B (11 bytes, 2 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003C5E80_1CMG_SearchFactionThreat_UAE_XZ(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C5E80:
    MEM32(ecx) = 0x557E0C;
    g_seh_ebp = ebp; fn_001E2AF0_1CMemberGoal_UAE_XZ(); return; /* tail jmp 0x001E2AF0 */

}

/**
 * fn_003C5E90_0CMG_SearchFactionThreat_QAE_XZ
 * Symbol: ??0CMG_SearchFactionThreat@@QAE@XZ
 * Original: 0x003C5E90 - 0x003C5EDB (75 bytes, 22 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003C5E90_0CMG_SearchFactionThreat_QAE_XZ(void)
{
    float xmm0;

loc_003C5E90:
    esp = esp - 0xC;
    xmm0 = 0.0f; /* xorps self = zero */
    ecx = 0; /* xor self */
    MEM32(eax + 4) = ecx;
    MEM32(eax + 8) = ecx;
    MEM32(eax + 0xC) = ecx;
    MEM32(eax + 0x10) = ecx;
    MEM32(eax + 0x14) = ecx;
    MEM32(eax + 0x18) = ecx;
    MEMF(esp) = xmm0; /* movss */
    edx = MEM32(esp);
    ecx = eax + 0x1C;
    MEM32(ecx) = edx;
    MEMF(esp + 4) = xmm0; /* movss */
    edx = MEM32(esp + 4);
    MEM32(ecx + 4) = edx;
    MEMF(esp + 8) = xmm0; /* movss */
    edx = MEM32(esp + 8);
    MEM32(eax) = 0x557E0C;
    MEM32(ecx + 8) = edx;
    esp = esp + 0xC;
    esp += 4; return; /* ret */

}

/**
 * fn_003C5EE0_1CMG_SearchAimAtLast_UAE_XZ
 * Symbol: ??1CMG_SearchAimAtLast@@UAE@XZ
 * Original: 0x003C5EE0 - 0x003C5EEB (11 bytes, 2 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003C5EE0_1CMG_SearchAimAtLast_UAE_XZ(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C5EE0:
    MEM32(ecx) = 0x557E1C;
    g_seh_ebp = ebp; fn_001E2AF0_1CMemberGoal_UAE_XZ(); return; /* tail jmp 0x001E2AF0 */

}

/**
 * fn_003C5EF0_0CMG_SearchAimAtLast_QAE_XZ
 * Symbol: ??0CMG_SearchAimAtLast@@QAE@XZ
 * Original: 0x003C5EF0 - 0x003C5F0E (30 bytes, 10 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003C5EF0_0CMG_SearchAimAtLast_QAE_XZ(void)
{

loc_003C5EF0:
    ecx = 0; /* xor self */
    MEM32(eax + 4) = ecx;
    MEM32(eax + 8) = ecx;
    MEM32(eax + 0xC) = ecx;
    MEM32(eax + 0x10) = ecx;
    MEM32(eax + 0x14) = ecx;
    MEM32(eax + 0x18) = ecx;
    MEM32(eax) = 0x557E1C;
    MEM8(eax + 0x34) = LO8(ecx);
    esp += 4; return; /* ret */

}

/**
 * fn_003C5F10_CMG_Search_Initialize
 * Symbol: ?Initialize@CMG_Search@@UAEXPAVCMemberSoldier@@PAVCMemberGoal@@ABVCGroupOrder@@@Z
 * Original: 0x003C5F10 - 0x003C5FB9 (169 bytes, 65 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003C5F10_CMG_Search_Initialize(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C5F10:
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    ebp = MEM32(esp + 0x10);
    PUSH32(esp, esi);
    esi = ecx;
    PUSH32(esp, edi);
    edi = MEM32(esp + 0x14);
    eax = 0; /* xor self */
    ecx = 0x54E300;
    MEM32(esi + 0x10) = edi;
    MEM32(esi + 0x14) = ebp;
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_003C5F30:
    ebx = MEM32(esp + 0x1C);
    if (CMP_NE(MEM32(ebx + 0x68), eax)) goto loc_003C5FB2; /* jne: not equal / not zero */

loc_003C5F39:
    PUSH32(esp, 0x28);
    PUSH32(esp, 0); fn_00129450_2_YAPAXI_Z(); /* call 0x00129450 */

loc_003C5F40:
    esp = esp + 4;
    if (TEST_Z(eax, eax)) goto loc_003C5F4E; /* je: equal / zero */

loc_003C5F47:
    PUSH32(esp, 0); fn_003C5E90_0CMG_SearchFactionThreat_QAE_XZ(); /* call 0x003C5E90 */

loc_003C5F4C:
    goto loc_003C5F50;

loc_003C5F4E:
    eax = 0; /* xor self */

loc_003C5F50:
    edx = MEM32(eax);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    PUSH32(esp, edi);
    ecx = eax;
    MEM32(esp + 0x20) = eax;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 4), _icall_esp); /* indirect call */
    }

loc_003C5F5E:
    eax = esp + 0x14;
    esi = esi + 4;
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_00028E60_PAVCParticleEffect_ZeroList_Append(); /* call 0x00028E60 */

loc_003C5F6B:
    PUSH32(esp, 0x38);
    PUSH32(esp, 0); fn_00129450_2_YAPAXI_Z(); /* call 0x00129450 */

loc_003C5F72:
    ecx = 0; /* xor self */
    esp = esp + 4;
    if (CMP_EQ(eax, ecx)) goto loc_003C5F98; /* je: equal / zero */

loc_003C5F7B:
    MEM32(eax + 4) = ecx;
    MEM32(eax + 8) = ecx;
    MEM32(eax + 0xC) = ecx;
    MEM32(eax + 0x10) = ecx;
    MEM32(eax + 0x14) = ecx;
    MEM32(eax + 0x18) = ecx;
    MEM32(eax) = 0x557E1C;
    MEM8(eax + 0x34) = LO8(ecx);
    goto loc_003C5F9A;

loc_003C5F98:
    eax = 0; /* xor self */

loc_003C5F9A:
    edx = MEM32(eax);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    PUSH32(esp, edi);
    ecx = eax;
    MEM32(esp + 0x20) = eax;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 4), _icall_esp); /* indirect call */
    }

loc_003C5FA8:
    eax = esp + 0x14;
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_00028E60_PAVCParticleEffect_ZeroList_Append(); /* call 0x00028E60 */

loc_003C5FB2:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp += 16; return; /* ret 12 */

}

/**
 * fn_003C5FC0_1CMG_Search_UAE_XZ
 * Symbol: ??1CMG_Search@@UAE@XZ
 * Original: 0x003C5FC0 - 0x003C5FCB (11 bytes, 2 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003C5FC0_1CMG_Search_UAE_XZ(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C5FC0:
    MEM32(ecx) = 0x557E2C;
    g_seh_ebp = ebp; fn_001E2AF0_1CMemberGoal_UAE_XZ(); return; /* tail jmp 0x001E2AF0 */

}

/**
 * fn_003C5FD0_0CMG_Search_QAE_XZ
 * Symbol: ??0CMG_Search@@QAE@XZ
 * Original: 0x003C5FD0 - 0x003C5FEB (27 bytes, 9 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003C5FD0_0CMG_Search_QAE_XZ(void)
{

loc_003C5FD0:
    ecx = 0; /* xor self */
    MEM32(eax + 4) = ecx;
    MEM32(eax + 8) = ecx;
    MEM32(eax + 0xC) = ecx;
    MEM32(eax + 0x10) = ecx;
    MEM32(eax + 0x14) = ecx;
    MEM32(eax + 0x18) = ecx;
    MEM32(eax) = 0x557E2C;
    esp += 4; return; /* ret */

}

/**
 * fn_003C5FF0_CMG_SearchFactionThreat_Relevance
 * Symbol: ?Relevance@CMG_SearchFactionThreat@@UAEMAAVCMemberStatus@@@Z
 * Original: 0x003C5FF0 - 0x003C6017 (39 bytes, 13 insns)
 * Category: game_audio
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003C5FF0_CMG_SearchFactionThreat_Relevance(void)
{
    int _flags = 0; /* fallback flag var */
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_003C5FF0:
    esp = esp - 0x24;
    PUSH32(esp, ebx);
    ebx = ecx;
    eax = MEM32(ebx + 0x10);
    eax = MEM32(eax + 0x44);
    eax = eax + 0x8C;
    PUSH32(esp, 0); fn_0030BBD0_CAIThreatTracker_ForceChooseThreat(); /* call 0x0030BBD0 */

loc_003C6006:
    if (TEST_Z(eax, eax)) { sub_003C6017(); return; } /* je: equal / zero */

loc_003C600A:
    fp_push(MEMF(0x561408)); /* fld float */
    POP32(esp, ebx);
    esp = esp + 0x24;
    esp += 8; return; /* ret 4 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_003C6017
 * Original: 0x003C6017 - 0x003C612F (280 bytes, 98 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003C6017(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    int _fpu_cmp = 0; /* FPU compare result: -1/0/1 */
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C6017:
    PUSH32(esp, ebp);
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    PUSH32(esp, 0); fn_00184970_CSpawnManager_Get(); /* call 0x00184970 */

loc_003C601F:
    esi = MEM32(eax + 0x44);
    eax = eax + 0x3C;
    (void)0; /* test esi, esi - flags set for next jcc */
    MEM32(esp + 0x10) = esi;
    if (TEST_NZ(esi, esi)) goto loc_003C6041; /* jne: not equal / not zero */

loc_003C602D:
    fp_push(MEMF(0x561408)); /* fld float */
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp = esp + 0x24;
    esp += 8; return; /* ret 4 */

loc_003C603D:
    esi = MEM32(esp + 0x10);

loc_003C6041:
    edi = MEM32(esi);
    edx = MEM32(edi);
    ecx = edi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xC4), _icall_esp); /* indirect call */
    }

loc_003C604D:
    if (TEST_NZ(LO8(eax), LO8(eax))) goto loc_003C6110; /* jne: not equal / not zero */

loc_003C6055:
    eax = MEM32(ebx + 0x10);
    eax = MEM32(eax + 0x44);
    if (TEST_Z(eax, eax)) goto loc_003C6064; /* je: equal / zero */

loc_003C605F:
    eax = MEM32(eax + 0x24);
    goto loc_003C6066;

loc_003C6064:
    eax = 0; /* xor self */

loc_003C6066:
    ecx = MEM32(edi + 0x24);
    edx = MEM32(ecx + 0x164);
    if (CMP_NE(edx, MEM32(eax + 0x164))) goto loc_003C6110; /* jne: not equal / not zero */

loc_003C607B:
    ebp = edi + 0x8C;
    eax = ebp;
    PUSH32(esp, 0); fn_0030BB30_CAIThreatTracker_ChooseThreat(); /* call 0x0030BB30 */

loc_003C6088:
    if (TEST_Z(eax, eax)) goto loc_003C6110; /* je: equal / zero */

loc_003C6090:
    eax = MEM32(ebx + 0x10);
    ecx = MEM32(eax + 0x44);
    edx = MEM32(ecx);
    eax = esp + 0x1C;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x38), _icall_esp); /* indirect call */
    }

loc_003C60A0:
    edx = MEM32(edi);
    esi = eax;
    eax = esp + 0x28;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    ecx = edi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x38), _icall_esp); /* indirect call */
    }

loc_003C60AE:
    fp_push(MEMF(eax)); /* fld float */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    fp_push(MEMF(eax + 4)); /* fld float */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    fp_push(MEMF(eax + 8)); /* fld float */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    /* fld st(0) */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    /* fld st(2) */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* faddp */
    /* fld st(3) */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* faddp */
    fp_top() = sqrt(fp_top()); /* fsqrt */
    /* fstp st(3) */
    /* fstp st(0) */
    /* fstp st(0) */
    fp_push(MEMF(0x5614F4)); /* fld float */
    _fpu_cmp = (fp_top() < fp_st1()) ? -1 : (fp_top() > fp_st1()) ? 1 : 0; fp_pop(); /* fcompi */
    /* fstp st(0) */
    if ((_fpu_cmp < 0) /* fcompi */) goto loc_003C610C; /* jb: below (unsigned <) */

loc_003C60E2:
    eax = ebp;
    PUSH32(esp, 0); fn_0030BB30_CAIThreatTracker_ChooseThreat(); /* call 0x0030BB30 */

loc_003C60E9:
    edi = eax;
    ecx = MEM32(edi + 0x50);
    eax = MEM32(ecx + 0xF0);
    if (TEST_Z(eax, eax)) goto loc_003C610C; /* je: equal / zero */

loc_003C60F8:
    edx = MEM32(ebx + 0x10);
    esi = MEM32(edx + 0x44);
    eax = eax + 0x8C;
    PUSH32(esp, 0); fn_0030B390_CAIThreatTracker_FindThreatByActor(); /* call 0x0030B390 */

loc_003C6108:
    if (TEST_NZ(eax, eax)) { sub_003C612F(); return; } /* jne: not equal / not zero */

loc_003C610C:
    esi = MEM32(esp + 0x10);

loc_003C6110:
    eax = MEM32(esi + 4);
    (void)0; /* test eax, eax - flags set for next jcc */
    MEM32(esp + 0x10) = eax;
    if (TEST_NZ(eax, eax)) goto loc_003C603D; /* jne: not equal / not zero */

loc_003C611F:
    fp_push(MEMF(0x561408)); /* fld float */
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp = esp + 0x24;
    esp += 8; return; /* ret 4 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_003C612F
 * Original: 0x003C612F - 0x003C61BA (139 bytes, 41 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003C612F(void)
{
    uint32_t ebp;
    float xmm0;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C612F:
    edx = MEM32(edi + 0x50);
    eax = MEM32(ebx + 0x10);
    edi = MEM32(edx + 0xF0);
    ecx = MEM32(eax + 0x44);
    eax = MEM32(ecx);
    edx = esp + 0x28;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, edx);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x38), _icall_esp); /* indirect call */
    }

loc_003C6148:
    ecx = esp + 0x1C;
    esi = eax;
    eax = MEM32(edi);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ecx);
    ecx = edi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x38), _icall_esp); /* indirect call */
    }

loc_003C6156:
    xmm0 = MEMF(eax); /* movss */
    xmm0 = xmm0 - MEMF(esi); /* subss */
    MEMF(esp + 0x10) = xmm0; /* movss */
    xmm0 = MEMF(eax + 4); /* movss */
    xmm0 = xmm0 - MEMF(esi + 4); /* subss */
    MEMF(esp + 0x14) = xmm0; /* movss */
    xmm0 = MEMF(eax + 8); /* movss */
    xmm0 = xmm0 - MEMF(esi + 8); /* subss */
    eax = MEM32(esp + 0x10);
    ecx = ebx + 0x1C;
    edx = ecx;
    MEM32(edx) = eax;
    eax = MEM32(esp + 0x14);
    MEM32(edx + 4) = eax;
    MEMF(esp + 0x18) = xmm0; /* movss */
    eax = MEM32(esp + 0x18);
    xmm0 = 0.0f; /* xorps self = zero */
    MEM32(edx + 8) = eax;
    MEMF(ebx + 0x20) = xmm0; /* movss */
    PUSH32(esp, 0); fn_00011150_ZeroVector3_Normalize(); /* call 0x00011150 */

loc_003C61AA:
    fp_push(MEMF(0x561418)); /* fld float */
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp = esp + 0x24;
    esp += 8; return; /* ret 4 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_003C61C0_CMG_SearchFactionThreat_Execute
 * Symbol: ?Execute@CMG_SearchFactionThreat@@UAEXXZ
 * Original: 0x003C61C0 - 0x003C62CC (268 bytes, 89 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003C61C0_CMG_SearchFactionThreat_Execute(void)
{
    int _flags = 0; /* fallback flag var */

loc_003C61C0:
    eax = MEM32(0);
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x40909A);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0xC8;
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    edi = ecx;
    eax = MEM32(edi + 0x10);
    ecx = MEM32(eax + 0x44);
    if (TEST_Z(ecx, ecx)) goto loc_003C61F8; /* je: equal / zero */

loc_003C61E9:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 1);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 1);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x48), _icall_esp); /* indirect call */
    }

loc_003C61F8:
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    ecx = MEM32(edi + 0x10);
    PUSH32(esp, 0);
    esi = MEM32(ecx + 0x44);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    eax = MEM32(esi);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 2);
    PUSH32(esp, 1);
    edx = edi + 0x1C;
    PUSH32(esp, edx);
    ecx = esp + 0x4C;
    PUSH32(esp, ecx);
    ecx = esi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x40), _icall_esp); /* indirect call */
    }

loc_003C6228:
    PUSH32(esp, eax);
    PUSH32(esp, esi);
    edx = esp + 0x60;
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_00018CE0_0CAISoldierPathActionSetup_QAE_AAVCAISoldier_ABVZeroVector3_1W4TMovePosture_W4TIdlePosture_NPAVCAIActionHandle_PAV_ZeroList_VZeroVector3_444444PAMM_Z(); /* call 0x00018CE0 */

loc_003C6234:
    eax = esp + 0x20;
    PUSH32(esp, eax);
    ecx = esp + 0x10;
    PUSH32(esp, ecx);
    PUSH32(esp, 0x5FB008);
    MEM32(esp + 0xE4) = 0;
    PUSH32(esp, 0); fn_000191E0_AllocAction_VCAISoldierPathAction_VCAISoldierPathActionSetup_CAIResourceManager_IAE_AVCAIActionHandle_PAVCAISoldierPathAction_PAVCAISoldierPathActionSetup_Z(); /* call 0x000191E0 */

loc_003C6253:
    edx = MEM32(edi + 0x10);
    ecx = MEM32(edx + 0x44);
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0x63);
    edx = esp + 0x18;
    PUSH32(esp, edx);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0xB0), _icall_esp); /* indirect call */
    }

loc_003C626C:
    eax = MEM32(edi + 0x10);
    PUSH32(esp, 0x3F000000);
    PUSH32(esp, ecx);
    eax = eax + 0x100;
    esi = esp;
    MEM32(esp + 0x10) = esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_002019C0_7CTrigger_QAE_AVCCondition_XZ(); /* call 0x002019C0 */

loc_003C6286:
    PUSH32(esp, ecx);
    ecx = MEM32(0x60E050);
    eax = esp;
    MEM32(eax) = ecx;
    edx = MEM32(edi + 0x10);
    MEM32(esp + 0x14) = esp;
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_00041FC0_CreateScriptAction_VCNPCScript_YAPAVCScriptAction_PAVCNPCScript_VCRC_VCCondition_M_Z(); /* call 0x00041FC0 */

loc_003C629E:
    esp = esp + 0x10;
    esi = esp + 0x44;
    MEM32(esp + 0xD8) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_0002CE70_VCKOH_FactionControlData_ZeroList_RemoveAll(); /* call 0x0002CE70 */

loc_003C62B5:
    ecx = MEM32(esp + 0xD0);
    POP32(esp, edi);
    MEM32(0) = ecx;
    POP32(esp, esi);
    esp = esp + 0xD4;
    esp += 4; return; /* ret */

}

/**
 * fn_003C62D0_CMG_SearchAimAtLast_Execute
 * Symbol: ?Execute@CMG_SearchAimAtLast@@UAEXXZ
 * Original: 0x003C62D0 - 0x003C636C (156 bytes, 53 insns)
 * Category: game_audio
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003C62D0_CMG_SearchAimAtLast_Execute(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C62D0:
    eax = MEM32(0);
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x4090BC);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x114;
    PUSH32(esp, ebp);
    ebp = ecx;
    eax = MEM32(ebp + 0x10);
    ecx = MEM32(eax + 0x44);
    (void)0; /* test ecx, ecx - flags set for next jcc */
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    if (TEST_Z(ecx, ecx)) goto loc_003C6309; /* je: equal / zero */

loc_003C62FA:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 1);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 1);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x48), _icall_esp); /* indirect call */
    }

loc_003C6309:
    ecx = MEM32(ebp + 0x10);
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_0004A470_KillAllScriptActions_VCMemberSoldier_YAXPAVCMemberSoldier_Z(); /* call 0x0004A470 */

loc_003C6312:
    edx = MEM32(ebp + 0x10);
    eax = MEM32(edx + 0x44);
    esp = esp + 4;
    eax = eax + 0x8C;
    PUSH32(esp, 0); fn_0030BBD0_CAIThreatTracker_ForceChooseThreat(); /* call 0x0030BBD0 */

loc_003C6325:
    if (TEST_Z(eax, eax)) goto loc_003C6336; /* je: equal / zero */

loc_003C6329:
    eax = MEM32(eax + 0x50);
    eax = MEM32(eax + 0xF0);
    if (TEST_NZ(eax, eax)) goto loc_003C633E; /* jne: not equal / not zero */

loc_003C6336:
    eax = MEM32(ebp + 0x10);
    PUSH32(esp, 0); fn_001EA4A0_CGroupMemberScript_QG_GetGroupThreat(); /* call 0x001EA4A0 */

loc_003C633E:
    (void)0; /* cmp MEM8(ebp + 0x34), 1 - flags set for next jcc */
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    if (CMP_NE(MEM8(ebp + 0x34), 1)) { sub_003C6433(); return; } /* jne: not equal / not zero */

loc_003C634C:
    edx = MEM32(eax);
    ecx = esp + 0x3C;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ecx);
    ecx = eax;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x3C), _icall_esp); /* indirect call */
    }

loc_003C6358:
    eax = MEM32(ebp + 0x10);
    ecx = MEM32(eax + 0x44);
    if (TEST_Z(ecx, ecx)) { sub_003C636C(); return; } /* je: equal / zero */

loc_003C6362:
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x80), _icall_esp); /* indirect call */
    }

loc_003C636A:
    g_seh_ebp = ebp; sub_003C636E(); return; /* tail jmp 0x003C636E */

}

/**
 * sub_003C636C
 * Original: 0x003C636C - 0x003C636E (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003C636C(void)
{

loc_003C636C:
    eax = 0; /* xor self */

}

/**
 * sub_003C636E
 * Original: 0x003C636E - 0x003C6433 (197 bytes, 65 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003C636E(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C636E:
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 1);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    esi = 0; /* xor self */
    ecx = esp + 0x60;
    PUSH32(esp, 0); fn_0001AB60_0CAISoldierUseCoverActionSetup_QAE_PAVCAISoldier_W4TCoverType_N22PAVZeroVector3_222H_Z(); /* call 0x0001AB60 */

loc_003C6389:
    eax = esp + 0x10;
    PUSH32(esp, eax);
    PUSH32(esp, 0x5FB008);
    edi = esp + 0x48;
    PUSH32(esp, 0); fn_0001AE80_AllocAction_VCAISoldierUseCoverAction_VCAISoldierUseCoverActionSetup_CAIResourceManager_IAE_AVCAIActionHandle_PAVCAISoldierUseCoverAction_PAVCAISoldierUseCoverActionSet(); /* call 0x0001AE80 */

loc_003C639C:
    ecx = MEM32(ebp + 0x10);
    ecx = MEM32(ecx + 0x44);
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, esi);
    PUSH32(esp, esi);
    PUSH32(esp, 0x63);
    eax = esp + 0x1C;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xB0), _icall_esp); /* indirect call */
    }

loc_003C63B3:
    PUSH32(esp, esi);
    PUSH32(esp, 1);
    PUSH32(esp, esi);
    ecx = esp + 0x2C;
    PUSH32(esp, 0x40A00000);
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_001EEBE0_CTimerTrigger_CreateTrigger(); /* call 0x001EEBE0 */

loc_003C63C6:
    esp = esp + 0x14;
    PUSH32(esp, esi);
    PUSH32(esp, ecx);
    MEM32(esp + 0x130) = esi;
    edx = MEM32(esp + 0x38);
    eax = esp;
    MEM32(eax) = edx;
    ecx = MEM32(esp + 0x38);
    (void)0; /* test ecx, ecx - flags set for next jcc */
    MEM32(esp + 0x14) = esp;
    if (TEST_Z(ecx, ecx)) goto loc_003C63EB; /* je: equal / zero */

loc_003C63E6:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x34), _icall_esp); /* indirect call */
    }

loc_003C63EB:
    PUSH32(esp, ecx);
    ecx = MEM32(0x60E050);
    eax = esp;
    MEM32(eax) = ecx;
    edx = MEM32(ebp + 0x10);
    MEM32(esp + 0x18) = esp;
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_00041FC0_CreateScriptAction_VCNPCScript_YAPAVCScriptAction_PAVCNPCScript_VCRC_VCCondition_M_Z(); /* call 0x00041FC0 */

loc_003C6403:
    esp = esp + 0x10;
    eax = esp + 0x20;
    PUSH32(esp, eax);
    MEM32(esp + 0x12C) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_0002F150_1CTrigger_UAE_XZ(); /* call 0x0002F150 */

loc_003C641B:
    ecx = MEM32(esp + 0x120);
    MEM32(0) = ecx;
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    esp = esp + 0x120;
    esp += 4; return; /* ret */

}

/**
 * sub_003C6433
 * Original: 0x003C6433 - 0x003C6564 (305 bytes, 99 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003C6433(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C6433:
    PUSH32(esp, 0);
    ecx = MEM32(ebp + 0x10);
    PUSH32(esp, 0);
    eax = MEM32(ecx + 0x44);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 2);
    PUSH32(esp, 1);
    edx = ebp + 0x28;
    PUSH32(esp, edx);
    edi = ebp + 0x1C;
    PUSH32(esp, edi);
    PUSH32(esp, eax);
    eax = esp + 0xB0;
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_00018CE0_0CAISoldierPathActionSetup_QAE_AAVCAISoldier_ABVZeroVector3_1W4TMovePosture_W4TIdlePosture_NPAVCAIActionHandle_PAV_ZeroList_VZeroVector3_444444PAMM_Z(); /* call 0x00018CE0 */

loc_003C6465:
    ecx = esp + 0x70;
    PUSH32(esp, ecx);
    edx = esp + 0x1C;
    PUSH32(esp, edx);
    PUSH32(esp, 0x5FB008);
    MEM32(esp + 0x134) = 1;
    PUSH32(esp, 0); fn_000191E0_AllocAction_VCAISoldierPathAction_VCAISoldierPathActionSetup_CAIResourceManager_IAE_AVCAIActionHandle_PAVCAISoldierPathAction_PAVCAISoldierPathActionSetup_Z(); /* call 0x000191E0 */

loc_003C6484:
    eax = MEM32(ebp + 0x10);
    ecx = MEM32(eax + 0x44);
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0x63);
    eax = esp + 0x24;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xB0), _icall_esp); /* indirect call */
    }

loc_003C649D:
    PUSH32(esp, 0x3F800000);
    PUSH32(esp, ecx);
    ecx = MEM32(ebp + 0x10);
    ecx = ecx + 0x100;
    esi = esp;
    MEM32(esp + 0x14) = esp;
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_002019C0_7CTrigger_QAE_AVCCondition_XZ(); /* call 0x002019C0 */

loc_003C64B8:
    edx = MEM32(0x60E050);
    PUSH32(esp, ecx);
    eax = esp;
    MEM32(eax) = edx;
    eax = MEM32(ebp + 0x10);
    MEM32(esp + 0x18) = esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_00041FC0_CreateScriptAction_VCNPCScript_YAPAVCScriptAction_PAVCNPCScript_VCRC_VCCondition_M_Z(); /* call 0x00041FC0 */

loc_003C64D0:
    ebp = MEM32(ebp + 0x10);
    eax = MEM32(ebp + 0x44);
    esp = esp + 0x10;
    if (TEST_Z(eax, eax)) goto loc_003C6535; /* je: equal / zero */

loc_003C64DD:
    eax = MEM32(eax + 0x24);
    if (TEST_Z(eax, eax)) goto loc_003C6535; /* je: equal / zero */

loc_003C64E4:
    ecx = MEM32(eax + 0x154);
    edx = 2;
    if (CMP_NE(ecx, edx)) goto loc_003C6535; /* jne: not equal / not zero */

loc_003C64F3:
    ecx = MEM32(eax + 0x100);
    if (TEST_Z(ecx, ecx)) goto loc_003C6535; /* je: equal / zero */

loc_003C64FD:
    eax = MEM32(ebp + 0x44);
    if (TEST_Z(eax, eax)) goto loc_003C6509; /* je: equal / zero */

loc_003C6504:
    ecx = MEM32(eax + 0x24);
    goto loc_003C650B;

loc_003C6509:
    ecx = 0; /* xor self */

loc_003C650B:
    ebp = MEM32(ebp + 0x44);
    if (TEST_Z(ebp, ebp)) goto loc_003C6529; /* je: equal / zero */

loc_003C6512:
    eax = MEM32(ebp + 0x24);
    if (TEST_Z(eax, eax)) goto loc_003C6529; /* je: equal / zero */

loc_003C6519:
    if (CMP_NE(MEM32(eax + 0x154), edx)) goto loc_003C6529; /* jne: not equal / not zero */

loc_003C6521:
    eax = MEM32(eax + 0x100);
    goto loc_003C652B;

loc_003C6529:
    eax = 0; /* xor self */

loc_003C652B:
    PUSH32(esp, edi);
    PUSH32(esp, ecx);
    eax = eax + 0x28;
    PUSH32(esp, 0); fn_0038D740_CGroupBlackboard_ReportMovement(); /* call 0x0038D740 */

loc_003C6535:
    esi = esp + 0x94;
    MEM32(esp + 0x128) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_0002CE70_VCKOH_FactionControlData_ZeroList_RemoveAll(); /* call 0x0002CE70 */

loc_003C654C:
    ecx = MEM32(esp + 0x120);
    POP32(esp, edi);
    POP32(esp, esi);
    MEM32(0) = ecx;
    POP32(esp, ebp);
    esp = esp + 0x120;
    esp += 4; return; /* ret */

}

/**
 * fn_003C6570_CMG_SearchAimAtLast_Relevance
 * Symbol: ?Relevance@CMG_SearchAimAtLast@@UAEMAAVCMemberStatus@@@Z
 * Original: 0x003C6570 - 0x003C6756 (486 bytes, 158 insns)
 * Category: game_audio
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003C6570_CMG_SearchAimAtLast_Relevance(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_003C6570:
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ebp);
    ebp = esp;
    esp = esp & 0xFFFFFFF0u;
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x40ABE7);
    eax = MEM32(0);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x1D8;
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    esi = ecx;
    eax = MEM32(esi + 0x10);
    eax = MEM32(eax + 0x44);
    ecx = MEM32(eax + 0x2F8);
    edx = MEM32(ecx);
    PUSH32(esp, edi);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xF8), _icall_esp); /* indirect call */
    }

loc_003C65AA:
    if (TEST_NZ(LO8(eax), LO8(eax))) goto loc_003C66BF; /* jne: not equal / not zero */

loc_003C65B2:
    eax = MEM32(esi + 0x10);
    eax = MEM32(eax + 0x44);
    eax = eax + 0x8C;
    PUSH32(esp, 0); fn_0030BBD0_CAIThreatTracker_ForceChooseThreat(); /* call 0x0030BBD0 */

loc_003C65C2:
    if (TEST_Z(eax, eax)) goto loc_003C65D3; /* je: equal / zero */

loc_003C65C6:
    ecx = MEM32(eax + 0x50);
    ebx = MEM32(ecx + 0xF0);
    if (TEST_NZ(ebx, ebx)) goto loc_003C6615; /* jne: not equal / not zero */

loc_003C65D3:
    eax = MEM32(esi + 0x10);
    PUSH32(esp, 0); fn_001EA4A0_CGroupMemberScript_QG_GetGroupThreat(); /* call 0x001EA4A0 */

loc_003C65DB:
    if (TEST_Z(eax, eax)) goto loc_003C66BF; /* je: equal / zero */

loc_003C65E3:
    edx = MEM32(esi + 0x10);
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_001E7710_CMemberSoldier_AddGroupThreatsToTracker(); /* call 0x001E7710 */

loc_003C65EC:
    eax = MEM32(esi + 0x10);
    eax = MEM32(eax + 0x44);
    eax = eax + 0x8C;
    PUSH32(esp, 0); fn_0030BBD0_CAIThreatTracker_ForceChooseThreat(); /* call 0x0030BBD0 */

loc_003C65FC:
    if (TEST_Z(eax, eax)) goto loc_003C66BF; /* je: equal / zero */

loc_003C6604:
    ecx = MEM32(eax + 0x50);
    ebx = MEM32(ecx + 0xF0);
    if (TEST_Z(ebx, ebx)) goto loc_003C66BF; /* je: equal / zero */

loc_003C6615:
    edx = MEM32(esi + 0x10);
    eax = MEM32(ebx);
    edi = MEM32(edx + 0x44);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    ecx = esp + 0x1C;
    PUSH32(esp, ecx);
    ecx = ebx;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x3C), _icall_esp); /* indirect call */
    }

loc_003C662B:
    edx = MEM32(edi);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    eax = esp + 0x30;
    PUSH32(esp, eax);
    ecx = edi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x3C), _icall_esp); /* indirect call */
    }

loc_003C663C:
    ecx = MEM32(esi + 0x10);
    PUSH32(esp, eax);
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_001EB3D0_CGroupMemberScript_PositionIsFiringPos(); /* call 0x001EB3D0 */

loc_003C6646:
    if (TEST_NZ(LO8(eax), LO8(eax))) { sub_003C69A2(); return; } /* jne: not equal / not zero */

loc_003C664E:
    ecx = MEM32(esi + 0x10);
    edx = MEM32(ecx);
    eax = esp + 0x140;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xD4), _icall_esp); /* indirect call */
    }

loc_003C6661:
    edx = MEM32(eax + 0x74);
    PUSH32(esp, ecx);
    eax = eax + 0x74;
    ecx = esp;
    MEM32(esp + 0x28) = esp;
    MEM32(ecx) = edx;
    PUSH32(esp, 0); fn_002047A0_CScriptManager_Get(); /* call 0x002047A0 */

loc_003C6675:
    PUSH32(esp, 0); fn_00202970_CScriptManager_GetPath(); /* call 0x00202970 */

loc_003C667A:
    edi = eax;
    (void)0; /* test edi, edi - flags set for next jcc */
    eax = MEM32(esi + 0x10);
    ecx = MEM32(eax + 0x44);
    MEM32(esp + 0x30) = edi;
    if (TEST_Z(edi, edi)) { sub_003C67F3(); return; } /* je: equal / zero */

loc_003C668E:
    edx = MEM32(ebx);
    eax = esp + 0x14;
    MEM32(esp + 0x20) = ecx;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    ecx = ebx;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x40), _icall_esp); /* indirect call */
    }

loc_003C669E:
    ecx = MEM32(esp + 0x20);
    edx = MEM32(ecx);
    eax = esp + 0x24;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x40), _icall_esp); /* indirect call */
    }

loc_003C66AC:
    eax = MEM32(edi + 4);
    (void)0; /* test eax, eax - flags set for next jcc */
    MEM32(esp + 0x24) = eax;
    MEM32(esp + 0x20) = 0;
    if (CMP_G(eax & eax, 0)) goto loc_003C66E0; /* jg: greater (signed >) */

loc_003C66BF:
    fp_push(MEMF(0x561408)); /* fld float */
    ecx = MEM32(esp + 0x1E4);
    MEM32(0) = ecx;
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp = ebp;
    POP32(esp, ebp);
    esp += 8; return; /* ret 4 */

loc_003C66DC:
    edi = MEM32(esp + 0x30);

loc_003C66E0:
    ecx = MEM32(esp + 0x20);
    eax = edi;
    PUSH32(esp, 0); fn_003A08C0_CPath_GetLocator(); /* call 0x003A08C0 */

loc_003C66EB:
    ecx = MEM32(eax);
    MEM32(esp + 0x14) = ecx;
    edx = MEM32(eax + 4);
    MEM32(esp + 0x18) = edx;
    eax = MEM32(eax + 8);
    MEM32(esp + 0x1C) = eax;
    eax = MEM32(esi + 0x10);
    edi = esp + 0x14;
    PUSH32(esp, 0); fn_001EB690_CGroupMemberScript_PositionClean(); /* call 0x001EB690 */

loc_003C670B:
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_003C6740; /* je: equal / zero */

loc_003C670F:
    edx = MEM32(esi + 0x10);
    ecx = edi;
    PUSH32(esp, ecx);
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_001EA580_CGroupMemberScript_PositionClear(); /* call 0x001EA580 */

loc_003C671B:
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_003C6740; /* je: equal / zero */

loc_003C671F:
    eax = MEM32(ebx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    ecx = esp + 0x54;
    PUSH32(esp, ecx);
    ecx = ebx;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x3C), _icall_esp); /* indirect call */
    }

loc_003C672F:
    PUSH32(esp, eax);
    eax = MEM32(esi + 0x10);
    edx = edi;
    PUSH32(esp, edx);
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_001EB3D0_CGroupMemberScript_PositionIsFiringPos(); /* call 0x001EB3D0 */

loc_003C673C:
    if (TEST_NZ(LO8(eax), LO8(eax))) { sub_003C6756(); return; } /* jne: not equal / not zero */

loc_003C6740:
    eax = MEM32(esp + 0x20);
    ecx = MEM32(esp + 0x24);
    eax++;
    (void)0; /* cmp eax, ecx - flags set for next jcc */
    MEM32(esp + 0x20) = eax;
    if (CMP_L(eax, ecx)) goto loc_003C66DC; /* jl: less (signed <) */

loc_003C6751:
    goto loc_003C66BF;

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/* Fallback for unresolved generated target 0x003C66BF. */
void sub_003C66BF(void)
{
    recomp_missing_target(0x003C66BFu);
}

/**
 * sub_003C6756
 * Original: 0x003C6756 - 0x003C67F3 (157 bytes, 42 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003C6756(void)
{
    uint32_t ebp;
    float xmm0;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C6756:
    edx = MEM32(esp + 0x14);
    eax = MEM32(esp + 0x18);
    ecx = esi + 0x1C;
    MEM32(ecx) = edx;
    edx = MEM32(esp + 0x1C);
    MEM32(ecx + 4) = eax;
    MEM32(ecx + 8) = edx;
    ecx = MEM32(esi + 0x10);
    eax = MEM32(ecx);
    edx = esp + 0x4C;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, edx);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x30), _icall_esp); /* indirect call */
    }

loc_003C677A:
    xmm0 = MEMF(esp + 0x14); /* movss */
    xmm0 = xmm0 - MEMF(eax); /* subss */
    MEMF(esp + 0x24) = xmm0; /* movss */
    xmm0 = MEMF(esp + 0x18); /* movss */
    xmm0 = xmm0 - MEMF(eax + 4); /* subss */
    edx = MEM32(esp + 0x24);
    MEMF(esp + 0x28) = xmm0; /* movss */
    xmm0 = MEMF(esp + 0x1C); /* movss */
    xmm0 = xmm0 - MEMF(eax + 8); /* subss */
    ecx = esi + 0x28;
    eax = ecx;
    MEM32(eax) = edx;
    edx = MEM32(esp + 0x28);
    MEM32(eax + 4) = edx;
    MEMF(esp + 0x2C) = xmm0; /* movss */
    edx = MEM32(esp + 0x2C);
    xmm0 = 0.0f; /* xorps self = zero */
    MEM32(eax + 8) = edx;
    MEMF(esi + 0x2C) = xmm0; /* movss */
    PUSH32(esp, 0); fn_00011150_ZeroVector3_Normalize(); /* call 0x00011150 */

loc_003C67D2:
    fp_push(MEMF(0x561418)); /* fld float */
    MEM8(esi + 0x34) = 0;
    ecx = MEM32(esp + 0x1E4);
    MEM32(0) = ecx;
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp = ebp;
    POP32(esp, ebp);
    esp += 8; return; /* ret 4 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_003C67F3
 * Original: 0x003C67F3 - 0x003C6832 (63 bytes, 24 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003C67F3(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C67F3:
    edx = MEM32(ecx);
    eax = esp + 0x58;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x38), _icall_esp); /* indirect call */
    }

loc_003C67FD:
    edx = MEM32(ebx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    eax = esp + 0x48;
    PUSH32(esp, eax);
    ecx = ebx;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x3C), _icall_esp); /* indirect call */
    }

loc_003C680D:
    eax = MEM32(esi + 0x10);
    PUSH32(esp, 0);
    ecx = esp + 0x38;
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_001E3840_CMemberSoldier_GetCoverSearchCenter(); /* call 0x001E3840 */

loc_003C681C:
    eax = MEM32(esi + 0x10);
    ecx = MEM32(eax + 0x44);
    if (TEST_Z(ecx, ecx)) { sub_003C6832(); return; } /* je: equal / zero */

loc_003C6826:
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x80), _icall_esp); /* indirect call */
    }

loc_003C682E:
    edi = eax;
    g_seh_ebp = ebp; sub_003C6834(); return; /* tail jmp 0x003C6834 */

}

/**
 * sub_003C6832
 * Original: 0x003C6832 - 0x003C6834 (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003C6832(void)
{

loc_003C6832:
    edi = 0; /* xor self */

}

/**
 * sub_003C6834
 * Original: 0x003C6834 - 0x003C6986 (338 bytes, 93 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003C6834(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C6834:
    PUSH32(esp, 0);
    PUSH32(esp, 0x3F800000);
    PUSH32(esp, 1);
    PUSH32(esp, 0);
    eax = esp + 0x50;
    PUSH32(esp, eax);
    PUSH32(esp, 1);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    eax = MEM32(esi + 0x10);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    ecx = esp + 0x6C;
    PUSH32(esp, ecx);
    PUSH32(esp, 1);
    PUSH32(esp, 1);
    PUSH32(esp, 0);
    edx = esp + 0x188;
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_001E3950_CMemberSoldier_GetCoverSearchShape(); /* call 0x001E3950 */

loc_003C6871:
    PUSH32(esp, eax);
    PUSH32(esp, edi);
    eax = esp + 0xB8;
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_00016AA0_0CAISoldierTakeCoverActionSetup_QAE_PAVCAISoldier_ABVCAITakeCoverSearchShape_NPAVZeroVector3_PAV_ZeroList_VZeroVector3_W4TCoverType_22233223W4TSearchType_2MH_Z(); /* call 0x00016AA0 */

loc_003C6880:
    ecx = esp + 0x70;
    PUSH32(esp, ecx);
    edx = esp + 0x28;
    PUSH32(esp, edx);
    MEM32(esp + 0x1F4) = 0;
    PUSH32(esp, 0x5FB008);
    MEM32(esp + 0x140) = 0x82;
    PUSH32(esp, 0); fn_000159E0_AllocAction_VCAISoldierTakeCoverAction_VCAISoldierTakeCoverActionSetup_CAIResourceManager_IAE_AVCAIActionHandle_PAVCAISoldierTakeCoverAction_PAVCAISoldierTakeCoverActio(); /* call 0x000159E0 */

loc_003C68AA:
    edx = esp + 0x24;
    ecx = 0x5FB008;
    PUSH32(esp, 0); fn_00011420_CAIResourceManager_GetActionPtrFromHandle(); /* call 0x00011420 */

loc_003C68B8:
    if (TEST_Z(eax, eax)) { sub_003C6986(); return; } /* je: equal / zero */

loc_003C68C0:
    eax = eax + 0x110;
    edx = eax;
    eax = MEM32(edx);
    ecx = MEM32(edx + 4);
    edx = MEM32(edx + 8);
    edi = esi + 0x1C;
    MEM32(edi) = eax;
    MEM32(edi + 4) = ecx;
    MEM32(esp + 0x14) = eax;
    eax = MEM32(esi + 0x10);
    MEM32(edi + 8) = edx;
    MEM32(esp + 0x18) = ecx;
    ecx = MEM32(eax + 0x44);
    eax = esp + 0x64;
    MEM32(esp + 0x1C) = edx;
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x40), _icall_esp); /* indirect call */
    }

loc_003C68F6:
    xmm2 = MEMF(esp + 0x14); /* movss */
    xmm2 = xmm2 - MEMF(eax); /* subss */
    xmm0 = MEMF(esp + 0x1C); /* movss */
    xmm0 = xmm0 - MEMF(eax + 8); /* subss */
    xmm1 = MEMF(esp + 0x18); /* movss */
    xmm1 = xmm1 - MEMF(eax + 4); /* subss */
    ecx = esi + 0x28;
    MEMF(esp + 0x14) = xmm2; /* movss */
    eax = MEM32(esp + 0x14);
    edx = ecx;
    MEM32(edx) = eax;
    MEMF(esp + 0x18) = xmm1; /* movss */
    eax = MEM32(esp + 0x18);
    MEM32(edx + 4) = eax;
    MEMF(esp + 0x1C) = xmm0; /* movss */
    eax = MEM32(esp + 0x1C);
    xmm0 = 0.0f; /* xorps self = zero */
    MEM32(edx + 8) = eax;
    MEMF(esi + 0x2C) = xmm0; /* movss */
    PUSH32(esp, 0); fn_00011150_ZeroVector3_Normalize(); /* call 0x00011150 */

loc_003C694E:
    MEM8(esi + 0x34) = 0;
    esi = esp + 0x98;
    MEM32(esp + 0x1EC) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_0002CE70_VCKOH_FactionControlData_ZeroList_RemoveAll(); /* call 0x0002CE70 */

loc_003C6969:
    fp_push(MEMF(0x561418)); /* fld float */
    ecx = MEM32(esp + 0x1E4);
    MEM32(0) = ecx;
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp = ebp;
    POP32(esp, ebp);
    esp += 8; return; /* ret 4 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_003C6986
 * Original: 0x003C6986 - 0x003C69A2 (28 bytes, 4 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003C6986(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C6986:
    esi = esp + 0x98;
    MEM32(esp + 0x1EC) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_0002CE70_VCKOH_FactionControlData_ZeroList_RemoveAll(); /* call 0x0002CE70 */

loc_003C699D:
    g_seh_ebp = ebp; sub_003C66BF(); return; /* tail jmp 0x003C66BF */

}

/**
 * sub_003C69A2
 * Original: 0x003C69A2 - 0x003C69C3 (33 bytes, 10 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003C69A2(void)
{
    uint32_t ebp;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003C69A2:
    ecx = MEM32(esp + 0x1E4);
    fp_push(MEMF(0x561418)); /* fld float */
    POP32(esp, edi);
    MEM8(esi + 0x34) = 1;
    POP32(esp, esi);
    MEM32(0) = ecx;
    POP32(esp, ebx);
    esp = ebp;
    POP32(esp, ebp);
    esp += 8; return; /* ret 4 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}
