/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: dsound/codecs/sase3200/codegain.c
 * Functions: 2
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_0006C480_QuanGainSC3
 * Symbol: _QuanGainSC3
 * Original: 0x0006C480 - 0x0006C495 (21 bytes, 7 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0006C480_QuanGainSC3(void)
{

loc_0006C480:
    eax = MEM32(esp + 4);
    PUSH32(esp, 0x40);
    PUSH32(esp, 0x50D238);
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0007A790_ScalarQuant(); /* call 0x0007A790 */

loc_0006C491:
    esp = esp + 0xC;
    esp += 4; return; /* ret */

}

/**
 * fn_0006C4A0_UnQuanGainSC3
 * Symbol: _UnQuanGainSC3
 * Original: 0x0006C4A0 - 0x0006C4B5 (21 bytes, 7 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0006C4A0_UnQuanGainSC3(void)
{

loc_0006C4A0:
    eax = MEM32(esp + 4);
    PUSH32(esp, eax);
    PUSH32(esp, 0x40);
    PUSH32(esp, 0x50D238);
    PUSH32(esp, 0); fn_0007A890_ScalarLUT(); /* call 0x0007A890 */

loc_0006C4B1:
    esp = esp + 0xC;
    esp += 4; return; /* ret */

}
