/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: dsound/codecs/sase3200/oladd.c
 * Functions: 5
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_000967C0_OlAdd
 * Symbol: _OlAdd
 * Original: 0x000967C0 - 0x00096867 (167 bytes, 64 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_000967C0_OlAdd(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_000967C0:
    eax = MEM32(esp + 0x14);
    ecx = MEM32(esp + 4);
    PUSH32(esp, ebx);
    ebx = MEM32(esp + 0x14);
    PUSH32(esp, edi);
    edi = MEM32(esp + 0x14);
    ebx = ebx - edi;
    if (TEST_Z(LO8(ebx), 1)) goto loc_000967E6; /* je: equal / zero */

loc_000967D9:
    fp_push(MEMF(ecx)); /* fld float */
    ecx = ecx + 4;
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    eax = eax + 4;
    MEMF(eax + -4) = (float)fp_top(); fp_popp(); /* fstp */

loc_000967E6:
    ebx = (uint32_t)((int32_t)ebx >> 1);
    (void)0; /* cmp ebx, 4 - flags set for next jcc */
    PUSH32(esp, esi);
    edx = ebx;
    if (CMP_L(ebx, 4)) goto loc_00096843; /* jl: less (signed <) */

loc_000967F0:
    esi = ebx + -4;
    esi = esi >> 2;
    esi++;
    edx = esi * 4;
    PUSH32(esp, ebp);
    ebp = edx;
    edx = ebx;
    edx = edx - ebp;
    POP32(esp, ebp);

loc_00096806:
    fp_push(MEMF(ecx)); /* fld float */
    ecx = ecx + 4;
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    eax = eax + 4;
    ecx = ecx + 4;
    eax = eax + 4;
    MEMF(eax + -8) = (float)fp_top(); fp_popp(); /* fstp */
    ecx = ecx + 4;
    fp_push(MEMF(ecx + -8)); /* fld float */
    eax = eax + 4;
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    ecx = ecx + 4;
    eax = eax + 4;
    esi--;
    MEMF(eax + -12) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(ecx + -8)); /* fld float */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(eax + -8) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(ecx + -4)); /* fld float */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(eax + -4) = (float)fp_top(); fp_popp(); /* fstp */
    if ((esi != 0)) goto loc_00096806; /* jne: not equal / not zero */

loc_00096843:
    if (CMP_LE(edx & edx, 0)) goto loc_00096857; /* jle: less or equal (signed <=) */

loc_00096847:
    fp_push(MEMF(ecx)); /* fld float */
    ecx = ecx + 4;
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    eax = eax + 4;
    edx--;
    MEMF(eax + -4) = (float)fp_top(); fp_popp(); /* fstp */
    if ((edx != 0)) goto loc_00096847; /* jne: not equal / not zero */

loc_00096857:
    if (CMP_LE(edi & edi, 0)) { sub_00096867(); return; } /* jle: less or equal (signed <=) */

loc_0009685B:
    fp_push((double)SMEM32(esp + 0x18)); /* fild */
    /* FPU: fdivr dword ptr [0x561418] */
    g_seh_ebp = ebp; sub_0009686D(); return; /* tail jmp 0x0009686D */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_00096867
 * Original: 0x00096867 - 0x0009686D (6 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00096867(void)
{
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_00096867:
    fp_push(MEMF(0x561408)); /* fld float */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_0009686D
 * Original: 0x0009686D - 0x00096940 (211 bytes, 68 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0009686D(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_0009686D:
    (void)0; /* cmp edi, 4 - flags set for next jcc */
    fp_push(MEMF(0x561408)); /* fld float */
    fp_push(MEMF(0x561418)); /* fld float */
    MEMF(esp + 0x1C) = (float)fp_top(); fp_pop(); /* fst */
    if (CMP_L(edi, 4)) { sub_00096940(); return; } /* jl: less (signed <) */

loc_00096886:
    esi = edi + -4;
    esi = esi >> 2;
    esi++;
    edx = esi * 4;
    edi = edi - edx;
    edx = MEM32(esp + 0x14);
    /* nop */

loc_000968A0:
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    ecx = ecx + 4;
    /* fld st(1) */
    eax = eax + 4;
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    ecx = ecx + 4;
    eax = eax + 4;
    fp_st1() += fp_top(); fp_pop(); /* faddp */
    ecx = ecx + 4;
    eax = eax + 4;
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    ecx = ecx + 4;
    eax = eax + 4;
    edx = edx + 0x10;
    esi--;
    MEMF(eax + -16) = (float)fp_top(); fp_popp(); /* fstp */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    fp_push(MEMF(esp + 0x1C)); /* fld float */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    /* fld st(1) */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    /* fld st(1) */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* faddp */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(eax + -12) = (float)fp_top(); fp_popp(); /* fstp */
    { double _t = fp_top(); fp_top() = fp_st1(); fp_st1() = _t; } /* fxch */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(esp + 0x18) = (float)fp_top(); fp_popp(); /* fstp */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    fp_push(MEMF(esp + 0x18)); /* fld float */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    /* fld st(1) */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* faddp */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(eax + -8) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp + 0x18)); /* fld float */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(esp + 0x18) = (float)fp_top(); fp_popp(); /* fstp */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    MEMF(esp + 0x1C) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp + 0x18)); /* fld float */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_push(MEMF(esp + 0x1C)); /* fld float */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* faddp */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(eax + -4) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp + 0x18)); /* fld float */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    fp_push(MEMF(esp + 0x1C)); /* fld float */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    MEMF(esp + 0x1C) = (float)fp_top(); fp_pop(); /* fst */
    if ((esi != 0)) goto loc_000968A0; /* jne: not equal / not zero */

loc_0009693E:
    g_seh_ebp = ebp; sub_00096944(); return; /* tail jmp 0x00096944 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_00096940
 * Original: 0x00096940 - 0x00096944 (4 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00096940(void)
{

loc_00096940:
    edx = MEM32(esp + 0x14);

}

/**
 * sub_00096944
 * Original: 0x00096944 - 0x000969E8 (164 bytes, 66 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00096944(void)
{
    int _flags = 0; /* fallback flag var */
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_00096944:
    if (CMP_LE(edi & edi, 0)) goto loc_00096976; /* jle: less or equal (signed <=) */

loc_00096948:
    esi = edi;
    /* nop */

loc_00096950:
    /* fld st(0) */
    ecx = ecx + 4;
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    eax = eax + 4;
    /* fld st(2) */
    edx = edx + 4;
    esi--;
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* faddp */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(eax + -4) = (float)fp_top(); fp_popp(); /* fstp */
    { double _t = fp_top(); fp_top() = fp_st1(); fp_st1() = _t; } /* fxch */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    { double _t = fp_top(); fp_top() = fp_st1(); fp_st1() = _t; } /* fxch */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    if ((esi != 0)) goto loc_00096950; /* jne: not equal / not zero */

loc_00096976:
    (void)0; /* cmp ebx, 4 - flags set for next jcc */
    /* fstp st(0) */
    /* fstp st(0) */
    /* fstp st(0) */
    if (CMP_L(ebx, 4)) goto loc_000969CE; /* jl: less (signed <) */

loc_00096981:
    esi = ebx + -4;
    esi = esi >> 2;
    esi++;
    ecx = esi * 4;
    ebx = ebx - ecx;

loc_00096991:
    fp_push(MEMF(edx)); /* fld float */
    edx = edx + 4;
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    eax = eax + 4;
    edx = edx + 4;
    eax = eax + 4;
    MEMF(eax + -8) = (float)fp_top(); fp_popp(); /* fstp */
    edx = edx + 4;
    fp_push(MEMF(edx + -8)); /* fld float */
    eax = eax + 4;
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    edx = edx + 4;
    eax = eax + 4;
    esi--;
    MEMF(eax + -12) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(edx + -8)); /* fld float */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(eax + -8) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(edx + -4)); /* fld float */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(eax + -4) = (float)fp_top(); fp_popp(); /* fstp */
    if ((esi != 0)) goto loc_00096991; /* jne: not equal / not zero */

loc_000969CE:
    (void)0; /* test ebx, ebx - flags set for next jcc */
    POP32(esp, esi);
    if (CMP_LE(ebx & ebx, 0)) goto loc_000969E5; /* jle: less or equal (signed <=) */

loc_000969D3:
    ecx = ebx;

loc_000969D5:
    fp_push(MEMF(edx)); /* fld float */
    edx = edx + 4;
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    eax = eax + 4;
    ecx--;
    MEMF(eax + -4) = (float)fp_top(); fp_popp(); /* fstp */
    if ((ecx != 0)) goto loc_000969D5; /* jne: not equal / not zero */

loc_000969E5:
    POP32(esp, edi);
    POP32(esp, ebx);
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}
