/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: dsound/codecs/sase3200/refinec0.c
 * Functions: 3
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_000862B0_NellyRefineC0
 * Symbol: _NellyRefineC0
 * Original: 0x000862B0 - 0x000863BE (270 bytes, 84 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_000862B0_NellyRefineC0(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_000862B0:
    esp = esp - 0x1B4;
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x1CC);
    eax = 0; /* xor self */
    (void)0; /* test esi, esi - flags set for next jcc */
    PUSH32(esp, edi);
    if (CMP_LE(esi & esi, 0)) goto loc_000862FF; /* jle: less or equal (signed <=) */

loc_000862C6:
    ecx = MEM32(esp + 0x1CC);
    edx = esp + 0x30;
    ecx = ecx - edx;

loc_000862D3:
    edx = ecx + eax * 4;
    fp_push(MEMF(esp + edx + 0x30)); /* fld float */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(esp + 0x24) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp + 0x24)); /* fld float */
    MEM32(esp + 0x10) = (int32_t)fp_top(); /* fistp */
    edx = MEM32(esp + 0x10);
    MEM32(esp + eax * 4 + 0x30) = edx;
    eax++;
    if (CMP_L(eax, esi)) goto loc_000862D3; /* jl: less (signed <) */

loc_000862FF:
    eax = esp + 0x2C;
    PUSH32(esp, eax);
    ecx = esp + 0x24;
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_000780E0_GetPitchTable(); /* call 0x000780E0 */

loc_0008630E:
    eax = MEM32(esp + 0x34);
    ecx = MEM32(esp + 0x28);
    edx = MEM32(esp + 0x1CC);
    PUSH32(esp, eax);
    PUSH32(esp, ecx);
    PUSH32(esp, edx);
    MEM32(esp + 0x20) = edx;
    PUSH32(esp, 0); fn_0007A790_ScalarQuant(); /* call 0x0007A790 */

loc_00086329:
    ecx = MEM32(esp + 0x34);
    esp = esp + 0x14;
    if (CMP_B(eax, 1)) goto loc_0008635B; /* jb: below (unsigned <) */

loc_00086335:
    fp_push(MEMF(ecx + eax * 4)); /* fld float */
    edi = MEM32(esp + 0x2C);
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    edx = ecx + eax * 4 + -4;
    edi--;
    (void)0; /* cmp eax, edi - flags set for next jcc */
    MEMF(esp + 0x1C) = (float)fp_top(); fp_popp(); /* fstp */
    if (CMP_AE(eax, edi)) goto loc_00086366; /* jae: above or equal (unsigned >=) */

loc_0008634D:
    fp_push(MEMF(ecx + eax * 4 + 4)); /* fld float */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    goto loc_00086362;

loc_0008635B:
    fp_push(MEMF(ecx + eax * 4 + 4)); /* fld float */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */

loc_00086362:
    MEMF(esp + 0x1C) = (float)fp_top(); fp_popp(); /* fstp */

loc_00086366:
    fp_push(MEMF(0x52F46C)); /* fld float */
    edi = MEM32(esp + 0x1C8);
    edx = 0; /* xor self */
    MEMF(esp + 0x10) = (float)fp_top(); fp_pop(); /* fst */
    if (CMP_L(esi, 4)) goto loc_000863A6; /* jl: less (signed <) */

loc_0008637E:
    ecx = esi + -4;
    ecx = ecx >> 2;
    ecx++;
    eax = edi + 8;
    edx = ecx * 4;
    /* nop */

loc_00086390:
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    eax = eax + 0x10;
    ecx--;
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    if ((ecx != 0)) goto loc_00086390; /* jne: not equal / not zero */

loc_000863A2:
    MEMF(esp + 0x10) = (float)fp_top(); fp_pop(); /* fst */

loc_000863A6:
    if (CMP_GE(edx, esi)) { sub_000863BE(); return; } /* jge: greater or equal (signed >=) */

loc_000863AA:
    /* nop */

loc_000863B0:
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    edx++;
    if (CMP_L(edx, esi)) goto loc_000863B0; /* jl: less (signed <) */

loc_000863B8:
    MEMF(esp + 0x10) = (float)fp_top(); fp_popp(); /* fstp */
    g_seh_ebp = ebp; sub_000863C0(); return; /* tail jmp 0x000863C0 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_000863BE
 * Original: 0x000863BE - 0x000863C0 (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_000863BE(void)
{
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_000863BE:
    (void)0;
    /* fstp st(0) */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_000863C0
 * Original: 0x000863C0 - 0x00086503 (323 bytes, 93 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_000863C0(void)
{
    int _flags = 0; /* fallback flag var */
    int _fpu_cmp = 0; /* FPU compare result: -1/0/1 */
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_000863C0:
    fp_push(MEMF(esp + 0x1C)); /* fld float */
    MEM32(esp + 0x28) = 0;
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    MEMF(esp + 0x24) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp + 0x1C)); /* fld float */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_push(MEMF(esp + 0xC)); /* fld float */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    MEMF(esp + 0x18) = (float)fp_top(); fp_pop(); /* fst */
    _fpu_cmp = (fp_top() < fp_st1()) ? -1 : (fp_top() > fp_st1()) ? 1 : 0; /* fcomp dword ptr [0x5615e4] */
    /* fnstsw ax - store FPU status word */
    if (1 /* jp after test - parity */) goto loc_000863FF; /* jp: parity */

loc_000863F7:
    MEM32(esp + 0x18) = 0x41000000;

loc_000863FF:
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(esp + 0x14) = (float)fp_top(); fp_pop(); /* fst */
    _fpu_cmp = (fp_top() < fp_st1()) ? -1 : (fp_top() > fp_st1()) ? 1 : 0; /* fcomp dword ptr [0x561630] */
    /* fnstsw ax - store FPU status word */
    if (TEST_NZ(HI8(eax), 0x41)) goto loc_0008641C; /* jne: not equal / not zero */

loc_00086414:
    MEM32(esp + 0x14) = 0x43200000;

loc_0008641C:
    ebx = MEM32(esp + 0x10);
    eax = esp + 0xC;
    PUSH32(esp, eax);
    eax = MEM32(esp + 0x18);
    ecx = esp + 0x34;
    PUSH32(esp, ecx);
    ecx = MEM32(esp + 0x20);
    PUSH32(esp, ebx);
    PUSH32(esp, edi);
    PUSH32(esp, esi);
    edx = esp + 0x3C;
    PUSH32(esp, edx);
    edx = MEM32(esp + 0x3C);
    PUSH32(esp, eax);
    PUSH32(esp, ecx);
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_000960C0_corrfunc(); /* call 0x000960C0 */

loc_00086446:
    fp_push(MEMF(esp + 0x40)); /* fld float */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    esp = esp + 0x24;
    MEMF(esp + 0x24) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp + 0x1C)); /* fld float */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_push(MEMF(esp + 0xC)); /* fld float */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    MEMF(esp + 0x18) = (float)fp_top(); fp_pop(); /* fst */
    _fpu_cmp = (fp_top() < fp_st1()) ? -1 : (fp_top() > fp_st1()) ? 1 : 0; /* fcomp dword ptr [0x5615e4] */
    /* fnstsw ax - store FPU status word */
    if (1 /* jp after test - parity */) goto loc_00086480; /* jp: parity */

loc_00086478:
    MEM32(esp + 0x18) = 0x41000000;

loc_00086480:
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(esp + 0x14) = (float)fp_top(); fp_pop(); /* fst */
    _fpu_cmp = (fp_top() < fp_st1()) ? -1 : (fp_top() > fp_st1()) ? 1 : 0; /* fcomp dword ptr [0x561630] */
    /* fnstsw ax - store FPU status word */
    if (TEST_NZ(HI8(eax), 0x41)) goto loc_0008649D; /* jne: not equal / not zero */

loc_00086495:
    MEM32(esp + 0x14) = 0x43200000;

loc_0008649D:
    eax = esp + 0xC;
    PUSH32(esp, eax);
    eax = MEM32(esp + 0x18);
    ecx = esp + 0x34;
    PUSH32(esp, ecx);
    ecx = MEM32(esp + 0x20);
    PUSH32(esp, ebx);
    PUSH32(esp, edi);
    PUSH32(esp, esi);
    edx = esp + 0x3C;
    PUSH32(esp, edx);
    edx = MEM32(esp + 0x3C);
    PUSH32(esp, eax);
    PUSH32(esp, ecx);
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_000960C0_corrfunc(); /* call 0x000960C0 */

loc_000864C3:
    fp_push(MEMF(esp + 0x34)); /* fld float */
    eax = MEM32(esp + 0x1F8);
    MEMF(eax) = (float)fp_top(); fp_popp(); /* fstp */
    ecx = MEM32(esp + 0x200);
    fp_push(MEMF(esp + 0x4C)); /* fld float */
    edx = MEM32(esp + 0x1FC);
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    esp = esp + 0x24;
    POP32(esp, edi);
    POP32(esp, esi);
    fp_st1() /= fp_top(); fp_pop(); /* fdiv */
    SET_LO16(eax, 0); /* xor self */
    POP32(esp, ebx);
    MEMF(ecx) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp)); /* fld float */
    MEMF(edx) = (float)fp_top(); fp_popp(); /* fstp */
    esp = esp + 0x1B4;
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}
