/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/camera/cameraprecisionfire.c
 * Functions: 12
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_002FD340_CameraPrecisionFire_SetAccuracy
 * Symbol: ?SetAccuracy@CameraPrecisionFire@@QAEXM@Z
 * Original: 0x002FD340 - 0x002FD38C (76 bytes, 17 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002FD340_CameraPrecisionFire_SetAccuracy(void)
{
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2, xmm3;

loc_002FD340:
    if (TEST_Z(MEM8(eax + 0x5C), 1)) goto loc_002FD389; /* je: equal / zero */

loc_002FD346:
    xmm0 = MEMF(0x5FC52C); /* movss */
    xmm1 = MEMF(0x5FC530); /* movss */
    xmm3 = MEMF(eax + 0x6C); /* movss */
    xmm2 = xmm0; /* movaps */
    xmm2 = xmm2 / xmm1; /* divss */
    /* comiss xmm3, xmm2 - sets EFLAGS */
    xmm0 = xmm0 / xmm3; /* divss */
    if ((xmm3 > xmm2)) goto loc_002FD36E; /* ja: above (unsigned >) */

loc_002FD36B:
    xmm0 = xmm1; /* movaps */

loc_002FD36E:
    xmm1 = MEMF(0x561418); /* movss */
    xmm0 = xmm0 - xmm1; /* subss */
    xmm0 = xmm0 * MEMF(esp + 4); /* mulss */
    xmm0 = xmm0 + xmm1; /* addss */
    MEMF(eax + 0x58) = xmm0; /* movss */

loc_002FD389:
    esp += 8; return; /* ret 4 */

}

/**
 * fn_002FD390_CameraPrecisionFire_Clear
 * Symbol: ?Clear@CameraPrecisionFire@@MAEXXZ
 * Original: 0x002FD390 - 0x002FD3EE (94 bytes, 31 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002FD390_CameraPrecisionFire_Clear(void)
{
    float xmm0;

loc_002FD390:
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    ebx = ecx;
    PUSH32(esp, 0); fn_00019360_GetIdentityMatrix(); /* call 0x00019360 */

loc_002FD39A:
    xmm0 = 0.0f; /* xorps self = zero */
    esi = eax;
    SET_LO8(eax, MEM8(ebx + 0x5C));
    SET_LO8(eax, LO8(eax) & 0xFC);
    SET_LO8(eax, LO8(eax) | 4);
    edi = ebx + 0x10;
    ecx = 0x10;
    memcpy((void*)XBOX_PTR(edi), (void*)XBOX_PTR(esi), ecx * 4);
    esi += ecx * 4; edi += ecx * 4; ecx = 0; /* rep movsd */
    MEM8(ebx + 0x5C) = LO8(eax);
    eax = 0; /* xor self */
    MEM32(ebx + 0x60) = eax;
    MEM32(ebx + 0x64) = eax;
    MEM32(ebx + 0x68) = eax;
    SET_LO8(eax, MEM8(ebx + 0x70));
    MEMF(ebx + 0x50) = xmm0; /* movss */
    MEMF(ebx + 0x54) = xmm0; /* movss */
    xmm0 = MEMF(0x561418); /* movss */
    POP32(esp, edi);
    MEMF(ebx + 0x58) = xmm0; /* movss */
    xmm0 = MEMF(0x53EDB0); /* movss */
    SET_LO8(eax, LO8(eax) & 0xFE);
    POP32(esp, esi);
    MEMF(ebx + 0x6C) = xmm0; /* movss */
    MEM8(ebx + 0x70) = LO8(eax);
    POP32(esp, ebx);
    esp += 4; return; /* ret */

}

/**
 * fn_002FD3F0_CameraPrecisionFire_UpdatePos
 * Symbol: ?UpdatePos@CameraPrecisionFire@@IAEXXZ
 * Original: 0x002FD3F0 - 0x002FD5EE (510 bytes, 126 insns)
 * Category: game_audio
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002FD3F0_CameraPrecisionFire_UpdatePos(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2, xmm3, xmm4, xmm5;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002FD3F0:
    esp = esp - 0x24;
    xmm0 = MEMF(0x561418); /* movss */
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    ebp = MEM32(esp + 0x30);
    eax = MEM32(ebp + 0x68);
    ecx = MEM32(eax + 0xB0);
    eax = eax + 0xB0;
    ebx = ebp + 0x40;
    MEM32(ebx) = ecx;
    edx = MEM32(eax + 4);
    MEM32(ebx + 4) = edx;
    eax = MEM32(eax + 8);
    MEM32(ebx + 8) = eax;
    MEMF(ebx + 0xC) = xmm0; /* movss */
    ecx = MEM32(ebp + 0x64);
    (void)0; /* test ecx, ecx - flags set for next jcc */
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    MEM32(esp + 0x38) = ebx;
    eax = 0x5FC51C;
    if (TEST_NZ(ecx, ecx)) goto loc_002FD43C; /* jne: not equal / not zero */

loc_002FD437:
    eax = 0x5FC510;

loc_002FD43C:
    edx = MEM32(eax);
    esi = MEM32(eax + 4);
    eax = MEM32(eax + 8);
    xmm3 = 0.0f; /* xorps self = zero */
    MEM32(esp + 0x30) = eax;
    (void)0; /* test MEM8(ebp + 0x70), 1 - flags set for next jcc */
    MEM32(esp + 0x28) = edx;
    if (TEST_Z(MEM8(ebp + 0x70), 1)) goto loc_002FD464; /* je: equal / zero */

loc_002FD455:
    xmm0 = xmm3; /* movaps */
    xmm0 = xmm0 - MEMF(esp + 0x30); /* subss */
    MEMF(esp + 0x30) = xmm0; /* movss */

loc_002FD464:
    (void)0; /* test ecx, ecx - flags set for next jcc */
    xmm0 = MEMF(ebp + 0x20); /* movss */
    xmm1 = MEMF(ebp + 0x30); /* movss */
    xmm2 = MEMF(ebp + 0x34); /* movss */
    MEM32(esp + 0x1C) = edx;
    edx = MEM32(esp + 0x30);
    MEM32(esp + 0x24) = edx;
    xmm5 = MEMF(esp + 0x24); /* movss */
    xmm1 = xmm1 * xmm5; /* mulss */
    MEM32(esp + 0x20) = esi;
    xmm4 = MEMF(esp + 0x20); /* movss */
    xmm0 = xmm0 * xmm4; /* mulss */
    xmm0 = xmm0 + xmm1; /* addss */
    xmm1 = MEMF(ebp + 0x10); /* movss */
    xmm1 = xmm1 * xmm3; /* mulss */
    xmm0 = xmm0 + xmm1; /* addss */
    xmm1 = MEMF(ebp + 0x24); /* movss */
    xmm2 = xmm2 * xmm5; /* mulss */
    xmm1 = xmm1 * xmm4; /* mulss */
    xmm1 = xmm1 + xmm2; /* addss */
    xmm2 = MEMF(ebp + 0x14); /* movss */
    xmm2 = xmm2 * xmm3; /* mulss */
    xmm1 = xmm1 + xmm2; /* addss */
    xmm2 = MEMF(ebp + 0x28); /* movss */
    xmm2 = xmm2 * xmm4; /* mulss */
    xmm4 = MEMF(ebp + 0x38); /* movss */
    xmm4 = xmm4 * xmm5; /* mulss */
    xmm2 = xmm2 + xmm4; /* addss */
    xmm4 = MEMF(ebp + 0x18); /* movss */
    xmm4 = xmm4 * xmm3; /* mulss */
    xmm3 = MEMF(ebp + 0x40); /* movss */
    xmm3 = xmm3 + xmm0; /* addss */
    xmm0 = MEMF(ebp + 0x44); /* movss */
    xmm0 = xmm0 + xmm1; /* addss */
    MEMF(esp + 0x20) = xmm0; /* movss */
    xmm0 = MEMF(ebp + 0x48); /* movss */
    edx = MEM32(esp + 0x20);
    MEMF(esp + 0x1C) = xmm3; /* movss */
    eax = MEM32(esp + 0x1C);
    xmm2 = xmm2 + xmm4; /* addss */
    xmm0 = xmm0 + xmm2; /* addss */
    MEMF(esp + 0x24) = xmm0; /* movss */
    MEM32(esp + 0x10) = eax;
    eax = MEM32(esp + 0x24);
    MEM32(esp + 0x14) = edx;
    MEM32(esp + 0x18) = eax;
    if (TEST_NZ(ecx, ecx)) goto loc_002FD57E; /* jne: not equal / not zero */

loc_002FD532:
    ecx = MEM32(ebp + 0x60);
    xmm0 = MEMF(0x5FC494); /* movss */
    ecx = ecx + 0xB0;
    edx = MEM32(ecx);
    eax = MEM32(ecx + 4);
    ecx = MEM32(ecx + 8);
    MEM32(esp + 0x20) = eax;
    xmm0 = xmm0 + MEMF(esp + 0x20); /* addss */
    ebx = esp + 0x10;
    PUSH32(esp, 0x3E800000);
    esi = ebx;
    edi = esp + 0x20;
    MEM32(esp + 0x20) = edx;
    MEM32(esp + 0x28) = ecx;
    MEMF(esp + 0x24) = xmm0; /* movss */
    PUSH32(esp, 0); fn_002FF550_CameraMisc_ProvideClearance(); /* call 0x002FF550 */

loc_002FD577:
    ebx = MEM32(esp + 0x3C);
    esp = esp + 4;

loc_002FD57E:
    xmm3 = MEMF(esp + 0x28); /* movss */
    xmm0 = MEMF(ebp + 0x10); /* movss */
    xmm1 = MEMF(ebp + 0x14); /* movss */
    xmm2 = MEMF(ebp + 0x18); /* movss */
    xmm0 = xmm0 * xmm3; /* mulss */
    xmm1 = xmm1 * xmm3; /* mulss */
    xmm2 = xmm2 * xmm3; /* mulss */
    xmm3 = MEMF(esp + 0x10); /* movss */
    xmm3 = xmm3 + xmm0; /* addss */
    xmm0 = MEMF(esp + 0x14); /* movss */
    xmm0 = xmm0 + xmm1; /* addss */
    MEMF(esp + 0x2C) = xmm0; /* movss */
    xmm0 = MEMF(esp + 0x18); /* movss */
    xmm0 = xmm0 + xmm2; /* addss */
    PUSH32(esp, 0x3F400000);
    esi = esp + 0x2C;
    edi = esp + 0x14;
    MEMF(esp + 0x2C) = xmm3; /* movss */
    MEMF(esp + 0x34) = xmm0; /* movss */
    PUSH32(esp, 0); fn_002FF550_CameraMisc_ProvideClearance(); /* call 0x002FF550 */

loc_002FD5E1:
    esp = esp + 4;
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp = esp + 0x24;
    esp += 8; return; /* ret 4 */

}

/**
 * fn_002FD5F0_CameraPrecisionFire_AttachToCore
 * Symbol: ?AttachToCore@CameraPrecisionFire@@IAE_NXZ
 * Original: 0x002FD5F0 - 0x002FD638 (72 bytes, 23 insns)
 * Category: game_video
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002FD5F0_CameraPrecisionFire_AttachToCore(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002FD5F0:
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    PUSH32(esp, 0); fn_002E0910_CHUDCmd_Get(); /* call 0x002E0910 */

loc_002FD5F7:
    edi = MEM32(eax + 0xD8);
    if (TEST_Z(edi, edi)) { sub_002FD692(); return; } /* je: equal / zero */

loc_002FD605:
    esi = MEM32(edi + 0xF0);
    if (TEST_Z(esi, esi)) { sub_002FD638(); return; } /* je: equal / zero */

loc_002FD60F:
    eax = MEM32(esi);
    ecx = esi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x80), _icall_esp); /* indirect call */
    }

loc_002FD619:
    if (TEST_Z(eax, eax)) { sub_002FD638(); return; } /* je: equal / zero */

loc_002FD61D:
    edx = MEM32(esi);
    ecx = esi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x80), _icall_esp); /* indirect call */
    }

loc_002FD627:
    ecx = MEM32(eax + 0x2F8);
    if (TEST_Z(ecx, ecx)) { sub_002FD638(); return; } /* je: equal / zero */

loc_002FD631:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x58), _icall_esp); /* indirect call */
    }

loc_002FD636:
    g_seh_ebp = ebp; sub_002FD63A(); return; /* tail jmp 0x002FD63A */

}

/**
 * sub_002FD638
 * Original: 0x002FD638 - 0x002FD63A (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002FD638(void)
{

loc_002FD638:
    eax = 0; /* xor self */

}

/**
 * sub_002FD63A
 * Original: 0x002FD63A - 0x002FD65D (35 bytes, 15 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002FD63A(void)
{
    int _flags = 0; /* fallback flag var */

loc_002FD63A:
    (void)0; /* test eax, eax - flags set for next jcc */
    MEM32(ebx + 0x60) = eax;
    if (TEST_Z(eax, eax)) { sub_002FD65D(); return; } /* je: equal / zero */

loc_002FD641:
    edx = MEM32(0x5FC3F8);
    PUSH32(esp, ecx);
    ecx = esp;
    MEM32(ecx) = edx;
    PUSH32(esp, 0); fn_00121290_ZeroBaseNode_Find(); /* call 0x00121290 */

loc_002FD651:
    (void)0; /* test eax, eax - flags set for next jcc */
    MEM32(ebx + 0x68) = eax;
    if (TEST_Z(eax, eax)) { sub_002FD692(); return; } /* je: equal / zero */

loc_002FD658:
    SET_LO8(eax, 1);
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 4; return; /* ret */

}

/**
 * sub_002FD65D
 * Original: 0x002FD65D - 0x002FD681 (36 bytes, 12 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002FD65D(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002FD65D:
    eax = MEM32(edi + 0xF0);
    if (TEST_Z(eax, eax)) { sub_002FD681(); return; } /* je: equal / zero */

loc_002FD667:
    ecx = eax;
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x88), _icall_esp); /* indirect call */
    }

loc_002FD671:
    if (TEST_Z(eax, eax)) { sub_002FD681(); return; } /* je: equal / zero */

loc_002FD675:
    edx = MEM32(eax);
    ecx = eax;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xE4), _icall_esp); /* indirect call */
    }

loc_002FD67F:
    g_seh_ebp = ebp; sub_002FD683(); return; /* tail jmp 0x002FD683 */

}

/**
 * sub_002FD681
 * Original: 0x002FD681 - 0x002FD683 (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002FD681(void)
{

loc_002FD681:
    eax = 0; /* xor self */

}

/**
 * sub_002FD683
 * Original: 0x002FD683 - 0x002FD692 (15 bytes, 8 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002FD683(void)
{
    int _flags = 0; /* fallback flag var */

loc_002FD683:
    (void)0; /* test eax, eax - flags set for next jcc */
    MEM32(ebx + 0x64) = eax;
    if (TEST_Z(eax, eax)) { sub_002FD692(); return; } /* je: equal / zero */

loc_002FD68A:
    MEM32(ebx + 0x68) = eax;
    SET_LO8(eax, 1);
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 4; return; /* ret */

}

/**
 * sub_002FD692
 * Original: 0x002FD692 - 0x002FD697 (5 bytes, 4 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002FD692(void)
{

loc_002FD692:
    POP32(esp, edi);
    SET_LO8(eax, 0); /* xor self */
    POP32(esp, esi);
    esp += 4; return; /* ret */

}

/**
 * fn_002FD6A0_CameraPrecisionFire_Activate
 * Symbol: ?Activate@CameraPrecisionFire@@QAEXABVZeroMatrix@@M@Z
 * Original: 0x002FD6A0 - 0x002FD791 (241 bytes, 75 insns)
 * Category: game_audio
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002FD6A0_CameraPrecisionFire_Activate(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2, xmm3;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002FD6A0:
    esp = esp - 0x10;
    PUSH32(esp, ebx);
    ebx = eax;
    MEMF(ebx + 0x6C) = xmm0; /* movss */
    PUSH32(esp, 0); fn_002E0910_CHUDCmd_Get(); /* call 0x002E0910 */

loc_002FD6B0:
    SET_LO8(edx, MEM8(eax + 0xC8));
    ecx = 0; /* xor self */
    if (CMP_NE(LO8(edx), LO8(ecx))) goto loc_002FD76F; /* jne: not equal / not zero */

loc_002FD6C0:
    PUSH32(esp, 0); fn_002FD5F0_CameraPrecisionFire_AttachToCore(); /* call 0x002FD5F0 */

loc_002FD6C5:
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_002FD76D; /* je: equal / zero */

loc_002FD6CD:
    PUSH32(esp, ebp);
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    PUSH32(esp, ebx);
    PUSH32(esp, 0); fn_002FD3F0_CameraPrecisionFire_UpdatePos(); /* call 0x002FD3F0 */

loc_002FD6D6:
    eax = ebx + 0x40;
    ecx = eax;
    edx = MEM32(ecx);
    ebp = MEM32(ecx + 4);
    esi = MEM32(ecx + 8);
    ecx = MEM32(ecx + 0xC);
    MEM32(esp + 0x1C) = ecx;
    MEM32(esp + 0x18) = esi;
    esi = MEM32(esp + 0x24);
    edi = ebx + 0x10;
    ecx = 0x10;
    memcpy((void*)XBOX_PTR(edi), (void*)XBOX_PTR(esi), ecx * 4);
    esi += ecx * 4; edi += ecx * 4; ecx = 0; /* rep movsd */
    ecx = MEM32(esp + 0x1C);
    MEM32(eax) = edx;
    edx = MEM32(esp + 0x18);
    MEM32(eax + 4) = ebp;
    MEM32(eax + 8) = edx;
    MEM32(eax + 0xC) = ecx;
    SET_LO8(ecx, MEM8(ebx + 0x5C));
    SET_LO8(ecx, LO8(ecx) | 1);
    POP32(esp, edi);
    SET_LO8(eax, LO8(ecx));
    (void)0; /* test LO8(eax), 1 - flags set for next jcc */
    POP32(esp, esi);
    MEM8(ebx + 0x5C) = LO8(ecx);
    POP32(esp, ebp);
    if (TEST_Z(LO8(eax), 1)) goto loc_002FD78A; /* je: equal / zero */

loc_002FD721:
    xmm0 = MEMF(0x5FC52C); /* movss */
    xmm1 = MEMF(0x5FC530); /* movss */
    xmm3 = MEMF(ebx + 0x6C); /* movss */
    xmm2 = xmm0; /* movaps */
    xmm2 = xmm2 / xmm1; /* divss */
    /* comiss xmm3, xmm2 - sets EFLAGS */
    xmm0 = xmm0 / xmm3; /* divss */
    if ((xmm3 > xmm2)) goto loc_002FD749; /* ja: above (unsigned >) */

loc_002FD746:
    xmm0 = xmm1; /* movaps */

loc_002FD749:
    xmm1 = MEMF(0x561418); /* movss */
    xmm0 = xmm0 - xmm1; /* subss */
    xmm0 = xmm0 * MEMF(0x561408); /* mulss */
    xmm0 = xmm0 + xmm1; /* addss */
    MEMF(ebx + 0x58) = xmm0; /* movss */
    POP32(esp, ebx);
    esp = esp + 0x10;
    esp += 8; return; /* ret 4 */

loc_002FD76D:
    ecx = 0; /* xor self */

loc_002FD76F:
    SET_LO8(edx, MEM8(ebx + 0x5C));
    SET_LO8(eax, 0xFE);
    MEM32(ebx + 0x60) = ecx;
    MEM32(ebx + 0x64) = ecx;
    MEM32(ebx + 0x68) = ecx;
    SET_LO8(ecx, MEM8(ebx + 0x70));
    SET_LO8(edx, LO8(edx) & LO8(eax));
    SET_LO8(ecx, LO8(ecx) & LO8(eax));
    MEM8(ebx + 0x5C) = LO8(edx);
    MEM8(ebx + 0x70) = LO8(ecx);

loc_002FD78A:
    POP32(esp, ebx);
    esp = esp + 0x10;
    esp += 8; return; /* ret 4 */

}

/**
 * fn_002FD7A0_CameraPrecisionFire_Update
 * Symbol: ?Update@CameraPrecisionFire@@UAEXM@Z
 * Original: 0x002FD7A0 - 0x002FD8A9 (265 bytes, 87 insns)
 * Category: game_audio
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002FD7A0_CameraPrecisionFire_Update(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002FD7A0:
    esp = esp - 0x10;
    PUSH32(esp, ebp);
    ebp = ecx;
    if (TEST_Z(MEM8(ebp + 0x5C), 1)) goto loc_002FD7F8; /* je: equal / zero */

loc_002FD7AC:
    PUSH32(esp, ebx);
    PUSH32(esp, 0); fn_002E0910_CHUDCmd_Get(); /* call 0x002E0910 */

loc_002FD7B2:
    SET_LO8(ecx, MEM8(eax + 0xC8));
    ebx = 0; /* xor self */
    if (CMP_NE(LO8(ecx), LO8(ebx))) goto loc_002FD7DC; /* jne: not equal / not zero */

loc_002FD7BE:
    PUSH32(esp, 0); fn_002E0910_CHUDCmd_Get(); /* call 0x002E0910 */

loc_002FD7C3:
    (void)0; /* cmp MEM32(ebp + 0x64), ebx - flags set for next jcc */
    eax = MEM32(eax + 0xD8);
    if (CMP_EQ(MEM32(ebp + 0x64), ebx)) goto loc_002FD7FF; /* je: equal / zero */

loc_002FD7CE:
    if (CMP_EQ(eax, ebx)) goto loc_002FD7DC; /* je: equal / zero */

loc_002FD7D2:
    PUSH32(esp, 0); fn_00181460_CCore_GetVehicle(); /* call 0x00181460 */

loc_002FD7D7:
    if (CMP_EQ(eax, MEM32(ebp + 0x64))) goto loc_002FD80D; /* je: equal / zero */

loc_002FD7DC:
    SET_LO8(edx, MEM8(ebp + 0x5C));
    SET_LO8(ecx, MEM8(ebp + 0x70));
    SET_LO8(eax, 0xFE);
    SET_LO8(edx, LO8(edx) & LO8(eax));
    SET_LO8(ecx, LO8(ecx) & LO8(eax));
    MEM8(ebp + 0x5C) = LO8(edx);
    MEM32(ebp + 0x60) = ebx;
    MEM32(ebp + 0x64) = ebx;
    MEM32(ebp + 0x68) = ebx;
    MEM8(ebp + 0x70) = LO8(ecx);

loc_002FD7F7:
    POP32(esp, ebx);

loc_002FD7F8:
    POP32(esp, ebp);
    esp = esp + 0x10;
    esp += 8; return; /* ret 4 */

loc_002FD7FF:
    if (CMP_EQ(eax, ebx)) goto loc_002FD7DC; /* je: equal / zero */

loc_002FD803:
    PUSH32(esp, 0); fn_001814C0_CCore_GetSoldier(); /* call 0x001814C0 */

loc_002FD808:
    if (CMP_NE(eax, MEM32(ebp + 0x60))) goto loc_002FD7DC; /* jne: not equal / not zero */

loc_002FD80D:
    PUSH32(esp, ebp);
    PUSH32(esp, 0); fn_002FD3F0_CameraPrecisionFire_UpdatePos(); /* call 0x002FD3F0 */

loc_002FD813:
    if (TEST_Z(MEM8(0x5FC3D8), 1)) goto loc_002FD7F7; /* je: equal / zero */

loc_002FD81C:
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    eax = esp + 0x10;
    PUSH32(esp, eax);
    ecx = esp + 0x18;
    esi = ebp + 0x10;
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_002FE5F0_CameraMisc_CalcAnglesFromVector(); /* call 0x002FE5F0 */

loc_002FD830:
    edx = esp + 0x24;
    PUSH32(esp, edx);
    eax = esp + 0x24;
    PUSH32(esp, eax);
    ecx = ebp + 0x40;
    eax = 0x5FC3C4;
    PUSH32(esp, 0); fn_00026370_CameraMisc_CalcAnglesFromLookat(); /* call 0x00026370 */

loc_002FD847:
    ecx = MEM32(esp + 0x24);
    xmm0 = MEMF(esp + 0x28); /* movss */
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_001921C0_SubtractAngles(); /* call 0x001921C0 */

loc_002FD857:
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    edx = MEM32(esp + 0x24);
    xmm0 = MEMF(esp + 0x30); /* movss */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    PUSH32(esp, edx);
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(esp + 0x2C) = (float)fp_top(); fp_popp(); /* fstp */
    PUSH32(esp, 0); fn_001921C0_SubtractAngles(); /* call 0x001921C0 */

loc_002FD879:
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    ecx = MEM32(esp + 0x2C);
    edi = esi;
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(esp + 0x28) = (float)fp_top(); fp_popp(); /* fstp */
    eax = MEM32(esp + 0x28);
    PUSH32(esp, eax);
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_002FEDD0_CameraMisc_CalcOrient(); /* call 0x002FEDD0 */

loc_002FD89C:
    esp = esp + 0x20;
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    POP32(esp, ebp);
    esp = esp + 0x10;
    esp += 8; return; /* ret 4 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}
