/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: xboxfre-dec03/private/sdktools/crt/crtw32/stdio/sprintf.c
 * Functions: 2
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

static int sprintf_va_is_valid(uint32_t va)
{
    return va >= 0x00010000u && va < 0x04000000u;
}

static void sprintf_append_char(char *out, size_t out_cap, size_t *pos, char ch)
{
    if (*pos + 1 < out_cap) {
        out[*pos] = ch;
    }
    (*pos)++;
}

static void sprintf_append_cstr(char *out, size_t out_cap, size_t *pos, uint32_t src)
{
    if (!sprintf_va_is_valid(src)) {
        return;
    }
    for (uint32_t i = 0; i < 1024; i++) {
        char ch = (char)MEM8(src + i);
        if (ch == 0) {
            return;
        }
        sprintf_append_char(out, out_cap, pos, ch);
    }
}

static void sprintf_append_host(char *out, size_t out_cap, size_t *pos, const char *src)
{
    while (*src) {
        sprintf_append_char(out, out_cap, pos, *src++);
    }
}

static int xbox_vsnprintf_lite(uint32_t dest, size_t dest_cap, uint32_t fmt_va, uint32_t args_va)
{
    char out[1024];
    size_t pos = 0;

    if (dest_cap == 0 || !sprintf_va_is_valid(dest) || !sprintf_va_is_valid(fmt_va)) {
        return 0;
    }
    if (dest_cap > sizeof(out)) {
        dest_cap = sizeof(out);
    }

    for (uint32_t i = 0; i < 4096; i++) {
        char ch = (char)MEM8(fmt_va + i);
        if (ch == 0) {
            break;
        }
        if (ch != '%') {
            sprintf_append_char(out, dest_cap, &pos, ch);
            continue;
        }

        ch = (char)MEM8(fmt_va + ++i);
        if (ch == '%') {
            sprintf_append_char(out, dest_cap, &pos, '%');
            continue;
        }

        char spec[32];
        size_t spec_len = 0;
        spec[spec_len++] = '%';
        while (ch && strchr("-+ #0", ch) && spec_len + 1 < sizeof(spec)) {
            spec[spec_len++] = ch;
            ch = (char)MEM8(fmt_va + ++i);
        }
        while (ch >= '0' && ch <= '9' && spec_len + 1 < sizeof(spec)) {
            spec[spec_len++] = ch;
            ch = (char)MEM8(fmt_va + ++i);
        }
        if (ch == '.' && spec_len + 1 < sizeof(spec)) {
            spec[spec_len++] = ch;
            ch = (char)MEM8(fmt_va + ++i);
            while (ch >= '0' && ch <= '9' && spec_len + 1 < sizeof(spec)) {
                spec[spec_len++] = ch;
                ch = (char)MEM8(fmt_va + ++i);
            }
        }
        while ((ch == 'h' || ch == 'l' || ch == 'I') && spec_len + 1 < sizeof(spec)) {
            spec[spec_len++] = ch;
            ch = (char)MEM8(fmt_va + ++i);
            if (ch == '6' || ch == '4' || ch == '3' || ch == '2') {
                spec[spec_len++] = ch;
                ch = (char)MEM8(fmt_va + ++i);
            }
        }
        if (!ch || spec_len + 1 >= sizeof(spec)) {
            break;
        }
        spec[spec_len++] = ch;
        spec[spec_len] = 0;

        uint32_t arg = MEM32(args_va);
        args_va += 4;
        char tmp[128];
        switch (ch) {
        case 'd':
        case 'i':
            snprintf(tmp, sizeof(tmp), spec, (int32_t)arg);
            sprintf_append_host(out, dest_cap, &pos, tmp);
            break;
        case 'u':
        case 'x':
        case 'X':
        case 'o':
            snprintf(tmp, sizeof(tmp), spec, arg);
            sprintf_append_host(out, dest_cap, &pos, tmp);
            break;
        case 'p':
            snprintf(tmp, sizeof(tmp), "0x%08X", arg);
            sprintf_append_host(out, dest_cap, &pos, tmp);
            break;
        case 'c':
            sprintf_append_char(out, dest_cap, &pos, (char)arg);
            break;
        case 's':
            sprintf_append_cstr(out, dest_cap, &pos, arg);
            break;
        case 'f':
        case 'g':
        case 'e':
        case 'E':
            sprintf_append_host(out, dest_cap, &pos, "0");
            args_va += 4;
            break;
        default:
            sprintf_append_char(out, dest_cap, &pos, ch);
            break;
        }
    }

    size_t written = pos;
    if (written >= dest_cap) {
        written = dest_cap - 1;
    }
    for (size_t i = 0; i < written; i++) {
        MEM8(dest + (uint32_t)i) = (uint8_t)out[i];
    }
    MEM8(dest + (uint32_t)written) = 0;
    return (int)pos;
}

/**
 * fn_0009B73D_snprintf
 * Symbol: __snprintf
 * Original: 0x0009B73D - 0x0009B794 (87 bytes, 37 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0009B73D_snprintf(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */

loc_0009B73D:
    eax = (uint32_t)xbox_vsnprintf_lite(MEM32(esp + 4), MEM32(esp + 8), MEM32(esp + 0xC), esp + 0x10);
    esp += 4; return; /* ret */

    PUSH32(esp, ebp);
    ebp = esp;
    esp = esp - 0x20;
    eax = MEM32(ebp + 0xC);
    PUSH32(esp, esi);
    esi = MEM32(ebp + 8);
    MEM32(ebp + -28) = eax;
    PUSH32(esp, edi);
    eax = ebp + 0x14;
    PUSH32(esp, eax);
    PUSH32(esp, MEM32(ebp + 0x10));
    eax = ebp + -32;
    PUSH32(esp, eax);
    MEM32(ebp + -20) = 0x42;
    MEM32(ebp + -24) = esi;
    MEM32(ebp + -32) = esi;
    PUSH32(esp, 0); fn_0009F2B7_output(); /* call 0x0009F2B7 */

loc_0009B76B:
    esp = esp + 0xC;
    (void)0; /* test esi, esi - flags set for next jcc */
    edi = eax;
    if (TEST_Z(esi, esi)) goto loc_0009B78E; /* je: equal / zero */

loc_0009B774:
    MEM32(ebp + -28) = MEM32(ebp + -28) - 1;
    if (((int32_t)MEM32(ebp + -28) < 0)) goto loc_0009B781; /* js: sign (negative) */

loc_0009B779:
    eax = MEM32(ebp + -32);
    MEM8(eax) = 0;
    goto loc_0009B78E;

loc_0009B781:
    eax = ebp + -32;
    PUSH32(esp, eax);
    PUSH32(esp, 0);
    PUSH32(esp, 0); fn_0009F113_flsbuf(); /* call 0x0009F113 */

loc_0009B78C:
    POP32(esp, ecx);
    POP32(esp, ecx);

loc_0009B78E:
    eax = edi;
    POP32(esp, edi);
    POP32(esp, esi);
    esp = ebp;
    POP32(esp, ebp); /* leave */
    esp += 4; return; /* ret */

}

/**
 * fn_0009B794_sprintf
 * Symbol: _sprintf
 * Original: 0x0009B794 - 0x0009B7EC (88 bytes, 36 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0009B794_sprintf(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */

loc_0009B794:
    eax = (uint32_t)xbox_vsnprintf_lite(MEM32(esp + 4), 1024, MEM32(esp + 8), esp + 0xC);
    esp += 4; return; /* ret */

    PUSH32(esp, ebp);
    ebp = esp;
    esp = esp - 0x20;
    PUSH32(esp, esi);
    esi = MEM32(ebp + 8);
    PUSH32(esp, edi);
    eax = ebp + 0x10;
    PUSH32(esp, eax);
    PUSH32(esp, MEM32(ebp + 0xC));
    eax = ebp + -32;
    PUSH32(esp, eax);
    MEM32(ebp + -28) = 0x7FFFFFFF;
    MEM32(ebp + -20) = 0x42;
    MEM32(ebp + -24) = esi;
    MEM32(ebp + -32) = esi;
    PUSH32(esp, 0); fn_0009F2B7_output(); /* call 0x0009F2B7 */

loc_0009B7C3:
    esp = esp + 0xC;
    (void)0; /* test esi, esi - flags set for next jcc */
    edi = eax;
    if (TEST_Z(esi, esi)) goto loc_0009B7E6; /* je: equal / zero */

loc_0009B7CC:
    MEM32(ebp + -28) = MEM32(ebp + -28) - 1;
    if (((int32_t)MEM32(ebp + -28) < 0)) goto loc_0009B7D9; /* js: sign (negative) */

loc_0009B7D1:
    eax = MEM32(ebp + -32);
    MEM8(eax) = 0;
    goto loc_0009B7E6;

loc_0009B7D9:
    eax = ebp + -32;
    PUSH32(esp, eax);
    PUSH32(esp, 0);
    PUSH32(esp, 0); fn_0009F113_flsbuf(); /* call 0x0009F113 */

loc_0009B7E4:
    POP32(esp, ecx);
    POP32(esp, ecx);

loc_0009B7E6:
    eax = edi;
    POP32(esp, edi);
    POP32(esp, esi);
    esp = ebp;
    POP32(esp, ebp); /* leave */
    esp += 4; return; /* ret */

}
