/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/objects/havok/cphysicalvehiclewheelcollide.c
 * Functions: 23
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_00034780_hkRigidBody_getPointVelocity
 * Symbol: ?getPointVelocity@hkRigidBody@@QBEXABVhkVector4@@AAV2@@Z
 * Original: 0x00034780 - 0x000347DB (91 bytes, 28 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00034780_hkRigidBody_getPointVelocity(void)
{
    uint32_t ebp;
    float xmm0, xmm1, xmm2, xmm3;

loc_00034780:
    PUSH32(esp, ebp);
    ebp = esp;
    eax = MEM32(ecx + 0x50);
    xmm1 = MEMF(eax + 0x60); /* movaps */
    ecx = MEM32(ebp + 8);
    xmm0 = MEMF(ecx); /* movaps */
    ecx = MEM32(ebp + 0xC);
    /* subps: xmm0 -= xmm1 (packed 4xfloat) */
    xmm1 = MEMF(eax + 0xE0); /* movaps */
    xmm2 = xmm0; /* movaps */
    /* shufps xmm2, xmm0, 0xc9 */
    xmm3 = xmm1; /* movaps */
    /* shufps xmm3, xmm1, 0xd2 */
    /* mulps: xmm3 *= xmm2 (packed 4xfloat) */
    xmm2 = xmm0; /* movaps */
    /* shufps xmm2, xmm0, 0xd2 */
    xmm0 = xmm1; /* movaps */
    /* shufps xmm0, xmm1, 0xc9 */
    /* mulps: xmm0 *= xmm2 (packed 4xfloat) */
    /* subps: xmm0 -= xmm3 (packed 4xfloat) */
    MEMF(ecx) = xmm0; /* movaps */
    xmm1 = MEMF(eax + 0xD0); /* movaps */
    /* addps: xmm0 += xmm1 (packed 4xfloat) */
    esp = esp & 0xFFFFFFF0u;
    MEMF(ecx) = xmm0; /* movaps */
    esp = ebp;
    POP32(esp, ebp);
    esp += 12; return; /* ret 8 */

}

/**
 * fn_000347E0_GhkPhantomOverlapListener_UAEPAXI_Z
 * Symbol: ??_GhkPhantomOverlapListener@@UAEPAXI@Z
 * Original: 0x000347E0 - 0x000347FF (31 bytes, 11 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_000347E0_GhkPhantomOverlapListener_UAEPAXI_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_000347E0:
    (void)0; /* test MEM8(esp + 4), 1 - flags set for next jcc */
    PUSH32(esp, esi);
    esi = ecx;
    MEM32(esi) = 0x543774;
    if (TEST_Z(MEM8(esp + 4), 1)) goto loc_000347F9; /* je: equal / zero */

loc_000347F0:
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_001293F0_3_YAXPAX_Z(); /* call 0x001293F0 */

loc_000347F6:
    esp = esp + 4;

loc_000347F9:
    eax = esi;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_00034800_GCPhysicalVehicleWheelCollideListener_UAEPAXI_Z
 * Symbol: ??_GCPhysicalVehicleWheelCollideListener@@UAEPAXI@Z
 * Original: 0x00034800 - 0x00034828 (40 bytes, 15 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00034800_GCPhysicalVehicleWheelCollideListener_UAEPAXI_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_00034800:
    PUSH32(esp, esi);
    esi = ecx;
    PUSH32(esp, 0); fn_0024C890_1CPhysicalVehicleWheelCollideListener_UAE_XZ(); /* call 0x0024C890 */

loc_00034808:
    if (TEST_Z(MEM8(esp + 8), 1)) goto loc_00034822; /* je: equal / zero */

loc_0003480F:
    edx = ZX16(MEM16(esi + 4));
    ecx = MEM32(0x5D5A88);
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0xB);
    PUSH32(esp, edx);
    PUSH32(esp, esi);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x14), _icall_esp); /* indirect call */
    }

loc_00034822:
    eax = esi;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_00034830_GCPhysicalVehicleWheelCollide_UAEPAXI_Z
 * Symbol: ??_GCPhysicalVehicleWheelCollide@@UAEPAXI@Z
 * Original: 0x00034830 - 0x00034859 (41 bytes, 16 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00034830_GCPhysicalVehicleWheelCollide_UAEPAXI_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_00034830:
    PUSH32(esp, esi);
    esi = ecx;
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_0024CAE0_1CPhysicalVehicleWheelCollide_UAE_XZ(); /* call 0x0024CAE0 */

loc_00034839:
    if (TEST_Z(MEM8(esp + 8), 1)) goto loc_00034853; /* je: equal / zero */

loc_00034840:
    edx = ZX16(MEM16(esi + 4));
    ecx = MEM32(0x5D5A88);
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0xB);
    PUSH32(esp, edx);
    PUSH32(esp, esi);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x14), _icall_esp); /* indirect call */
    }

loc_00034853:
    eax = esi;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_00034860_ECPhysicalVehicleWheelCollideListener_W7AEPAXI_Z
 * Symbol: ??_ECPhysicalVehicleWheelCollideListener@@W7AEPAXI@Z
 * Original: 0x00034860 - 0x00034868 (8 bytes, 2 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00034860_ECPhysicalVehicleWheelCollideListener_W7AEPAXI_Z(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00034860:
    ecx = ecx - 8;
    g_seh_ebp = ebp; fn_00034800_GCPhysicalVehicleWheelCollideListener_UAEPAXI_Z(); return; /* tail jmp 0x00034800 */

}

/**
 * fn_0024C810_CPhysicalVehicleWheelCollideListener_collidableRemovedCallback
 * Symbol: ?collidableRemovedCallback@CPhysicalVehicleWheelCollideListener@@UAEXABUhkCollidableRemovedEvent@@@Z
 * Original: 0x0024C810 - 0x0024C813 (3 bytes, 1 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024C810_CPhysicalVehicleWheelCollideListener_collidableRemovedCallback(void)
{

loc_0024C810:
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0024C820_CPhysicalVehicleWheelCollideListener_collidableAddedCallback
 * Symbol: ?collidableAddedCallback@CPhysicalVehicleWheelCollideListener@@UAEXABUhkCollidableAddedEvent@@@Z
 * Original: 0x0024C820 - 0x0024C836 (22 bytes, 6 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024C820_CPhysicalVehicleWheelCollideListener_collidableAddedCallback(void)
{
    int _flags = 0; /* fallback flag var */

loc_0024C820:
    eax = MEM32(esp + 4);
    edx = MEM32(eax + 4);
    if (CMP_NE(edx, MEM32(ecx + 4))) goto loc_0024C833; /* jne: not equal / not zero */

loc_0024C82C:
    MEM32(eax + 8) = 1;

loc_0024C833:
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0024C840_CPhysicalVehicleWheelCollide_calcSingleWheelGroundFriction
 * Symbol: ?calcSingleWheelGroundFriction@CPhysicalVehicleWheelCollide@@UBEXPAVhkVehicleInstance@@CABUhkWorldRayCastOutput@@AAM@Z
 * Original: 0x0024C840 - 0x0024C843 (3 bytes, 1 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024C840_CPhysicalVehicleWheelCollide_calcSingleWheelGroundFriction(void)
{

loc_0024C840:
    esp += 20; return; /* ret 16 */

}

/**
 * fn_0024C850_CPhysicalVehicleWheelCollide_getPhantoms
 * Symbol: ?getPhantoms@CPhysicalVehicleWheelCollide@@UAEXAAV?$hkArray@PAVhkPhantom@@@@@Z
 * Original: 0x0024C850 - 0x0024C887 (55 bytes, 22 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024C850_CPhysicalVehicleWheelCollide_getPhantoms(void)
{
    int _flags = 0; /* fallback flag var */

loc_0024C850:
    PUSH32(esp, esi);
    esi = MEM32(esp + 8);
    eax = MEM32(esi + 8);
    PUSH32(esp, edi);
    edi = MEM32(ecx + 0x10);
    ecx = MEM32(esi + 4);
    eax = eax & 0x3FFFFFFF;
    if (CMP_NE(ecx, eax)) goto loc_0024C873; /* jne: not equal / not zero */

loc_0024C868:
    PUSH32(esp, 4);
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_000A5270_hkArrayUtil_reserveMore(); /* call 0x000A5270 */

loc_0024C870:
    esp = esp + 8;

loc_0024C873:
    ecx = MEM32(esi + 4);
    edx = MEM32(esi);
    MEM32(edx + ecx * 4) = edi;
    eax = MEM32(esi + 4);
    eax++;
    POP32(esp, edi);
    MEM32(esi + 4) = eax;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0024C890_1CPhysicalVehicleWheelCollideListener_UAE_XZ
 * Symbol: ??1CPhysicalVehicleWheelCollideListener@@UAE@XZ
 * Original: 0x0024C890 - 0x0024C8A5 (21 bytes, 4 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024C890_1CPhysicalVehicleWheelCollideListener_UAE_XZ(void)
{

loc_0024C890:
    MEM32(ecx + 8) = 0x543760;
    MEM32(ecx + 8) = 0x543774;
    MEM32(ecx) = 0x541014;
    esp += 4; return; /* ret */

}

/**
 * fn_0024C8B0_0CPhysicalVehicleWheelCollideListener_QAE_XZ
 * Symbol: ??0CPhysicalVehicleWheelCollideListener@@QAE@XZ
 * Original: 0x0024C8B0 - 0x0024C8D2 (34 bytes, 6 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024C8B0_0CPhysicalVehicleWheelCollideListener_QAE_XZ(void)
{

loc_0024C8B0:
    MEM16(eax + 6) = 1;
    MEM32(eax + 8) = 0x543774;
    MEM32(eax) = 0x54376C;
    MEM32(eax + 8) = 0x543760;
    MEM32(eax + 0xC) = 0;
    esp += 4; return; /* ret */

}

/**
 * fn_0024C8E0_CPhysicalVehicleWheelCollide_updatePhantom
 * Symbol: ?updatePhantom@CPhysicalVehicleWheelCollide@@UAEXPAVhkVehicleInstance@@@Z
 * Original: 0x0024C8E0 - 0x0024C910 (48 bytes, 21 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024C8E0_CPhysicalVehicleWheelCollide_updatePhantom(void)
{
    uint32_t ebp;

loc_0024C8E0:
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ebp);
    ebp = esp;
    esp = esp & 0xFFFFFFF0u;
    esp = esp - 0x2C;
    edx = MEM32(ebp + 8);
    PUSH32(esp, esi);
    esi = ecx;
    eax = MEM32(esi);
    ecx = esp + 0x10;
    PUSH32(esp, ecx);
    PUSH32(esp, edx);
    ecx = esi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x18), _icall_esp); /* indirect call */
    }

loc_0024C8FC:
    ecx = MEM32(esi + 0x10);
    eax = esp + 0x10;
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_000AB200_hkAabbPhantom_setAabb(); /* call 0x000AB200 */

loc_0024C909:
    POP32(esp, esi);
    esp = ebp;
    POP32(esp, ebp);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0024C910_CPhysicalVehicleWheelCollide_castSingleWheel
 * Symbol: ?castSingleWheel@CPhysicalVehicleWheelCollide@@UAEXABUWheelInfo@hkVehicleInstance@@PAV3@AAUhkWorldRayCastOutput@@@Z
 * Original: 0x0024C910 - 0x0024C970 (96 bytes, 33 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024C910_CPhysicalVehicleWheelCollide_castSingleWheel(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1;

loc_0024C910:
    PUSH32(esp, ebp);
    ebp = esp;
    esp = esp & 0xFFFFFFF0u;
    esp = esp - 0x38;
    eax = MEM32(ecx + 0xC);
    ecx = MEM32(ecx + 0x10);
    PUSH32(esp, esi);
    esi = MEM32(ebp + 0x10);
    PUSH32(esp, edi);
    edi = MEM32(ebp + 8);
    xmm0 = MEMF(edi + 0x30); /* movaps */
    PUSH32(esp, esi);
    edx = esp + 0x14;
    MEMF(esp + 0x14) = xmm0; /* movaps */
    xmm0 = MEMF(edi + 0x40); /* movaps */
    PUSH32(esp, edx);
    MEMF(esp + 0x28) = xmm0; /* movaps */
    MEM8(esp + 0x38) = 1;
    MEM32(esp + 0x3C) = eax;
    PUSH32(esp, 0); fn_000AB2D0_hkAabbPhantom_castRay(); /* call 0x000AB2D0 */

loc_0024C94D:
    eax = MEM32(esi + 0x20);
    if (TEST_Z(eax, eax)) goto loc_0024C968; /* je: equal / zero */

loc_0024C954:
    xmm0 = MEMF(edi + 0x60); /* movaps */
    MEMF(esi) = xmm0; /* movaps */
    xmm1 = MEMF(0x5437B0); /* movaps */
    /* xorps xmm0, xmm1 */
    MEMF(esi) = xmm0; /* movaps */

loc_0024C968:
    POP32(esp, edi);
    POP32(esp, esi);
    esp = ebp;
    POP32(esp, ebp);
    esp += 16; return; /* ret 12 */

}

/**
 * fn_0024C970_CPhysicalVehicleWheelCollide_calcWheelsAABB
 * Symbol: ?calcWheelsAABB@CPhysicalVehicleWheelCollide@@UAEXPBVhkVehicleInstance@@AAVhkAabb@@@Z
 * Original: 0x0024C970 - 0x0024CA12 (162 bytes, 55 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024C970_CPhysicalVehicleWheelCollide_calcWheelsAABB(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1;

loc_0024C970:
    PUSH32(esp, ebp);
    ebp = esp;
    esp = esp & 0xFFFFFFF0u;
    PUSH32(esp, ecx);
    edx = MEM32(ebp + 8);
    eax = MEM32(edx + 0x4C);
    xmm0 = MEMF(eax + 0x40); /* movaps */
    xmm1 = MEMF(eax + 0x30); /* movaps */
    ecx = MEM32(ebp + 0xC);
    /* minps xmm1, xmm0 (packed 4xfloat) */
    MEMF(ecx) = xmm1; /* movaps */
    eax = MEM32(edx + 0x4C);
    xmm0 = MEMF(eax + 0x40); /* movaps */
    xmm1 = MEMF(eax + 0x30); /* movaps */
    /* maxps xmm1, xmm0 (packed 4xfloat) */
    MEMF(ecx + 0x10) = xmm1; /* movaps */
    eax = MEM32(edx + 0x1C);
    PUSH32(esp, ebx);
    (void)0; /* cmp MEM8(eax + 0x20), 1 - flags set for next jcc */
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    esi = 1;
    if (CMP_LE(MEM8(eax + 0x20), 1)) goto loc_0024CA09; /* jle: less or equal (signed <=) */

loc_0024C9B1:
    edi = 0xC0;
    goto loc_0024C9C0;

    /* nop */
    /* nop */

loc_0024C9C0:
    eax = MEM32(edx + 0x4C);
    xmm1 = MEMF(eax + edi + 0x40); /* movaps */
    xmm0 = MEMF(ecx); /* movaps */
    eax = eax + edi;
    /* minps xmm0, xmm1 (packed 4xfloat) */
    MEMF(ecx) = xmm0; /* movaps */
    xmm1 = MEMF(eax + 0x30); /* movaps */
    /* minps xmm0, xmm1 (packed 4xfloat) */
    MEMF(ecx) = xmm0; /* movaps */
    xmm1 = MEMF(eax + 0x40); /* movaps */
    xmm0 = MEMF(ecx + 0x10); /* movaps */
    /* maxps xmm0, xmm1 (packed 4xfloat) */
    MEMF(ecx + 0x10) = xmm0; /* movaps */
    xmm1 = MEMF(eax + 0x30); /* movaps */
    /* maxps xmm0, xmm1 (packed 4xfloat) */
    MEMF(ecx + 0x10) = xmm0; /* movaps */
    eax = MEM32(edx + 0x1C);
    eax = (uint32_t)(int32_t)SMEM8(eax + 0x20);
    esi++;
    edi = edi + 0xC0;
    if (CMP_L(esi, eax)) goto loc_0024C9C0; /* jl: less (signed <) */

loc_0024CA09:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp = ebp;
    POP32(esp, ebp);
    esp += 12; return; /* ret 8 */

}

/**
 * fn_0024CA20_CPhysicalVehicleWheelCollide_init
 * Symbol: ?init@CPhysicalVehicleWheelCollide@@UAEXPBVhkVehicleInstance@@@Z
 * Original: 0x0024CA20 - 0x0024CABA (154 bytes, 47 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024CA20_CPhysicalVehicleWheelCollide_init(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0;

loc_0024CA20:
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ebp);
    ebp = esp;
    esp = esp & 0xFFFFFFF0u;
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x4028CB);
    eax = MEM32(0);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x4C;
    PUSH32(esp, esi);
    esi = ecx;
    eax = MEM32(esi);
    PUSH32(esp, edi);
    edi = MEM32(ebp + 8);
    ecx = esp + 0x10;
    PUSH32(esp, ecx);
    PUSH32(esp, edi);
    ecx = esi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x18), _icall_esp); /* indirect call */
    }

loc_0024CA52:
    xmm0 = MEMF(esp + 0x10); /* movaps */
    ecx = MEM32(0x5D5A88);
    MEMF(esp + 0x30) = xmm0; /* movaps */
    xmm0 = MEMF(esp + 0x20); /* movaps */
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0x2E);
    MEMF(esp + 0x44) = xmm0; /* movaps */
    edx = MEM32(ecx);
    PUSH32(esp, 0xA0);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x10), _icall_esp); /* indirect call */
    }

loc_0024CA78:
    MEM16(eax + 4) = 0xA0;
    MEM32(esp + 0xC) = eax;
    MEM32(esp + 0x5C) = 0;
    ecx = MEM32(esi + 0xC);
    PUSH32(esp, ecx);
    edx = esp + 0x34;
    PUSH32(esp, edx);
    ecx = eax;
    PUSH32(esp, 0); fn_000AB5B0_0hkAabbPhantom_QAE_ABVhkAabb_I_Z(); /* call 0x000AB5B0 */

loc_0024CA9A:
    MEM32(esp + 0x5C) = 0xFFFFFFFFu;
    MEM32(esi + 0x10) = eax;
    ecx = MEM32(edi + 0x44);
    ecx = ecx + 0x14;
    edx = esi + 0x14;
    (void)0; /* test edx, edx - flags set for next jcc */
    MEM32(esi + 0x20) = ecx;
    if (TEST_Z(edx, edx)) { sub_0024CABA(); return; } /* je: equal / zero */

loc_0024CAB5:
    ecx = esi + 0x1C;
    g_seh_ebp = ebp; sub_0024CABC(); return; /* tail jmp 0x0024CABC */

}

/**
 * sub_0024CABA
 * Original: 0x0024CABA - 0x0024CABC (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0024CABA(void)
{

loc_0024CABA:
    ecx = 0; /* xor self */

}

/**
 * sub_0024CABC
 * Original: 0x0024CABC - 0x0024CAD7 (27 bytes, 10 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0024CABC(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_0024CABC:
    PUSH32(esp, ecx);
    ecx = eax;
    PUSH32(esp, 0); fn_000AB9F0_hkPhantom_addPhantomOverlapListener(); /* call 0x000AB9F0 */

loc_0024CAC4:
    ecx = MEM32(esp + 0x54);
    POP32(esp, edi);
    MEM32(0) = ecx;
    POP32(esp, esi);
    esp = ebp;
    POP32(esp, ebp);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0024CAE0_1CPhysicalVehicleWheelCollide_UAE_XZ
 * Symbol: ??1CPhysicalVehicleWheelCollide@@UAE@XZ
 * Original: 0x0024CAE0 - 0x0024CB6B (139 bytes, 38 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024CAE0_1CPhysicalVehicleWheelCollide_UAE_XZ(void)
{
    int _flags = 0; /* fallback flag var */

loc_0024CAE0:
    eax = MEM32(0);
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x4039EB);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x14);
    MEM32(esi) = 0x543780;
    MEM32(esp + 0xC) = 1;
    ecx = MEM32(esi + 0x10);
    if (TEST_Z(ecx, ecx)) goto loc_0024CB3E; /* je: equal / zero */

loc_0024CB0F:
    eax = esi + 0x14;
    if (TEST_Z(eax, eax)) goto loc_0024CB1B; /* je: equal / zero */

loc_0024CB16:
    eax = esi + 0x1C;
    goto loc_0024CB1D;

loc_0024CB1B:
    eax = 0; /* xor self */

loc_0024CB1D:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_000AB9A0_hkPhantom_removePhantomOverlapListener(); /* call 0x000AB9A0 */

loc_0024CB23:
    ecx = MEM32(esi + 0x10);
    if (CMP_EQ(MEM16(ecx + 4), 0)) goto loc_0024CB3E; /* je: equal / zero */

loc_0024CB2D:
    MEM16(ecx + 6) = MEM16(ecx + 6) - 1;
    if (CMP_NE(MEM16(ecx + 6), 0)) goto loc_0024CB3E; /* jne: not equal / not zero */

loc_0024CB38:
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 1);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx), _icall_esp); /* indirect call */
    }

loc_0024CB3E:
    ecx = MEM32(esp + 4);
    MEM32(esi + 0x1C) = 0x543760;
    MEM32(esi + 0x1C) = 0x543774;
    MEM32(esi + 0x14) = 0x541014;
    MEM32(esi) = 0x541014;
    MEM32(0) = ecx;
    POP32(esp, esi);
    esp = esp + 0xC;
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0024CB70_0CPhysicalVehicleWheelCollide_QAE_XZ
 * Symbol: ??0CPhysicalVehicleWheelCollide@@QAE@XZ
 * Original: 0x0024CB70 - 0x0024CBA7 (55 bytes, 13 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024CB70_0CPhysicalVehicleWheelCollide_QAE_XZ(void)
{

loc_0024CB70:
    MEM32(eax) = 0x543780;
    ecx = 1;
    MEM16(eax + 6) = LO16(ecx);
    MEM16(eax + 0x1A) = LO16(ecx);
    MEM32(eax + 0x1C) = 0x543774;
    ecx = 0; /* xor self */
    MEM32(eax + 0x14) = 0x54376C;
    MEM32(eax + 0x1C) = 0x543760;
    MEM32(eax + 0x20) = ecx;
    MEM32(eax + 0xC) = ecx;
    MEM8(eax + 8) = LO8(ecx);
    MEM32(eax + 0x10) = ecx;
    esp += 4; return; /* ret */

}

/**
 * fn_0024CBB0_CPhysicalVehicleWheelCollide_collideWheels
 * Symbol: ?collideWheels@CPhysicalVehicleWheelCollide@@UAEXMPAVhkVehicleInstance@@PAUCollisionDetectionWheelOutput@hkVehicleWheelCollide@@@Z
 * Original: 0x0024CBB0 - 0x0024CE82 (722 bytes, 200 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024CBB0_CPhysicalVehicleWheelCollide_collideWheels(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2, xmm3, xmm4, xmm5, xmm6, xmm7;

loc_0024CBB0:
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ebp);
    ebp = esp;
    esp = esp & 0xFFFFFFF0u;
    esp = esp - 0x44;
    eax = MEM32(ecx);
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    esi = MEM32(ebp + 0xC);
    PUSH32(esp, edi);
    PUSH32(esp, esi);
    MEM32(esp + 0x14) = ecx;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x24), _icall_esp); /* indirect call */
    }

loc_0024CBC9:
    ecx = MEM32(esi + 0x1C);
    SET_LO8(eax, MEM8(ecx + 0x20));
    (void)0; /* test LO8(eax), LO8(eax) - flags set for next jcc */
    MEM8(esp + 0xC) = 0;
    if (CMP_LE(LO8(eax) & LO8(eax), 0)) goto loc_0024CE79; /* jle: less or equal (signed <=) */

loc_0024CBDC:
    /* nop */

loc_0024CBE0:
    edi = (uint32_t)(int32_t)SMEM8(esp + 0xC);
    edx = MEM32(ebp + 0x10);
    ecx = MEM32(esp + 0x10);
    xmm0 = MEMF(0x561418); /* movss */
    esi = edi;
    esi = esi << 6;
    esi = esi + edx;
    edx = MEM32(ebp + 0xC);
    eax = MEM32(edx + 0x4C);
    edx = esp + 0x20;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, edx);
    edx = MEM32(ebp + 0xC);
    ebx = edi + edi * 2;
    ebx = ebx << 6;
    ebx = ebx + eax;
    eax = MEM32(ecx);
    PUSH32(esp, edx);
    PUSH32(esp, ebx);
    MEMF(esp + 0x40) = xmm0; /* movss */
    MEM32(esp + 0x4C) = 0;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x20), _icall_esp); /* indirect call */
    }

loc_0024CC26:
    eax = MEM32(ebp + 0xC);
    edx = MEM32(eax + 0x34);
    edx = MEM32(edx + 8);
    ecx = edi + edi * 2;
    ecx = ecx << 4;
    xmm2 = MEMF(ecx + edx + 0x20); /* movss */
    edx = MEM32(eax + 0x1C);
    edx = MEM32(edx + 0x88);
    ecx = edi + edi * 8;
    xmm1 = MEMF(edx + ecx * 4); /* movss */
    ecx = MEM32(esp + 0x40);
    edi = 0; /* xor self */
    if (CMP_EQ(ecx, edi)) goto loc_0024CE1C; /* je: equal / zero */

loc_0024CC5A:
    xmm0 = MEMF(esi + 0x1C); /* movss */
    edx = MEM32(esp + 0x30);
    xmm3 = MEMF(esp + 0x20); /* movaps */
    MEMF(esi + 0x10) = xmm3; /* movaps */
    MEMF(esi + 0x1C) = xmm0; /* movss */
    MEM32(esi + 0x28) = edx;
    if (CMP_NE(MEM8(ecx + 0x18), 1)) goto loc_0024CC7F; /* jne: not equal / not zero */

loc_0024CC7A:
    edi = MEM32(ecx + 0x10);
    edi = edi + ecx;

loc_0024CC7F:
    ecx = MEM32(esp + 0x10);
    xmm0 = xmm1; /* movaps */
    xmm0 = xmm0 + xmm2; /* addss */
    xmm0 = xmm0 * MEMF(esp + 0x34); /* mulss */
    xmm2 = xmm0; /* movaps */
    xmm2 = xmm2 - xmm1; /* subss */
    MEMF(esi + 0x2C) = xmm2; /* movss */
    MEM32(esi + 0x24) = edi;
    xmm1 = MEMF(ebx + 0x60); /* movaps */
    xmm2 = xmm0; /* movaps */
    /* shufps xmm2, xmm0, 0 */
    xmm0 = MEMF(ebx + 0x30); /* movaps */
    /* mulps: xmm2 *= xmm1 (packed 4xfloat) */
    /* addps: xmm0 += xmm2 (packed 4xfloat) */
    MEMF(esi) = xmm0; /* movaps */
    edx = MEM32(ecx);
    xmm0 = MEMF(edi + 0x5C); /* movss */
    ecx = esp + 0x14;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ecx);
    ecx = esp + 0x24;
    PUSH32(esp, ecx);
    ecx = MEM32(esp + 0x14);
    PUSH32(esp, ecx);
    ecx = MEM32(esp + 0x1C);
    PUSH32(esp, eax);
    MEMF(esp + 0x24) = xmm0; /* movss */
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x1C), _icall_esp); /* indirect call */
    }

loc_0024CCDB:
    xmm0 = MEMF(esp + 0x14); /* movss */
    xmm1 = MEMF(esi + 0x10); /* movaps */
    ecx = MEM32(ebp + 0xC);
    MEMF(esi + 0x20) = xmm0; /* movss */
    xmm2 = MEMF(ebx + 0x60); /* movaps */
    eax = MEM32(ecx + 0x44);
    eax = MEM32(eax + 0x50);
    edi = MEM32(edi + 0x50);
    xmm4 = MEMF(eax + 0xE0); /* movaps */
    xmm5 = MEMF(edi + 0xD0); /* movaps */
    xmm0 = xmm1; /* movaps */
    /* mulps: xmm0 *= xmm2 (packed 4xfloat) */
    xmm2 = xmm0; /* movaps */
    /* shufps xmm2, xmm0, 0x55 */
    xmm2 = xmm2 + xmm0; /* addss */
    xmm3 = xmm0; /* movaps */
    /* shufps xmm3, xmm0, 0xaa */
    xmm3 = xmm3 + xmm2; /* addss */
    xmm2 = MEMF(esi); /* movaps */
    xmm0 = xmm2; /* movaps */
    edx = esp + 0x18;
    MEMF(edx) = xmm3; /* movss */
    xmm3 = MEMF(eax + 0x60); /* movaps */
    /* subps: xmm0 -= xmm3 (packed 4xfloat) */
    xmm3 = MEMF(edi + 0x60); /* movaps */
    /* subps: xmm2 -= xmm3 (packed 4xfloat) */
    xmm3 = MEMF(edi + 0xE0); /* movaps */
    xmm6 = xmm2; /* movaps */
    /* shufps xmm6, xmm2, 0xc9 */
    xmm7 = xmm3; /* movaps */
    /* shufps xmm7, xmm3, 0xd2 */
    /* mulps: xmm7 *= xmm6 (packed 4xfloat) */
    xmm6 = xmm2; /* movaps */
    /* shufps xmm6, xmm2, 0xd2 */
    xmm2 = xmm3; /* movaps */
    /* shufps xmm2, xmm3, 0xc9 */
    xmm3 = MEMF(eax + 0xD0); /* movaps */
    /* mulps: xmm2 *= xmm6 (packed 4xfloat) */
    /* subps: xmm2 -= xmm7 (packed 4xfloat) */
    /* addps: xmm2 += xmm5 (packed 4xfloat) */
    xmm5 = xmm0; /* movaps */
    /* shufps xmm5, xmm0, 0xc9 */
    xmm6 = xmm4; /* movaps */
    /* shufps xmm6, xmm4, 0xd2 */
    /* mulps: xmm6 *= xmm5 (packed 4xfloat) */
    xmm5 = xmm0; /* movaps */
    /* shufps xmm5, xmm0, 0xd2 */
    xmm0 = xmm4; /* movaps */
    /* shufps xmm0, xmm4, 0xc9 */
    /* mulps: xmm0 *= xmm5 (packed 4xfloat) */
    /* subps: xmm0 -= xmm6 (packed 4xfloat) */
    /* addps: xmm0 += xmm3 (packed 4xfloat) */
    /* subps: xmm0 -= xmm2 (packed 4xfloat) */
    /* mulps: xmm1 *= xmm0 (packed 4xfloat) */
    eax = MEM32(ecx + 0x1C);
    xmm0 = xmm1; /* movaps */
    /* shufps xmm1, xmm0, 0x55 */
    xmm1 = xmm1 + xmm0; /* addss */
    xmm2 = xmm0; /* movaps */
    /* shufps xmm2, xmm0, 0xaa */
    xmm0 = MEMF(esp + 0x18); /* movss */
    xmm2 = xmm2 + xmm1; /* addss */
    xmm1 = 0.0f; /* xorps self = zero */
    edx = esp + 0x1C;
    MEMF(edx) = xmm2; /* movss */
    xmm2 = xmm1; /* movaps */
    xmm2 = xmm2 - MEMF(eax + 0x84); /* subss */
    /* comiss xmm0, xmm2 - sets EFLAGS */
    eax = ecx;
    if ((xmm0 < xmm2)) goto loc_0024CDFA; /* jb: below (unsigned <) */

loc_0024CDE0:
    xmm0 = MEMF(0x561418); /* movss */
    MEMF(esi + 0x30) = xmm1; /* movss */
    ecx = MEM32(ecx + 0x1C);
    xmm0 = xmm0 / MEMF(ecx + 0x84); /* divss */
    goto loc_0024CE5C;

loc_0024CDFA:
    xmm1 = MEMF(0x56149C); /* movss */
    xmm1 = xmm1 / xmm0; /* divss */
    xmm0 = MEMF(esp + 0x1C); /* movss */
    xmm0 = xmm0 * xmm1; /* mulss */
    MEMF(esi + 0x30) = xmm0; /* movss */
    MEMF(esi + 0x34) = xmm1; /* movss */
    goto loc_0024CE61;

loc_0024CE1C:
    xmm1 = 0.0f; /* xorps self = zero */
    MEM32(esi + 0x24) = edi;
    MEMF(esi + 0x2C) = xmm2; /* movss */
    MEMF(esi + 0x30) = xmm1; /* movss */
    xmm0 = MEMF(ebx + 0x40); /* movaps */
    MEMF(esi) = xmm0; /* movaps */
    xmm2 = MEMF(0x532EC0); /* movaps */
    xmm3 = MEMF(ebx + 0x60); /* movaps */
    xmm0 = MEMF(esi + 0x1C); /* movss */
    /* xorps xmm3, xmm2 */
    MEMF(esi + 0x10) = xmm3; /* movaps */
    MEMF(esi + 0x1C) = xmm0; /* movss */
    xmm0 = MEMF(0x561418); /* movss */
    MEMF(esi + 0x20) = xmm1; /* movss */

loc_0024CE5C:
    MEMF(esi + 0x34) = xmm0; /* movss */

loc_0024CE61:
    SET_LO8(ecx, MEM8(esp + 0xC));
    edx = MEM32(eax + 0x1C);
    SET_LO8(eax, MEM8(edx + 0x20));
    SET_LO8(ecx, LO8(ecx) + 1);
    (void)0; /* cmp LO8(ecx), LO8(eax) - flags set for next jcc */
    MEM8(esp + 0xC) = LO8(ecx);
    if (CMP_L(LO8(ecx), LO8(eax))) goto loc_0024CBE0; /* jl: less (signed <) */

loc_0024CE79:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp = ebp;
    POP32(esp, ebp);
    esp += 16; return; /* ret 12 */

}

/**
 * fn_0024CE90_CPhysicalVehicleWheelCollide_clone
 * Symbol: ?clone@CPhysicalVehicleWheelCollide@@UAEPAVhkVehicleWheelCollide@@ABV?$hkArray@PAVhkPhantom@@@@@Z
 * Original: 0x0024CE90 - 0x0024CF06 (118 bytes, 37 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0024CE90_CPhysicalVehicleWheelCollide_clone(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_0024CE90:
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    ebp = ecx;
    ecx = MEM32(0x5D5A88);
    eax = MEM32(ecx);
    PUSH32(esp, 0xB);
    PUSH32(esp, 0x24);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x10), _icall_esp); /* indirect call */
    }

loc_0024CEA5:
    ecx = MEM32(esp + 0x14);
    esi = eax;
    MEM16(esi + 4) = 0x24;
    MEM32(esi) = 0x543780;
    edi = esi + 0x14;
    eax = 1;
    MEM16(esi + 6) = LO16(eax);
    MEM16(edi + 6) = LO16(eax);
    MEM32(edi + 8) = 0x543774;
    MEM32(edi) = 0x54376C;
    MEM32(edi + 8) = 0x543760;
    ebx = 0; /* xor self */
    MEM32(edi + 0xC) = ebx;
    MEM32(esi + 0xC) = ebx;
    MEM8(esi + 8) = LO8(ebx);
    MEM32(esi + 0x10) = ebx;
    edx = MEM32(ecx);
    eax = MEM32(edx);
    MEM32(esi + 0x10) = eax;
    if (CMP_EQ(MEM16(eax + 4), LO16(ebx))) goto loc_0024CEFA; /* je: equal / zero */

loc_0024CEF6:
    MEM16(eax + 6) = MEM16(eax + 6) + 1;

loc_0024CEFA:
    eax = ebp + 0x14;
    if (TEST_Z(eax, eax)) { sub_0024CF06(); return; } /* je: equal / zero */

loc_0024CF01:
    eax = ebp + 0x1C;
    g_seh_ebp = ebp; sub_0024CF08(); return; /* tail jmp 0x0024CF08 */

}

/**
 * sub_0024CF06
 * Original: 0x0024CF06 - 0x0024CF08 (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0024CF06(void)
{

loc_0024CF06:
    eax = 0; /* xor self */

}

/**
 * sub_0024CF08
 * Original: 0x0024CF08 - 0x0024CF2A (34 bytes, 15 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0024CF08(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_0024CF08:
    ecx = MEM32(esi + 0x10);
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_000AB9A0_hkPhantom_removePhantomOverlapListener(); /* call 0x000AB9A0 */

loc_0024CF11:
    if (CMP_EQ(edi, ebx)) goto loc_0024CF18; /* je: equal / zero */

loc_0024CF15:
    ebx = esi + 0x1C;

loc_0024CF18:
    ecx = MEM32(esi + 0x10);
    PUSH32(esp, ebx);
    PUSH32(esp, 0); fn_000AB9F0_hkPhantom_addPhantomOverlapListener(); /* call 0x000AB9F0 */

loc_0024CF21:
    POP32(esp, edi);
    eax = esi;
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp += 8; return; /* ret 4 */

}
