/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/ui/uiicon3d.c
 * Functions: 12
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_001C2F30_CUIIcon3D_SetPos
 * Symbol: ?SetPos@CUIIcon3D@@QAEXAAVZeroVector3@@@Z
 * Original: 0x001C2F30 - 0x001C2F44 (20 bytes, 8 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C2F30_CUIIcon3D_SetPos(void)
{

loc_001C2F30:
    edx = MEM32(eax);
    ecx = ecx + 0x30;
    MEM32(ecx) = edx;
    edx = MEM32(eax + 4);
    MEM32(ecx + 4) = edx;
    eax = MEM32(eax + 8);
    MEM32(ecx + 8) = eax;
    esp += 4; return; /* ret */

}

/**
 * fn_001C2F50_CUIIcon3D_SetParentObjectMatrix
 * Symbol: ?SetParentObjectMatrix@CUIIcon3D@@QAEXAAVZeroMatrix@@@Z
 * Original: 0x001C2F50 - 0x001C2F51 (1 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C2F50_CUIIcon3D_SetParentObjectMatrix(void)
{

loc_001C2F50:
    esp += 4; return; /* ret */

}

/**
 * fn_001C2F60_CUIIcon3D_Scale
 * Symbol: ?Scale@CUIIcon3D@@QAEXM@Z
 * Original: 0x001C2F60 - 0x001C2F61 (1 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C2F60_CUIIcon3D_Scale(void)
{

loc_001C2F60:
    esp += 4; return; /* ret */

}

/**
 * fn_001C2F70_CUIIcon3D_SetRotationAngle
 * Symbol: ?SetRotationAngle@CUIIcon3D@@QAEXM@Z
 * Original: 0x001C2F70 - 0x001C2F71 (1 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C2F70_CUIIcon3D_SetRotationAngle(void)
{

loc_001C2F70:
    esp += 4; return; /* ret */

}

/**
 * fn_001C2F80_CUIIcon3D_SetRotationAxis
 * Symbol: ?SetRotationAxis@CUIIcon3D@@QAEXAAVZeroVector3@@@Z
 * Original: 0x001C2F80 - 0x001C2F81 (1 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C2F80_CUIIcon3D_SetRotationAxis(void)
{

loc_001C2F80:
    esp += 4; return; /* ret */

}

/**
 * fn_001C2F90_CUIIcon3D_SetPosition
 * Symbol: ?SetPosition@CUIIcon3D@@QAEXAAVZeroVector3@@@Z
 * Original: 0x001C2F90 - 0x001C2F91 (1 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C2F90_CUIIcon3D_SetPosition(void)
{

loc_001C2F90:
    esp += 4; return; /* ret */

}

/**
 * fn_001C2FA0_CUIIcon3D_NewMenuLaunched
 * Symbol: ?NewMenuLaunched@CUIIcon3D@@SAX_N@Z
 * Original: 0x001C2FA0 - 0x001C2FAD (13 bytes, 3 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C2FA0_CUIIcon3D_NewMenuLaunched(void)
{

loc_001C2FA0:
    MEM8(0x5FA4F1) = 1;
    MEM8(0x5FA4F2) = LO8(eax);
    esp += 4; return; /* ret */

}

/**
 * fn_001C2FB0_CUIIcon3D_CopyFrom
 * Symbol: ?CopyFrom@CUIIcon3D@@UAEXABVCUIIcon@@@Z
 * Original: 0x001C2FB0 - 0x001C2FB5 (5 bytes, 1 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C2FB0_CUIIcon3D_CopyFrom(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_001C2FB0:
    g_seh_ebp = ebp; fn_001C37F0_CUIIcon_CopyFrom(); return; /* tail jmp 0x001C37F0 */

}

/**
 * fn_001C2FC0_CUIIcon3D_CopyFrom
 * Symbol: ?CopyFrom@CUIIcon3D@@UAEXABV1@@Z
 * Original: 0x001C2FC0 - 0x001C2FE9 (41 bytes, 17 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C2FC0_CUIIcon3D_CopyFrom(void)
{

loc_001C2FC0:
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    edi = MEM32(esp + 0xC);
    PUSH32(esp, edi);
    esi = ecx;
    PUSH32(esp, 0); fn_001C37F0_CUIIcon_CopyFrom(); /* call 0x001C37F0 */

loc_001C2FCE:
    edi = edi + 0x30;
    eax = MEM32(edi);
    esi = esi + 0x30;
    MEM32(esi) = eax;
    ecx = MEM32(edi + 4);
    MEM32(esi + 4) = ecx;
    edx = MEM32(edi + 8);
    POP32(esp, edi);
    MEM32(esi + 8) = edx;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_001C2FF0_1CUIIcon3D_QAE_XZ
 * Symbol: ??1CUIIcon3D@@QAE@XZ
 * Original: 0x001C2FF0 - 0x001C3011 (33 bytes, 11 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C2FF0_1CUIIcon3D_QAE_XZ(void)
{
    int _flags = 0; /* fallback flag var */

loc_001C2FF0:
    ecx = MEM32(esi + 0x2C);
    (void)0; /* test ecx, ecx - flags set for next jcc */
    MEM32(esi) = 0x55A24C;
    if (TEST_Z(ecx, ecx)) goto loc_001C3010; /* je: equal / zero */

loc_001C2FFD:
    MEM32(ecx + 8) = MEM32(ecx + 8) - 1;
    if ((MEM32(ecx + 8) != 0)) goto loc_001C3009; /* jne: not equal / not zero */

loc_001C3002:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 1);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x10), _icall_esp); /* indirect call */
    }

loc_001C3009:
    MEM32(esi + 0x2C) = 0;

loc_001C3010:
    esp += 4; return; /* ret */

}

/**
 * fn_001C3020_0CUIIcon3D_QAE_XZ
 * Symbol: ??0CUIIcon3D@@QAE@XZ
 * Original: 0x001C3020 - 0x001C3083 (99 bytes, 25 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C3020_0CUIIcon3D_QAE_XZ(void)
{
    float xmm0, xmm1;

loc_001C3020:
    PUSH32(esp, ecx);
    xmm1 = MEMF(0x561464); /* movss */
    xmm0 = 0.0f; /* xorps self = zero */
    SET_LO8(ecx, 0xFF);
    edx = 0; /* xor self */
    MEM8(esp) = LO8(ecx);
    MEM8(esp + 1) = LO8(ecx);
    MEM8(esp + 2) = LO8(ecx);
    MEM8(esp + 3) = LO8(ecx);
    ecx = MEM32(esp);
    MEMF(eax + 0xC) = xmm1; /* movss */
    MEMF(eax + 0x10) = xmm1; /* movss */
    xmm1 = MEMF(0x561418); /* movss */
    MEMF(eax + 4) = xmm0; /* movss */
    MEMF(eax + 8) = xmm0; /* movss */
    MEMF(eax + 0x1C) = xmm0; /* movss */
    MEMF(eax + 0x20) = xmm1; /* movss */
    MEMF(eax + 0x24) = xmm0; /* movss */
    MEMF(eax + 0x28) = xmm1; /* movss */
    MEM32(eax + 0x18) = edx;
    MEM32(eax + 0x14) = ecx;
    MEM32(eax + 0x2C) = edx;
    MEM32(eax) = 0x55A250;
    POP32(esp, ecx);
    esp += 4; return; /* ret */

}

/**
 * fn_001C3090_CUIIcon3D_Submit
 * Symbol: ?Submit@CUIIcon3D@@QAEXPAVZeroCamera@@MM_N11@Z
 * Original: 0x001C3090 - 0x001C37E7 (1879 bytes, 428 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_001C3090_CUIIcon3D_Submit(void)
{
    int _flags = 0; /* fallback flag var */
    int _cf = 0; /* carry flag */
    int _fpu_cmp = 0; /* FPU compare result: -1/0/1 */
    float xmm0, xmm1, xmm2, xmm3, xmm4, xmm5, xmm6;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_001C3090:
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x403497);
    eax = MEM32(0);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x130;
    eax = MEM32(0x57ED94);
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    esi = ecx;
    MEM32(esp + 0x134) = eax;
    eax = MEM32(esi + 0x2C);
    ebx = 0; /* xor self */
    if (CMP_EQ(eax, ebx)) goto loc_001C37C2; /* je: equal / zero */

loc_001C30C8:
    if (CMP_EQ(MEM8(esp + 0x150), LO8(ebx))) goto loc_001C30ED; /* je: equal / zero */

loc_001C30D1:
    if (CMP_NE(MEM8(esp + 0x154), LO8(ebx))) goto loc_001C30ED; /* jne: not equal / not zero */

loc_001C30DA:
    eax = MEM32(0x5FA38C);
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_002A6830_CSettings_IsInShell(); /* call 0x002A6830 */

loc_001C30E5:
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_001C37C2; /* je: equal / zero */

loc_001C30ED:
    ecx = MEM32(0x5FA38C);
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_002A6830_CSettings_IsInShell(); /* call 0x002A6830 */

loc_001C30F9:
    SET_LO8(ecx, MEM8(esp + 0x158));
    SET_LO8(eax, (uint32_t)(-(int32_t)LO8(eax)));
    SET_LO8(eax, _cf ? 0xFFFFFFFF : 0); /* sbb self (CF extend) */
    SET_LO8(eax, LO8(eax) + 1);
    (void)0; /* cmp LO8(ecx), LO8(ebx) - flags set for next jcc */
    MEM8(esp + 0xF) = LO8(eax);
    if (CMP_NE(LO8(ecx), LO8(ebx))) goto loc_001C3117; /* jne: not equal / not zero */

loc_001C310E:
    MEM8(esp + 0xF) = 1;
    SET_LO8(eax, MEM8(esp + 0xF));

loc_001C3117:
    if (CMP_EQ(MEM8(esp + 0x150), LO8(ebx))) goto loc_001C313F; /* je: equal / zero */

loc_001C3120:
    SET_LO8(edx, MEM8(esp + 0x154));
    if (CMP_NE(LO8(edx), LO8(ebx))) goto loc_001C3133; /* jne: not equal / not zero */

loc_001C312B:
    if (CMP_EQ(LO8(ecx), LO8(ebx))) goto loc_001C37C2; /* je: equal / zero */

loc_001C3133:
    if (CMP_EQ(LO8(eax), LO8(ebx))) goto loc_001C313F; /* je: equal / zero */

loc_001C3137:
    if (CMP_EQ(LO8(edx), LO8(ebx))) goto loc_001C37C2; /* je: equal / zero */

loc_001C313F:
    (void)0; /* test MEM8(esi + 0x18), 1 - flags set for next jcc */
    xmm0 = MEMF(esi + 0x30); /* movss */
    xmm3 = MEMF(esi + 0x34); /* movss */
    xmm5 = MEMF(esi + 0x38); /* movss */
    xmm6 = MEMF(0x561404); /* movss */
    MEMF(esp + 0x18) = xmm0; /* movss */
    MEMF(esp + 0x14) = xmm3; /* movss */
    MEMF(esp + 8) = xmm5; /* movss */
    if (TEST_Z(MEM8(esi + 0x18), 1)) goto loc_001C318F; /* je: equal / zero */

loc_001C316E:
    eax = MEM32(esi + 0x2C);
    xmm0 = (float)(int32_t)MEM32(eax + 0x1C); /* cvtsi2ss */
    xmm1 = (float)(int32_t)MEM32(eax + 0x20); /* cvtsi2ss */
    xmm0 = xmm0 * MEMF(esp + 0x148); /* mulss */
    xmm1 = xmm1 * MEMF(esp + 0x14C); /* mulss */
    goto loc_001C3199;

loc_001C318F:
    xmm0 = MEMF(esi + 0xC); /* movss */
    xmm1 = MEMF(esi + 0x10); /* movss */

loc_001C3199:
    eax = MEM32(esi + 0x18);
    edx = eax;
    edx = edx >> 1;
    (void)0; /* test LO8(edx), 1 - flags set for next jcc */
    xmm0 = xmm0 * xmm6; /* mulss */
    xmm1 = xmm1 * xmm6; /* mulss */
    if (TEST_Z(LO8(edx), 1)) goto loc_001C31B7; /* je: equal / zero */

loc_001C31AD:
    xmm5 = xmm5 - xmm0; /* subss */
    MEMF(esp + 8) = xmm5; /* movss */

loc_001C31B7:
    eax = eax >> 2;
    if (TEST_Z(LO8(eax), 1)) goto loc_001C31CE; /* je: equal / zero */

loc_001C31BE:
    xmm2 = xmm1; /* movaps */
    xmm2 = xmm2 + xmm3; /* addss */
    MEMF(esp + 0x14) = xmm2; /* movss */
    xmm3 = xmm2; /* movaps */

loc_001C31CE:
    xmm4 = MEMF(0x561428); /* movss */
    (void)0; /* cmp MEM8(0x5FA4F0), LO8(ebx) - flags set for next jcc */
    xmm2 = xmm0; /* movaps */
    xmm2 = xmm2 * xmm4; /* mulss */
    xmm1 = xmm1 * xmm4; /* mulss */
    xmm2 = xmm2 + xmm5; /* addss */
    xmm3 = xmm3 - xmm1; /* subss */
    MEMF(esp + 0x10) = xmm2; /* movss */
    MEMF(esp + 0x1C) = xmm3; /* movss */
    if (CMP_EQ(MEM8(0x5FA4F0), LO8(ebx))) goto loc_001C3227; /* je: equal / zero */

loc_001C31FD:
    xmm0 = xmm0 * MEMF(0x5614B8); /* mulss */
    xmm1 = xmm2; /* movaps */
    xmm1 = xmm1 + xmm5; /* addss */
    xmm1 = xmm1 * xmm6; /* mulss */
    xmm2 = xmm1; /* movaps */
    xmm2 = xmm2 - xmm0; /* subss */
    xmm0 = xmm0 + xmm1; /* addss */
    MEMF(esp + 8) = xmm2; /* movss */
    MEMF(esp + 0x10) = xmm0; /* movss */

loc_001C3227:
    eax = MEM32(esi + 0x2C);
    ecx = MEM32(eax + 0x14);
    PUSH32(esp, edi);
    edi = MEM32(0x5FA8E8);
    MEM32(esp + 0x30) = ecx;
    MEM32(esp + 0x40) = ebx;
    MEM32(esp + 0x3C) = 1;
    MEM32(esp + 0x34) = 0x53C2FC;
    MEM32(esp + 0x5C) = ebx;
    MEM8(esp + 0x58) = LO8(ebx);
    MEM32(esp + 0x144) = ebx;
    eax = esp + 0x60;
    MEM32(esp + 0x44) = 0x1000110;
    MEM32(esp + 0x54) = 0x50001;
    MEM32(esp + 0x48) = 6;
    MEM32(esp + 0x4C) = 4;
    MEM32(esp + 0x50) = ebx;
    PUSH32(esp, 0); fn_00025E70_0ZeroVertexRecord_QAE_XZ(); /* call 0x00025E70 */

loc_001C3288:
    eax = MEM32(esp + 0x5C);
    if (CMP_NE(eax, ebx)) goto loc_001C329B; /* jne: not equal / not zero */

loc_001C3290:
    edx = MEM32(edi);
    ecx = edi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x3C), _icall_esp); /* indirect call */
    }

loc_001C3297:
    MEM32(esp + 0x5C) = eax;

loc_001C329B:
    edx = MEM32(eax);
    ecx = esp + 0x60;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ecx);
    PUSH32(esp, 1);
    ecx = esp + 0x3C;
    PUSH32(esp, ecx);
    ecx = eax;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 4), _icall_esp); /* indirect call */
    }

loc_001C32AE:
    edx = MEM32(esp + 0x60);
    xmm0 = MEMF(esp + 0x1C); /* movss */
    xmm3 = MEMF(esp + 0x18); /* movss */
    xmm1 = MEMF(esp + 0xC); /* movss */
    MEMF(edx) = xmm0; /* movss */
    eax = MEM32(esp + 0x60);
    MEMF(eax + 4) = xmm3; /* movss */
    ecx = MEM32(esp + 0x60);
    xmm2 = MEMF(esp + 0x20); /* movss */
    MEMF(ecx + 8) = xmm1; /* movss */
    eax = MEM32(esp + 0x60);
    eax = eax + MEM32(esp + 0x64);
    MEM32(esp + 0x60) = eax;
    MEMF(eax) = xmm0; /* movss */
    edx = MEM32(esp + 0x60);
    MEMF(edx + 4) = xmm2; /* movss */
    eax = MEM32(esp + 0x60);
    MEMF(eax + 8) = xmm1; /* movss */
    eax = MEM32(esp + 0x60);
    edx = MEM32(esp + 0x64);
    xmm1 = MEMF(esp + 0x14); /* movss */
    eax = eax + edx;
    MEM32(esp + 0x60) = eax;
    MEMF(eax) = xmm0; /* movss */
    ecx = MEM32(esp + 0x60);
    MEMF(ecx + 4) = xmm2; /* movss */
    edx = MEM32(esp + 0x60);
    MEMF(edx + 8) = xmm1; /* movss */
    eax = MEM32(esp + 0x60);
    eax = eax + MEM32(esp + 0x64);
    MEM32(esp + 0x60) = eax;
    MEMF(eax) = xmm0; /* movss */
    eax = MEM32(esp + 0x60);
    MEMF(eax + 4) = xmm3; /* movss */
    ecx = MEM32(esp + 0x60);
    MEMF(ecx + 8) = xmm1; /* movss */
    eax = MEM32(esp + 0x60);
    edx = MEM32(esp + 0x64);
    SET_LO8(ecx, MEM8(esp + 0x154));
    eax = eax + edx;
    (void)0; /* cmp LO8(ecx), LO8(ebx) - flags set for next jcc */
    MEM32(esp + 0x60) = eax;
    eax = MEM32(esi + 0x14);
    MEM32(esp + 0x18) = eax;
    if (CMP_EQ(LO8(ecx), LO8(ebx))) goto loc_001C368E; /* je: equal / zero */

loc_001C3372:
    if (CMP_NE(MEM8(esp + 0x13), LO8(ebx))) goto loc_001C368E; /* jne: not equal / not zero */

loc_001C337C:
    if (TEST_NZ(MEM8(0x6230D0), 1)) goto loc_001C3396; /* jne: not equal / not zero */

loc_001C3385:
    MEM32(0x6230D0) = MEM32(0x6230D0) | 1;
    PUSH32(esp, 0); fn_0005A39C_GetTickCount_0(); /* call 0x0005A39C */

loc_001C3391:
    MEM32(0x6230CC) = eax;

loc_001C3396:
    PUSH32(esp, 0); fn_0005A39C_GetTickCount_0(); /* call 0x0005A39C */

loc_001C339B:
    eax = eax - MEM32(0x6230CC);
    (void)0; /* test eax, eax - flags set for next jcc */
    MEM32(esp + 0x2C) = eax;
    fp_push((double)SMEM32(esp + 0x2C)); /* fild */
    if (CMP_GE(eax & eax, 0)) goto loc_001C33B3; /* jge: greater or equal (signed >=) */

loc_001C33AD:
    fp_st1() += fp_top(); fp_pop(); /* fadd */

loc_001C33B3:
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    SET_LO8(eax, MEM8(0x5FA4F1));
    (void)0; /* cmp LO8(eax), LO8(ebx) - flags set for next jcc */
    fp_push(MEMF(0x561B14)); /* fld float */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(esp + 0x20) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(0x561B10)); /* fld float */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(esp + 0x28) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(0x561B0C)); /* fld float */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(esp + 0x2C) = (float)fp_top(); fp_popp(); /* fstp */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    fp_st1() += fp_top(); fp_pop(); /* fadd */
    MEMF(esp + 0x24) = (float)fp_top(); fp_popp(); /* fstp */
    if (CMP_EQ(LO8(eax), LO8(ebx))) goto loc_001C3419; /* je: equal / zero */

loc_001C3408:
    xmm0 = 0.0f; /* xorps self = zero */
    MEMF(0x613FF0) = xmm0; /* movss */
    MEM8(0x5FA4F1) = LO8(ebx);

loc_001C3419:
    PUSH32(esp, 0); fn_0005A39C_GetTickCount_0(); /* call 0x0005A39C */

loc_001C341E:
    eax = eax - MEM32(0x613FF4);
    (void)0; /* test eax, eax - flags set for next jcc */
    MEM32(esp + 0x1C) = eax;
    fp_push((double)SMEM32(esp + 0x1C)); /* fild */
    if (CMP_GE(eax & eax, 0)) goto loc_001C3436; /* jge: greater or equal (signed >=) */

loc_001C3430:
    fp_st1() += fp_top(); fp_pop(); /* fadd */

loc_001C3436:
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    MEMF(esp + 0xC) = (float)fp_top(); fp_popp(); /* fstp */
    PUSH32(esp, 0); fn_0005A39C_GetTickCount_0(); /* call 0x0005A39C */

loc_001C3445:
    fp_push(MEMF(esp + 0xC)); /* fld float */
    MEM32(0x613FF4) = eax;
    fp_push(MEMF(0x561408)); /* fld float */
    eax = MEM32(esp + 0xC);
    _fpu_cmp = (fp_top() < fp_st1()) ? -1 : (fp_top() > fp_st1()) ? 1 : 0; fp_pop(); /* fcompi */
    /* fstp st(0) */
    MEM32(esp + 0x1C) = eax;
    if ((_fpu_cmp <= 0) /* fcompi */) goto loc_001C3467; /* jbe: below or equal (unsigned <=) */

loc_001C3462:
    xmm0 = 0.0f; /* xorps self = zero */
    goto loc_001C3480;

loc_001C3467:
    xmm1 = MEMF(esp + 0xC); /* movss */
    xmm0 = MEMF(0x5614D8); /* movss */
    /* comiss xmm1, xmm0 - sets EFLAGS */
    if ((xmm1 > xmm0)) goto loc_001C3480; /* ja: above (unsigned >) */

loc_001C347A:
    xmm0 = MEMF(esp + 0x1C); /* movss */

loc_001C3480:
    xmm0 = xmm0 + MEMF(0x613FF0); /* addss */
    xmm1 = 0.0f; /* xorps self = zero */
    MEMF(0x613FF0) = xmm0; /* movss */
    xmm0 = xmm0 * MEMF(0x561600); /* mulss */
    /* comiss xmm1, xmm0 - sets EFLAGS */
    MEMF(esp + 0xC) = xmm0; /* movss */
    if ((xmm1 > xmm0)) goto loc_001C34B3; /* ja: above (unsigned >) */

loc_001C34A6:
    xmm1 = MEMF(0x561418); /* movss */
    /* comiss xmm0, xmm1 - sets EFLAGS */
    if ((xmm0 <= xmm1)) goto loc_001C34BC; /* jbe: below or equal (unsigned <=) */

loc_001C34B3:
    xmm0 = xmm1; /* movaps */
    MEMF(esp + 0xC) = xmm0; /* movss */

loc_001C34BC:
    (void)0; /* cmp MEM8(0x5FA4F2), LO8(ebx) - flags set for next jcc */
    MEMF(esp + 0x14) = xmm0; /* movss */
    if (CMP_EQ(MEM8(0x5FA4F2), LO8(ebx))) goto loc_001C3525; /* je: equal / zero */

loc_001C34CA:
    fp_push(MEMF(esp + 0xC)); /* fld float */
    fp_push(MEMD(0x561B00)); /* fld double */
    PUSH32(esp, 0); fn_0009D7CC_CIpow(); /* call 0x0009D7CC */

loc_001C34D9:
    /* FPU: fsubr dword ptr [0x561418] */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    PUSH32(esp, 0); fn_0009D720_ftol2(); /* call 0x0009D720 */

loc_001C34EA:
    fp_push(MEMF(esp + 0xC)); /* fld float */
    fp_push(MEMD(0x561AF8)); /* fld double */
    MEM8(esp + 0x1B) = LO8(eax);
    PUSH32(esp, 0); fn_0009D7CC_CIpow(); /* call 0x0009D7CC */

loc_001C34FD:
    MEMF(esp + 0x14) = (float)fp_top(); fp_popp(); /* fstp */

loc_001C3501:
    (void)0; /* cmp MEM8(esp + 0x158), LO8(ebx) - flags set for next jcc */
    xmm1 = 0.0f; /* xorps self = zero */
    if (CMP_EQ(MEM8(esp + 0x158), LO8(ebx))) goto loc_001C3540; /* je: equal / zero */

loc_001C350D:
    (void)0; /* cmp MEM8(0x5FA4F2), LO8(ebx) - flags set for next jcc */
    xmm0 = xmm1; /* movaps */
    if (CMP_NE(MEM8(0x5FA4F2), LO8(ebx))) goto loc_001C351E; /* jne: not equal / not zero */

loc_001C3518:
    xmm0 = MEMF(esp + 0x14); /* movss */

loc_001C351E:
    MEM8(esp + 0x1B) = 0xFF;
    goto loc_001C3546;

loc_001C3525:
    fp_push(MEMF(0x561418)); /* fld float */
    fp_st1() -= fp_top(); fp_pop(); /* fsub */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    PUSH32(esp, 0); fn_0009D720_ftol2(); /* call 0x0009D720 */

loc_001C353A:
    MEM8(esp + 0x1B) = LO8(eax);
    goto loc_001C3501;

loc_001C3540:
    xmm0 = MEMF(esp + 0x14); /* movss */

loc_001C3546:
    (void)0; /* cmp MEM8(0x5FA4F2), LO8(ebx) - flags set for next jcc */
    xmm2 = MEMF(0x561418); /* movss */
    if (CMP_NE(MEM8(0x5FA4F2), LO8(ebx))) goto loc_001C3566; /* jne: not equal / not zero */

loc_001C3556:
    xmm3 = xmm2; /* movaps */
    xmm3 = xmm3 - xmm0; /* subss */
    MEMF(esp + 0x14) = xmm3; /* movss */
    xmm0 = xmm3; /* movaps */

loc_001C3566:
    /* comiss xmm1, xmm0 - sets EFLAGS */
    if ((xmm1 <= xmm0)) goto loc_001C3570; /* jbe: below or equal (unsigned <=) */

loc_001C356B:
    xmm0 = xmm1; /* movaps */
    goto loc_001C3578;

loc_001C3570:
    /* comiss xmm0, xmm2 - sets EFLAGS */
    if ((xmm0 <= xmm2)) goto loc_001C3578; /* jbe: below or equal (unsigned <=) */

loc_001C3575:
    xmm0 = xmm2; /* movaps */

loc_001C3578:
    fp_push(MEMF(esp + 0x20)); /* fld float */
    xmm0 = xmm0 * MEMF(0x561AD0); /* mulss */
    /* FPU: fsin  */
    PUSH32(esp, ecx);
    eax = esp + 0x64;
    MEMF(esp + 0x18) = xmm0; /* movss */
    MEMF(esp + 0x24) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp + 0x28)); /* fld float */
    /* FPU: fsin  */
    xmm2 = MEMF(esp + 0x24); /* movss */
    xmm2 = xmm2 * xmm1; /* mulss */
    xmm2 = xmm2 + xmm0; /* addss */
    MEMF(esp + 0x28) = (float)fp_top(); fp_popp(); /* fstp */
    xmm3 = MEMF(esp + 0x28); /* movss */
    xmm3 = xmm3 * xmm1; /* mulss */
    xmm3 = xmm3 + xmm0; /* addss */
    MEMF(esp) = xmm3; /* movss */
    PUSH32(esp, 0); fn_0002C6E0_ZeroVertexRecord_AddVertexUVCompressed(); /* call 0x0002C6E0 */

loc_001C35C5:
    fp_push(MEMF(esp + 0x28)); /* fld float */
    /* FPU: fsin  */
    xmm1 = MEMF(esp + 0x14); /* movss */
    xmm3 = 0.0f; /* xorps self = zero */
    xmm0 = MEMF(0x561418); /* movss */
    xmm0 = xmm0 - xmm1; /* subss */
    PUSH32(esp, ecx);
    eax = esp + 0x64;
    MEMF(esp + 0x20) = xmm0; /* movss */
    MEMF(esp + 0x2C) = (float)fp_top(); fp_popp(); /* fstp */
    fp_push(MEMF(esp + 0x30)); /* fld float */
    /* FPU: fsin  */
    xmm2 = MEMF(esp + 0x2C); /* movss */
    xmm2 = xmm2 * xmm3; /* mulss */
    xmm2 = xmm2 + xmm1; /* addss */
    MEMF(esp + 0x10) = (float)fp_top(); fp_popp(); /* fstp */
    xmm4 = MEMF(esp + 0x10); /* movss */
    xmm4 = xmm4 * xmm3; /* mulss */
    xmm4 = xmm4 + xmm0; /* addss */
    MEMF(esp) = xmm4; /* movss */
    PUSH32(esp, 0); fn_0002C6E0_ZeroVertexRecord_AddVertexUVCompressed(); /* call 0x0002C6E0 */

loc_001C361F:
    xmm3 = 0.0f; /* xorps self = zero */
    xmm0 = MEMF(esp + 0x28); /* movss */
    xmm1 = MEMF(esp + 0x1C); /* movss */
    xmm2 = MEMF(esp + 0xC); /* movss */
    xmm0 = xmm0 * xmm3; /* mulss */
    PUSH32(esp, ecx);
    xmm0 = xmm0 + xmm1; /* addss */
    xmm2 = xmm2 * xmm3; /* mulss */
    eax = esp + 0x64;
    MEMF(esp) = xmm0; /* movss */
    xmm2 = xmm2 + xmm1; /* addss */
    PUSH32(esp, 0); fn_0002C6E0_ZeroVertexRecord_AddVertexUVCompressed(); /* call 0x0002C6E0 */

loc_001C3653:
    xmm1 = 0.0f; /* xorps self = zero */
    xmm0 = MEMF(esp + 0x20); /* movss */
    xmm2 = MEMF(esp + 0x24); /* movss */
    xmm0 = xmm0 * xmm1; /* mulss */
    xmm0 = xmm0 + MEMF(esp + 0x14); /* addss */
    PUSH32(esp, ecx);
    xmm2 = xmm2 * xmm1; /* mulss */
    xmm2 = xmm2 + MEMF(esp + 0x20); /* addss */
    eax = esp + 0x64;
    MEMF(esp) = xmm0; /* movss */
    PUSH32(esp, 0); fn_0002C6E0_ZeroVertexRecord_AddVertexUVCompressed(); /* call 0x0002C6E0 */

loc_001C3685:
    eax = MEM32(esp + 0x18);
    goto loc_001C3728;

loc_001C368E:
    ecx = MEM32(esp + 0xA8);
    MEM16(ecx) = LO16(ebx);
    edx = MEM32(esp + 0xA8);
    MEM16(edx + 2) = LO16(ebx);
    ecx = MEM32(esp + 0xA8);
    ecx = ecx + MEM32(esp + 0xAC);
    MEM32(esp + 0xA8) = ecx;
    MEM16(ecx) = LO16(ebx);
    ecx = MEM32(esp + 0xA8);
    edx = 0x7FF;
    MEM16(ecx + 2) = LO16(edx);
    ecx = MEM32(esp + 0xA8);
    ecx = ecx + MEM32(esp + 0xAC);
    MEM32(esp + 0xA8) = ecx;
    MEM16(ecx) = LO16(edx);
    ecx = MEM32(esp + 0xA8);
    MEM16(ecx + 2) = LO16(edx);
    ecx = MEM32(esp + 0xA8);
    ecx = ecx + MEM32(esp + 0xAC);
    MEM32(esp + 0xA8) = ecx;
    MEM16(ecx) = LO16(edx);
    edx = MEM32(esp + 0xA8);
    MEM16(edx + 2) = LO16(ebx);
    edx = MEM32(esp + 0xA8);
    ecx = MEM32(esp + 0xAC);
    edx = edx + ecx;
    MEM32(esp + 0xA8) = edx;

loc_001C3728:
    edx = MEM32(esp + 0x90);
    MEM32(edx) = eax;
    ecx = MEM32(esp + 0x90);
    ecx = ecx + MEM32(esp + 0x94);
    MEM32(esp + 0x90) = ecx;
    MEM32(ecx) = eax;
    ecx = MEM32(esp + 0x90);
    ecx = ecx + MEM32(esp + 0x94);
    MEM32(esp + 0x90) = ecx;
    MEM32(ecx) = eax;
    ecx = MEM32(esp + 0x90);
    ecx = ecx + MEM32(esp + 0x94);
    MEM32(esp + 0x90) = ecx;
    MEM32(ecx) = eax;
    eax = MEM32(esp + 0x94);
    ebx = MEM32(esp + 0x90);
    ecx = MEM32(esp + 0x5C);
    ebx = ebx + eax;
    eax = esp + 0x34;
    MEM32(esp + 0x90) = ebx;
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 8), _icall_esp); /* indirect call */
    }

loc_001C379B:
    eax = MEM32(esp + 0x30);
    edx = MEM32(edi);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    ecx = esp + 0x38;
    PUSH32(esp, ecx);
    ecx = edi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x20), _icall_esp); /* indirect call */
    }

loc_001C37AC:
    edx = esp + 0x34;
    PUSH32(esp, edx);
    MEM32(esp + 0x148) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_00026120_1ZeroRenderDescriptor_UAE_XZ(); /* call 0x00026120 */

loc_001C37C1:
    POP32(esp, edi);

loc_001C37C2:
    ecx = MEM32(esp + 0x138);
    POP32(esp, esi);
    MEM32(0) = ecx;
    ecx = MEM32(esp + 0x130);
    POP32(esp, ebx);
    PUSH32(esp, 0); fn_00401B62_security_check_cookie_4(); /* call 0x00401B62 */

loc_001C37DE:
    esp = esp + 0x13C;
    esp += 24; return; /* ret 20 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}
