/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/hud/hud_util/hudiconmanager.c
 * Functions: 30
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_0002C730_0HUDIconManager_QAE_XZ
 * Symbol: ??0HUDIconManager@@QAE@XZ
 * Original: 0x0002C730 - 0x0002C74E (30 bytes, 11 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0002C730_0HUDIconManager_QAE_XZ(void)
{

loc_0002C730:
    ecx = 0; /* xor self */
    MEM32(eax) = ecx;
    MEM32(eax + 8) = eax;
    MEM32(eax + 4) = eax;
    MEM32(eax + 0x10) = ecx;
    MEM32(eax + 0x14) = ecx;
    MEM32(eax + 0x18) = ecx;
    MEM32(eax + 0x1C) = ecx;
    MEM32(eax + 0x20) = ecx;
    MEM8(eax + 0xC) = 1;
    esp += 4; return; /* ret */

}

/**
 * fn_0002C750_VHUDIcon_HUDCircularListNode_UnlinkAll
 * Symbol: ?UnlinkAll@?$HUDCircularListNode@VHUDIcon@@@@QAEXXZ
 * Original: 0x0002C750 - 0x0002C781 (49 bytes, 19 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0002C750_VHUDIcon_HUDCircularListNode_UnlinkAll(void)
{
    int _flags = 0; /* fallback flag var */

loc_0002C750:
    eax = MEM32(ecx + 8);
    if (CMP_EQ(eax, ecx)) goto loc_0002C780; /* je: equal / zero */

loc_0002C757:
    PUSH32(esp, esi);
    goto loc_0002C760;

    /* nop */

loc_0002C760:
    edx = MEM32(eax + 4);
    esi = MEM32(eax + 8);
    MEM32(edx + 8) = esi;
    edx = MEM32(eax + 8);
    esi = MEM32(eax + 4);
    MEM32(edx + 4) = esi;
    MEM32(eax + 8) = eax;
    MEM32(eax + 4) = eax;
    eax = MEM32(ecx + 8);
    if (CMP_NE(eax, ecx)) goto loc_0002C760; /* jne: not equal / not zero */

loc_0002C77F:
    POP32(esp, esi);

loc_0002C780:
    esp += 4; return; /* ret */

}

/**
 * fn_002C55D0_HUDIconManager_Clear
 * Symbol: ?Clear@HUDIconManager@@IAEXXZ
 * Original: 0x002C55D0 - 0x002C55E6 (22 bytes, 8 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002C55D0_HUDIconManager_Clear(void)
{

loc_002C55D0:
    ecx = 0; /* xor self */
    MEM32(eax + 0x10) = ecx;
    MEM32(eax + 0x14) = ecx;
    MEM32(eax + 0x18) = ecx;
    MEM32(eax + 0x1C) = ecx;
    MEM32(eax + 0x20) = ecx;
    MEM8(eax + 0xC) = 1;
    esp += 4; return; /* ret */

}

/**
 * fn_002C55F0_HUDIconManager_Cleanup
 * Symbol: ?Cleanup@HUDIconManager@@QAEXXZ
 * Original: 0x002C55F0 - 0x002C564C (92 bytes, 35 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002C55F0_HUDIconManager_Cleanup(void)
{
    int _flags = 0; /* fallback flag var */

loc_002C55F0:
    PUSH32(esp, edi);
    ecx = esi;
    PUSH32(esp, 0); fn_0002C750_VHUDIcon_HUDCircularListNode_UnlinkAll(); /* call 0x0002C750 */

loc_002C55F8:
    ecx = MEM32(esi + 0x10);
    edi = 0; /* xor self */
    if (CMP_EQ(ecx, edi)) goto loc_002C560D; /* je: equal / zero */

loc_002C5601:
    MEM32(ecx + 8) = MEM32(ecx + 8) - 1;
    if ((MEM32(ecx + 8) != 0)) goto loc_002C560D; /* jne: not equal / not zero */

loc_002C5606:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 1);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x10), _icall_esp); /* indirect call */
    }

loc_002C560D:
    ecx = MEM32(esi + 0x14);
    if (CMP_EQ(ecx, edi)) goto loc_002C5620; /* je: equal / zero */

loc_002C5614:
    MEM32(ecx + 8) = MEM32(ecx + 8) - 1;
    if ((MEM32(ecx + 8) != 0)) goto loc_002C5620; /* jne: not equal / not zero */

loc_002C5619:
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 1);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x10), _icall_esp); /* indirect call */
    }

loc_002C5620:
    ecx = MEM32(0x5FA324);
    (void)0; /* cmp ecx, edi - flags set for next jcc */
    MEM32(esi + 0x10) = edi;
    MEM32(esi + 0x14) = edi;
    MEM32(esi + 0x18) = edi;
    MEM32(esi + 0x1C) = edi;
    MEM32(esi + 0x20) = edi;
    MEM8(esi + 0xC) = 1;
    if (CMP_EQ(ecx, edi)) goto loc_002C5644; /* je: equal / zero */

loc_002C563D:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 1);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x10), _icall_esp); /* indirect call */
    }

loc_002C5644:
    MEM32(0x5FA324) = edi;
    POP32(esp, edi);
    esp += 4; return; /* ret */

}

/**
 * fn_002C5650_HUDIconManager_SubmitFan
 * Symbol: ?SubmitFan@HUDIconManager@@QAEXPBUHUD_VERTEX@@HPAVZeroTexGroup@@@Z
 * Original: 0x002C5650 - 0x002C57EA (410 bytes, 118 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002C5650_HUDIconManager_SubmitFan(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2, xmm3, xmm4;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C5650:
    esp = esp - 0xE0;
    ecx = MEM32(0x5FA8E8);
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    ebp = MEM32(esp + 0xF0);
    PUSH32(esp, esi);
    esi = MEM32(edx + 0x14);
    PUSH32(esp, edi);
    edi = MEM32(0x5FA324);
    MEM32(esi + 0x30) = eax;
    MEM32(esi + 0x34) = eax;
    MEM32(esi + 0x38) = eax;
    MEM32(esi + 0x3C) = eax;
    MEM32(esi + 0x40) = eax;
    MEM32(esi + 0x44) = eax;
    MEM32(esi + 0x48) = eax;
    MEM32(esi + 0x4C) = eax;
    eax = MEM32(edi + 0x18);
    MEM32(esp + 0x10) = ecx;
    ecx = eax;
    ecx = ecx ^ ebp;
    ecx = ecx & 0x1FFFF;
    ebx = eax;
    ecx = ecx ^ eax;
    eax = esp + 0x18;
    ebx = ebx & 0x1FFFF;
    MEM32(edi + 0x18) = ecx;
    PUSH32(esp, 0); fn_00025E70_0ZeroVertexRecord_QAE_XZ(); /* call 0x00025E70 */

loc_002C56AF:
    eax = MEM32(edi + 0x28);
    MEM32(esp + 0x14) = edi;
    edi = edi + 0x28;
    if (TEST_NZ(eax, eax)) goto loc_002C56CA; /* jne: not equal / not zero */

loc_002C56BD:
    ecx = MEM32(0x5FA8E8);
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x3C), _icall_esp); /* indirect call */
    }

loc_002C56C8:
    MEM32(edi) = eax;

loc_002C56CA:
    edi = MEM32(edi);
    edx = MEM32(esp + 0x14);
    eax = MEM32(edi);
    ecx = esp + 0x18;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ecx);
    PUSH32(esp, 1);
    PUSH32(esp, edx);
    ecx = edi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 4), _icall_esp); /* indirect call */
    }

loc_002C56DF:
    if (CMP_LE(ebp & ebp, 0)) goto loc_002C57A6; /* jle: less or equal (signed <=) */

loc_002C56E7:
    eax = MEM32(esp + 0xF4);
    xmm1 = MEMF(0x561418); /* movss */
    xmm2 = MEMF(0x561484); /* movss */
    xmm3 = MEMF(0x561404); /* movss */
    eax = eax + 0x10;
    /* nop */

loc_002C5710:
    ecx = MEM32(eax + -16);
    edx = MEM32(esp + 0x18);
    xmm0 = MEMF(eax + -12); /* movss */
    MEM32(edx) = ecx;
    ecx = MEM32(esp + 0x18);
    MEMF(ecx + 4) = xmm0; /* movss */
    edx = MEM32(esp + 0x18);
    MEMF(edx + 8) = xmm1; /* movss */
    ecx = MEM32(esp + 0x18);
    MEMF(ecx + 0xC) = xmm1; /* movss */
    edx = MEM32(esp + 0x1C);
    edi = MEM32(esp + 0x18);
    ecx = MEM32(eax);
    edi = edi + edx;
    edx = MEM32(esp + 0x48);
    MEM32(esp + 0x18) = edi;
    MEM32(edx) = ecx;
    ecx = MEM32(esp + 0x4C);
    edx = MEM32(esp + 0x48);
    xmm4 = MEMF(eax + -8); /* movss */
    xmm0 = MEMF(eax + -4); /* movss */
    edx = edx + ecx;
    ecx = MEM32(esp + 0x60);
    MEM32(esp + 0x48) = edx;
    xmm4 = xmm4 * xmm2; /* mulss */
    xmm4 = xmm4 - xmm3; /* subss */
    edx = (int32_t)xmm4; /* cvttss2si */
    MEM16(ecx) = LO16(edx);
    ecx = MEM32(esp + 0x60);
    xmm0 = xmm0 * xmm2; /* mulss */
    xmm0 = xmm0 - xmm3; /* subss */
    edx = (int32_t)xmm0; /* cvttss2si */
    MEM16(ecx + 2) = LO16(edx);
    edi = MEM32(esp + 0x60);
    edx = MEM32(esp + 0x64);
    edi = edi + edx;
    eax = eax + 0x14;
    ebp--;
    MEM32(esp + 0x60) = edi;
    if ((ebp != 0)) goto loc_002C5710; /* jne: not equal / not zero */

loc_002C57A6:
    eax = MEM32(0x5FA324);
    ecx = MEM32(eax + 0x28);
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 8), _icall_esp); /* indirect call */
    }

loc_002C57B4:
    ecx = MEM32(esp + 0x10);
    edx = MEM32(0x5FA324);
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, esi);
    PUSH32(esp, edx);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x20), _icall_esp); /* indirect call */
    }

loc_002C57C5:
    eax = MEM32(0x5FA324);
    ecx = MEM32(eax + 0x18);
    edx = MEM32(eax + 0x18);
    ecx = ecx ^ ebx;
    POP32(esp, edi);
    POP32(esp, esi);
    ecx = ecx & 0x1FFFF;
    edx = edx ^ ecx;
    POP32(esp, ebp);
    MEM32(eax + 0x18) = edx;
    POP32(esp, ebx);
    esp = esp + 0xE0;
    esp += 12; return; /* ret 8 */

}

/**
 * fn_002C57F0_HUDIconManager_SubmitIcon
 * Symbol: ?SubmitIcon@HUDIconManager@@IAEXPBVHUDIcon@@@Z
 * Original: 0x002C57F0 - 0x002C580F (31 bytes, 8 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002C57F0_HUDIconManager_SubmitIcon(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C57F0:
    esp = esp - 0x1CC;
    ecx = MEM32(0x5FA8E8);
    MEM32(esp + 0x18) = ecx;
    if (TEST_Z(MEM8(esi + 0x48), 0x20)) { sub_002C580F(); return; } /* je: equal / zero */

loc_002C5806:
    ecx = MEM32(eax + 0x14);
    MEM32(esp + 0xC) = ecx;
    g_seh_ebp = ebp; sub_002C5818(); return; /* tail jmp 0x002C5818 */

}

/**
 * sub_002C580F
 * Original: 0x002C580F - 0x002C5818 (9 bytes, 3 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C580F(void)
{

loc_002C580F:
    edx = MEM32(eax + 0x10);
    MEM32(esp + 0xC) = edx;
    ecx = edx;

}

/**
 * sub_002C5818
 * Original: 0x002C5818 - 0x002C5864 (76 bytes, 22 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C5818(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm2;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C5818:
    eax = MEM32(esi + 0x54);
    MEM32(ecx + 0x30) = eax;
    MEM32(ecx + 0x34) = eax;
    MEM32(ecx + 0x38) = eax;
    MEM32(ecx + 0x3C) = eax;
    MEM32(ecx + 0x40) = eax;
    MEM32(ecx + 0x44) = eax;
    MEM32(ecx + 0x48) = eax;
    MEM32(ecx + 0x4C) = eax;
    eax = MEM32(esi + 0xC);
    ecx = MEM32(esi + 0x10);
    MEM32(esp) = eax;
    eax = MEM32(esi + 0x40);
    (void)0; /* test LO8(eax), 2 - flags set for next jcc */
    MEM32(esp + 4) = ecx;
    if (TEST_Z(LO8(eax), 2)) { sub_002C5864(); return; } /* je: equal / zero */

loc_002C5847:
    xmm0 = MEMF(esi + 0x14); /* movss */
    xmm2 = MEMF(esp); /* movss */
    xmm0 = xmm0 * MEMF(0x561404); /* mulss */
    xmm2 = xmm2 - xmm0; /* subss */
    MEMF(esp) = xmm2; /* movss */
    g_seh_ebp = ebp; sub_002C587C(); return; /* tail jmp 0x002C587C */

}

/**
 * sub_002C5864
 * Original: 0x002C5864 - 0x002C587C (24 bytes, 6 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C5864(void)
{
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm2;

loc_002C5864:
    if (TEST_Z(LO8(eax), 4)) goto loc_002C5877; /* je: equal / zero */

loc_002C5868:
    xmm0 = MEMF(esp); /* movss */
    xmm0 = xmm0 - MEMF(esi + 0x14); /* subss */
    MEMF(esp) = xmm0; /* movss */

loc_002C5877:
    xmm2 = MEMF(esp); /* movss */

}

/**
 * sub_002C587C
 * Original: 0x002C587C - 0x002C589F (35 bytes, 8 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C587C(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C587C:
    if (TEST_Z(LO8(eax), 0x20)) { sub_002C589F(); return; } /* je: equal / zero */

loc_002C5880:
    xmm0 = MEMF(esi + 0x18); /* movss */
    xmm1 = MEMF(esp + 4); /* movss */
    xmm0 = xmm0 * MEMF(0x561404); /* mulss */
    xmm1 = xmm1 - xmm0; /* subss */
    MEMF(esp + 4) = xmm1; /* movss */
    g_seh_ebp = ebp; sub_002C58BA(); return; /* tail jmp 0x002C58BA */

}

/**
 * sub_002C589F
 * Original: 0x002C589F - 0x002C58BA (27 bytes, 6 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C589F(void)
{
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1;

loc_002C589F:
    if (TEST_Z(LO8(eax), 0x40)) goto loc_002C58B4; /* je: equal / zero */

loc_002C58A3:
    xmm0 = MEMF(esp + 4); /* movss */
    xmm0 = xmm0 - MEMF(esi + 0x18); /* subss */
    MEMF(esp + 4) = xmm0; /* movss */

loc_002C58B4:
    xmm1 = MEMF(esp + 4); /* movss */

}

/**
 * sub_002C58BA
 * Original: 0x002C58BA - 0x002C5F57 (1693 bytes, 388 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C58BA(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2, xmm3, xmm4;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C58BA:
    xmm0 = MEMF(esi + 0x14); /* movss */
    (void)0; /* test MEM8(esi + 0x48), 0x40 - flags set for next jcc */
    xmm0 = xmm0 + xmm2; /* addss */
    MEMF(esp + 0x10) = xmm0; /* movss */
    xmm0 = MEMF(esi + 0x18); /* movss */
    PUSH32(esp, ebp);
    xmm0 = xmm0 + xmm1; /* addss */
    PUSH32(esp, edi);
    MEMF(esp + 0x1C) = xmm0; /* movss */
    if (TEST_Z(MEM8(esi + 0x48), 0x40)) goto loc_002C5C4B; /* je: equal / zero */

loc_002C58E4:
    eax = esp + 0x24;
    PUSH32(esp, 0); fn_00025E70_0ZeroVertexRecord_QAE_XZ(); /* call 0x00025E70 */

loc_002C58ED:
    ebp = MEM32(0x5FA324);
    eax = MEM32(ebp + 0x28);
    (void)0; /* test eax, eax - flags set for next jcc */
    edi = ebp + 0x28;
    if (TEST_NZ(eax, eax)) goto loc_002C590A; /* jne: not equal / not zero */

loc_002C58FD:
    ecx = MEM32(0x5FA8E8);
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x3C), _icall_esp); /* indirect call */
    }

loc_002C5908:
    MEM32(edi) = eax;

loc_002C590A:
    ecx = MEM32(edi);
    eax = MEM32(ecx);
    edx = esp + 0x24;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, edx);
    PUSH32(esp, 1);
    PUSH32(esp, ebp);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 4), _icall_esp); /* indirect call */
    }

loc_002C5919:
    eax = MEM32(esi + 0x48);
    eax = eax >> 7;
    eax = eax & 0xF;
    (void)0; /* test eax, eax - flags set for next jcc */
    MEM32(esp + 0x10) = eax;
    fp_push((double)SMEM32(esp + 0x10)); /* fild */
    if (CMP_GE(eax & eax, 0)) goto loc_002C5934; /* jge: greater or equal (signed >=) */

loc_002C592E:
    fp_st1() += fp_top(); fp_pop(); /* fadd */

loc_002C5934:
    ecx = MEM32(esp + 0x24);
    MEMF(esp + 0x10) = (float)fp_top(); fp_popp(); /* fstp */
    xmm4 = MEMF(esp + 0x10); /* movss */
    xmm3 = MEMF(0x561418); /* movss */
    xmm1 = MEMF(esp + 0x1C); /* movss */
    xmm2 = MEMF(esp + 0x18); /* movss */
    xmm0 = xmm4; /* movaps */
    xmm0 = xmm0 + MEMF(esp + 8); /* addss */
    MEMF(ecx) = xmm0; /* movss */
    edx = MEM32(esp + 0x24);
    xmm1 = xmm1 + xmm4; /* addss */
    MEMF(edx + 4) = xmm1; /* movss */
    eax = MEM32(esp + 0x24);
    MEMF(eax + 8) = xmm3; /* movss */
    ecx = MEM32(esp + 0x24);
    MEMF(ecx + 0xC) = xmm3; /* movss */
    eax = MEM32(esp + 0x24);
    eax = eax + MEM32(esp + 0x28);
    MEM32(esp + 0x24) = eax;
    MEMF(eax) = xmm0; /* movss */
    edx = MEM32(esp + 0x24);
    xmm0 = xmm4; /* movaps */
    xmm0 = xmm0 + MEMF(esp + 0xC); /* addss */
    MEMF(edx + 4) = xmm0; /* movss */
    eax = MEM32(esp + 0x24);
    MEMF(eax + 8) = xmm3; /* movss */
    ecx = MEM32(esp + 0x24);
    MEMF(ecx + 0xC) = xmm3; /* movss */
    eax = MEM32(esp + 0x24);
    eax = eax + MEM32(esp + 0x28);
    MEM32(esp + 0x24) = eax;
    xmm2 = xmm2 + xmm4; /* addss */
    MEMF(eax) = xmm2; /* movss */
    edx = MEM32(esp + 0x24);
    MEMF(edx + 4) = xmm0; /* movss */
    eax = MEM32(esp + 0x24);
    MEMF(eax + 8) = xmm3; /* movss */
    ecx = MEM32(esp + 0x24);
    MEMF(ecx + 0xC) = xmm3; /* movss */
    eax = MEM32(esp + 0x24);
    eax = eax + MEM32(esp + 0x28);
    MEM32(esp + 0x24) = eax;
    MEMF(eax) = xmm2; /* movss */
    edx = MEM32(esp + 0x24);
    MEMF(edx + 4) = xmm1; /* movss */
    eax = MEM32(esp + 0x24);
    MEMF(eax + 8) = xmm3; /* movss */
    ecx = MEM32(esp + 0x24);
    MEMF(ecx + 0xC) = xmm3; /* movss */
    edx = MEM32(esp + 0x28);
    eax = MEM32(esp + 0x24);
    ecx = MEM32(esp + 0x54);
    eax = eax + edx;
    MEM32(esp + 0x24) = eax;
    SET_LO8(eax, MEM8(esi + 0x47));
    MEM8(esp + 0x10) = 0;
    MEM8(esp + 0x11) = 0;
    MEM8(esp + 0x12) = 0;
    MEM8(esp + 0x13) = LO8(eax);
    eax = MEM32(esp + 0x10);
    MEM32(ecx) = eax;
    ecx = MEM32(esp + 0x54);
    ecx = ecx + MEM32(esp + 0x58);
    MEM32(esp + 0x54) = ecx;
    MEM32(ecx) = eax;
    ecx = MEM32(esp + 0x54);
    ecx = ecx + MEM32(esp + 0x58);
    MEM32(esp + 0x54) = ecx;
    MEM32(ecx) = eax;
    ecx = MEM32(esp + 0x54);
    ecx = ecx + MEM32(esp + 0x58);
    MEM32(esp + 0x54) = ecx;
    MEM32(ecx) = eax;
    edx = MEM32(esp + 0x58);
    ecx = MEM32(esp + 0x54);
    SET_LO8(eax, MEM8(esi + 0x48));
    xmm0 = MEMF(0x561484); /* movss */
    xmm3 = MEMF(esi + 0x1C); /* movss */
    xmm1 = MEMF(0x561404); /* movss */
    ecx = ecx + edx;
    (void)0; /* test LO8(eax), 1 - flags set for next jcc */
    xmm3 = xmm3 * xmm0; /* mulss */
    MEM32(esp + 0x54) = ecx;
    xmm3 = xmm3 - xmm1; /* subss */
    if (TEST_Z(LO8(eax), 1)) goto loc_002C5B47; /* je: equal / zero */

loc_002C5A9E:
    ecx = MEM32(esp + 0x6C);
    xmm2 = MEMF(esi + 0x28); /* movss */
    eax = (int32_t)xmm3; /* cvttss2si */
    MEM16(ecx) = LO16(eax);
    eax = MEM32(esp + 0x6C);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    eax = MEM32(esp + 0x6C);
    edi = MEM32(esp + 0x70);
    xmm3 = MEMF(esi + 0x1C); /* movss */
    xmm2 = MEMF(esi + 0x20); /* movss */
    eax = eax + edi;
    MEM32(esp + 0x6C) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(ecx);
    eax = MEM32(esp + 0x6C);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    eax = MEM32(esp + 0x6C);
    edx = MEM32(esp + 0x70);
    xmm3 = MEMF(esi + 0x24); /* movss */
    xmm2 = MEMF(esi + 0x20); /* movss */
    eax = eax + edx;
    xmm3 = xmm3 * xmm0; /* mulss */
    MEM32(esp + 0x6C) = eax;
    xmm3 = xmm3 - xmm1; /* subss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(ecx);
    eax = MEM32(esp + 0x6C);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    xmm2 = MEMF(esi + 0x28); /* movss */
    xmm3 = MEMF(esi + 0x24); /* movss */
    goto loc_002C5BEB;

loc_002C5B47:
    eax = MEM32(esp + 0x6C);
    xmm2 = MEMF(esi + 0x20); /* movss */
    edx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(edx);
    edx = MEM32(esp + 0x6C);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    ecx = (int32_t)xmm2; /* cvttss2si */
    MEM16(edx + 2) = LO16(ecx);
    eax = MEM32(esp + 0x6C);
    edi = MEM32(esp + 0x70);
    xmm3 = MEMF(esi + 0x24); /* movss */
    xmm2 = MEMF(esi + 0x28); /* movss */
    eax = eax + edi;
    MEM32(esp + 0x6C) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(ecx);
    eax = MEM32(esp + 0x6C);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    eax = MEM32(esp + 0x6C);
    edx = MEM32(esp + 0x70);
    xmm3 = MEMF(esi + 0x2C); /* movss */
    xmm2 = MEMF(esi + 0x30); /* movss */
    eax = eax + edx;
    xmm3 = xmm3 * xmm0; /* mulss */
    MEM32(esp + 0x6C) = eax;
    xmm3 = xmm3 - xmm1; /* subss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(ecx);
    eax = MEM32(esp + 0x6C);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    xmm2 = MEMF(esi + 0x38); /* movss */
    xmm3 = MEMF(esi + 0x34); /* movss */

loc_002C5BEB:
    eax = MEM32(esp + 0x6C);
    eax = eax + MEM32(esp + 0x70);
    MEM32(esp + 0x6C) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(ecx);
    eax = MEM32(esp + 0x6C);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    eax = MEM32(esp + 0x6C);
    ecx = MEM32(esp + 0x70);
    eax = eax + ecx;
    MEM32(esp + 0x6C) = eax;
    eax = MEM32(0x5FA324);
    ecx = MEM32(eax + 0x28);
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 8), _icall_esp); /* indirect call */
    }

loc_002C5C36:
    edx = MEM32(esp + 0x14);
    ecx = MEM32(esp + 0x20);
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, edx);
    edx = MEM32(0x5FA324);
    PUSH32(esp, edx);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x20), _icall_esp); /* indirect call */
    }

loc_002C5C4B:
    eax = esp + 0xFC;
    PUSH32(esp, 0); fn_00025E70_0ZeroVertexRecord_QAE_XZ(); /* call 0x00025E70 */

loc_002C5C57:
    ebp = MEM32(0x5FA324);
    eax = MEM32(ebp + 0x28);
    (void)0; /* test eax, eax - flags set for next jcc */
    edi = ebp + 0x28;
    if (TEST_NZ(eax, eax)) goto loc_002C5C74; /* jne: not equal / not zero */

loc_002C5C67:
    ecx = MEM32(0x5FA8E8);
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x3C), _icall_esp); /* indirect call */
    }

loc_002C5C72:
    MEM32(edi) = eax;

loc_002C5C74:
    ecx = MEM32(edi);
    edx = MEM32(ecx);
    eax = esp + 0xFC;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 1);
    PUSH32(esp, ebp);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 4), _icall_esp); /* indirect call */
    }

loc_002C5C86:
    ecx = MEM32(esp + 0xFC);
    xmm1 = MEMF(esp + 8); /* movss */
    MEMF(ecx) = xmm1; /* movss */
    edx = MEM32(esp + 0xFC);
    xmm0 = MEMF(0x561418); /* movss */
    xmm2 = MEMF(esp + 0x1C); /* movss */
    MEMF(edx + 4) = xmm2; /* movss */
    eax = MEM32(esp + 0xFC);
    MEMF(eax + 8) = xmm0; /* movss */
    ecx = MEM32(esp + 0xFC);
    MEMF(ecx + 0xC) = xmm0; /* movss */
    eax = MEM32(esp + 0xFC);
    edi = MEM32(esp + 0x100);
    xmm3 = MEMF(esp + 0xC); /* movss */
    eax = eax + edi;
    MEM32(esp + 0xFC) = eax;
    MEMF(eax) = xmm1; /* movss */
    edx = MEM32(esp + 0xFC);
    MEMF(edx + 4) = xmm3; /* movss */
    eax = MEM32(esp + 0xFC);
    MEMF(eax + 8) = xmm0; /* movss */
    ecx = MEM32(esp + 0xFC);
    MEMF(ecx + 0xC) = xmm0; /* movss */
    eax = MEM32(esp + 0xFC);
    edx = MEM32(esp + 0x100);
    xmm1 = MEMF(esp + 0x18); /* movss */
    eax = eax + edx;
    MEM32(esp + 0xFC) = eax;
    MEMF(eax) = xmm1; /* movss */
    edx = MEM32(esp + 0xFC);
    MEMF(edx + 4) = xmm3; /* movss */
    eax = MEM32(esp + 0xFC);
    MEMF(eax + 8) = xmm0; /* movss */
    ecx = MEM32(esp + 0xFC);
    MEMF(ecx + 0xC) = xmm0; /* movss */
    eax = MEM32(esp + 0xFC);
    eax = eax + MEM32(esp + 0x100);
    MEM32(esp + 0xFC) = eax;
    MEMF(eax) = xmm1; /* movss */
    edx = MEM32(esp + 0xFC);
    MEMF(edx + 4) = xmm2; /* movss */
    eax = MEM32(esp + 0xFC);
    MEMF(eax + 8) = xmm0; /* movss */
    ecx = MEM32(esp + 0xFC);
    MEMF(ecx + 0xC) = xmm0; /* movss */
    edx = MEM32(esp + 0x100);
    eax = MEM32(esp + 0xFC);
    ecx = MEM32(esp + 0x12C);
    eax = eax + edx;
    MEM32(esp + 0xFC) = eax;
    eax = MEM32(esi + 0x44);
    MEM32(ecx) = eax;
    eax = MEM32(esp + 0x12C);
    ebp = MEM32(esp + 0x130);
    edx = MEM32(esi + 0x44);
    eax = eax + ebp;
    MEM32(esp + 0x12C) = eax;
    MEM32(eax) = edx;
    eax = MEM32(esp + 0x12C);
    edi = MEM32(esp + 0x130);
    ecx = MEM32(esi + 0x44);
    eax = eax + edi;
    MEM32(esp + 0x12C) = eax;
    MEM32(eax) = ecx;
    eax = MEM32(esp + 0x12C);
    eax = eax + MEM32(esp + 0x130);
    edx = MEM32(esi + 0x44);
    MEM32(esp + 0x12C) = eax;
    MEM32(eax) = edx;
    eax = MEM32(esp + 0x130);
    ecx = MEM32(esp + 0x12C);
    ecx = ecx + eax;
    (void)0; /* test MEM8(esi + 0x48), 1 - flags set for next jcc */
    xmm0 = MEMF(0x561484); /* movss */
    xmm3 = MEMF(esi + 0x1C); /* movss */
    xmm1 = MEMF(0x561404); /* movss */
    xmm3 = xmm3 * xmm0; /* mulss */
    MEM32(esp + 0x12C) = ecx;
    xmm3 = xmm3 - xmm1; /* subss */
    if (TEST_Z(MEM8(esi + 0x48), 1)) { sub_002C5F57(); return; } /* je: equal / zero */

loc_002C5E43:
    edx = MEM32(esp + 0x144);
    xmm2 = MEMF(esi + 0x28); /* movss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(edx) = LO16(ecx);
    ecx = MEM32(esp + 0x144);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    eax = (int32_t)xmm2; /* cvttss2si */
    MEM16(ecx + 2) = LO16(eax);
    eax = MEM32(esp + 0x144);
    edi = MEM32(esp + 0x148);
    xmm3 = MEMF(esi + 0x1C); /* movss */
    xmm2 = MEMF(esi + 0x20); /* movss */
    eax = eax + edi;
    MEM32(esp + 0x144) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    edx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(edx);
    ecx = MEM32(esp + 0x144);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    eax = (int32_t)xmm2; /* cvttss2si */
    MEM16(ecx + 2) = LO16(eax);
    eax = MEM32(esp + 0x144);
    edx = MEM32(esp + 0x148);
    xmm3 = MEMF(esi + 0x24); /* movss */
    xmm2 = MEMF(esi + 0x20); /* movss */
    eax = eax + edx;
    MEM32(esp + 0x144) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    edx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(edx);
    ecx = MEM32(esp + 0x144);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    eax = (int32_t)xmm2; /* cvttss2si */
    MEM16(ecx + 2) = LO16(eax);
    eax = MEM32(esp + 0x144);
    ecx = MEM32(esp + 0x148);
    xmm3 = MEMF(esi + 0x24); /* movss */
    xmm2 = MEMF(esi + 0x28); /* movss */
    eax = eax + ecx;
    MEM32(esp + 0x144) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    edx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(edx);
    ecx = MEM32(esp + 0x144);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    eax = (int32_t)xmm2; /* cvttss2si */
    MEM16(ecx + 2) = LO16(eax);
    edx = MEM32(esp + 0x148);
    eax = MEM32(esp + 0x144);
    eax = eax + edx;
    g_seh_ebp = ebp; sub_002C6066(); return; /* tail jmp 0x002C6066 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * sub_002C5F57
 * Original: 0x002C5F57 - 0x002C6066 (271 bytes, 57 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C5F57(void)
{
    float xmm0, xmm1, xmm2, xmm3;

loc_002C5F57:
    ecx = MEM32(esp + 0x144);
    xmm2 = MEMF(esi + 0x20); /* movss */
    eax = (int32_t)xmm3; /* cvttss2si */
    MEM16(ecx) = LO16(eax);
    eax = MEM32(esp + 0x144);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    eax = MEM32(esp + 0x144);
    edi = MEM32(esp + 0x148);
    xmm3 = MEMF(esi + 0x24); /* movss */
    xmm2 = MEMF(esi + 0x28); /* movss */
    eax = eax + edi;
    MEM32(esp + 0x144) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(ecx);
    eax = MEM32(esp + 0x144);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    eax = MEM32(esp + 0x144);
    edx = MEM32(esp + 0x148);
    xmm3 = MEMF(esi + 0x2C); /* movss */
    xmm2 = MEMF(esi + 0x30); /* movss */
    eax = eax + edx;
    MEM32(esp + 0x144) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(ecx);
    eax = MEM32(esp + 0x144);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    eax = MEM32(esp + 0x144);
    ecx = MEM32(esp + 0x148);
    xmm3 = MEMF(esi + 0x34); /* movss */
    xmm2 = MEMF(esi + 0x38); /* movss */
    eax = eax + ecx;
    MEM32(esp + 0x144) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(ecx);
    eax = MEM32(esp + 0x144);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    ecx = MEM32(esp + 0x148);
    eax = MEM32(esp + 0x144);
    eax = eax + ecx;

}

/**
 * sub_002C6066
 * Original: 0x002C6066 - 0x002C6099 (51 bytes, 17 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C6066(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C6066:
    MEM32(esp + 0x144) = eax;
    eax = MEM32(0x5FA324);
    ecx = MEM32(eax + 0x28);
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 8), _icall_esp); /* indirect call */
    }

loc_002C607B:
    edx = MEM32(esp + 0x14);
    ecx = MEM32(esp + 0x20);
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, edx);
    edx = MEM32(0x5FA324);
    PUSH32(esp, edx);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x20), _icall_esp); /* indirect call */
    }

loc_002C6090:
    POP32(esp, edi);
    POP32(esp, ebp);
    esp = esp + 0x1CC;
    esp += 4; return; /* ret */

}

/**
 * fn_002C60A0_HUDIconManager_SubmitIconOriented
 * Symbol: ?SubmitIconOriented@HUDIconManager@@IAEXPBVHUDIcon@@@Z
 * Original: 0x002C60A0 - 0x002C60F0 (80 bytes, 22 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002C60A0_HUDIconManager_SubmitIconOriented(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2, xmm3, xmm4;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C60A0:
    esp = esp - 0x124;
    xmm0 = MEMF(0x561404); /* movss */
    xmm1 = MEMF(esi + 0x14); /* movss */
    xmm4 = MEMF(esi + 0x18); /* movss */
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    PUSH32(esp, edi);
    edi = eax;
    eax = MEM32(0x5FA8E8);
    MEM32(esp + 0x54) = eax;
    eax = MEM32(esi + 0x40);
    (void)0; /* test LO8(eax), 1 - flags set for next jcc */
    xmm1 = xmm1 * xmm0; /* mulss */
    xmm4 = xmm4 * xmm0; /* mulss */
    xmm0 = 0.0f; /* xorps self = zero */
    MEMF(esp + 0x2C) = xmm1; /* movss */
    MEMF(esp + 0x30) = xmm4; /* movss */
    xmm2 = xmm0; /* movaps */
    xmm3 = xmm0; /* movaps */
    if (TEST_Z(LO8(eax), 1)) { sub_002C60F0(); return; } /* je: equal / zero */

loc_002C60EA:
    xmm2 = xmm2 - xmm1; /* subss */
    g_seh_ebp = ebp; sub_002C60F7(); return; /* tail jmp 0x002C60F7 */

}

/**
 * sub_002C60F0
 * Original: 0x002C60F0 - 0x002C60F7 (7 bytes, 3 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C60F0(void)
{
    int _flags = 0; /* fallback flag var */
    float xmm1, xmm2;

loc_002C60F0:
    if (TEST_Z(LO8(eax), 4)) { sub_002C60F7(); return; } /* je: equal / zero */

loc_002C60F4:
    xmm2 = xmm1; /* movaps */

}

/**
 * sub_002C60F7
 * Original: 0x002C60F7 - 0x002C6104 (13 bytes, 5 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C60F7(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm3, xmm4;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C60F7:
    if (TEST_Z(LO8(eax), 0x10)) { sub_002C6104(); return; } /* je: equal / zero */

loc_002C60FB:
    xmm3 = xmm0; /* movaps */
    xmm3 = xmm3 - xmm4; /* subss */
    g_seh_ebp = ebp; sub_002C610B(); return; /* tail jmp 0x002C610B */

}

/**
 * sub_002C6104
 * Original: 0x002C6104 - 0x002C610B (7 bytes, 3 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C6104(void)
{
    int _flags = 0; /* fallback flag var */
    float xmm3, xmm4;

loc_002C6104:
    if (TEST_Z(LO8(eax), 0x40)) { sub_002C610B(); return; } /* je: equal / zero */

loc_002C6108:
    xmm3 = xmm4; /* movaps */

}

/**
 * sub_002C610B
 * Original: 0x002C610B - 0x002C6193 (136 bytes, 29 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C610B(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2, xmm3;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C610B:
    xmm1 = MEMF(esi + 0xC); /* movss */
    ecx = MEM32(esi + 0x3C);
    MEMF(esp + 0x14) = xmm1; /* movss */
    xmm1 = MEMF(esi + 0x10); /* movss */
    MEMF(esp + 0x18) = xmm1; /* movss */
    xmm1 = xmm0; /* movaps */
    xmm1 = xmm1 - xmm2; /* subss */
    xmm2 = xmm0; /* movaps */
    xmm2 = xmm2 - xmm3; /* subss */
    xmm3 = MEMF(0x561418); /* movss */
    PUSH32(esp, ecx);
    eax = esp + 0x38;
    MEMF(esp + 0x38) = xmm3; /* movss */
    MEMF(esp + 0x3C) = xmm0; /* movss */
    MEMF(esp + 0x40) = xmm0; /* movss */
    MEMF(esp + 0x44) = xmm3; /* movss */
    MEMF(esp + 0x48) = xmm1; /* movss */
    MEMF(esp + 0x4C) = xmm2; /* movss */
    PUSH32(esp, 0); fn_0002B290_HUDMatrix2D_Rotate(); /* call 0x0002B290 */

loc_002C6168:
    xmm0 = MEMF(esp + 0x14); /* movss */
    xmm0 = xmm0 + MEMF(eax + 0x10); /* addss */
    MEMF(eax + 0x10) = xmm0; /* movss */
    xmm0 = MEMF(esp + 0x18); /* movss */
    xmm0 = xmm0 + MEMF(eax + 0x14); /* addss */
    MEMF(eax + 0x14) = xmm0; /* movss */
    if (TEST_Z(MEM8(esi + 0x48), 0x20)) { sub_002C6193(); return; } /* je: equal / zero */

loc_002C618E:
    edi = MEM32(edi + 0x14);
    g_seh_ebp = ebp; sub_002C6196(); return; /* tail jmp 0x002C6196 */

}

/**
 * sub_002C6193
 * Original: 0x002C6193 - 0x002C6196 (3 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C6193(void)
{

loc_002C6193:
    edi = MEM32(edi + 0x10);

}

/**
 * sub_002C6196
 * Original: 0x002C6196 - 0x002C6619 (1155 bytes, 259 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C6196(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2, xmm3, xmm4, xmm5, xmm6, xmm7;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C6196:
    eax = MEM32(esi + 0x54);
    xmm1 = 0.0f; /* xorps self = zero */
    xmm6 = MEMF(esp + 0x30); /* movss */
    edx = MEM32(esp + 0x2C);
    MEM32(edi + 0x30) = eax;
    MEM32(edi + 0x34) = eax;
    MEM32(edi + 0x38) = eax;
    MEM32(edi + 0x3C) = eax;
    MEM32(edi + 0x40) = eax;
    MEM32(edi + 0x44) = eax;
    MEM32(edi + 0x48) = eax;
    MEM32(edi + 0x4C) = eax;
    xmm2 = MEMF(esp + 0x34); /* movss */
    xmm4 = MEMF(esp + 0x44); /* movss */
    eax = MEM32(esp + 0x30);
    xmm0 = xmm1; /* movaps */
    xmm0 = xmm0 - MEMF(esp + 0x2C); /* subss */
    xmm1 = xmm1 - xmm6; /* subss */
    MEMF(esp + 0x20) = xmm1; /* movss */
    MEMF(esp + 0x18) = xmm1; /* movss */
    xmm5 = xmm0; /* movaps */
    MEMF(esp + 0x1C) = xmm0; /* movss */
    xmm0 = MEMF(esp + 0x3C); /* movss */
    xmm1 = xmm0; /* movaps */
    xmm1 = xmm1 * xmm6; /* mulss */
    xmm3 = xmm2; /* movaps */
    xmm3 = xmm3 * xmm5; /* mulss */
    xmm1 = xmm1 + xmm3; /* addss */
    xmm3 = MEMF(esp + 0x38); /* movss */
    xmm1 = xmm1 + xmm4; /* addss */
    MEMF(esp + 0xC) = xmm1; /* movss */
    xmm1 = MEMF(esp + 0x40); /* movss */
    ecx = MEM32(esp + 0xC);
    xmm7 = xmm3; /* movaps */
    xmm7 = xmm7 * xmm5; /* mulss */
    xmm5 = xmm1; /* movaps */
    xmm5 = xmm5 * xmm6; /* mulss */
    xmm7 = xmm7 + xmm5; /* addss */
    xmm7 = xmm7 + MEMF(esp + 0x48); /* addss */
    xmm5 = MEMF(esp + 0x1C); /* movss */
    MEMF(esp + 0x10) = xmm7; /* movss */
    xmm6 = xmm0; /* movaps */
    xmm6 = xmm6 * MEMF(esp + 0x20); /* mulss */
    xmm7 = xmm2; /* movaps */
    xmm7 = xmm7 * xmm5; /* mulss */
    xmm6 = xmm6 + xmm7; /* addss */
    xmm6 = xmm6 + xmm4; /* addss */
    MEMF(esp + 0xC) = xmm6; /* movss */
    xmm6 = xmm1; /* movaps */
    xmm6 = xmm6 * MEMF(esp + 0x20); /* mulss */
    xmm7 = xmm3; /* movaps */
    xmm7 = xmm7 * xmm5; /* mulss */
    xmm5 = MEMF(esp + 0x2C); /* movss */
    xmm6 = xmm6 + xmm7; /* addss */
    xmm6 = xmm6 + MEMF(esp + 0x48); /* addss */
    MEM32(esp + 0x24) = edx;
    edx = MEM32(esp + 0x10);
    MEMF(esp + 0x10) = xmm6; /* movss */
    xmm6 = xmm0; /* movaps */
    xmm6 = xmm6 * MEMF(esp + 0x18); /* mulss */
    xmm7 = xmm2; /* movaps */
    xmm7 = xmm7 * xmm5; /* mulss */
    xmm6 = xmm6 + xmm7; /* addss */
    xmm6 = xmm6 + xmm4; /* addss */
    MEM32(esp + 0x28) = eax;
    eax = MEM32(esp + 0xC);
    MEMF(esp + 0xC) = xmm6; /* movss */
    xmm6 = xmm1; /* movaps */
    xmm6 = xmm6 * MEMF(esp + 0x18); /* mulss */
    xmm7 = xmm3; /* movaps */
    xmm7 = xmm7 * xmm5; /* mulss */
    xmm5 = MEMF(esp + 0x48); /* movss */
    MEM32(esp + 0x4C) = ecx;
    ecx = MEM32(esp + 0x10);
    xmm6 = xmm6 + xmm7; /* addss */
    MEM32(esp + 0x50) = edx;
    edx = MEM32(esp + 0xC);
    xmm6 = xmm6 + xmm5; /* addss */
    MEM32(esp + 0x1C) = eax;
    MEM32(esp + 0x20) = ecx;
    MEMF(esp + 0x10) = xmm6; /* movss */
    xmm6 = MEMF(esp + 0x28); /* movss */
    xmm7 = MEMF(esp + 0x24); /* movss */
    eax = MEM32(esp + 0x10);
    xmm0 = xmm0 * xmm6; /* mulss */
    xmm1 = xmm1 * xmm6; /* mulss */
    xmm2 = xmm2 * xmm7; /* mulss */
    xmm3 = xmm3 * xmm7; /* mulss */
    xmm0 = xmm0 + xmm2; /* addss */
    xmm1 = xmm1 + xmm3; /* addss */
    xmm0 = xmm0 + xmm4; /* addss */
    xmm1 = xmm1 + xmm5; /* addss */
    MEM32(esp + 0x14) = edx;
    MEMF(esp + 0xC) = xmm0; /* movss */
    ecx = MEM32(esp + 0xC);
    MEMF(esp + 0x10) = xmm1; /* movss */
    edx = MEM32(esp + 0x10);
    MEM32(esp + 0x18) = eax;
    eax = esp + 0x58;
    MEM32(esp + 0x24) = ecx;
    MEM32(esp + 0x28) = edx;
    PUSH32(esp, 0); fn_00025E70_0ZeroVertexRecord_QAE_XZ(); /* call 0x00025E70 */

loc_002C6351:
    ebp = MEM32(0x5FA324);
    eax = MEM32(ebp + 0x28);
    (void)0; /* test eax, eax - flags set for next jcc */
    ebx = ebp + 0x28;
    if (TEST_NZ(eax, eax)) goto loc_002C636E; /* jne: not equal / not zero */

loc_002C6361:
    ecx = MEM32(0x5FA8E8);
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x3C), _icall_esp); /* indirect call */
    }

loc_002C636C:
    MEM32(ebx) = eax;

loc_002C636E:
    ecx = MEM32(ebx);
    edx = MEM32(ecx);
    eax = esp + 0x58;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 1);
    PUSH32(esp, ebp);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 4), _icall_esp); /* indirect call */
    }

loc_002C637D:
    ecx = MEM32(esp + 0x58);
    xmm0 = MEMF(esp + 0x4C); /* movss */
    MEMF(ecx) = xmm0; /* movss */
    edx = MEM32(esp + 0x58);
    xmm0 = MEMF(esp + 0x50); /* movss */
    MEMF(edx + 4) = xmm0; /* movss */
    eax = MEM32(esp + 0x58);
    xmm0 = MEMF(0x561418); /* movss */
    MEMF(eax + 8) = xmm0; /* movss */
    ecx = MEM32(esp + 0x58);
    MEMF(ecx + 0xC) = xmm0; /* movss */
    eax = MEM32(esp + 0x58);
    ebx = MEM32(esp + 0x5C);
    xmm1 = MEMF(esp + 0x1C); /* movss */
    eax = eax + ebx;
    MEM32(esp + 0x58) = eax;
    MEMF(eax) = xmm1; /* movss */
    edx = MEM32(esp + 0x58);
    xmm1 = MEMF(esp + 0x20); /* movss */
    MEMF(edx + 4) = xmm1; /* movss */
    eax = MEM32(esp + 0x58);
    MEMF(eax + 8) = xmm0; /* movss */
    ecx = MEM32(esp + 0x58);
    xmm1 = MEMF(esp + 0x14); /* movss */
    MEMF(ecx + 0xC) = xmm0; /* movss */
    eax = MEM32(esp + 0x58);
    eax = eax + MEM32(esp + 0x5C);
    MEM32(esp + 0x58) = eax;
    MEMF(eax) = xmm1; /* movss */
    edx = MEM32(esp + 0x58);
    xmm1 = MEMF(esp + 0x18); /* movss */
    MEMF(edx + 4) = xmm1; /* movss */
    eax = MEM32(esp + 0x58);
    MEMF(eax + 8) = xmm0; /* movss */
    ecx = MEM32(esp + 0x58);
    xmm1 = MEMF(esp + 0x24); /* movss */
    MEMF(ecx + 0xC) = xmm0; /* movss */
    eax = MEM32(esp + 0x58);
    eax = eax + MEM32(esp + 0x5C);
    MEM32(esp + 0x58) = eax;
    MEMF(eax) = xmm1; /* movss */
    edx = MEM32(esp + 0x58);
    xmm1 = MEMF(esp + 0x28); /* movss */
    MEMF(edx + 4) = xmm1; /* movss */
    eax = MEM32(esp + 0x58);
    MEMF(eax + 8) = xmm0; /* movss */
    ecx = MEM32(esp + 0x58);
    MEMF(ecx + 0xC) = xmm0; /* movss */
    edx = MEM32(esp + 0x5C);
    eax = MEM32(esp + 0x58);
    ecx = MEM32(esp + 0x88);
    eax = eax + edx;
    MEM32(esp + 0x58) = eax;
    eax = MEM32(esi + 0x44);
    MEM32(ecx) = eax;
    eax = MEM32(esp + 0x88);
    ebp = MEM32(esp + 0x8C);
    edx = MEM32(esi + 0x44);
    eax = eax + ebp;
    MEM32(esp + 0x88) = eax;
    MEM32(eax) = edx;
    eax = MEM32(esp + 0x88);
    ebx = MEM32(esp + 0x8C);
    ecx = MEM32(esi + 0x44);
    eax = eax + ebx;
    MEM32(esp + 0x88) = eax;
    MEM32(eax) = ecx;
    eax = MEM32(esp + 0x88);
    eax = eax + MEM32(esp + 0x8C);
    edx = MEM32(esi + 0x44);
    MEM32(esp + 0x88) = eax;
    xmm0 = MEMF(0x561484); /* movss */
    xmm1 = MEMF(0x561404); /* movss */
    MEM32(eax) = edx;
    eax = MEM32(esp + 0x8C);
    ecx = MEM32(esp + 0x88);
    xmm3 = MEMF(esi + 0x1C); /* movss */
    ecx = ecx + eax;
    (void)0; /* test MEM8(esi + 0x48), 1 - flags set for next jcc */
    xmm3 = xmm3 * xmm0; /* mulss */
    MEM32(esp + 0x88) = ecx;
    xmm3 = xmm3 - xmm1; /* subss */
    if (TEST_Z(MEM8(esi + 0x48), 1)) { sub_002C6619(); return; } /* je: equal / zero */

loc_002C6505:
    edx = MEM32(esp + 0xA0);
    xmm2 = MEMF(esi + 0x28); /* movss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(edx) = LO16(ecx);
    ecx = MEM32(esp + 0xA0);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    eax = (int32_t)xmm2; /* cvttss2si */
    MEM16(ecx + 2) = LO16(eax);
    eax = MEM32(esp + 0xA0);
    ebx = MEM32(esp + 0xA4);
    xmm3 = MEMF(esi + 0x1C); /* movss */
    xmm2 = MEMF(esi + 0x20); /* movss */
    eax = eax + ebx;
    MEM32(esp + 0xA0) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    edx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(edx);
    ecx = MEM32(esp + 0xA0);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    eax = (int32_t)xmm2; /* cvttss2si */
    MEM16(ecx + 2) = LO16(eax);
    eax = MEM32(esp + 0xA0);
    edx = MEM32(esp + 0xA4);
    xmm3 = MEMF(esi + 0x24); /* movss */
    xmm2 = MEMF(esi + 0x20); /* movss */
    eax = eax + edx;
    MEM32(esp + 0xA0) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    edx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(edx);
    ecx = MEM32(esp + 0xA0);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    eax = (int32_t)xmm2; /* cvttss2si */
    MEM16(ecx + 2) = LO16(eax);
    eax = MEM32(esp + 0xA0);
    ecx = MEM32(esp + 0xA4);
    xmm3 = MEMF(esi + 0x24); /* movss */
    xmm2 = MEMF(esi + 0x28); /* movss */
    eax = eax + ecx;
    MEM32(esp + 0xA0) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    edx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(edx);
    ecx = MEM32(esp + 0xA0);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    eax = (int32_t)xmm2; /* cvttss2si */
    MEM16(ecx + 2) = LO16(eax);
    edx = MEM32(esp + 0xA4);
    eax = MEM32(esp + 0xA0);
    eax = eax + edx;
    g_seh_ebp = ebp; sub_002C6728(); return; /* tail jmp 0x002C6728 */

}

/**
 * sub_002C6619
 * Original: 0x002C6619 - 0x002C6728 (271 bytes, 57 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C6619(void)
{
    float xmm0, xmm1, xmm2, xmm3;

loc_002C6619:
    ecx = MEM32(esp + 0xA0);
    xmm2 = MEMF(esi + 0x20); /* movss */
    eax = (int32_t)xmm3; /* cvttss2si */
    MEM16(ecx) = LO16(eax);
    eax = MEM32(esp + 0xA0);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    eax = MEM32(esp + 0xA0);
    ebx = MEM32(esp + 0xA4);
    xmm3 = MEMF(esi + 0x24); /* movss */
    xmm2 = MEMF(esi + 0x28); /* movss */
    eax = eax + ebx;
    MEM32(esp + 0xA0) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(ecx);
    eax = MEM32(esp + 0xA0);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    eax = MEM32(esp + 0xA0);
    edx = MEM32(esp + 0xA4);
    xmm3 = MEMF(esi + 0x2C); /* movss */
    xmm2 = MEMF(esi + 0x30); /* movss */
    eax = eax + edx;
    MEM32(esp + 0xA0) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(ecx);
    eax = MEM32(esp + 0xA0);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    eax = MEM32(esp + 0xA0);
    ecx = MEM32(esp + 0xA4);
    xmm3 = MEMF(esi + 0x34); /* movss */
    xmm2 = MEMF(esi + 0x38); /* movss */
    eax = eax + ecx;
    MEM32(esp + 0xA0) = eax;
    xmm3 = xmm3 * xmm0; /* mulss */
    xmm3 = xmm3 - xmm1; /* subss */
    ecx = (int32_t)xmm3; /* cvttss2si */
    MEM16(eax) = LO16(ecx);
    eax = MEM32(esp + 0xA0);
    xmm2 = xmm2 * xmm0; /* mulss */
    xmm2 = xmm2 - xmm1; /* subss */
    edx = (int32_t)xmm2; /* cvttss2si */
    MEM16(eax + 2) = LO16(edx);
    ecx = MEM32(esp + 0xA4);
    eax = MEM32(esp + 0xA0);
    eax = eax + ecx;

}

/**
 * sub_002C6728
 * Original: 0x002C6728 - 0x002C6758 (48 bytes, 17 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C6728(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C6728:
    MEM32(esp + 0xA0) = eax;
    eax = MEM32(0x5FA324);
    ecx = MEM32(eax + 0x28);
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 8), _icall_esp); /* indirect call */
    }

loc_002C673D:
    ecx = MEM32(esp + 0x54);
    edx = MEM32(0x5FA324);
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, edi);
    PUSH32(esp, edx);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x20), _icall_esp); /* indirect call */
    }

loc_002C674E:
    POP32(esp, edi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp = esp + 0x124;
    esp += 4; return; /* ret */

}

/**
 * fn_002C6760_HUDIconManager_Setup
 * Symbol: ?Setup@HUDIconManager@@QAEXXZ
 * Original: 0x002C6760 - 0x002C67A5 (69 bytes, 24 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002C6760_HUDIconManager_Setup(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C6760:
    esp = esp - 0x110;
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    edi = MEM32(0x5FA8E8);
    ebx = 0; /* xor self */
    PUSH32(esp, ebx);
    esi = eax;
    MEM8(esp + 0x10) = 8;
    MEM8(esp + 0x11) = 0x12;
    MEM8(esp + 0x12) = LO8(ebx);
    MEM8(esp + 0x13) = LO8(ebx);
    eax = MEM32(esp + 0x10);
    PUSH32(esp, ebx);
    PUSH32(esp, eax);
    PUSH32(esp, ecx);
    ecx = MEM32(0x5D1AE8);
    (void)0; /* cmp ecx, ebx - flags set for next jcc */
    eax = esp;
    MEM32(esp + 0x20) = esp;
    MEM32(esp + 0x20) = eax;
    if (CMP_NE(ecx, ebx)) { sub_002C67A5(); return; } /* jne: not equal / not zero */

loc_002C67A1:
    MEM32(eax) = ebx;
    g_seh_ebp = ebp; sub_002C67B2(); return; /* tail jmp 0x002C67B2 */

}

/**
 * sub_002C67A5
 * Original: 0x002C67A5 - 0x002C67B2 (13 bytes, 4 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C67A5(void)
{

loc_002C67A5:
    eax = 0; /* xor self */
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_002C67AC:
    ecx = MEM32(esp + 0x20);
    MEM32(ecx) = eax;

}

/**
 * sub_002C67B2
 * Original: 0x002C67B2 - 0x002C6852 (160 bytes, 54 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C67B2(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C67B2:
    ecx = ebx;
    edx = esp + 0x24;
    PUSH32(esp, 0); fn_000280C0_0ZeroMaterialDesc_QAE_VCRC_TAttribData_KQBQAVZeroSurface_H_Z(); /* call 0x000280C0 */

loc_002C67BD:
    edx = MEM32(edi);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    ecx = edi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x40), _icall_esp); /* indirect call */
    }

loc_002C67C5:
    MEM32(esi + 0x10) = eax;
    PUSH32(esp, 0); fn_0014D0F0_XBShaderFactory_Get(); /* call 0x0014D0F0 */

loc_002C67CD:
    edx = 0x50000010;
    PUSH32(esp, 0); fn_00148C60_XBShaderFactory_FindShader(); /* call 0x00148C60 */

loc_002C67D7:
    PUSH32(esp, ebx);
    PUSH32(esp, ebx);
    PUSH32(esp, ebx);
    PUSH32(esp, 0x5CE6D8);
    edx = 0x5CE6A4;
    SET_LO8(ecx, 0xF0);
    MEM32(esi + 0x18) = eax;
    PUSH32(esp, 0); fn_00125AD0_ZeroStateGroup_Create(); /* call 0x00125AD0 */

loc_002C67EE:
    ecx = MEM32(esi + 0x10);
    esp = esp + 0x10;
    (void)0; /* cmp ecx, ebx - flags set for next jcc */
    MEM32(esi + 0x1C) = eax;
    if (CMP_EQ(ecx, ebx)) goto loc_002C6832; /* je: equal / zero */

loc_002C67FB:
    edx = MEM32(esi + 0x18);
    if (CMP_EQ(edx, ebx)) goto loc_002C6832; /* je: equal / zero */

loc_002C6802:
    if (CMP_EQ(eax, ebx)) goto loc_002C6832; /* je: equal / zero */

loc_002C6806:
    eax = ZX8(MEM8(0x5CD920));
    MEM32(ecx + eax * 4 + 0xA8) = edx;
    eax = MEM32(esi + 0x1C);
    ecx = MEM32(esi + 0x10);
    MEM32(ecx + 0x10) = eax;
    MEM32(ecx + 0x14) = eax;
    MEM32(ecx + 0x18) = eax;
    MEM32(ecx + 0x1C) = eax;
    MEM32(ecx + 0x20) = eax;
    MEM32(ecx + 0x24) = eax;
    MEM32(ecx + 0x28) = eax;
    MEM32(ecx + 0x2C) = eax;

loc_002C6832:
    ecx = MEM32(esp + 0xC);
    PUSH32(esp, ebx);
    PUSH32(esp, ebx);
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    ecx = MEM32(0x5D1AE8);
    (void)0; /* cmp ecx, ebx - flags set for next jcc */
    eax = esp;
    MEM32(esp + 0x20) = esp;
    MEM32(esp + 0x20) = eax;
    if (CMP_NE(ecx, ebx)) { sub_002C6852(); return; } /* jne: not equal / not zero */

loc_002C684E:
    MEM32(eax) = ebx;
    g_seh_ebp = ebp; sub_002C685F(); return; /* tail jmp 0x002C685F */

}

/**
 * sub_002C6852
 * Original: 0x002C6852 - 0x002C685F (13 bytes, 4 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C6852(void)
{

loc_002C6852:
    eax = 0; /* xor self */
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_002C6859:
    edx = MEM32(esp + 0x20);
    MEM32(edx) = eax;

}

/**
 * sub_002C685F
 * Original: 0x002C685F - 0x002C6991 (306 bytes, 92 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_002C685F(void)
{
    int _flags = 0; /* fallback flag var */

loc_002C685F:
    ecx = ebx;
    edx = esp + 0x24;
    PUSH32(esp, 0); fn_000280C0_0ZeroMaterialDesc_QAE_VCRC_TAttribData_KQBQAVZeroSurface_H_Z(); /* call 0x000280C0 */

loc_002C686A:
    edx = MEM32(edi);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    ecx = edi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x40), _icall_esp); /* indirect call */
    }

loc_002C6872:
    PUSH32(esp, ebx);
    PUSH32(esp, ebx);
    PUSH32(esp, ebx);
    PUSH32(esp, 0x5CE748);
    edx = 0x5CE6A4;
    SET_LO8(ecx, 0xF0);
    MEM32(esi + 0x14) = eax;
    PUSH32(esp, 0); fn_00125AD0_ZeroStateGroup_Create(); /* call 0x00125AD0 */

loc_002C6889:
    ecx = MEM32(esi + 0x14);
    esp = esp + 0x10;
    (void)0; /* cmp ecx, ebx - flags set for next jcc */
    MEM32(esi + 0x20) = eax;
    if (CMP_EQ(ecx, ebx)) goto loc_002C68CD; /* je: equal / zero */

loc_002C6896:
    edx = MEM32(esi + 0x18);
    if (CMP_EQ(edx, ebx)) goto loc_002C68CD; /* je: equal / zero */

loc_002C689D:
    if (CMP_EQ(eax, ebx)) goto loc_002C68CD; /* je: equal / zero */

loc_002C68A1:
    eax = ZX8(MEM8(0x5CD920));
    MEM32(ecx + eax * 4 + 0xA8) = edx;
    eax = MEM32(esi + 0x20);
    esi = MEM32(esi + 0x14);
    MEM32(esi + 0x10) = eax;
    MEM32(esi + 0x14) = eax;
    MEM32(esi + 0x18) = eax;
    MEM32(esi + 0x1C) = eax;
    MEM32(esi + 0x20) = eax;
    MEM32(esi + 0x24) = eax;
    MEM32(esi + 0x28) = eax;
    MEM32(esi + 0x2C) = eax;

loc_002C68CD:
    if (CMP_NE(MEM32(0x5FA324), ebx)) goto loc_002C6987; /* jne: not equal / not zero */

loc_002C68D9:
    edx = MEM32(0x6135C8);
    ecx = esp + 0xC;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ecx);
    PUSH32(esp, 0x2C);
    ecx = 0x6135C8;
    MEM32(esp + 0x14) = ebx;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx), _icall_esp); /* indirect call */
    }

loc_002C68F1:
    esi = eax;
    eax = MEM32(esp + 0xC);
    MEM32(esi + 4) = eax;
    MEM32(esi + 0xC) = ebx;
    MEM32(esi + 8) = 1;
    MEM32(esi) = 0x53C2FC;
    MEM32(esi + 0x10) = ebx;
    MEM32(esi + 0x14) = ebx;
    MEM32(esi + 0x18) = ebx;
    MEM32(esi + 0x1C) = ebx;
    MEM32(esi + 0x20) = 0x50000;
    MEM32(esi + 0x28) = ebx;
    MEM8(esi + 0x24) = LO8(ebx);
    ecx = MEM32(esi + 0x18);
    ecx = ecx & 0xFFFE0004u;
    ecx = ecx | 4;
    eax = esp + 0x44;
    MEM32(0x5FA324) = esi;
    MEM32(esi + 0x14) = 6;
    MEM32(esi + 0x18) = ecx;
    MEM32(esi + 0x10) = 0x1000111;
    MEM32(esi + 0x20) = 0x50001;
    PUSH32(esp, 0); fn_00025E70_0ZeroVertexRecord_QAE_XZ(); /* call 0x00025E70 */

loc_002C6956:
    if (CMP_NE(MEM32(esi + 0x28), ebx)) goto loc_002C6969; /* jne: not equal / not zero */

loc_002C695B:
    ecx = MEM32(0x5FA8E8);
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x3C), _icall_esp); /* indirect call */
    }

loc_002C6966:
    MEM32(esi + 0x28) = eax;

loc_002C6969:
    ecx = MEM32(esi + 0x28);
    eax = MEM32(ecx);
    edx = esp + 0x44;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, edx);
    PUSH32(esp, 1);
    PUSH32(esp, esi);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 4), _icall_esp); /* indirect call */
    }

loc_002C6979:
    eax = MEM32(0x5FA324);
    ecx = MEM32(eax + 0x28);
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 8), _icall_esp); /* indirect call */
    }

loc_002C6987:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp = esp + 0x110;
    esp += 4; return; /* ret */

}

/**
 * fn_002C69A0_HUDIconManager_SubmitIconLabel
 * Symbol: ?SubmitIconLabel@HUDIconManager@@IAEXPBVHUDIcon@@@Z
 * Original: 0x002C69A0 - 0x002C6B2C (396 bytes, 111 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002C69A0_HUDIconManager_SubmitIconLabel(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C69A0:
    esp = esp - 0x14;
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    PUSH32(esp, edi);
    edi = MEM32(0x5FA8E8);
    PUSH32(esp, ecx);
    ecx = MEM32(esi + 0x50);
    eax = esp;
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_00133270_CUIFont_GetFont(); /* call 0x00133270 */

loc_002C69B9:
    ebx = eax;
    eax = MEM32(esi + 0x4C);
    esp = esp + 4;
    (void)0; /* test ebx, ebx - flags set for next jcc */
    MEM32(esp + 0x14) = eax;
    if (TEST_Z(ebx, ebx)) goto loc_002C6B25; /* je: equal / zero */

loc_002C69CD:
    if (TEST_Z(eax, eax)) goto loc_002C6B25; /* je: equal / zero */

loc_002C69D5:
    if (TEST_Z(edi, edi)) goto loc_002C6B25; /* je: equal / zero */

loc_002C69DD:
    ecx = MEM32(edi + 0xD0);
    if (TEST_Z(ecx, ecx)) goto loc_002C6B25; /* je: equal / zero */

loc_002C69EB:
    edx = MEM32(esi + 0xC);
    ecx = MEM32(esi + 0x10);
    edi = MEM32(esi + 0x40);
    MEM32(esp + 0x18) = edx;
    MEM32(esp + 0x1C) = ecx;
    edx = esp + 0x10;
    PUSH32(esp, edx);
    edi = edi >> 3;
    ecx = esp + 0x10;
    PUSH32(esp, ecx);
    edi = ~edi;
    PUSH32(esp, eax);
    edi = edi & 0x200;
    PUSH32(esp, ebx);
    eax = eax | 0xFFFFFFFFu;
    ecx = edi;
    MEM32(esp + 0x1C) = 0x3E8;
    PUSH32(esp, 0); fn_00133B10_CUIFont_CalcArea(); /* call 0x00133B10 */

loc_002C6A25:
    eax = MEM32(esi + 0x40);
    (void)0; /* test LO8(eax), 2 - flags set for next jcc */
    xmm1 = MEMF(0x561404); /* movss */
    if (TEST_Z(LO8(eax), 2)) goto loc_002C6A40; /* je: equal / zero */

loc_002C6A34:
    xmm2 = (float)(int32_t)MEM32(esp + 0xC); /* cvtsi2ss */
    xmm2 = xmm2 * xmm1; /* mulss */
    goto loc_002C6A4A;

loc_002C6A40:
    if (TEST_Z(LO8(eax), 4)) goto loc_002C6A5A; /* je: equal / zero */

loc_002C6A44:
    xmm2 = (float)(int32_t)MEM32(esp + 0xC); /* cvtsi2ss */

loc_002C6A4A:
    xmm0 = MEMF(esp + 0x18); /* movss */
    xmm0 = xmm0 - xmm2; /* subss */
    MEMF(esp + 0x18) = xmm0; /* movss */

loc_002C6A5A:
    if (TEST_Z(LO8(eax), 0x20)) goto loc_002C6A74; /* je: equal / zero */

loc_002C6A5E:
    xmm2 = (float)(int32_t)MEM32(esp + 0x10); /* cvtsi2ss */
    xmm0 = MEMF(esp + 0x1C); /* movss */
    xmm2 = xmm2 * xmm1; /* mulss */
    xmm0 = xmm0 - xmm2; /* subss */
    goto loc_002C6A88;

loc_002C6A74:
    if (TEST_Z(LO8(eax), 0x40)) goto loc_002C6A8E; /* je: equal / zero */

loc_002C6A78:
    xmm1 = (float)(int32_t)MEM32(esp + 0x10); /* cvtsi2ss */
    xmm0 = MEMF(esp + 0x1C); /* movss */
    xmm0 = xmm0 - xmm1; /* subss */

loc_002C6A88:
    MEMF(esp + 0x1C) = xmm0; /* movss */

loc_002C6A8E:
    edx = ZX8(MEM8(esi + 0x44));
    ebp = esi + 0x44;
    MEM32(esp + 0x10) = edx;
    fp_push((double)SMEM32(esp + 0x10)); /* fild */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    PUSH32(esp, 0); fn_0009D720_ftol2(); /* call 0x0009D720 */

loc_002C6AA8:
    MEM8(esp + 0xC) = LO8(eax);
    eax = ZX8(MEM8(esi + 0x45));
    MEM32(esp + 0x10) = eax;
    fp_push((double)SMEM32(esp + 0x10)); /* fild */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    PUSH32(esp, 0); fn_0009D720_ftol2(); /* call 0x0009D720 */

loc_002C6AC3:
    ecx = ZX8(MEM8(esi + 0x46));
    MEM32(esp + 0x10) = ecx;
    MEM8(esp + 0xD) = LO8(eax);
    fp_push((double)SMEM32(esp + 0x10)); /* fild */
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    PUSH32(esp, 0); fn_0009D720_ftol2(); /* call 0x0009D720 */

loc_002C6ADE:
    SET_LO8(edx, MEM8(esi + 0x47));
    ecx = (int32_t)MEMF(esp + 0x1C); /* cvttss2si */
    PUSH32(esp, 0xFFFFFFFFu);
    MEM8(esp + 0x12) = LO8(eax);
    eax = esp + 0x10;
    PUSH32(esp, eax);
    edi = edi | 2;
    PUSH32(esp, edi);
    PUSH32(esp, ebp);
    PUSH32(esp, 0);
    esp = esp - 8;
    xmm0 = (float)(int32_t)ecx; /* cvtsi2ss */
    MEMF(esp + 4) = xmm0; /* movss */
    MEM8(esp + 0x2B) = LO8(edx);
    edx = (int32_t)MEMF(esp + 0x34); /* cvttss2si */
    xmm0 = (float)(int32_t)edx; /* cvtsi2ss */
    MEMF(esp) = xmm0; /* movss */
    PUSH32(esp, ebx);
    ebx = MEM32(esp + 0x34);
    eax = 0; /* xor self */
    PUSH32(esp, 0); fn_001363E0_CUIFont_DrawEx(); /* call 0x001363E0 */

loc_002C6B25:
    POP32(esp, edi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp = esp + 0x14;
    esp += 4; return; /* ret */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_002C6B30_HUDIconManager_Submit
 * Symbol: ?Submit@HUDIconManager@@QAEXXZ
 * Original: 0x002C6B30 - 0x002C6C89 (345 bytes, 119 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002C6B30_HUDIconManager_Submit(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_002C6B30:
    PUSH32(esp, ecx);
    PUSH32(esp, ebx);
    ebx = MEM32(esp + 0xC);
    SET_LO8(eax, MEM8(ebx + 0xC));
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_002C6C84; /* je: equal / zero */

loc_002C6B41:
    eax = MEM32(ebx + 0x10);
    if (TEST_Z(eax, eax)) goto loc_002C6C84; /* je: equal / zero */

loc_002C6B4C:
    eax = MEM32(ebx + 0x18);
    if (TEST_Z(eax, eax)) goto loc_002C6C84; /* je: equal / zero */

loc_002C6B57:
    eax = MEM32(ebx + 0x1C);
    if (TEST_Z(eax, eax)) goto loc_002C6C84; /* je: equal / zero */

loc_002C6B62:
    eax = MEM32(ebx + 0x14);
    if (TEST_Z(eax, eax)) goto loc_002C6C84; /* je: equal / zero */

loc_002C6B6D:
    eax = MEM32(ebx + 0x20);
    if (TEST_Z(eax, eax)) goto loc_002C6C84; /* je: equal / zero */

loc_002C6B78:
    PUSH32(esp, ebp);
    SET_LO8(eax, 0); /* xor self */
    PUSH32(esp, esi);
    MEM8(esp + 0xE) = LO8(eax);
    PUSH32(esp, edi);

loc_002C6B81:
    edi = MEM32(ebx + 8);
    (void)0; /* cmp edi, ebx - flags set for next jcc */
    MEM8(esp + 0x13) = LO8(eax);
    if (CMP_EQ(edi, ebx)) goto loc_002C6C81; /* je: equal / zero */

loc_002C6B90:
    ebp = ZX8(LO8(eax));

loc_002C6B93:
    esi = MEM32(edi);
    if (TEST_Z(esi, esi)) goto loc_002C6C3A; /* je: equal / zero */

loc_002C6B9D:
    edx = MEM32(esi + 0x48);
    ecx = edx;
    ecx = ecx >> 0xB;
    eax = ecx;
    eax = eax & 0xFF;
    if (CMP_NE(eax, ebp)) goto loc_002C6C1F; /* jne: not equal / not zero */

loc_002C6BB0:
    eax = MEM32(esi + 0x54);
    if (TEST_Z(eax, eax)) goto loc_002C6BFB; /* je: equal / zero */

loc_002C6BB7:
    if (TEST_Z(LO8(edx), 2)) goto loc_002C6BFB; /* je: equal / zero */

loc_002C6BBC:
    if (TEST_NZ(LO8(edx), 4)) goto loc_002C6BFB; /* jne: not equal / not zero */

loc_002C6BC1:
    SET_LO8(eax, MEM8(esi + 0x47));
    if (CMP_BE(LO8(eax) & LO8(eax), 0)) goto loc_002C6BFB; /* jbe: below or equal (unsigned <=) */

loc_002C6BC8:
    xmm1 = MEMF(esi + 0x14); /* movss */
    xmm0 = 0.0f; /* xorps self = zero */
    /* comiss xmm1, xmm0 - sets EFLAGS */
    if ((xmm1 <= xmm0)) goto loc_002C6BFB; /* jbe: below or equal (unsigned <=) */

loc_002C6BD5:
    xmm1 = MEMF(esi + 0x18); /* movss */
    /* comiss xmm1, xmm0 - sets EFLAGS */
    if ((xmm1 <= xmm0)) goto loc_002C6BFB; /* jbe: below or equal (unsigned <=) */

loc_002C6BDF:
    xmm1 = MEMF(esi + 0x3C); /* movss */
    /* ucomiss xmm1, xmm0 - sets EFLAGS */
    /* lahf - load AH from flags (used in FPU compare idiom) */
    (void)0; /* test HI8(eax), 0x44 - flags set for next jcc */
    eax = ebx;
    if (1 /* jp after test - parity */) goto loc_002C6BF6; /* jp: parity */

loc_002C6BEF:
    PUSH32(esp, 0); fn_002C57F0_HUDIconManager_SubmitIcon(); /* call 0x002C57F0 */

loc_002C6BF4:
    goto loc_002C6BFB;

loc_002C6BF6:
    PUSH32(esp, 0); fn_002C60A0_HUDIconManager_SubmitIconOriented(); /* call 0x002C60A0 */

loc_002C6BFB:
    eax = MEM32(esi + 0x48);
    if (TEST_Z(LO8(eax), 8)) goto loc_002C6C3A; /* je: equal / zero */

loc_002C6C02:
    if (TEST_Z(LO8(eax), 2)) goto loc_002C6C3A; /* je: equal / zero */

loc_002C6C06:
    if (TEST_NZ(LO8(eax), 4)) goto loc_002C6C3A; /* jne: not equal / not zero */

loc_002C6C0A:
    eax = MEM32(esi + 0x50);
    if (TEST_Z(eax, eax)) goto loc_002C6C3A; /* je: equal / zero */

loc_002C6C11:
    eax = MEM32(esi + 0x4C);
    if (TEST_Z(eax, eax)) goto loc_002C6C3A; /* je: equal / zero */

loc_002C6C18:
    PUSH32(esp, 0); fn_002C69A0_HUDIconManager_SubmitIconLabel(); /* call 0x002C69A0 */

loc_002C6C1D:
    goto loc_002C6C3A;

loc_002C6C1F:
    if (CMP_BE(eax & eax, 0)) goto loc_002C6C3A; /* jbe: below or equal (unsigned <=) */

loc_002C6C21:
    SET_LO8(edx, MEM8(esp + 0x12));
    if (CMP_BE(LO8(edx), MEM8(esp + 0x13))) goto loc_002C6C32; /* jbe: below or equal (unsigned <=) */

loc_002C6C2B:
    edx = ZX8(LO8(edx));
    if (CMP_AE(eax, edx)) goto loc_002C6C36; /* jae: above or equal (unsigned >=) */

loc_002C6C32:
    MEM8(esp + 0x12) = LO8(ecx);

loc_002C6C36:
    ebx = MEM32(esp + 0x18);

loc_002C6C3A:
    eax = MEM32(esi + 0x48);
    edi = MEM32(edi + 8);
    ecx = eax;
    ecx = ecx >> 0xB;
    ecx = ecx & 0xFF;
    if (CMP_NE(ecx, ebp)) goto loc_002C6C6B; /* jne: not equal / not zero */

loc_002C6C4F:
    if (TEST_NZ(LO8(eax), 0x10)) goto loc_002C6C6B; /* jne: not equal / not zero */

loc_002C6C53:
    edx = MEM32(esi + 4);
    eax = MEM32(esi + 8);
    MEM32(edx + 8) = eax;
    ecx = MEM32(esi + 8);
    edx = MEM32(esi + 4);
    MEM32(ecx + 4) = edx;
    MEM32(esi + 8) = esi;
    MEM32(esi + 4) = esi;

loc_002C6C6B:
    if (CMP_NE(edi, ebx)) goto loc_002C6B93; /* jne: not equal / not zero */

loc_002C6C73:
    SET_LO8(eax, MEM8(esp + 0x12));
    if (CMP_A(LO8(eax), MEM8(esp + 0x13))) goto loc_002C6B81; /* ja: above (unsigned >) */

loc_002C6C81:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);

loc_002C6C84:
    POP32(esp, ebx);
    POP32(esp, ecx);
    esp += 8; return; /* ret 4 */

}
