/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/script/behaviors/civilianbehaviors/ccivconversation.c
 * Functions: 23
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_00043DF0_GCCivConversation_UAEPAXI_Z
 * Symbol: ??_GCCivConversation@@UAEPAXI@Z
 * Original: 0x00043DF0 - 0x00043E28 (56 bytes, 24 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00043DF0_GCCivConversation_UAEPAXI_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_00043DF0:
    PUSH32(esp, esi);
    esi = ecx;
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_00043E30_1CCivConversation_UAE_XZ(); /* call 0x00043E30 */

loc_00043DF9:
    if (TEST_Z(MEM8(esp + 8), 1)) goto loc_00043E22; /* je: equal / zero */

loc_00043E00:
    if (TEST_Z(esi, esi)) goto loc_00043E19; /* je: equal / zero */

loc_00043E04:
    eax = MEM32(esi + 4);
    if (TEST_Z(eax, eax)) goto loc_00043E19; /* je: equal / zero */

loc_00043E0B:
    ecx = eax;
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, esi);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 4), _icall_esp); /* indirect call */
    }

loc_00043E13:
    eax = esi;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

loc_00043E19:
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_001293F0_3_YAXPAX_Z(); /* call 0x001293F0 */

loc_00043E1F:
    esp = esp + 4;

loc_00043E22:
    eax = esi;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_00043E30_1CCivConversation_UAE_XZ
 * Symbol: ??1CCivConversation@@UAE@XZ
 * Original: 0x00043E30 - 0x00043E9F (111 bytes, 36 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00043E30_1CCivConversation_UAE_XZ(void)
{
    int _flags = 0; /* fallback flag var */

loc_00043E30:
    eax = MEM32(0);
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x40D76A);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x18);
    PUSH32(esp, edi);
    PUSH32(esp, 0);
    MEM32(esp + 0x18) = 0;
    PUSH32(esp, 0); fn_002A3EB0_CCinematicManager_Get(); /* call 0x002A3EB0 */

loc_00043E5B:
    ebx = MEM32(esi + 0x7C);
    edi = eax;
    PUSH32(esp, 0); fn_002A1BC0_CCinematicManager_FindPlayingOrQueuedCinematic(); /* call 0x002A1BC0 */

loc_00043E65:
    if (TEST_Z(eax, eax)) goto loc_00043E7D; /* je: equal / zero */

loc_00043E69:
    edx = MEM32(eax + 0x24);
    edx--;
    ecx = edx;
    (void)0; /* test ecx, ecx - flags set for next jcc */
    MEM32(eax + 0x24) = edx;
    if (CMP_G(ecx & ecx, 0)) goto loc_00043E7D; /* jg: greater (signed >) */

loc_00043E76:
    edx = MEM32(eax);
    ecx = eax;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xC), _icall_esp); /* indirect call */
    }

loc_00043E7D:
    PUSH32(esp, esi);
    MEM32(esp + 0x18) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_001FEBB0_1CCivBehavior_UAE_XZ(); /* call 0x001FEBB0 */

loc_00043E8B:
    ecx = MEM32(esp + 0xC);
    POP32(esp, edi);
    POP32(esp, esi);
    MEM32(0) = ecx;
    POP32(esp, ebx);
    esp = esp + 0xC;
    esp += 8; return; /* ret 4 */

}

/**
 * fn_00043EA0_VCCivConversation_CBehaviorFactoryT_CreateObject
 * Symbol: ?CreateObject@?$CBehaviorFactoryT@VCCivConversation@@@@UAEPAVCScript@@VCRC@@_N@Z
 * Original: 0x00043EA0 - 0x00043F22 (130 bytes, 39 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00043EA0_VCCivConversation_CBehaviorFactoryT_CreateObject(void)
{

loc_00043EA0:
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x40D8B8);
    eax = MEM32(0);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 8;
    edx = MEM32(0x6135C8);
    PUSH32(esp, esi);
    eax = esp + 4;
    PUSH32(esp, eax);
    esi = 0; /* xor self */
    PUSH32(esp, 0x80);
    ecx = 0x6135C8;
    MEM32(esp + 0xC) = esi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx), _icall_esp); /* indirect call */
    }

loc_00043ED6:
    ecx = MEM32(esp + 4);
    MEM32(eax + 4) = ecx;
    MEM32(esp + 8) = eax;
    PUSH32(esp, eax);
    MEM32(esp + 0x18) = esi;
    PUSH32(esp, 0); fn_003F1810_0CCivConversation_QAE_XZ(); /* call 0x003F1810 */

loc_00043EEB:
    edx = MEM32(esp + 0x20);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, edx);
    PUSH32(esp, ecx);
    ecx = MEM32(esp + 0x24);
    esi = eax;
    MEM32(esp + 0x1C) = 0xFFFFFFFFu;
    eax = esp;
    MEM32(eax) = ecx;
    edx = MEM32(esi);
    ecx = esi;
    MEM32(esp + 0x28) = esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x5C), _icall_esp); /* indirect call */
    }

loc_00043F0E:
    ecx = MEM32(esp + 0xC);
    eax = esi;
    MEM32(0) = ecx;
    POP32(esp, esi);
    esp = esp + 0x14;
    esp += 12; return; /* ret 8 */

}

/**
 * fn_00043F30_RegisterScriptAction_VCCivConversation_YA_AVCRC_P8CCivConversation_AE_NXZV0_Z
 * Symbol: ??$RegisterScriptAction@VCCivConversation@@@@YA?AVCRC@@P8CCivConversation@@AE_NXZV0@@Z
 * Original: 0x00043F30 - 0x00043FC4 (148 bytes, 51 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00043F30_RegisterScriptAction_VCCivConversation_YA_AVCRC_P8CCivConversation_AE_NXZV0_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_00043F30:
    PUSH32(esp, ecx);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x14);
    PUSH32(esp, ecx);
    eax = esp;
    MEM32(esp + 8) = esp;
    MEM32(eax) = esi;
    PUSH32(esp, 0); fn_002047A0_CScriptManager_Get(); /* call 0x002047A0 */

loc_00043F44:
    PUSH32(esp, 0); fn_00037210_CScriptManager_GetCallback(); /* call 0x00037210 */

loc_00043F49:
    if (TEST_NZ(eax, eax)) goto loc_00043FBD; /* jne: not equal / not zero */

loc_00043F4D:
    eax = MEM32(0x5F9E40);
    if (TEST_NZ(eax, eax)) goto loc_00043F62; /* jne: not equal / not zero */

loc_00043F56:
    PUSH32(esp, 0x10);
    PUSH32(esp, 0); fn_0009E3F2_malloc(); /* call 0x0009E3F2 */

loc_00043F5D:
    esp = esp + 4;
    goto loc_00043F7C;

loc_00043F62:
    eax = MEM32(0x6135C8);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, 0x10);
    ecx = 0x6135C8;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax), _icall_esp); /* indirect call */
    }

loc_00043F72:
    if (TEST_NZ(eax, eax)) goto loc_00043F80; /* jne: not equal / not zero */

loc_00043F76:
    MEM32(eax) = 0x12345678;

loc_00043F7C:
    if (TEST_Z(eax, eax)) goto loc_00043F99; /* je: equal / zero */

loc_00043F80:
    ecx = MEM32(esp + 0xC);
    edx = MEM32(esp + 0x10);
    MEM32(eax + 4) = esi;
    MEM32(eax) = 0x54BF40;
    MEM32(eax + 8) = ecx;
    MEM32(eax + 0xC) = edx;
    goto loc_00043F9B;

loc_00043F99:
    eax = 0; /* xor self */

loc_00043F9B:
    MEM32(esp + 0x14) = esi;
    MEM32(esp + 4) = eax;
    PUSH32(esp, 0); fn_002047A0_CScriptManager_Get(); /* call 0x002047A0 */

loc_00043FA8:
    ecx = esp + 0x14;
    PUSH32(esp, ecx);
    edx = esp + 8;
    PUSH32(esp, edx);
    eax = eax + 0x160;
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_000366F0_PAVCUITexture_ZeroTree_Insert(); /* call 0x000366F0 */

loc_00043FBD:
    MEM32(edi) = esi;
    eax = edi;
    POP32(esp, esi);
    POP32(esp, ecx);
    esp += 4; return; /* ret */

}

/**
 * fn_00044020_9_BIA_AE
 * Symbol: ??_9@$BIA@AE
 * Original: 0x00044020 - 0x00044028 (8 bytes, 2 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00044020_9_BIA_AE(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00044020:
    eax = MEM32(ecx);
    g_seh_ebp = ebp; RECOMP_ITAIL(MEM32(eax + 0x80)); return; /* indirect tail jmp */

}

/**
 * fn_00044030_ECCivConversation_WBA_AEPAXI_Z
 * Symbol: ??_ECCivConversation@@WBA@AEPAXI@Z
 * Original: 0x00044030 - 0x00044038 (8 bytes, 2 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_00044030_ECCivConversation_WBA_AEPAXI_Z(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00044030:
    ecx = ecx - 0x10;
    g_seh_ebp = ebp; fn_00043DF0_GCCivConversation_UAEPAXI_Z(); return; /* tail jmp 0x00043DF0 */

}

/**
 * fn_003F0EB0_CCivConversation_ParseLine
 * Symbol: ?ParseLine@CCivConversation@@UAEXPBDPAD@Z
 * Original: 0x003F0EB0 - 0x003F0EF3 (67 bytes, 25 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F0EB0_CCivConversation_ParseLine(void)
{
    int _flags = 0; /* fallback flag var */

loc_003F0EB0:
    eax = MEM32(esp + 8);
    PUSH32(esp, esi);
    esi = MEM32(esp + 8);
    PUSH32(esp, edi);
    PUSH32(esp, eax);
    PUSH32(esp, esi);
    edi = ecx;
    PUSH32(esp, 0); fn_001FEA70_CCivBehavior_ParseLine(); /* call 0x001FEA70 */

loc_003F0EC3:
    PUSH32(esp, 0x550AC0);
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_003F0ECE:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) goto loc_003F0EEE; /* jne: not equal / not zero */

loc_003F0ED5:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_003F0EDE:
    ecx = eax;
    eax = 0; /* xor self */
    if (TEST_Z(ecx, ecx)) goto loc_003F0EEB; /* je: equal / zero */

loc_003F0EE6:
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_003F0EEB:
    MEM32(edi + 0x78) = eax;

loc_003F0EEE:
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

}

/**
 * fn_003F0F00_CCivConversation_MoveToConversation
 * Symbol: ?MoveToConversation@CCivConversation@@QAEXH@Z
 * Original: 0x003F0F00 - 0x003F10B7 (439 bytes, 125 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F0F00_CCivConversation_MoveToConversation(void)
{
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1, xmm2;
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_003F0F00:
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x4098A1);
    eax = MEM32(0);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x34;
    ecx = MEM32(edi + 0x64);
    xmm0 = MEMF(0x60DE14); /* movss */
    eax = MEM32(esp + 0x44);
    (void)0; /* test eax, eax - flags set for next jcc */
    xmm1 = (float)(int32_t)ecx; /* cvtsi2ss */
    xmm2 = xmm1; /* movaps */
    xmm2 = xmm2 / xmm0; /* divss */
    xmm2 = xmm2 * MEMF(0x5616A8); /* mulss */
    xmm0 = xmm0 / xmm1; /* divss */
    PUSH32(esp, esi);
    MEMF(esp + 4) = xmm2; /* movss */
    MEMF(esp + 8) = xmm0; /* movss */
    if (TEST_S(eax, eax)) goto loc_003F103F; /* jl: less (signed <) */

loc_003F0F53:
    if (CMP_GE(eax, ecx)) goto loc_003F103F; /* jge: greater or equal (signed >=) */

loc_003F0F5B:
    ecx = MEM32(edi + 0x68);
    eax = MEM32(ecx + eax * 4);
    if (CMP_NE(MEM32(eax + 0x154), 2)) goto loc_003F103F; /* jne: not equal / not zero */

loc_003F0F6E:
    esi = MEM32(eax + 0xF4);
    if (TEST_Z(esi, esi)) goto loc_003F103F; /* je: equal / zero */

loc_003F0F7C:
    edx = MEM32(esi);
    ecx = esi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x1C), _icall_esp); /* indirect call */
    }

loc_003F0F83:
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_003F103F; /* je: equal / zero */

loc_003F0F8B:
    eax = MEM32(esi);
    ecx = esi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x98), _icall_esp); /* indirect call */
    }

loc_003F0F95:
    if (TEST_Z(eax, eax)) goto loc_003F0FA8; /* je: equal / zero */

loc_003F0F99:
    edx = MEM32(eax);
    ecx = eax;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x78), _icall_esp); /* indirect call */
    }

loc_003F0FA0:
    if (TEST_NZ(LO8(eax), LO8(eax))) goto loc_003F103F; /* jne: not equal / not zero */

loc_003F0FA8:
    fp_push((double)SMEM32(esp + 0x48)); /* fild */
    ecx = MEM32(edi + 0x74);
    edx = MEM32(ecx);
    eax = MEM32(ecx + 4);
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    ecx = MEM32(ecx + 8);
    xmm0 = 0.0f; /* xorps self = zero */
    xmm1 = MEMF(0x56149C); /* movss */
    /* fld st(0) */
    MEM32(esp + 0x18) = edx;
    /* FPU: fcos  */
    MEM32(esp + 0x20) = ecx;
    PUSH32(esp, 0);
    esp = esp - 0xC;
    edx = esp;
    MEMF(esp + 0x20) = xmm0; /* movss */
    esp = esp - 0xC;
    fp_top() = -fp_top(); /* fchs */
    MEMF(esp + 0x28) = (float)fp_top(); fp_popp(); /* fstp */
    ecx = MEM32(esp + 0x28);
    MEM32(edx) = ecx;
    /* FPU: fsin  */
    ecx = MEM32(esp + 0x2C);
    MEM32(edx + 4) = ecx;
    fp_top() = -fp_top(); /* fchs */
    MEMF(esp + 0x30) = (float)fp_top(); fp_popp(); /* fstp */
    ecx = MEM32(esp + 0x30);
    fp_push(MEMF(esp + 0x28)); /* fld float */
    MEM32(edx + 8) = ecx;
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    edx = esp;
    /* FPU: fsubr dword ptr [esp + 0x34] */
    MEMF(esp + 0x34) = (float)fp_top(); fp_popp(); /* fstp */
    ecx = MEM32(esp + 0x34);
    fp_push(MEMF(esp + 0x30)); /* fld float */
    MEM32(edx) = ecx;
    fp_st1() *= fp_top(); fp_pop(); /* fmul */
    MEM32(edx + 4) = eax;
    ecx = 0; /* xor self */
    /* FPU: fsubr dword ptr [esp + 0x3c] */
    MEMF(esp + 0x3C) = (float)fp_top(); fp_popp(); /* fstp */
    eax = MEM32(esp + 0x3C);
    MEM32(edx + 8) = eax;
    edx = esi;
    PUSH32(esp, 0); fn_0020CA60_CHumanScript_MoveAndPath(); /* call 0x0020CA60 */

loc_003F103F:
    PUSH32(esp, 0);
    PUSH32(esp, 1);
    PUSH32(esp, 0);
    ecx = esp + 0x30;
    PUSH32(esp, 0x3F000000);
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_001EEBE0_CTimerTrigger_CreateTrigger(); /* call 0x001EEBE0 */

loc_003F1054:
    esp = esp + 0x14;
    PUSH32(esp, 0);
    PUSH32(esp, ecx);
    MEM32(esp + 0x48) = 0;
    edx = MEM32(esp + 0x3C);
    eax = esp;
    MEM32(eax) = edx;
    ecx = MEM32(esp + 0x3C);
    (void)0; /* test ecx, ecx - flags set for next jcc */
    MEM32(esp + 0x50) = esp;
    if (TEST_Z(ecx, ecx)) goto loc_003F107B; /* je: equal / zero */

loc_003F1076:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x34), _icall_esp); /* indirect call */
    }

loc_003F107B:
    PUSH32(esp, ecx);
    ecx = MEM32(0x60DE0C);
    eax = esp;
    MEM32(esp + 0x54) = esp;
    PUSH32(esp, edi);
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_00041FC0_CreateScriptAction_VCNPCScript_YAPAVCScriptAction_PAVCNPCScript_VCRC_VCCondition_M_Z(); /* call 0x00041FC0 */

loc_003F1090:
    esp = esp + 0x10;
    edx = esp + 0x24;
    PUSH32(esp, edx);
    MEM32(esp + 0x44) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_0002F150_1CTrigger_UAE_XZ(); /* call 0x0002F150 */

loc_003F10A5:
    ecx = MEM32(esp + 0x38);
    MEM32(0) = ecx;
    POP32(esp, esi);
    esp = esp + 0x40;
    esp += 8; return; /* ret 4 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_003F10C0_CCivConversation_Setup
 * Symbol: ?Setup@CCivConversation@@UAE_NXZ
 * Original: 0x003F10C0 - 0x003F10E4 (36 bytes, 14 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F10C0_CCivConversation_Setup(void)
{
    int _flags = 0; /* fallback flag var */

loc_003F10C0:
    PUSH32(esp, esi);
    esi = ecx;
    PUSH32(esp, 0); fn_001FEC50_CCivBehavior_Setup(); /* call 0x001FEC50 */

loc_003F10C8:
    PUSH32(esp, ecx);
    ecx = MEM32(esi + 0x78);
    eax = esp;
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_002047A0_CScriptManager_Get(); /* call 0x002047A0 */

loc_003F10D5:
    PUSH32(esp, 0); fn_002029C0_CScriptManager_GetLocator(); /* call 0x002029C0 */

loc_003F10DA:
    MEM32(esi + 0x74) = eax;
    (void)0; /* test eax, eax - flags set for next jcc */
    SET_LO8(eax, (TEST_NZ(eax, eax)) ? 1 : 0); /* setne */
    POP32(esp, esi);
    esp += 4; return; /* ret */

}

/**
 * fn_003F10F0_CCivConversation_AttachCivilian
 * Symbol: ?AttachCivilian@CCivConversation@@UAEXPAVCCore@@@Z
 * Original: 0x003F10F0 - 0x003F1118 (40 bytes, 15 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F10F0_CCivConversation_AttachCivilian(void)
{
    int _flags = 0; /* fallback flag var */

loc_003F10F0:
    PUSH32(esp, edi);
    PUSH32(esp, ecx);
    edi = ecx;
    ecx = MEM32(esp + 0xC);
    edx = MEM32(ecx + 0x15C);
    eax = esp;
    ecx = edi;
    MEM32(eax) = edx;
    PUSH32(esp, 0); fn_001FEA10_CCivBehavior_GetIndex(); /* call 0x001FEA10 */

loc_003F1109:
    if (CMP_LE(eax, 0xFFFFFFFFu)) goto loc_003F1114; /* jle: less or equal (signed <=) */

loc_003F110E:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_003F0F00_CCivConversation_MoveToConversation(); /* call 0x003F0F00 */

loc_003F1114:
    POP32(esp, edi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_003F1120_CCivConversation_DetachCivilian
 * Symbol: ?DetachCivilian@CCivConversation@@UAEXPAVCCore@@@Z
 * Original: 0x003F1120 - 0x003F1145 (37 bytes, 15 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F1120_CCivConversation_DetachCivilian(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F1120:
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    edi = ecx;
    eax = edi;
    PUSH32(esp, 0); fn_0004A010_KillAllScriptActions_VCNPCBehavior_YAXPAVCNPCBehavior_Z(); /* call 0x0004A010 */

loc_003F112D:
    ecx = MEM32(esp + 0x14);
    eax = MEM32(ecx + 0x108);
    if (CMP_EQ(eax, 1)) { sub_003F1145(); return; } /* je: equal / zero */

loc_003F113C:
    if (CMP_EQ(eax, 2)) { sub_003F1145(); return; } /* je: equal / zero */

loc_003F1141:
    ebp = 0; /* xor self */
    g_seh_ebp = ebp; sub_003F114B(); return; /* tail jmp 0x003F114B */

}

/**
 * sub_003F1145
 * Original: 0x003F1145 - 0x003F114B (6 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F1145(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F1145:
    ebp = MEM32(ecx + 0xF4);

}

/**
 * sub_003F114B
 * Original: 0x003F114B - 0x003F117E (51 bytes, 18 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F114B(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F114B:
    eax = MEM32(ebp + 0x44);
    esi = MEM32(eax + 0x2F8);
    PUSH32(esp, 0);
    PUSH32(esp, 0); fn_002A3EB0_CCinematicManager_Get(); /* call 0x002A3EB0 */

loc_003F115B:
    ebx = MEM32(edi + 0x7C);
    edi = eax;
    PUSH32(esp, 0); fn_002A1BC0_CCinematicManager_FindPlayingOrQueuedCinematic(); /* call 0x002A1BC0 */

loc_003F1165:
    edi = eax;
    eax = MEM32(esi);
    ecx = esi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x58), _icall_esp); /* indirect call */
    }

loc_003F116E:
    (void)0; /* test eax, eax - flags set for next jcc */
    edi = MEM32(edi + 8);
    if (TEST_Z(eax, eax)) { sub_003F117E(); return; } /* je: equal / zero */

loc_003F1175:
    if (TEST_Z(edi, edi)) { sub_003F1187(); return; } /* je: equal / zero */

loc_003F1179:
    eax = edi + 4;
    g_seh_ebp = ebp; sub_003F1189(); return; /* tail jmp 0x003F1189 */

}

/**
 * sub_003F117E
 * Original: 0x003F117E - 0x003F1187 (9 bytes, 4 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F117E(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F117E:
    if (TEST_Z(edi, edi)) { sub_003F1187(); return; } /* je: equal / zero */

loc_003F1182:
    eax = edi + 0x1C;
    g_seh_ebp = ebp; sub_003F1189(); return; /* tail jmp 0x003F1189 */

}

/**
 * sub_003F1187
 * Original: 0x003F1187 - 0x003F1189 (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F1187(void)
{

loc_003F1187:
    eax = 0; /* xor self */

}

/**
 * sub_003F1189
 * Original: 0x003F1189 - 0x003F11BE (53 bytes, 20 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F1189(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F1189:
    ecx = MEM32(ebp + 0x44);
    esi = MEM32(ecx + 0x2F8);
    PUSH32(esp, 0);
    PUSH32(esp, 0x3F800000);
    PUSH32(esp, 0);
    PUSH32(esp, eax);
    PUSH32(esp, ecx);
    eax = 0; /* xor self */
    ecx = 0x54494C;
    edi = esp;
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_003F11AB:
    MEM32(edi) = eax;
    edx = MEM32(esi);
    ecx = esi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xD4), _icall_esp); /* indirect call */
    }

loc_003F11B7:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_003F11C0_CCivConversation_LoadSave
 * Symbol: ?LoadSave@CCivConversation@@UAEXPAVCBitStream@@W4TLoadSavePass@@@Z
 * Original: 0x003F11C0 - 0x003F1243 (131 bytes, 53 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F11C0_CCivConversation_LoadSave(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F11C0:
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x10);
    PUSH32(esp, edi);
    edi = MEM32(esp + 0x10);
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    ebx = ecx;
    PUSH32(esp, 0); fn_00214290_CBehavior_LoadSave(); /* call 0x00214290 */

loc_003F11D4:
    eax = esi + -2;
    if (CMP_A(eax, 3)) goto loc_003F123D; /* ja: above (unsigned >) */

loc_003F11DC:
    { uint32_t _jt = MEM32(eax * 4 + 0x3F1244); /* switch: 4 entries, 4 targets */
    if (_jt == 0x003F11E3u) goto loc_003F11E3;
    if (_jt == 0x003F11F5u) goto loc_003F11F5;
    if (_jt == 0x003F1209u) goto loc_003F1209;
    if (_jt == 0x003F1227u) goto loc_003F1227;
    g_seh_ebp = ebp; RECOMP_ITAIL(_jt); return; }

loc_003F11E3:
    esi = ebx + 0x6C;
    PUSH32(esp, edi);
    PUSH32(esp, 0); fn_001897C0_CEventAnimSet_Save(); /* call 0x001897C0 */

loc_003F11EC:
    esp = esp + 4;
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp += 12; return; /* ret 8 */

loc_003F11F5:
    ebx = ebx + 0x6C;
    PUSH32(esp, ebx);
    eax = edi;
    PUSH32(esp, 0); fn_00189760_CEventAnimSet_Load(); /* call 0x00189760 */

loc_003F1200:
    esp = esp + 4;
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp += 12; return; /* ret 8 */

loc_003F1209:
    eax = ZX8(MEM8(ebx + 0x60));
    PUSH32(esp, 8);
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_001946E0_CBitStream_WriteBits(); /* call 0x001946E0 */

loc_003F1215:
    ecx = ZX8(MEM8(ebx + 0x61));
    PUSH32(esp, 8);
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_001946E0_CBitStream_WriteBits(); /* call 0x001946E0 */

loc_003F1221:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp += 12; return; /* ret 8 */

loc_003F1227:
    PUSH32(esp, 8);
    esi = edi;
    PUSH32(esp, 0); fn_001947F0_CBitStream_ReadBits(); /* call 0x001947F0 */

loc_003F1230:
    PUSH32(esp, 8);
    MEM8(ebx + 0x60) = LO8(eax);
    PUSH32(esp, 0); fn_001947F0_CBitStream_ReadBits(); /* call 0x001947F0 */

loc_003F123A:
    MEM8(ebx + 0x61) = LO8(eax);

loc_003F123D:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebx);
    esp += 12; return; /* ret 8 */

}

/**
 * fn_003F1260_CCivConversation_OnRespond
 * Symbol: ?OnRespond@CCivConversation@@UAE_NXZ
 * Original: 0x003F1260 - 0x003F1434 (468 bytes, 138 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F1260_CCivConversation_OnRespond(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F1260:
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x40AE1C);
    eax = MEM32(0);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x44;
    xmm0 = 0.0f; /* xorps self = zero */
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    ebp = ecx;
    ecx = MEM32(ebp + 0x64);
    eax = 0; /* xor self */
    (void)0; /* test ecx, ecx - flags set for next jcc */
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    MEMF(esp + 0x14) = xmm0; /* movss */
    MEM32(esp + 0x20) = eax;
    if (CMP_LE(ecx & ecx, 0)) goto loc_003F13C8; /* jle: less or equal (signed <=) */

loc_003F1298:
    goto loc_003F12A0;

    /* nop */

loc_003F12A0:
    ecx = ZX8(MEM8(ebp + 0x71));
    if (CMP_EQ(eax, ecx)) goto loc_003F13B8; /* je: equal / zero */

loc_003F12AC:
    if (TEST_S(eax, eax)) goto loc_003F12D0; /* jl: less (signed <) */

loc_003F12B0:
    if (CMP_GE(eax, MEM32(ebp + 0x64))) goto loc_003F12D0; /* jge: greater or equal (signed >=) */

loc_003F12B5:
    edx = MEM32(ebp + 0x68);
    eax = MEM32(edx + eax * 4);
    if (CMP_NE(MEM32(eax + 0x154), 2)) goto loc_003F12D0; /* jne: not equal / not zero */

loc_003F12C4:
    eax = MEM32(eax + 0xF4);
    MEM32(esp + 0x1C) = eax;
    goto loc_003F12D8;

loc_003F12D0:
    MEM32(esp + 0x1C) = 0;

loc_003F12D8:
    PUSH32(esp, 0); fn_00299110_CRandomManager_Get(); /* call 0x00299110 */

loc_003F12DD:
    ecx = eax;
    edx = MEM32(ecx + 4);
    MEM32(esp + 0x24) = 4;
    MEM32(esp + 0x18) = edx;
    eax = MEM32(esp + 0x18);
    edx = 0x19660D;
    { uint64_t _r = (uint64_t)eax * (uint64_t)edx;
      eax = (uint32_t)_r; edx = (uint32_t)(_r >> 32); }
    eax = eax + 0x3C6EF35F;
    MEM32(esp + 0x18) = eax;
    eax = MEM32(esp + 0x18);
    MEM32(ecx + 4) = eax;
    MEM32(esp + 0x18) = eax;
    eax = MEM32(esp + 0x18);
    { uint64_t _r = (uint64_t)eax * (uint64_t)MEM32(esp + 0x24);
      eax = (uint32_t)_r; edx = (uint32_t)(_r >> 32); }
    MEM32(esp + 0x28) = edx;
    eax = MEM32(esp + 0x1C);
    eax = MEM32(eax + 0x44);
    esi = MEM32(eax + 0x2F8);
    PUSH32(esp, 0);
    PUSH32(esp, 0); fn_002A3EB0_CCinematicManager_Get(); /* call 0x002A3EB0 */

loc_003F132D:
    ebx = MEM32(ebp + 0x7C);
    edi = eax;
    PUSH32(esp, 0); fn_002A1BC0_CCinematicManager_FindPlayingOrQueuedCinematic(); /* call 0x002A1BC0 */

loc_003F1337:
    edx = MEM32(esi);
    ecx = esi;
    edi = eax;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x58), _icall_esp); /* indirect call */
    }

loc_003F1340:
    (void)0; /* test eax, eax - flags set for next jcc */
    edi = MEM32(edi + 8);
    if (TEST_Z(eax, eax)) goto loc_003F1350; /* je: equal / zero */

loc_003F1347:
    if (TEST_Z(edi, edi)) goto loc_003F1359; /* je: equal / zero */

loc_003F134B:
    ecx = edi + 4;
    goto loc_003F135B;

loc_003F1350:
    if (TEST_Z(edi, edi)) goto loc_003F1359; /* je: equal / zero */

loc_003F1354:
    ecx = edi + 0x1C;
    goto loc_003F135B;

loc_003F1359:
    ecx = 0; /* xor self */

loc_003F135B:
    eax = MEM32(esp + 0x1C);
    eax = MEM32(eax + 0x44);
    edi = MEM32(eax + 0x2F8);
    eax = MEM32(esp + 0x28);
    PUSH32(esp, 0);
    PUSH32(esp, 0x3F800000);
    edx = esp + 0x18;
    PUSH32(esp, edx);
    PUSH32(esp, ecx);
    ecx = MEM32(eax * 4 + 0x57FE60);
    (void)0; /* test ecx, ecx - flags set for next jcc */
    PUSH32(esp, ecx);
    MEM32(esp + 0x38) = esp;
    esi = esp;
    if (TEST_NZ(ecx, ecx)) goto loc_003F138F; /* jne: not equal / not zero */

loc_003F138B:
    MEM32(esi) = ecx;
    goto loc_003F1398;

loc_003F138F:
    eax = 0; /* xor self */
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_003F1396:
    MEM32(esi) = eax;

loc_003F1398:
    edx = MEM32(edi);
    ecx = edi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xD4), _icall_esp); /* indirect call */
    }

loc_003F13A2:
    xmm0 = MEMF(esp + 0x10); /* movss */
    xmm0 = xmm0 + MEMF(esp + 0x14); /* addss */
    eax = MEM32(esp + 0x20);
    MEMF(esp + 0x14) = xmm0; /* movss */

loc_003F13B8:
    ecx = MEM32(ebp + 0x64);
    eax++;
    (void)0; /* cmp eax, ecx - flags set for next jcc */
    MEM32(esp + 0x20) = eax;
    if (CMP_L(eax, ecx)) goto loc_003F12A0; /* jl: less (signed <) */

loc_003F13C8:
    eax = MEM32(ebp + 0x64);
    ecx = eax + -1;
    xmm1 = (float)(int32_t)ecx; /* cvtsi2ss */
    xmm0 = xmm0 / xmm1; /* divss */
    MEMF(esp + 0x14) = xmm0; /* movss */
    MEM32(esp + 0x28) = eax;
    PUSH32(esp, 0); fn_00299110_CRandomManager_Get(); /* call 0x00299110 */

loc_003F13E5:
    ecx = eax;
    edx = MEM32(ecx + 4);
    MEM32(esp + 0x1C) = edx;
    eax = MEM32(esp + 0x1C);
    edx = 0x19660D;
    { uint64_t _r = (uint64_t)eax * (uint64_t)edx;
      eax = (uint32_t)_r; edx = (uint32_t)(_r >> 32); }
    eax = eax + 0x3C6EF35F;
    MEM32(esp + 0x1C) = eax;
    eax = MEM32(esp + 0x1C);
    MEM32(ecx + 4) = eax;
    MEM32(esp + 0x24) = eax;
    eax = MEM32(esp + 0x24);
    { uint64_t _r = (uint64_t)eax * (uint64_t)MEM32(esp + 0x28);
      eax = (uint32_t)_r; edx = (uint32_t)(_r >> 32); }
    MEM32(esp + 0x20) = edx;
    SET_LO8(eax, MEM8(esp + 0x20));
    MEM8(ebp + 0x71) = LO8(eax);
    eax = ZX8(LO8(eax));
    if (TEST_S(eax, eax)) { sub_003F1434(); return; } /* jl: less (signed <) */

loc_003F1427:
    if (CMP_GE(eax, MEM32(ebp + 0x64))) { sub_003F1434(); return; } /* jge: greater or equal (signed >=) */

loc_003F142C:
    ecx = MEM32(ebp + 0x68);
    eax = MEM32(ecx + eax * 4);
    g_seh_ebp = ebp; sub_003F1436(); return; /* tail jmp 0x003F1436 */

}

/**
 * sub_003F1434
 * Original: 0x003F1434 - 0x003F1436 (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F1434(void)
{

loc_003F1434:
    eax = 0; /* xor self */

}

/**
 * sub_003F1436
 * Original: 0x003F1436 - 0x003F14FD (199 bytes, 63 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F1436(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F1436:
    PUSH32(esp, 1);
    PUSH32(esp, eax);
    ebx = esp + 0x48;
    PUSH32(esp, 0); fn_001F00D0_CIdleTrigger_CreateTrigger(); /* call 0x001F00D0 */

loc_003F1442:
    edx = MEM32(esp + 0x1C);
    PUSH32(esp, 0);
    PUSH32(esp, 1);
    PUSH32(esp, 0);
    PUSH32(esp, edx);
    eax = esp + 0x44;
    PUSH32(esp, eax);
    MEM32(esp + 0x78) = 0;
    PUSH32(esp, 0); fn_001EEBE0_CTimerTrigger_CreateTrigger(); /* call 0x001EEBE0 */

loc_003F145F:
    esp = esp + 0x1C;
    PUSH32(esp, 0);
    PUSH32(esp, ecx);
    MEM8(esp + 0x64) = 1;
    esi = esp;
    MEM32(esp + 0x30) = esp;
    ecx = ebx;
    PUSH32(esp, ecx);
    edx = esp + 0x38;
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_00201B00_VCTrigger_QAE_AVCCondition_ABV0_Z(); /* call 0x00201B00 */

loc_003F147D:
    PUSH32(esp, ecx);
    ecx = MEM32(0x60DE0C);
    eax = esp;
    MEM32(esp + 0x34) = esp;
    PUSH32(esp, ebp);
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_00041FC0_CreateScriptAction_VCNPCScript_YAPAVCScriptAction_PAVCNPCScript_VCRC_VCCondition_M_Z(); /* call 0x00041FC0 */

loc_003F1492:
    esi = 0x541104;
    esp = esp + 0x10;
    MEM32(esp + 0x2C) = esi;
    MEM8(esp + 0x5C) = 2;
    ecx = MEM32(esp + 0x3C);
    if (TEST_Z(ecx, ecx)) goto loc_003F14B0; /* je: equal / zero */

loc_003F14AB:
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x38), _icall_esp); /* indirect call */
    }

loc_003F14B0:
    edi = 0x53F9E8;
    ecx = esp + 0x2C;
    MEM32(esp + 0x2C) = edi;
    PUSH32(esp, 0); fn_002B6A90_CLoadSave_UnregisterSaveID(); /* call 0x002B6A90 */

loc_003F14C2:
    MEM32(esp + 0x40) = esi;
    MEM32(esp + 0x5C) = 3;
    ecx = MEM32(esp + 0x50);
    if (TEST_Z(ecx, ecx)) goto loc_003F14DB; /* je: equal / zero */

loc_003F14D6:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x38), _icall_esp); /* indirect call */
    }

loc_003F14DB:
    ecx = esp + 0x40;
    MEM32(esp + 0x40) = edi;
    PUSH32(esp, 0); fn_002B6A90_CLoadSave_UnregisterSaveID(); /* call 0x002B6A90 */

loc_003F14E8:
    ecx = MEM32(esp + 0x54);
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    SET_LO8(eax, 0); /* xor self */
    MEM32(0) = ecx;
    POP32(esp, ebx);
    esp = esp + 0x50;
    esp += 4; return; /* ret */

}

/**
 * fn_003F1500_CCivConversation_OnSpeak
 * Symbol: ?OnSpeak@CCivConversation@@UAE_NXZ
 * Original: 0x003F1500 - 0x003F1802 (770 bytes, 231 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F1500_CCivConversation_OnSpeak(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    int _cf = 0; /* carry flag */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F1500:
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x40AE38);
    eax = MEM32(0);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x24;
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    ebx = ecx;
    eax = MEM32(ebx + 0x64);
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    edi = 0; /* xor self */
    (void)0; /* test eax, eax - flags set for next jcc */
    MEM32(esp + 0x14) = ebx;
    MEM32(esp + 0x10) = edi;
    if (CMP_LE(eax & eax, 0)) goto loc_003F1753; /* jle: less or equal (signed <=) */

loc_003F1533:
    if (TEST_S(edi, edi)) goto loc_003F167A; /* jl: less (signed <) */

loc_003F153B:
    if (CMP_GE(edi, eax)) goto loc_003F167A; /* jge: greater or equal (signed >=) */

loc_003F1543:
    eax = MEM32(ebx + 0x68);
    eax = MEM32(eax + edi * 4);
    if (CMP_NE(MEM32(eax + 0x154), 2)) goto loc_003F167A; /* jne: not equal / not zero */

loc_003F1556:
    ebp = MEM32(eax + 0xF4);
    if (TEST_Z(ebp, ebp)) goto loc_003F167A; /* je: equal / zero */

loc_003F1564:
    edx = MEM32(ebp);
    ecx = ebp;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x98), _icall_esp); /* indirect call */
    }

loc_003F156F:
    esi = eax;
    eax = MEM32(ebp);
    ecx = ebp;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x1C), _icall_esp); /* indirect call */
    }

loc_003F1579:
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_003F167A; /* je: equal / zero */

loc_003F1581:
    if (TEST_Z(esi, esi)) goto loc_003F1594; /* je: equal / zero */

loc_003F1585:
    edx = MEM32(esi);
    ecx = esi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x78), _icall_esp); /* indirect call */
    }

loc_003F158C:
    if (TEST_NZ(LO8(eax), LO8(eax))) goto loc_003F167A; /* jne: not equal / not zero */

loc_003F1594:
    ecx = MEM32(ebp + 0x44);
    if (TEST_Z(ecx, ecx)) goto loc_003F167A; /* je: equal / zero */

loc_003F159F:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0xB4), _icall_esp); /* indirect call */
    }

loc_003F15A7:
    SET_LO8(eax, (uint32_t)(-(int32_t)LO8(eax)));
    SET_LO8(eax, _cf ? 0xFFFFFFFF : 0); /* sbb self (CF extend) */
    SET_LO8(eax, LO8(eax) + 1);
    if ((LO8(eax) == 0)) goto loc_003F167A; /* je: equal / zero */

loc_003F15B3:
    edx = MEM32(ebp);
    ecx = ebp;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x90), _icall_esp); /* indirect call */
    }

loc_003F15BE:
    if (TEST_Z(eax, eax)) goto loc_003F15E6; /* je: equal / zero */

loc_003F15C2:
    ecx = MEM32(eax + 0x9C);
    if (TEST_Z(ecx, ecx)) goto loc_003F15DA; /* je: equal / zero */

loc_003F15CC:
    if (CMP_EQ(ecx, 2)) goto loc_003F15DA; /* je: equal / zero */

loc_003F15D1:
    if (CMP_NE(ecx, 4)) goto loc_003F167A; /* jne: not equal / not zero */

loc_003F15DA:
    if (CMP_NE(MEM32(eax + 0xC0), ebx)) goto loc_003F167A; /* jne: not equal / not zero */

loc_003F15E6:
    eax = MEM32(ebp + 0x44);
    ecx = MEM32(eax + 0x2F8);
    ecx = MEM32(ecx + 0x11C);
    if (TEST_Z(ecx, ecx)) goto loc_003F1602; /* je: equal / zero */

loc_003F15F9:
    if (CMP_EQ(MEM32(ecx), 0xA)) goto loc_003F168F; /* je: equal / zero */

loc_003F1602:
    ecx = MEM32(eax + 0x2F8);
    ecx = MEM32(ecx + 0x11C);
    if (TEST_Z(ecx, ecx)) goto loc_003F1617; /* je: equal / zero */

loc_003F1612:
    if (CMP_EQ(MEM32(ecx), 0xB)) goto loc_003F168F; /* je: equal / zero */

loc_003F1617:
    ecx = MEM32(eax + 0x2F8);
    ecx = MEM32(ecx + 0x11C);
    if (CMP_NE(MEM32(ecx), 0)) goto loc_003F167A; /* jne: not equal / not zero */

loc_003F1628:
    edi = MEM32(eax + 0x2F8);
    ebx = ebx + 0x7C;
    PUSH32(esp, ebx);
    PUSH32(esp, 0); fn_00189420_CCEventAnimSetPtr_QBEPAVCEventAnimSet_XZ(); /* call 0x00189420 */

loc_003F1637:
    ecx = edi;
    esi = eax;
    PUSH32(esp, 0); fn_00019B20_CCinematic_GetCustomAnimSet(); /* call 0x00019B20 */

loc_003F1640:
    ebp = MEM32(ebp + 0x44);
    esi = MEM32(ebp + 0x2F8);
    PUSH32(esp, 0);
    PUSH32(esp, 0x3F800000);
    PUSH32(esp, 0);
    PUSH32(esp, eax);
    PUSH32(esp, ecx);
    eax = 0; /* xor self */
    ecx = 0x54A5E8;
    MEM32(esp + 0x30) = esp;
    edi = esp;
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_003F1666:
    MEM32(edi) = eax;
    edx = MEM32(esi);
    ecx = esi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xD4), _icall_esp); /* indirect call */
    }

loc_003F1672:
    ebx = MEM32(esp + 0x14);
    edi = MEM32(esp + 0x10);

loc_003F167A:
    eax = MEM32(ebx + 0x64);
    edi++;
    (void)0; /* cmp edi, eax - flags set for next jcc */
    MEM32(esp + 0x10) = edi;
    if (CMP_L(edi, eax)) goto loc_003F1533; /* jl: less (signed <) */

loc_003F168A:
    goto loc_003F1753;

loc_003F168F:
    eax = MEM32(ebp + 0x44);
    esi = MEM32(eax + 0x2F8);
    PUSH32(esp, 0);
    PUSH32(esp, 0); fn_002A3EB0_CCinematicManager_Get(); /* call 0x002A3EB0 */

loc_003F169F:
    ebx = MEM32(ebx + 0x7C);
    edi = eax;
    PUSH32(esp, 0); fn_002A1BC0_CCinematicManager_FindPlayingOrQueuedCinematic(); /* call 0x002A1BC0 */

loc_003F16A9:
    edi = eax;
    eax = MEM32(esi);
    ecx = esi;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x58), _icall_esp); /* indirect call */
    }

loc_003F16B2:
    (void)0; /* test eax, eax - flags set for next jcc */
    edi = MEM32(edi + 8);
    if (TEST_Z(eax, eax)) goto loc_003F16C2; /* je: equal / zero */

loc_003F16B9:
    if (TEST_Z(edi, edi)) goto loc_003F16CB; /* je: equal / zero */

loc_003F16BD:
    edi = edi + 4;
    goto loc_003F16CD;

loc_003F16C2:
    if (TEST_Z(edi, edi)) goto loc_003F16CB; /* je: equal / zero */

loc_003F16C6:
    edi = edi + 0x1C;
    goto loc_003F16CD;

loc_003F16CB:
    edi = 0; /* xor self */

loc_003F16CD:
    PUSH32(esp, 0); fn_00299110_CRandomManager_Get(); /* call 0x00299110 */

loc_003F16D2:
    ecx = eax;
    edx = MEM32(ecx + 4);
    MEM32(esp + 0x18) = 7;
    MEM32(esp + 0x10) = edx;
    eax = MEM32(esp + 0x10);
    edx = 0x19660D;
    { uint64_t _r = (uint64_t)eax * (uint64_t)edx;
      eax = (uint32_t)_r; edx = (uint32_t)(_r >> 32); }
    eax = eax + 0x3C6EF35F;
    MEM32(esp + 0x10) = eax;
    eax = MEM32(esp + 0x10);
    MEM32(ecx + 4) = eax;
    MEM32(esp + 0x10) = eax;
    eax = MEM32(esp + 0x10);
    { uint64_t _r = (uint64_t)eax * (uint64_t)MEM32(esp + 0x18);
      eax = (uint32_t)_r; edx = (uint32_t)(_r >> 32); }
    MEM32(esp + 0x1C) = edx;
    eax = MEM32(esp + 0x1C);
    ecx = MEM32(eax * 4 + 0x57FE44);
    (void)0; /* test ecx, ecx - flags set for next jcc */
    ebp = MEM32(ebp + 0x44);
    ebp = MEM32(ebp + 0x2F8);
    PUSH32(esp, 0);
    PUSH32(esp, 0x3F800000);
    PUSH32(esp, 0);
    PUSH32(esp, edi);
    PUSH32(esp, ecx);
    MEM32(esp + 0x30) = esp;
    esi = esp;
    if (TEST_NZ(ecx, ecx)) goto loc_003F173B; /* jne: not equal / not zero */

loc_003F1737:
    MEM32(esi) = ecx;
    goto loc_003F1744;

loc_003F173B:
    eax = 0; /* xor self */
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_003F1742:
    MEM32(esi) = eax;

loc_003F1744:
    edx = MEM32(ebp);
    ecx = ebp;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xD4), _icall_esp); /* indirect call */
    }

loc_003F174F:
    ebx = MEM32(esp + 0x14);

loc_003F1753:
    PUSH32(esp, 1);
    PUSH32(esp, ecx);
    ecx = MEM32(0x60DE0C);
    eax = esp;
    MEM32(eax) = ecx;
    eax = ebx;
    MEM32(esp + 0x24) = esp;
    PUSH32(esp, 0); fn_00041140_KillScriptAction_VCNPCBehavior_YA_NPAVCNPCBehavior_VCRC_N_Z(); /* call 0x00041140 */

loc_003F176B:
    PUSH32(esp, 0);
    PUSH32(esp, 1);
    PUSH32(esp, 0);
    edx = esp + 0x34;
    PUSH32(esp, 0x3F4CCCCD);
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_001EEBE0_CTimerTrigger_CreateTrigger(); /* call 0x001EEBE0 */

loc_003F1780:
    esp = esp + 0x1C;
    MEM32(esp + 0x3C) = 0;
    PUSH32(esp, 0);
    PUSH32(esp, ecx);
    ecx = MEM32(esp + 0x38);
    eax = esp;
    MEM32(eax) = ecx;
    ecx = MEM32(esp + 0x38);
    (void)0; /* test ecx, ecx - flags set for next jcc */
    MEM32(esp + 0x24) = esp;
    if (TEST_Z(ecx, ecx)) goto loc_003F17A7; /* je: equal / zero */

loc_003F17A2:
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x34), _icall_esp); /* indirect call */
    }

loc_003F17A7:
    PUSH32(esp, ecx);
    ecx = MEM32(0x60DE0C);
    eax = esp;
    MEM32(esp + 0x28) = esp;
    PUSH32(esp, ebx);
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_00041FC0_CreateScriptAction_VCNPCScript_YAPAVCScriptAction_PAVCNPCScript_VCRC_VCCondition_M_Z(); /* call 0x00041FC0 */

loc_003F17BC:
    esp = esp + 0x10;
    MEM32(esp + 0x20) = 0x541104;
    MEM32(esp + 0x3C) = 1;
    ecx = MEM32(esp + 0x30);
    if (TEST_Z(ecx, ecx)) goto loc_003F17DC; /* je: equal / zero */

loc_003F17D7:
    edx = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x38), _icall_esp); /* indirect call */
    }

loc_003F17DC:
    ecx = esp + 0x20;
    MEM32(esp + 0x20) = 0x53F9E8;
    PUSH32(esp, 0); fn_002B6A90_CLoadSave_UnregisterSaveID(); /* call 0x002B6A90 */

loc_003F17ED:
    ecx = MEM32(esp + 0x34);
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    SET_LO8(eax, 0); /* xor self */
    MEM32(0) = ecx;
    POP32(esp, ebx);
    esp = esp + 0x30;
    esp += 4; return; /* ret */

}

/**
 * fn_003F1810_0CCivConversation_QAE_XZ
 * Symbol: ??0CCivConversation@@QAE@XZ
 * Original: 0x003F1810 - 0x003F18B0 (160 bytes, 55 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F1810_0CCivConversation_QAE_XZ(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F1810:
    eax = MEM32(0);
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x40AE59);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x1C);
    PUSH32(esp, edi);
    eax = esi;
    PUSH32(esp, 0); fn_00214550_0CBehavior_QAE_XZ(); /* call 0x00214550 */

loc_003F1834:
    eax = 0; /* xor self */
    SET_LO8(ecx, 1);
    MEM32(esi + 0x64) = eax;
    MEM32(esi + 0x68) = eax;
    MEM8(esi + 0x6D) = LO8(ecx);
    MEM8(esi + 0x6C) = LO8(ecx);
    MEM8(esi + 0x6E) = LO8(eax);
    MEM32(esp + 0x18) = eax;
    ebp = ebp | 0xFFFFFFFFu;
    MEM32(esi) = 0x553440;
    MEM32(esi + 0x10) = 0x553428;
    MEM32(esi + 0x7C) = ebp;
    MEM8(esp + 0x18) = LO8(ecx);
    MEM32(esi + 0x78) = eax;
    PUSH32(esp, eax);
    MEM32(esi + 0x74) = eax;
    MEM8(esi + 0x70) = LO8(eax);
    MEM8(esi + 0x71) = LO8(eax);
    PUSH32(esp, 0); fn_002A3EB0_CCinematicManager_Get(); /* call 0x002A3EB0 */

loc_003F1874:
    ebx = MEM32(esi + 0x7C);
    edi = eax;
    PUSH32(esp, 0); fn_002A1BC0_CCinematicManager_FindPlayingOrQueuedCinematic(); /* call 0x002A1BC0 */

loc_003F187E:
    if (TEST_Z(eax, eax)) goto loc_003F1896; /* je: equal / zero */

loc_003F1882:
    edx = MEM32(eax + 0x24);
    edx--;
    ecx = edx;
    (void)0; /* test ecx, ecx - flags set for next jcc */
    MEM32(eax + 0x24) = edx;
    if (CMP_G(ecx & ecx, 0)) goto loc_003F1896; /* jg: greater (signed >) */

loc_003F188F:
    edx = MEM32(eax);
    ecx = eax;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xC), _icall_esp); /* indirect call */
    }

loc_003F1896:
    ecx = MEM32(esp + 0x10);
    POP32(esp, edi);
    MEM32(esi + 0x7C) = ebp;
    eax = esi;
    POP32(esp, esi);
    POP32(esp, ebp);
    MEM32(0) = ecx;
    POP32(esp, ebx);
    esp = esp + 0xC;
    esp += 8; return; /* ret 4 */

}

/**
 * fn_003F18B0_CCivConversation_OnActivate
 * Symbol: ?OnActivate@CCivConversation@@UAEX_N@Z
 * Original: 0x003F18B0 - 0x003F1960 (176 bytes, 59 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F18B0_CCivConversation_OnActivate(void)
{
    int _flags = 0; /* fallback flag var */

loc_003F18B0:
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x40B71B);
    eax = MEM32(0);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    PUSH32(esp, ecx);
    SET_LO8(eax, MEM8(esp + 0x14));
    (void)0; /* test LO8(eax), LO8(eax) - flags set for next jcc */
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    esi = ecx;
    PUSH32(esp, edi);
    MEM8(esi + 0x34) = LO8(eax);
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_003F18DB; /* je: equal / zero */

loc_003F18D6:
    eax = MEM32(esi);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x60), _icall_esp); /* indirect call */
    }

loc_003F18DB:
    ebx = esi;
    PUSH32(esp, 0); fn_001FEDD0_CCivBehavior_Start(); /* call 0x001FEDD0 */

loc_003F18E2:
    PUSH32(esp, ecx);
    eax = 0; /* xor self */
    ecx = 0x5534C4;
    MEM32(esp + 0x10) = esp;
    edi = esp;
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_003F18F5:
    ecx = esp + 0x24;
    PUSH32(esp, ecx);
    MEM32(edi) = eax;
    PUSH32(esp, 0); fn_00189820_CEventAnimSet_Create(); /* call 0x00189820 */

loc_003F1901:
    esp = esp + 8;
    PUSH32(esp, eax);
    edx = esi + 0x7C;
    PUSH32(esp, edx);
    MEM32(esp + 0x20) = 0;
    PUSH32(esp, 0); fn_00189460_4CEventAnimSetPtr_QAEAAV0_ABV0_Z(); /* call 0x00189460 */

loc_003F1916:
    PUSH32(esp, 0);
    MEM32(esp + 0x1C) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_002A3EB0_CCinematicManager_Get(); /* call 0x002A3EB0 */

loc_003F1925:
    ebx = MEM32(esp + 0x24);
    edi = eax;
    PUSH32(esp, 0); fn_002A1BC0_CCinematicManager_FindPlayingOrQueuedCinematic(); /* call 0x002A1BC0 */

loc_003F1930:
    if (TEST_Z(eax, eax)) goto loc_003F1948; /* je: equal / zero */

loc_003F1934:
    edx = MEM32(eax + 0x24);
    edx--;
    ecx = edx;
    (void)0; /* test ecx, ecx - flags set for next jcc */
    MEM32(eax + 0x24) = edx;
    if (CMP_G(ecx & ecx, 0)) goto loc_003F1948; /* jg: greater (signed >) */

loc_003F1941:
    edx = MEM32(eax);
    ecx = eax;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xC), _icall_esp); /* indirect call */
    }

loc_003F1948:
    ecx = MEM32(esp + 0x10);
    POP32(esp, edi);
    MEM8(esi + 0x70) = 1;
    POP32(esp, esi);
    MEM32(0) = ecx;
    POP32(esp, ebx);
    esp = esp + 0x10;
    esp += 8; return; /* ret 4 */

}
