/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/main/capplicationcontext.c
 * Functions: 3
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_0002D880_GCApplicationContext_UAEPAXI_Z
 * Symbol: ??_GCApplicationContext@@UAEPAXI@Z
 * Original: 0x0002D880 - 0x0002D89F (31 bytes, 11 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0002D880_GCApplicationContext_UAEPAXI_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_0002D880:
    (void)0; /* test MEM8(esp + 4), 1 - flags set for next jcc */
    PUSH32(esp, esi);
    esi = ecx;
    MEM32(esi) = 0x53FED0;
    if (TEST_Z(MEM8(esp + 4), 1)) goto loc_0002D899; /* je: equal / zero */

loc_0002D890:
    PUSH32(esp, esi);
    PUSH32(esp, 0); fn_001293F0_3_YAXPAX_Z(); /* call 0x001293F0 */

loc_0002D896:
    esp = esp + 4;

loc_0002D899:
    eax = esi;
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_002B1360_1CApplicationContext_UAE_XZ
 * Symbol: ??1CApplicationContext@@UAE@XZ
 * Original: 0x002B1360 - 0x002B1367 (7 bytes, 2 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002B1360_1CApplicationContext_UAE_XZ(void)
{

loc_002B1360:
    MEM32(ecx) = 0x53FED0;
    esp += 4; return; /* ret */

}

/**
 * fn_002B1370_0CApplicationContext_QAE_VCRC_Z
 * Symbol: ??0CApplicationContext@@QAE@VCRC@@@Z
 * Original: 0x002B1370 - 0x002B1391 (33 bytes, 9 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_002B1370_0CApplicationContext_QAE_VCRC_Z(void)
{

loc_002B1370:
    eax = MEM32(esp + 4);
    MEM32(esi) = 0x53FED0;
    MEM32(esi + 4) = eax;
    PUSH32(esp, 0); fn_002B0C40_CApplicationManager_Get(); /* call 0x002B0C40 */

loc_002B1382:
    ecx = MEM32(eax + 0x18);
    MEM32(eax + ecx * 4 + 8) = esi;
    MEM32(eax + 0x18) = MEM32(eax + 0x18) + 1;
    eax = esi;
    esp += 8; return; /* ret 4 */

}
