/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/ai/cellmap/caidynamiccellprototype.c
 * Functions: 3
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_003132E0_CAIDynamicCellPrototype_Setup
 * Symbol: ?Setup@CAIDynamicCellPrototype@@SAXPAV1@H@Z
 * Original: 0x003132E0 - 0x003132EC (12 bytes, 3 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003132E0_CAIDynamicCellPrototype_Setup(void)
{

loc_003132E0:
    MEM32(0x5D5EA0) = eax;
    MEM32(0x5D5EA4) = ecx;
    esp += 4; return; /* ret */

}

/**
 * fn_003132F0_CAIDynamicCellPrototype_GetPrototypeByCRC
 * Symbol: ?GetPrototypeByCRC@CAIDynamicCellPrototype@@SAPAV1@VCRC@@@Z
 * Original: 0x003132F0 - 0x00313321 (49 bytes, 20 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003132F0_CAIDynamicCellPrototype_GetPrototypeByCRC(void)
{
    int _flags = 0; /* fallback flag var */

loc_003132F0:
    edx = MEM32(0x5D5EA4);
    PUSH32(esp, esi);
    eax = 0; /* xor self */
    (void)0; /* test edx, edx - flags set for next jcc */
    PUSH32(esp, edi);
    if (CMP_LE(edx & edx, 0)) goto loc_0031331C; /* jle: less or equal (signed <=) */

loc_003132FE:
    edi = MEM32(0x5D5EA0);
    esi = MEM32(esp + 0xC);
    ecx = edi;
    /* nop */

loc_00313310:
    if (CMP_EQ(MEM32(ecx), esi)) { sub_00313321(); return; } /* je: equal / zero */

loc_00313314:
    eax++;
    ecx = ecx + 0xC;
    if (CMP_L(eax, edx)) goto loc_00313310; /* jl: less (signed <) */

loc_0031331C:
    POP32(esp, edi);
    POP32(esp, esi);
    eax = 0; /* xor self */
    esp += 4; return; /* ret */

}

/**
 * sub_00313321
 * Original: 0x00313321 - 0x0031332A (9 bytes, 5 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_00313321(void)
{

loc_00313321:
    eax = eax + eax * 2;
    eax = edi + eax * 4;
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 4; return; /* ret */

}
