/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/ai/actions/caisoldiersmartfireaction.c
 * Functions: 28
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_0001E210_CAISoldierSmartFireAction_CreateNewInstance
 * Symbol: ?CreateNewInstance@CAISoldierSmartFireAction@@SAPAVCAIAction@@XZ
 * Original: 0x0001E210 - 0x0001E229 (25 bytes, 10 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0001E210_CAISoldierSmartFireAction_CreateNewInstance(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_0001E210:
    PUSH32(esp, ecx);
    eax = MEM32(0x5F9E40);
    PUSH32(esp, ebx);
    ebx = 0; /* xor self */
    if (CMP_NE(eax, ebx)) { sub_0001E229(); return; } /* jne: not equal / not zero */

loc_0001E21D:
    PUSH32(esp, 0x78);
    PUSH32(esp, 0); fn_0009E3F2_malloc(); /* call 0x0009E3F2 */

loc_0001E224:
    esp = esp + 4;
    g_seh_ebp = ebp; sub_0001E276(); return; /* tail jmp 0x0001E276 */

}

/**
 * sub_0001E229
 * Original: 0x0001E229 - 0x0001E276 (77 bytes, 20 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0001E229(void)
{
    int _flags = 0; /* fallback flag var */

loc_0001E229:
    edx = MEM32(0x6135C8);
    eax = esp + 4;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, eax);
    PUSH32(esp, 0x88);
    ecx = 0x6135C8;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx), _icall_esp); /* indirect call */
    }

loc_0001E240:
    if (CMP_NE(eax, ebx)) goto loc_0001E24A; /* jne: not equal / not zero */

loc_0001E244:
    MEM32(eax) = 0x12345678;

loc_0001E24A:
    ecx = MEM32(esp + 4);
    edx = ecx;
    MEM32(eax + 4) = ecx;
    ecx = MEM32(0x5FA8C4);
    edx = edx ^ eax;
    edx = edx ^ 0xC0DECA86u;
    ecx = ecx + 0x10;
    MEM32(eax + 8) = 0x78;
    MEM32(eax) = edx;
    MEM32(0x5FA8C4) = ecx;
    eax = eax + 0x10;

}

/**
 * sub_0001E276
 * Original: 0x0001E276 - 0x0001E2BE (72 bytes, 23 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0001E276(void)
{
    int _flags = 0; /* fallback flag var */

loc_0001E276:
    if (CMP_EQ(eax, ebx)) { sub_0001E2BE(); return; } /* je: equal / zero */

loc_0001E27A:
    MEM32(eax + 0xC) = ebx;
    MEM32(eax + 0x18) = ebx;
    ecx = ecx | 0xFFFFFFFFu;
    MEM32(eax + 0x14) = ecx;
    MEM32(eax + 0x1C) = ebx;
    MEM32(eax + 0x20) = ebx;
    MEM32(eax + 0x24) = ebx;
    MEM32(eax + 0x10) = ebx;
    MEM32(eax + 8) = ebx;
    MEM32(eax + 0xC) = ebx;
    MEM32(eax + 0x28) = 2;
    MEM32(eax) = 0x538500;
    MEM32(eax + 0x30) = ebx;
    MEM32(eax + 0x34) = ebx;
    MEM8(eax + 0x3C) = LO8(ebx);
    MEM32(eax + 0x2C) = 0x5384F8;
    MEM32(eax + 0x70) = ebx;
    MEM32(eax + 0x6C) = ecx;
    POP32(esp, ebx);
    POP32(esp, ecx);
    esp += 4; return; /* ret */

}

/**
 * sub_0001E2BE
 * Original: 0x0001E2BE - 0x0001E2C3 (5 bytes, 4 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0001E2BE(void)
{

loc_0001E2BE:
    eax = 0; /* xor self */
    POP32(esp, ebx);
    POP32(esp, ecx);
    esp += 4; return; /* ret */

}

/**
 * fn_0001E2D0_4CAISoldierSmartFireActionSetup_QAEAAV0_ABV0_Z
 * Symbol: ??4CAISoldierSmartFireActionSetup@@QAEAAV0@ABV0@@Z
 * Original: 0x0001E2D0 - 0x0001E3C4 (244 bytes, 89 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0001E2D0_4CAISoldierSmartFireActionSetup_QAEAAV0_ABV0_Z(void)
{

loc_0001E2D0:
    edx = MEM32(ecx + 4);
    MEM32(eax + 4) = edx;
    edx = MEM32(ecx + 8);
    MEM32(eax + 8) = edx;
    edx = MEM32(ecx + 0xC);
    MEM32(eax + 0xC) = edx;
    SET_LO8(edx, MEM8(ecx + 0x10));
    MEM8(eax + 0x10) = LO8(edx);
    edx = MEM32(ecx + 0x14);
    MEM32(eax + 0x14) = edx;
    PUSH32(esp, esi);
    edx = ecx + 0x18;
    PUSH32(esp, edi);
    edi = MEM32(edx);
    esi = eax + 0x18;
    MEM32(esi) = edi;
    edi = MEM32(edx + 4);
    MEM32(esi + 4) = edi;
    edx = MEM32(edx + 8);
    MEM32(esi + 8) = edx;
    edx = MEM32(ecx + 0x24);
    MEM32(eax + 0x24) = edx;
    edx = MEM32(ecx + 0x28);
    MEM32(eax + 0x28) = edx;
    edx = MEM32(ecx + 0x2C);
    MEM32(eax + 0x2C) = edx;
    edx = MEM32(ecx + 0x30);
    MEM32(eax + 0x30) = edx;
    edx = MEM32(ecx + 0x34);
    MEM32(eax + 0x34) = edx;
    edx = MEM32(ecx + 0x38);
    MEM32(eax + 0x38) = edx;
    esi = MEM32(ecx + 0x3C);
    edx = MEM32(eax + 0x3C);
    edx = edx ^ esi;
    esi = MEM32(eax + 0x3C);
    edx = edx & 1;
    esi = esi ^ edx;
    MEM32(eax + 0x3C) = esi;
    edx = MEM32(ecx + 0x3C);
    edx = edx ^ esi;
    edx = edx & 2;
    edx = edx ^ esi;
    MEM32(eax + 0x3C) = edx;
    esi = MEM32(ecx + 0x3C);
    esi = esi ^ edx;
    esi = esi & 4;
    esi = esi ^ edx;
    MEM32(eax + 0x3C) = esi;
    edx = MEM32(ecx + 0x3C);
    edx = edx ^ esi;
    edx = edx & 8;
    edx = edx ^ esi;
    MEM32(eax + 0x3C) = edx;
    esi = MEM32(ecx + 0x3C);
    esi = esi ^ edx;
    esi = esi & 0x10;
    esi = esi ^ edx;
    MEM32(eax + 0x3C) = esi;
    edx = MEM32(ecx + 0x3C);
    edx = edx ^ esi;
    edx = edx & 0x20;
    edx = edx ^ esi;
    MEM32(eax + 0x3C) = edx;
    esi = MEM32(ecx + 0x3C);
    esi = esi ^ edx;
    esi = esi & 0x40;
    esi = esi ^ edx;
    MEM32(eax + 0x3C) = esi;
    edx = MEM32(ecx + 0x3C);
    edx = edx ^ esi;
    edx = edx & 0x80;
    edx = edx ^ esi;
    MEM32(eax + 0x3C) = edx;
    esi = MEM32(ecx + 0x3C);
    esi = esi ^ edx;
    esi = esi & 0x100;
    esi = esi ^ edx;
    MEM32(eax + 0x3C) = esi;
    edx = MEM32(ecx + 0x3C);
    edx = edx ^ esi;
    edx = edx & 0x200;
    edx = edx ^ esi;
    MEM32(eax + 0x3C) = edx;
    ecx = MEM32(ecx + 0x3C);
    POP32(esp, edi);
    MEM32(eax + 0x3C) = ecx;
    POP32(esp, esi);
    esp += 4; return; /* ret */

}

/**
 * fn_003F5040_CAISoldierSmartFireAction_Init
 * Symbol: ?Init@CAISoldierSmartFireAction@@QAE_NPAVCAISoldierSmartFireActionSetup@@@Z
 * Original: 0x003F5040 - 0x003F50AE (110 bytes, 36 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F5040_CAISoldierSmartFireAction_Init(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F5040:
    eax = MEM32(0);
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x406A50);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    eax = MEM32(ecx + 4);
    MEM32(esi + 8) = eax;
    edx = MEM32(ecx + 8);
    MEM32(esi + 0xC) = edx;
    eax = MEM32(ecx + 0xC);
    edx = 0; /* xor self */
    MEM32(esi + 4) = eax;
    SET_LO8(edx, MEM8(ecx + 0x10));
    eax = MEM32(esi + 0x28);
    eax = eax & 0xFFFFFF85u;
    esp = esp - 0x30;
    PUSH32(esp, edi);
    edx = edx & 1;
    edx = edx << 3;
    edx = edx | eax;
    edx = edx | 1;
    eax = esi + 0x2C;
    MEM32(esi + 0x28) = edx;
    PUSH32(esp, 0); fn_0001E2D0_4CAISoldierSmartFireActionSetup_QAEAAV0_ABV0_Z(); /* call 0x0001E2D0 */

loc_003F508C:
    eax = MEM32(esi + 8);
    edi = 0; /* xor self */
    (void)0; /* cmp eax, edi - flags set for next jcc */
    MEM32(esi + 0x74) = edi;
    if (CMP_EQ(eax, edi)) { sub_003F50AE(); return; } /* je: equal / zero */

loc_003F5098:
    eax = MEM32(eax + 0xF0);
    if (CMP_EQ(eax, edi)) { sub_003F50AE(); return; } /* je: equal / zero */

loc_003F50A2:
    edx = MEM32(eax);
    ecx = eax;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x80), _icall_esp); /* indirect call */
    }

loc_003F50AC:
    g_seh_ebp = ebp; sub_003F50B0(); return; /* tail jmp 0x003F50B0 */

}

/**
 * sub_003F50AE
 * Original: 0x003F50AE - 0x003F50B0 (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F50AE(void)
{

loc_003F50AE:
    eax = 0; /* xor self */

}

/**
 * sub_003F50B0
 * Original: 0x003F50B0 - 0x003F5143 (147 bytes, 39 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F50B0(void)
{
    int _flags = 0; /* fallback flag var */
    float xmm0;

loc_003F50B0:
    MEM32(esi + 0x74) = MEM32(esi + 0x74) & 0xFFFFFFFCu;
    PUSH32(esp, 0); fn_00325E50_CAISoldier_ShouldEngage(); /* call 0x00325E50 */

loc_003F50B9:
    xmm0 = 0.0f; /* xorps self = zero */
    (void)0; /* test LO8(eax), LO8(eax) - flags set for next jcc */
    SET_LO8(eax, MEM8(esp + 0x30));
    MEM32(esp + 0x2C) = edi;
    MEM32(esp + 0x24) = edi;
    MEMF(esp + 0x20) = xmm0; /* movss */
    MEMF(esp + 0x1C) = xmm0; /* movss */
    MEMF(esp + 0x18) = xmm0; /* movss */
    if (TEST_NZ(LO8(eax), LO8(eax))) { sub_003F5143(); return; } /* jne: not equal / not zero */

loc_003F50DE:
    SET_LO8(eax, LO8(eax) & 0xFC);
    MEM8(esp + 0x30) = LO8(eax);
    eax = MEM32(esi + 8);
    PUSH32(esp, ecx);
    MEM32(esp + 0x18) = 0x42941681;
    MEM32(esp + 0x2C) = eax;
    MEM32(esp + 8) = esp;
    PUSH32(esp, 0); fn_00355430_CAIManager_Get(); /* call 0x00355430 */

loc_003F50FD:
    ecx = eax;
    eax = esp;
    PUSH32(esp, 0); fn_00016D20_CAIManager_GetID(); /* call 0x00016D20 */

loc_003F5106:
    PUSH32(esp, ecx);
    MEM32(esp + 0x44) = edi;
    MEM32(esp + 0x10) = esp;
    PUSH32(esp, 0); fn_0030A6A0_CAIVOManager_Get(); /* call 0x0030A6A0 */

loc_003F5114:
    ecx = eax;
    eax = esp;
    PUSH32(esp, 0); fn_00016D10_CAIVOManager_GetID(); /* call 0x00016D10 */

loc_003F511D:
    edx = esp + 0x14;
    MEM32(esp + 0x44) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_00014770_SendMsg_VMVOMacroEvent_YAXAAVMVOMacroEvent_VZeroID_1_Z(); /* call 0x00014770 */

loc_003F512E:
    esp = esp + 8;
    SET_LO8(eax, 0); /* xor self */
    ecx = MEM32(esp + 0x34);
    MEM32(0) = ecx;
    POP32(esp, edi);
    esp = esp + 0x3C;
    esp += 4; return; /* ret */

}

/**
 * sub_003F5143
 * Original: 0x003F5143 - 0x003F51AC (105 bytes, 28 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F5143(void)
{

loc_003F5143:
    ecx = MEM32(esi + 8);
    SET_LO8(eax, LO8(eax) & 0xFC);
    PUSH32(esp, ecx);
    MEM8(esp + 0x34) = LO8(eax);
    MEM32(esp + 0x18) = 0x5D8E2787;
    MEM32(esp + 0x2C) = ecx;
    MEM32(esp + 0xC) = esp;
    PUSH32(esp, 0); fn_00355430_CAIManager_Get(); /* call 0x00355430 */

loc_003F5162:
    ecx = eax;
    eax = esp;
    PUSH32(esp, 0); fn_00016D20_CAIManager_GetID(); /* call 0x00016D20 */

loc_003F516B:
    PUSH32(esp, ecx);
    MEM32(esp + 0x44) = 1;
    MEM32(esp + 0xC) = esp;
    PUSH32(esp, 0); fn_0030A6A0_CAIVOManager_Get(); /* call 0x0030A6A0 */

loc_003F517D:
    ecx = eax;
    eax = esp;
    PUSH32(esp, 0); fn_00016D10_CAIVOManager_GetID(); /* call 0x00016D10 */

loc_003F5186:
    edx = esp + 0x14;
    MEM32(esp + 0x44) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_00014770_SendMsg_VMVOMacroEvent_YAXAAVMVOMacroEvent_VZeroID_1_Z(); /* call 0x00014770 */

loc_003F5197:
    ecx = MEM32(esp + 0x3C);
    esp = esp + 8;
    SET_LO8(eax, 1);
    MEM32(0) = ecx;
    POP32(esp, edi);
    esp = esp + 0x3C;
    esp += 4; return; /* ret */

}

/**
 * fn_003F51B0_CAISoldierSmartFireAction_LoadSave
 * Symbol: ?LoadSave@CAISoldierSmartFireAction@@UAEXPAVCBitStream@@W4TLoadSavePass@@@Z
 * Original: 0x003F51B0 - 0x003F5234 (132 bytes, 58 insns)
 * Category: game_input
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F51B0_CAISoldierSmartFireAction_LoadSave(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F51B0:
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    ebp = MEM32(esp + 0x10);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x10);
    PUSH32(esp, edi);
    PUSH32(esp, ebp);
    PUSH32(esp, esi);
    ebx = ecx;
    PUSH32(esp, 0); fn_003699E0_CAIAction_LoadSave(); /* call 0x003699E0 */

loc_003F51C5:
    eax = MEM32(ebx + 0x2C);
    ecx = ebx + 0x2C;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ebp);
    PUSH32(esp, esi);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax), _icall_esp); /* indirect call */
    }

loc_003F51CF:
    eax = ebp;
    eax = eax - 4;
    if ((eax == 0)) goto loc_003F51EF; /* je: equal / zero */

loc_003F51D6:
    eax--;
    if ((eax != 0)) goto loc_003F5207; /* jne: not equal / not zero */

loc_003F51D9:
    PUSH32(esp, 0x20);
    PUSH32(esp, 0); fn_001947F0_CBitStream_ReadBits(); /* call 0x001947F0 */

loc_003F51E0:
    PUSH32(esp, 0x20);
    MEM32(ebx + 0x6C) = eax;
    PUSH32(esp, 0); fn_001947F0_CBitStream_ReadBits(); /* call 0x001947F0 */

loc_003F51EA:
    MEM32(ebx + 0x70) = eax;
    goto loc_003F5207;

loc_003F51EF:
    ecx = MEM32(ebx + 0x6C);
    PUSH32(esp, 0x20);
    PUSH32(esp, ecx);
    edi = esi;
    PUSH32(esp, 0); fn_001946E0_CBitStream_WriteBits(); /* call 0x001946E0 */

loc_003F51FC:
    edx = MEM32(ebx + 0x70);
    PUSH32(esp, 0x20);
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_001946E0_CBitStream_WriteBits(); /* call 0x001946E0 */

loc_003F5207:
    ebp = ebp - 4;
    if ((ebp == 0)) goto loc_003F5220; /* je: equal / zero */

loc_003F520C:
    ebp--;
    if ((ebp != 0)) goto loc_003F522D; /* jne: not equal / not zero */

loc_003F520F:
    PUSH32(esp, 0x20);
    PUSH32(esp, 0); fn_001947F0_CBitStream_ReadBits(); /* call 0x001947F0 */

loc_003F5216:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    MEM32(ebx + 0x74) = eax;
    POP32(esp, ebx);
    esp += 12; return; /* ret 8 */

loc_003F5220:
    eax = MEM32(ebx + 0x74);
    PUSH32(esp, 0x20);
    PUSH32(esp, eax);
    edi = esi;
    PUSH32(esp, 0); fn_001946E0_CBitStream_WriteBits(); /* call 0x001946E0 */

loc_003F522D:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp += 12; return; /* ret 8 */

}

/**
 * fn_003F5240_CAISoldierSmartFireActionSetup_LoadSave
 * Symbol: ?LoadSave@CAISoldierSmartFireActionSetup@@UAEXPAVCBitStream@@W4TLoadSavePass@@@Z
 * Original: 0x003F5240 - 0x003F53BA (378 bytes, 129 insns)
 * Category: game_input
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F5240_CAISoldierSmartFireActionSetup_LoadSave(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F5240:
    esp = esp - 0xC;
    PUSH32(esp, ebx);
    PUSH32(esp, ebp);
    ebp = MEM32(esp + 0x18);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x20);
    PUSH32(esp, esi);
    PUSH32(esp, ebp);
    ebx = ecx;
    PUSH32(esp, 0); fn_00369BC0_CAIActionSetup_LoadSave(); /* call 0x00369BC0 */

loc_003F5257:
    eax = esi + -2;
    if (CMP_A(eax, 3)) goto loc_003F53B1; /* ja: above (unsigned >) */

loc_003F5263:
    PUSH32(esp, edi);
    { uint32_t _jt = MEM32(eax * 4 + 0x3F53BC); /* switch: 4 entries, 4 targets */
    if (_jt == 0x003F526Bu) goto loc_003F526B;
    if (_jt == 0x003F529Fu) goto loc_003F529F;
    if (_jt == 0x003F52B3u) goto loc_003F52B3;
    if (_jt == 0x003F5323u) goto loc_003F5323;
    g_seh_ebp = ebp; RECOMP_ITAIL(_jt); return; }

loc_003F526B:
    ebx = MEM32(ebx + 0x38);
    if (TEST_Z(ebx, ebx)) goto loc_003F528C; /* je: equal / zero */

loc_003F5272:
    eax = MEM32(ebx + 0x50);
    esi = MEM32(eax + 0xF0);
    eax = ebp;
    PUSH32(esp, 0); fn_002B6990_CLoadSave_SavePtr(); /* call 0x002B6990 */

loc_003F5282:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp = esp + 0xC;
    esp += 12; return; /* ret 8 */

loc_003F528C:
    esi = 0; /* xor self */
    eax = ebp;
    PUSH32(esp, 0); fn_002B6990_CLoadSave_SavePtr(); /* call 0x002B6990 */

loc_003F5295:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp = esp + 0xC;
    esp += 12; return; /* ret 8 */

loc_003F529F:
    eax = ebp;
    PUSH32(esp, 0); fn_002B6B90_CLoadSave_LoadPtr(); /* call 0x002B6B90 */

loc_003F52A6:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    MEM32(ebx + 0x38) = eax;
    POP32(esp, ebx);
    esp = esp + 0xC;
    esp += 12; return; /* ret 8 */

loc_003F52B3:
    esi = ebx + 0x18;
    eax = ebp;
    PUSH32(esp, 0); fn_00195190_CBitStream_WriteVector3(); /* call 0x00195190 */

loc_003F52BD:
    ecx = MEM32(ebx + 0x24);
    PUSH32(esp, 0x20);
    PUSH32(esp, ecx);
    edi = ebp;
    PUSH32(esp, 0); fn_001946E0_CBitStream_WriteBits(); /* call 0x001946E0 */

loc_003F52CA:
    xmm0 = MEMF(ebx + 0x28); /* movss */
    MEMF(esp + 0x24) = xmm0; /* movss */
    edx = MEM32(esp + 0x24);
    PUSH32(esp, 0x20);
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_001946E0_CBitStream_WriteBits(); /* call 0x001946E0 */

loc_003F52E1:
    xmm0 = MEMF(ebx + 0x2C); /* movss */
    MEMF(esp + 0x24) = xmm0; /* movss */
    eax = MEM32(esp + 0x24);
    PUSH32(esp, 0x20);
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_001946E0_CBitStream_WriteBits(); /* call 0x001946E0 */

loc_003F52F8:
    ecx = MEM32(ebx + 0x30);
    PUSH32(esp, 0x20);
    PUSH32(esp, ecx);
    PUSH32(esp, 0); fn_001946E0_CBitStream_WriteBits(); /* call 0x001946E0 */

loc_003F5303:
    edx = MEM32(ebx + 0x34);
    PUSH32(esp, 0x20);
    PUSH32(esp, edx);
    PUSH32(esp, 0); fn_001946E0_CBitStream_WriteBits(); /* call 0x001946E0 */

loc_003F530E:
    eax = MEM32(ebx + 0x3C);
    PUSH32(esp, 0x20);
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_001946E0_CBitStream_WriteBits(); /* call 0x001946E0 */

loc_003F5319:
    POP32(esp, edi);
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp = esp + 0xC;
    esp += 12; return; /* ret 8 */

loc_003F5323:
    edi = esp + 0x10;
    eax = ebp;
    PUSH32(esp, 0); fn_00195280_CBitStream_ReadVector3(); /* call 0x00195280 */

loc_003F532E:
    edx = MEM32(eax);
    ecx = ebx + 0x18;
    MEM32(ecx) = edx;
    edx = MEM32(eax + 4);
    MEM32(ecx + 4) = edx;
    eax = MEM32(eax + 8);
    PUSH32(esp, 0x20);
    esi = ebp;
    MEM32(ecx + 8) = eax;
    PUSH32(esp, 0); fn_001947F0_CBitStream_ReadBits(); /* call 0x001947F0 */

loc_003F534A:
    PUSH32(esp, 0x20);
    MEM32(ebx + 0x24) = eax;
    PUSH32(esp, 0); fn_001947F0_CBitStream_ReadBits(); /* call 0x001947F0 */

loc_003F5354:
    MEM32(esp + 0x24) = eax;
    xmm0 = MEMF(esp + 0x24); /* movss */
    PUSH32(esp, 0x20);
    MEMF(ebx + 0x28) = xmm0; /* movss */
    PUSH32(esp, 0); fn_001947F0_CBitStream_ReadBits(); /* call 0x001947F0 */

loc_003F536A:
    MEM32(esp + 0x24) = eax;
    xmm0 = MEMF(esp + 0x24); /* movss */
    PUSH32(esp, 0x20);
    MEMF(ebx + 0x2C) = xmm0; /* movss */
    PUSH32(esp, 0); fn_001947F0_CBitStream_ReadBits(); /* call 0x001947F0 */

loc_003F5380:
    PUSH32(esp, 0x20);
    MEM32(ebx + 0x30) = eax;
    PUSH32(esp, 0); fn_001947F0_CBitStream_ReadBits(); /* call 0x001947F0 */

loc_003F538A:
    PUSH32(esp, 0x20);
    MEM32(ebx + 0x34) = eax;
    PUSH32(esp, 0); fn_001947F0_CBitStream_ReadBits(); /* call 0x001947F0 */

loc_003F5394:
    ecx = MEM32(ebx + 4);
    esi = MEM32(ebx + 0x38);
    MEM32(ebx + 0x3C) = eax;
    eax = MEM32(ecx + 0xF0);
    eax = eax + 0x8C;
    PUSH32(esp, 0); fn_0030B390_CAIThreatTracker_FindThreatByActor(); /* call 0x0030B390 */

loc_003F53AD:
    MEM32(ebx + 0x38) = eax;
    POP32(esp, edi);

loc_003F53B1:
    POP32(esp, esi);
    POP32(esp, ebp);
    POP32(esp, ebx);
    esp = esp + 0xC;
    esp += 12; return; /* ret 8 */

}

/**
 * fn_003F53D0_CAISoldierSmartFireAction_Process
 * Symbol: ?Process@CAISoldierSmartFireAction@@UAE_NM@Z
 * Original: 0x003F53D0 - 0x003F53E2 (18 bytes, 6 insns)
 * Category: game_input
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F53D0_CAISoldierSmartFireAction_Process(void)
{
    int _flags = 0; /* fallback flag var */

loc_003F53D0:
    eax = MEM32(esp + 4);
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_00369AE0_CAIAction_Process(); /* call 0x00369AE0 */

loc_003F53DA:
    (void)0; /* test LO8(eax), LO8(eax) - flags set for next jcc */
    SET_LO8(eax, (TEST_NZ(LO8(eax), LO8(eax))) ? 1 : 0); /* setne */
    esp += 8; return; /* ret 4 */

}

/**
 * fn_003F53F0_CAISoldierSmartFireAction_Begin
 * Symbol: ?Begin@CAISoldierSmartFireAction@@UAE_NXZ
 * Original: 0x003F53F0 - 0x003F5450 (96 bytes, 34 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_003F53F0_CAISoldierSmartFireAction_Begin(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */

loc_003F53F0:
    PUSH32(esp, ebp);
    ebp = esp;
    esp = esp & 0xFFFFFFF0u;
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0x40B234);
    eax = MEM32(0);
    PUSH32(esp, eax);
    MEM32(0) = esp;
    esp = esp - 0x188;
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    edi = ecx;
    ecx = MEM32(edi + 0x28);
    ecx = ecx | 0x40;
    SET_LO8(eax, LO8(ecx));
    (void)0; /* test LO8(eax), 0x90 - flags set for next jcc */
    MEM32(edi + 0x28) = ecx;
    if (TEST_NZ(LO8(eax), 0x90)) goto loc_003F5431; /* jne: not equal / not zero */

loc_003F5425:
    PUSH32(esp, 0); fn_000113C0_CAIAction_GetActor(); /* call 0x000113C0 */

loc_003F542A:
    edx = MEM32(eax);
    ecx = eax;
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0x4C), _icall_esp); /* indirect call */
    }

loc_003F5431:
    eax = MEM32(edi + 8);
    esi = 0; /* xor self */
    if (CMP_EQ(eax, esi)) { sub_003F5450(); return; } /* je: equal / zero */

loc_003F543A:
    ecx = MEM32(eax + 0xF0);
    if (CMP_EQ(ecx, esi)) { sub_003F5450(); return; } /* je: equal / zero */

loc_003F5444:
    eax = MEM32(ecx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x80), _icall_esp); /* indirect call */
    }

loc_003F544C:
    ebx = eax;
    g_seh_ebp = ebp; sub_003F5452(); return; /* tail jmp 0x003F5452 */

}

/**
 * sub_003F5450
 * Original: 0x003F5450 - 0x003F5452 (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F5450(void)
{

loc_003F5450:
    ebx = 0; /* xor self */

}

/**
 * sub_003F5452
 * Original: 0x003F5452 - 0x003F5664 (530 bytes, 172 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F5452(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0, xmm1;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F5452:
    xmm0 = 0.0f; /* xorps self = zero */
    eax = MEM32(edi + 0x68);
    (void)0; /* test HI8(eax), 2 - flags set for next jcc */
    MEMF(esp + 0x18) = xmm0; /* movss */
    MEMF(esp + 0x1C) = xmm0; /* movss */
    MEMF(esp + 0x20) = xmm0; /* movss */
    if (TEST_Z(HI8(eax), 2)) goto loc_003F55A5; /* je: equal / zero */

loc_003F5473:
    PUSH32(esp, esi);
    PUSH32(esp, esi);
    PUSH32(esp, esi);
    PUSH32(esp, esi);
    xmm1 = MEMF(0x561600); /* movss */
    ecx = edi + 0x44;
    PUSH32(esp, ecx);
    ecx = MEM32(edi + 0x5C);
    PUSH32(esp, 1);
    PUSH32(esp, esi);
    PUSH32(esp, esi);
    edx = 0; /* xor self */
    PUSH32(esp, esi);
    (void)0; /* cmp ecx, 1 - flags set for next jcc */
    PUSH32(esp, esi);
    SET_LO8(edx, (CMP_NE(ecx, 1)) ? 1 : 0); /* setne */
    PUSH32(esp, esi);
    PUSH32(esp, esi);
    eax = esp + 0x60;
    ecx = esp + 0xC0;
    MEM32(esp + 0x60) = esi;
    MEMF(esp + 0x64) = xmm1; /* movss */
    edx--;
    edx = edx & 2;
    PUSH32(esp, edx);
    PUSH32(esp, esi);
    PUSH32(esp, esi);
    PUSH32(esp, esi);
    PUSH32(esp, eax);
    PUSH32(esp, ebx);
    PUSH32(esp, ecx);
    MEMF(esp + 0xCC) = xmm0; /* movss */
    MEMF(esp + 0xD0) = xmm0; /* movss */
    MEMF(esp + 0xD4) = xmm0; /* movss */
    PUSH32(esp, 0); fn_00016AA0_0CAISoldierTakeCoverActionSetup_QAE_PAVCAISoldier_ABVCAITakeCoverSearchShape_NPAVZeroVector3_PAV_ZeroList_VZeroVector3_W4TCoverType_22233223W4TSearchType_2MH_Z(); /* call 0x00016AA0 */

loc_003F54D6:
    edx = esp + 0x90;
    PUSH32(esp, edx);
    eax = esp + 0x14;
    PUSH32(esp, eax);
    PUSH32(esp, 0x5FB008);
    MEM32(esp + 0x1A8) = esi;
    PUSH32(esp, 0); fn_000159E0_AllocAction_VCAISoldierTakeCoverAction_VCAISoldierTakeCoverActionSetup_CAIResourceManager_IAE_AVCAIActionHandle_PAVCAISoldierTakeCoverAction_PAVCAISoldierTakeCoverActio(); /* call 0x000159E0 */

loc_003F54F4:
    edx = esp + 0x10;
    ecx = 0x5FB008;
    PUSH32(esp, 0); fn_00011420_CAIResourceManager_GetActionPtrFromHandle(); /* call 0x00011420 */

loc_003F5502:
    esi = eax;
    if (TEST_Z(esi, esi)) goto loc_003F5514; /* je: equal / zero */

loc_003F5508:
    ecx = MEM32(esi + 0x11C);
    MEM32(esp + 0xC) = ecx;
    goto loc_003F551C;

loc_003F5514:
    MEM32(esp + 0xC) = 0;

loc_003F551C:
    eax = MEM32(esp + 0xC);
    if (TEST_Z(eax, eax)) goto loc_003F5581; /* je: equal / zero */

loc_003F5524:
    edx = MEM32(ebx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, edi);
    PUSH32(esp, 0x62);
    eax = esp + 0x1C;
    PUSH32(esp, eax);
    ecx = ebx;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xB0), _icall_esp); /* indirect call */
    }

loc_003F5538:
    edx = MEM32(esp + 0x14);
    ecx = MEM32(esp + 0x10);
    MEM32(edi + 0x70) = edx;
    MEM32(edi + 0x68) = MEM32(edi + 0x68) & 0xFFFFFFDFu;
    edx = MEM32(esp + 0xC);
    MEM32(edi + 0x6C) = ecx;
    PUSH32(esp, 0); fn_000184E0_CAICellEdge_IsLowerCoverOrWindow(); /* call 0x000184E0 */

loc_003F5553:
    (void)0; /* test LO8(eax), LO8(eax) - flags set for next jcc */
    eax = MEM32(edi + 0x74);
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_003F555F; /* je: equal / zero */

loc_003F555A:
    eax = eax | 2;
    goto loc_003F5562;

loc_003F555F:
    eax = eax | 1;

loc_003F5562:
    MEM32(edi + 0x74) = eax;
    esi = esi + 0x110;
    eax = MEM32(esi);
    ecx = MEM32(esi + 4);
    edx = MEM32(esi + 8);
    MEM32(esp + 0x18) = eax;
    MEM32(esp + 0x1C) = ecx;
    MEM32(esp + 0x20) = edx;
    goto loc_003F558E;

loc_003F5581:
    if (TEST_Z(esi, esi)) goto loc_003F558E; /* je: equal / zero */

loc_003F5585:
    eax = MEM32(esi);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    ecx = esi;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x1C), _icall_esp); /* indirect call */
    }

loc_003F558E:
    esi = esp + 0xB8;
    MEM32(esp + 0x19C) = 0xFFFFFFFFu;
    PUSH32(esp, 0); fn_0002CE70_VCKOH_FactionControlData_ZeroList_RemoveAll(); /* call 0x0002CE70 */

loc_003F55A5:
    eax = MEM32(edi + 0x68);
    if (TEST_Z(LO8(eax), 0x20)) goto loc_003F5640; /* je: equal / zero */

loc_003F55B0:
    if (TEST_NZ(HI8(eax), 1)) goto loc_003F5640; /* jne: not equal / not zero */

loc_003F55B9:
    if (TEST_Z(LO8(eax), 4)) goto loc_003F55C4; /* je: equal / zero */

loc_003F55BD:
    xmm0 = MEMF(edi + 0x54); /* movss */
    goto loc_003F55CC;

loc_003F55C4:
    xmm0 = MEMF(0x5616A0); /* movss */

loc_003F55CC:
    eax = MEM32(edi + 0x5C);
    ecx = 0; /* xor self */
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    esi = esi | 0xFFFFFFFFu;
    (void)0; /* cmp eax, 1 - flags set for next jcc */
    SET_LO8(edx, (CMP_EQ(eax, 1)) ? 1 : 0); /* sete */
    (void)0; /* test eax, eax - flags set for next jcc */
    SET_LO8(eax, (TEST_Z(eax, eax)) ? 1 : 0); /* sete */
    MEMF(esp + 0x14) = xmm0; /* movss */
    PUSH32(esp, edx);
    edx = MEM32(esp + 0x18);
    PUSH32(esp, eax);
    PUSH32(esp, ecx);
    PUSH32(esp, 1);
    PUSH32(esp, 1);
    PUSH32(esp, edx);
    PUSH32(esp, 0xC);
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    PUSH32(esp, 1);
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    PUSH32(esp, esi);
    eax = esp + 0xE8;
    PUSH32(esp, eax);
    ecx = edi + 0x44;
    eax = ebx;
    PUSH32(esp, 0); fn_0001B790_0CAISoldierGetLOSActionSetup_QAE_PAVCAISoldier_PAVZeroVector3_VCAIActionHandle_0M_NPAV3_1133113W4TMovePosture_M3333333_Z(); /* call 0x0001B790 */

loc_003F5615:
    ecx = esp + 0x90;
    PUSH32(esp, ecx);
    edx = esp + 0x14;
    PUSH32(esp, edx);
    PUSH32(esp, 0x5FB008);
    PUSH32(esp, 0); fn_0001C130_AllocAction_VCAISoldierGetLOSAction_VCAISoldierGetLOSActionSetup_CAIResourceManager_IAE_AVCAIActionHandle_PAVCAISoldierGetLOSAction_PAVCAISoldierGetLOSActionSetup_Z(); /* call 0x0001C130 */

loc_003F562C:
    eax = MEM32(ebx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, edi);
    PUSH32(esp, 0x62);
    ecx = esp + 0x1C;
    PUSH32(esp, ecx);
    ecx = ebx;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0xB0), _icall_esp); /* indirect call */
    }

loc_003F5640:
    eax = MEM32(edi + 0x74);
    if (TEST_Z(LO8(eax), 1)) { sub_003F5723(); return; } /* je: equal / zero */

loc_003F564B:
    ecx = MEM32(edi + 0x5C);
    if (TEST_NZ(ecx, ecx)) { sub_003F5723(); return; } /* jne: not equal / not zero */

loc_003F5656:
    eax = MEM32(edi + 0x68);
    if (TEST_Z(LO8(eax), 4)) { sub_003F5664(); return; } /* je: equal / zero */

loc_003F565D:
    xmm0 = MEMF(edi + 0x54); /* movss */
    g_seh_ebp = ebp; sub_003F566C(); return; /* tail jmp 0x003F566C */

}

/**
 * sub_003F5664
 * Original: 0x003F5664 - 0x003F566C (8 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F5664(void)
{
    float xmm0;

loc_003F5664:
    xmm0 = MEMF(0x5616A0); /* movss */

}

/**
 * sub_003F566C
 * Original: 0x003F566C - 0x003F5723 (183 bytes, 67 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F566C(void)
{
    uint32_t ebp;
    float xmm0;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F566C:
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 1);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 1);
    PUSH32(esp, 0x3F800000);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    edx = eax;
    edx = edx >> 6;
    edx = edx & 0xFFFFFF01u;
    PUSH32(esp, edx);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0xFFFFFFFFu);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    edx = eax;
    MEMF(esp + 0x7C) = xmm0; /* movss */
    ecx = MEM32(esp + 0x7C);
    PUSH32(esp, ecx);
    PUSH32(esp, 0);
    eax = eax >> 1;
    edx = edx >> 3;
    eax = eax & 0xFFFFFF01u;
    edx = edx & 0xFFFFFF01u;
    PUSH32(esp, edx);
    PUSH32(esp, eax);
    PUSH32(esp, 1);
    PUSH32(esp, 1);
    eax = 0; /* xor self */
    SET_LO8(eax, MEM8(edi + 0x68));
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    PUSH32(esp, 0);
    ecx = edi + 0x44;
    edx = esp + 0x124;
    eax = eax & 0xFFFFFF01u;
    PUSH32(esp, eax);
    PUSH32(esp, 1);
    PUSH32(esp, ecx);
    PUSH32(esp, edx);
    ecx = esp + 0xBC;
    eax = ebx;
    PUSH32(esp, 0); fn_00013D00_0CAISoldierFireActionSetup_QAE_PAVCAISoldier_ABVZeroVector3_W4TMode_1_NPA_NMPAV2_3333PAVCAICellEdge_M5W4TBulletType_333333W4WEAPON_TYPE_3HW4TFiring_3333333M33MPAVCAIAct(); /* call 0x00013D00 */

loc_003F5703:
    eax = esp + 0x90;
    PUSH32(esp, eax);
    ecx = esp + 0x14;
    PUSH32(esp, ecx);
    PUSH32(esp, 0x5FB008);
    PUSH32(esp, 0); fn_00016260_AllocAction_VCAISoldierFireAction_VCAISoldierFireActionSetup_CAIResourceManager_IAE_AVCAIActionHandle_PAVCAISoldierFireAction_PAVCAISoldierFireActionSetup_Z(); /* call 0x00016260 */

loc_003F571A:
    eax = esp + 0x10;
    g_seh_ebp = ebp; sub_003F5917(); return; /* tail jmp 0x003F5917 */

}

/**
 * sub_003F5723
 * Original: 0x003F5723 - 0x003F5742 (31 bytes, 10 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F5723(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F5723:
    if (TEST_Z(LO8(eax), 2)) { sub_003F57FB(); return; } /* je: equal / zero */

loc_003F572B:
    eax = MEM32(edi + 0x5C);
    if (TEST_NZ(eax, eax)) { sub_003F57FB(); return; } /* jne: not equal / not zero */

loc_003F5736:
    eax = MEM32(edi + 0x68);
    if (((int32_t)(LO8(eax) & LO8(eax)) >= 0)) { sub_003F5742(); return; } /* jns: not sign (positive) */

loc_003F573D:
    esi = MEM32(edi + 0x60);
    g_seh_ebp = ebp; sub_003F5744(); return; /* tail jmp 0x003F5744 */

}

/**
 * sub_003F5742
 * Original: 0x003F5742 - 0x003F5744 (2 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F5742(void)
{

loc_003F5742:
    esi = 0; /* xor self */

}

/**
 * sub_003F5744
 * Original: 0x003F5744 - 0x003F574F (11 bytes, 4 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F5744(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F5744:
    if (TEST_Z(LO8(eax), 4)) { sub_003F574F(); return; } /* je: equal / zero */

loc_003F5748:
    xmm0 = MEMF(edi + 0x54); /* movss */
    g_seh_ebp = ebp; sub_003F5757(); return; /* tail jmp 0x003F5757 */

}

/* Fallback for unresolved generated target 0x003F574F. */
void sub_003F574F(void)
{
    recomp_missing_target(0x003F574Fu);
}

/* Fallback for unresolved generated target 0x003F5757. */
void sub_003F5757(void)
{
    recomp_missing_target(0x003F5757u);
}

/**
 * sub_003F57FB
 * Original: 0x003F57FB - 0x003F580B (16 bytes, 6 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F57FB(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F57FB:
    eax = MEM32(edi + 0x68);
    if (((int32_t)(LO8(eax) & LO8(eax)) >= 0)) { sub_003F580B(); return; } /* jns: not sign (positive) */

loc_003F5802:
    ecx = MEM32(edi + 0x60);
    MEM32(esp + 0xC) = ecx;
    g_seh_ebp = ebp; sub_003F5813(); return; /* tail jmp 0x003F5813 */

}

/**
 * sub_003F580B
 * Original: 0x003F580B - 0x003F5813 (8 bytes, 1 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F580B(void)
{

loc_003F580B:
    MEM32(esp + 0xC) = 0;

}

/**
 * sub_003F5813
 * Original: 0x003F5813 - 0x003F5831 (30 bytes, 10 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F5813(void)
{
    uint32_t ebp;
    int _flags = 0; /* fallback flag var */
    float xmm0;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F5813:
    if (TEST_Z(LO8(eax), 0x20)) goto loc_003F5821; /* je: equal / zero */

loc_003F5817:
    (void)0; /* test HI8(eax), 1 - flags set for next jcc */
    MEM8(esp + 0x18) = 1;
    if (TEST_NZ(HI8(eax), 1)) goto loc_003F5826; /* jne: not equal / not zero */

loc_003F5821:
    MEM8(esp + 0x18) = 0;

loc_003F5826:
    if (TEST_Z(LO8(eax), 4)) { sub_003F5831(); return; } /* je: equal / zero */

loc_003F582A:
    xmm0 = MEMF(edi + 0x54); /* movss */
    g_seh_ebp = ebp; sub_003F5839(); return; /* tail jmp 0x003F5839 */

}

/* Fallback for unresolved generated target 0x003F5831. */
void sub_003F5831(void)
{
    recomp_missing_target(0x003F5831u);
}

/* Fallback for unresolved generated target 0x003F5839. */
void sub_003F5839(void)
{
    recomp_missing_target(0x003F5839u);
}

/**
 * sub_003F5917
 * Original: 0x003F5917 - 0x003F593E (39 bytes, 16 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_003F5917(void)
{
    uint32_t ebp;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_003F5917:
    edx = MEM32(ebx);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, edi);
    PUSH32(esp, 0x63);
    ecx = ebx;
    PUSH32(esp, eax);
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx + 0xB0), _icall_esp); /* indirect call */
    }

loc_003F5927:
    ecx = MEM32(esp + 0x194);
    POP32(esp, edi);
    POP32(esp, esi);
    SET_LO8(eax, 1);
    MEM32(0) = ecx;
    POP32(esp, ebx);
    esp = ebp;
    POP32(esp, ebp);
    esp += 4; return; /* ret */

}
