/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/script/behaviors/cchangereserves.c
 * Functions: 12
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_0003BE10_CChangeReserves_GetDebugName
 * Symbol: ?GetDebugName@CChangeReserves@@UBEPBDXZ
 * Original: 0x0003BE10 - 0x0003BE16 (6 bytes, 2 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0003BE10_CChangeReserves_GetDebugName(void)
{

loc_0003BE10:
    eax = 0x54C948;
    esp += 4; return; /* ret */

}

/**
 * fn_0003BE20_VCChangeReserves_CBehaviorFactoryT_CreateObject
 * Symbol: ?CreateObject@?$CBehaviorFactoryT@VCChangeReserves@@@@UAEPAVCScript@@VCRC@@_N@Z
 * Original: 0x0003BE20 - 0x0003BE8F (111 bytes, 39 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0003BE20_VCChangeReserves_CBehaviorFactoryT_CreateObject(void)
{
    float xmm0;

loc_0003BE20:
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ecx);
    edx = MEM32(0x6135C8);
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    eax = esp + 8;
    PUSH32(esp, eax);
    ebx = 0; /* xor self */
    PUSH32(esp, 0x74);
    ecx = 0x6135C8;
    MEM32(esp + 0x10) = ebx;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx), _icall_esp); /* indirect call */
    }

loc_0003BE3D:
    esi = eax;
    eax = MEM32(esp + 8);
    MEM32(esi + 4) = eax;
    eax = esi;
    PUSH32(esp, 0); fn_00214550_0CBehavior_QAE_XZ(); /* call 0x00214550 */

loc_0003BE4D:
    ecx = MEM32(esp + 0x14);
    xmm0 = 0.0f; /* xorps self = zero */
    edx = MEM32(esp + 0x10);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    MEM32(esi) = 0x54C888;
    MEM32(esi + 0x10) = 0x54C874;
    MEM32(esi + 0x6C) = ebx;
    MEMF(esi + 0x70) = xmm0; /* movss */
    MEM32(esi + 0x60) = ebx;
    eax = esp;
    MEM32(esi + 0x68) = ebx;
    MEM8(esi + 0x64) = LO8(ebx);
    MEM32(eax) = edx;
    eax = MEM32(esi);
    ecx = esi;
    MEM32(esp + 0x1C) = esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x5C), _icall_esp); /* indirect call */
    }

loc_0003BE87:
    eax = esi;
    POP32(esp, esi);
    POP32(esp, ebx);
    POP32(esp, ecx);
    esp += 12; return; /* ret 8 */

}

/**
 * fn_0003BE90_RegisterScriptAction_VCChangeReserves_YA_AVCRC_P8CChangeReserves_AE_NXZV0_Z
 * Symbol: ??$RegisterScriptAction@VCChangeReserves@@@@YA?AVCRC@@P8CChangeReserves@@AE_NXZV0@@Z
 * Original: 0x0003BE90 - 0x0003BF24 (148 bytes, 51 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0003BE90_RegisterScriptAction_VCChangeReserves_YA_AVCRC_P8CChangeReserves_AE_NXZV0_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_0003BE90:
    PUSH32(esp, ecx);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x14);
    PUSH32(esp, ecx);
    eax = esp;
    MEM32(esp + 8) = esp;
    MEM32(eax) = esi;
    PUSH32(esp, 0); fn_002047A0_CScriptManager_Get(); /* call 0x002047A0 */

loc_0003BEA4:
    PUSH32(esp, 0); fn_00037210_CScriptManager_GetCallback(); /* call 0x00037210 */

loc_0003BEA9:
    if (TEST_NZ(eax, eax)) goto loc_0003BF1D; /* jne: not equal / not zero */

loc_0003BEAD:
    eax = MEM32(0x5F9E40);
    if (TEST_NZ(eax, eax)) goto loc_0003BEC2; /* jne: not equal / not zero */

loc_0003BEB6:
    PUSH32(esp, 0x10);
    PUSH32(esp, 0); fn_0009E3F2_malloc(); /* call 0x0009E3F2 */

loc_0003BEBD:
    esp = esp + 4;
    goto loc_0003BEDC;

loc_0003BEC2:
    eax = MEM32(0x6135C8);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, 0x10);
    ecx = 0x6135C8;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax), _icall_esp); /* indirect call */
    }

loc_0003BED2:
    if (TEST_NZ(eax, eax)) goto loc_0003BEE0; /* jne: not equal / not zero */

loc_0003BED6:
    MEM32(eax) = 0x12345678;

loc_0003BEDC:
    if (TEST_Z(eax, eax)) goto loc_0003BEF9; /* je: equal / zero */

loc_0003BEE0:
    ecx = MEM32(esp + 0xC);
    edx = MEM32(esp + 0x10);
    MEM32(eax + 4) = esi;
    MEM32(eax) = 0x54BF40;
    MEM32(eax + 8) = ecx;
    MEM32(eax + 0xC) = edx;
    goto loc_0003BEFB;

loc_0003BEF9:
    eax = 0; /* xor self */

loc_0003BEFB:
    MEM32(esp + 0x14) = esi;
    MEM32(esp + 4) = eax;
    PUSH32(esp, 0); fn_002047A0_CScriptManager_Get(); /* call 0x002047A0 */

loc_0003BF08:
    ecx = esp + 0x14;
    PUSH32(esp, ecx);
    edx = esp + 8;
    PUSH32(esp, edx);
    eax = eax + 0x160;
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_000366F0_PAVCUITexture_ZeroTree_Insert(); /* call 0x000366F0 */

loc_0003BF1D:
    MEM32(edi) = esi;
    eax = edi;
    POP32(esp, esi);
    POP32(esp, ecx);
    esp += 4; return; /* ret */

}

/**
 * fn_0039ED30_CChangeReserves_Setup
 * Symbol: ?Setup@CChangeReserves@@MAE_NXZ
 * Original: 0x0039ED30 - 0x0039ED33 (3 bytes, 2 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0039ED30_CChangeReserves_Setup(void)
{

loc_0039ED30:
    SET_LO8(eax, 1);
    esp += 4; return; /* ret */

}

/**
 * fn_0039ED40_CChangeReserves_ParseLine
 * Symbol: ?ParseLine@CChangeReserves@@UAEXPBDPAD@Z
 * Original: 0x0039ED40 - 0x0039ED83 (67 bytes, 25 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0039ED40_CChangeReserves_ParseLine(void)
{
    int _flags = 0; /* fallback flag var */

loc_0039ED40:
    eax = MEM32(esp + 8);
    PUSH32(esp, esi);
    esi = MEM32(esp + 8);
    PUSH32(esp, edi);
    PUSH32(esp, eax);
    PUSH32(esp, esi);
    edi = ecx;
    PUSH32(esp, 0); fn_00214340_CBehavior_ParseLine(); /* call 0x00214340 */

loc_0039ED53:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54C2A8);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_0039ED5E:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) { sub_0039ED83(); return; } /* jne: not equal / not zero */

loc_0039ED65:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_0039ED6E:
    ecx = eax;
    eax = 0; /* xor self */
    if (TEST_Z(ecx, ecx)) goto loc_0039ED7B; /* je: equal / zero */

loc_0039ED76:
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_0039ED7B:
    MEM32(edi + 0x60) = eax;
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

}

/**
 * sub_0039ED83
 * Original: 0x0039ED83 - 0x0039EDB6 (51 bytes, 19 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0039ED83(void)
{
    int _flags = 0; /* fallback flag var */
    int _cf = 0; /* carry flag */

loc_0039ED83:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54C59C);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_0039ED8E:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) { sub_0039EDB6(); return; } /* jne: not equal / not zero */

loc_0039ED95:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_0039ED9E:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB68_atol(); /* call 0x0009BB68 */

loc_0039EDA4:
    esp = esp + 4;
    eax--;
    eax = (uint32_t)(-(int32_t)eax);
    SET_LO8(eax, _cf ? 0xFFFFFFFF : 0); /* sbb self (CF extend) */
    SET_LO8(eax, LO8(eax) + 1);
    MEM8(edi + 0x64) = LO8(eax);
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

}

/**
 * sub_0039EDB6
 * Original: 0x0039EDB6 - 0x0039EDE2 (44 bytes, 15 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0039EDB6(void)
{
    int _flags = 0; /* fallback flag var */

loc_0039EDB6:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54C594);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_0039EDC1:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) { sub_0039EDE2(); return; } /* jne: not equal / not zero */

loc_0039EDC8:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_0039EDD1:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB68_atol(); /* call 0x0009BB68 */

loc_0039EDD7:
    esp = esp + 4;
    MEM32(edi + 0x68) = eax;
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

}

/**
 * sub_0039EDE2
 * Original: 0x0039EDE2 - 0x0039EE0E (44 bytes, 15 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0039EDE2(void)
{
    int _flags = 0; /* fallback flag var */

loc_0039EDE2:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54C900);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_0039EDED:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) { sub_0039EE0E(); return; } /* jne: not equal / not zero */

loc_0039EDF4:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_0039EDFD:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB68_atol(); /* call 0x0009BB68 */

loc_0039EE03:
    esp = esp + 4;
    MEM32(edi + 0x6C) = eax;
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

}

/**
 * sub_0039EE0E
 * Original: 0x0039EE0E - 0x0039EE3A (44 bytes, 15 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0039EE0E(void)
{
    int _flags = 0; /* fallback flag var */
    double _fp_stack[8];
    int _fp_top = 0;
    #define fp_push(v) (_fp_stack[--_fp_top & 7] = (v))
    #define fp_pop() (_fp_top++)
    #define fp_popp() (fp_pop())
    #define fp_top() _fp_stack[_fp_top & 7]
    #define fp_st1() _fp_stack[(_fp_top + 1) & 7]

loc_0039EE0E:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54C8F0);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_0039EE19:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) goto loc_0039EE35; /* jne: not equal / not zero */

loc_0039EE20:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_0039EE29:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB16_atof(); /* call 0x0009BB16 */

loc_0039EE2F:
    MEMF(edi + 0x70) = (float)fp_top(); fp_popp(); /* fstp */
    esp = esp + 4;

loc_0039EE35:
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

    #undef fp_push
    #undef fp_pop
    #undef fp_popp
    #undef fp_top
    #undef fp_st1
}

/**
 * fn_0039EE40_CChangeReserves_OnStart
 * Symbol: ?OnStart@CChangeReserves@@QAE_NXZ
 * Original: 0x0039EE40 - 0x0039EEC9 (137 bytes, 51 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0039EE40_CChangeReserves_OnStart(void)
{
    int _flags = 0; /* fallback flag var */
    float xmm0;

loc_0039EE40:
    PUSH32(esp, ecx);
    PUSH32(esp, esi);
    PUSH32(esp, ecx);
    esi = ecx;
    ecx = MEM32(esi + 0x60);
    eax = esp;
    MEM32(esp + 8) = esp;
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_0029F2C0_CFactionManager_Get(); /* call 0x0029F2C0 */

loc_0039EE55:
    ecx = eax;
    PUSH32(esp, 0); fn_0029F210_CFactionManager_GetFaction(); /* call 0x0029F210 */

loc_0039EE5C:
    if (TEST_Z(eax, eax)) goto loc_0039EEC4; /* je: equal / zero */

loc_0039EE60:
    SET_LO8(ecx, MEM8(esi + 0x64));
    if (TEST_Z(LO8(ecx), LO8(ecx))) goto loc_0039EE76; /* je: equal / zero */

loc_0039EE67:
    ecx = MEM32(esi + 0x68);
    if (CMP_GE(ecx & ecx, 0)) goto loc_0039EE71; /* jge: greater or equal (signed >=) */

loc_0039EE6E:
    ecx = ecx | 0xFFFFFFFFu;

loc_0039EE71:
    MEM32(eax + 0x40) = ecx;
    goto loc_0039EE8F;

loc_0039EE76:
    ecx = MEM32(eax + 0x40);
    if (CMP_LE(ecx, 0xFFFFFFFFu)) goto loc_0039EE8F; /* jle: less or equal (signed <=) */

loc_0039EE7E:
    edx = MEM32(esi + 0x68);
    ecx = ecx + edx;
    MEM32(eax + 0x40) = ecx;
    if (((int32_t)ecx >= 0)) goto loc_0039EE8F; /* jns: not sign (positive) */

loc_0039EE88:
    MEM32(eax + 0x40) = 0;

loc_0039EE8F:
    PUSH32(esp, 0); fn_00184970_CSpawnManager_Get(); /* call 0x00184970 */

loc_0039EE94:
    eax = MEM32(eax + 8);
    if (TEST_Z(eax, eax)) goto loc_0039EEC4; /* je: equal / zero */

loc_0039EE9B:
    goto loc_0039EEA0;

    /* nop */

loc_0039EEA0:
    ecx = MEM32(eax + 0x18);
    if (CMP_NE(ecx, MEM32(esi + 0x60))) goto loc_0039EEBD; /* jne: not equal / not zero */

loc_0039EEA8:
    edx = MEM32(esi + 0x6C);
    MEM32(eax + 0x1C) = edx;
    xmm0 = MEMF(esi + 0x70); /* movss */
    MEMF(eax + 0x20) = xmm0; /* movss */
    MEMF(eax + 0x24) = xmm0; /* movss */

loc_0039EEBD:
    eax = MEM32(eax + 0x60);
    if (TEST_NZ(eax, eax)) goto loc_0039EEA0; /* jne: not equal / not zero */

loc_0039EEC4:
    SET_LO8(eax, 0); /* xor self */
    POP32(esp, esi);
    POP32(esp, ecx);
    esp += 4; return; /* ret */

}

/**
 * fn_0039EED0_CChangeReserves_OnActivate
 * Symbol: ?OnActivate@CChangeReserves@@MAEX_N@Z
 * Original: 0x0039EED0 - 0x0039EEE0 (16 bytes, 5 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0039EED0_CChangeReserves_OnActivate(void)
{
    int _flags = 0; /* fallback flag var */

loc_0039EED0:
    SET_LO8(eax, MEM8(esp + 4));
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_0039EEDD; /* je: equal / zero */

loc_0039EED8:
    PUSH32(esp, 0); fn_0039EE40_CChangeReserves_OnStart(); /* call 0x0039EE40 */

loc_0039EEDD:
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0039EEE0_0CChangeReserves_QAE_XZ
 * Symbol: ??0CChangeReserves@@QAE@XZ
 * Original: 0x0039EEE0 - 0x0039EF0D (45 bytes, 13 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0039EEE0_0CChangeReserves_QAE_XZ(void)
{
    float xmm0;

loc_0039EEE0:
    eax = esi;
    PUSH32(esp, 0); fn_00214550_0CBehavior_QAE_XZ(); /* call 0x00214550 */

loc_0039EEE7:
    xmm0 = 0.0f; /* xorps self = zero */
    eax = 0; /* xor self */
    MEM32(esi + 0x6C) = eax;
    MEM32(esi) = 0x54C888;
    MEM32(esi + 0x10) = 0x54C874;
    MEMF(esi + 0x70) = xmm0; /* movss */
    MEM32(esi + 0x60) = eax;
    MEM32(esi + 0x68) = eax;
    MEM8(esi + 0x64) = LO8(eax);
    eax = esi;
    esp += 4; return; /* ret */

}
