/**
 * Auto-generated by split_recomp_by_object.py
 * Object source: fsw/script/behaviors/cchangemaxspawn.c
 * Functions: 9
 */

#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <math.h>

/**
 * fn_0003BD00_CChangeMaxSpawn_GetDebugName
 * Symbol: ?GetDebugName@CChangeMaxSpawn@@UBEPBDXZ
 * Original: 0x0003BD00 - 0x0003BD06 (6 bytes, 2 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0003BD00_CChangeMaxSpawn_GetDebugName(void)
{

loc_0003BD00:
    eax = 0x54C860;
    esp += 4; return; /* ret */

}

/**
 * fn_0003BD10_VCChangeMaxSpawn_CBehaviorFactoryT_CreateObject
 * Symbol: ?CreateObject@?$CBehaviorFactoryT@VCChangeMaxSpawn@@@@UAEPAVCScript@@VCRC@@_N@Z
 * Original: 0x0003BD10 - 0x0003BD6B (91 bytes, 30 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0003BD10_VCChangeMaxSpawn_CBehaviorFactoryT_CreateObject(void)
{

loc_0003BD10:
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ecx);
    edx = MEM32(0x6135C8);
    PUSH32(esp, esi);
    eax = esp + 4;
    PUSH32(esp, eax);
    PUSH32(esp, 0x68);
    ecx = 0x6135C8;
    MEM32(esp + 0xC) = 0;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(edx), _icall_esp); /* indirect call */
    }

loc_0003BD2E:
    esi = eax;
    eax = MEM32(esp + 4);
    MEM32(esi + 4) = eax;
    eax = esi;
    PUSH32(esp, 0); fn_00214550_0CBehavior_QAE_XZ(); /* call 0x00214550 */

loc_0003BD3E:
    ecx = MEM32(esp + 0x10);
    edx = MEM32(esp + 0xC);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, ecx);
    PUSH32(esp, ecx);
    eax = esp;
    MEM32(esi) = 0x54C7B0;
    MEM32(esi + 0x10) = 0x54C79C;
    MEM32(eax) = edx;
    eax = MEM32(esi);
    ecx = esi;
    MEM32(esp + 0x18) = esp;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax + 0x5C), _icall_esp); /* indirect call */
    }

loc_0003BD64:
    eax = esi;
    POP32(esp, esi);
    POP32(esp, ecx);
    esp += 12; return; /* ret 8 */

}

/**
 * fn_0003BD70_RegisterScriptAction_VCChangeMaxSpawn_YA_AVCRC_P8CChangeMaxSpawn_AE_NXZV0_Z
 * Symbol: ??$RegisterScriptAction@VCChangeMaxSpawn@@@@YA?AVCRC@@P8CChangeMaxSpawn@@AE_NXZV0@@Z
 * Original: 0x0003BD70 - 0x0003BE04 (148 bytes, 51 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0003BD70_RegisterScriptAction_VCChangeMaxSpawn_YA_AVCRC_P8CChangeMaxSpawn_AE_NXZV0_Z(void)
{
    int _flags = 0; /* fallback flag var */

loc_0003BD70:
    PUSH32(esp, ecx);
    PUSH32(esp, esi);
    esi = MEM32(esp + 0x14);
    PUSH32(esp, ecx);
    eax = esp;
    MEM32(esp + 8) = esp;
    MEM32(eax) = esi;
    PUSH32(esp, 0); fn_002047A0_CScriptManager_Get(); /* call 0x002047A0 */

loc_0003BD84:
    PUSH32(esp, 0); fn_00037210_CScriptManager_GetCallback(); /* call 0x00037210 */

loc_0003BD89:
    if (TEST_NZ(eax, eax)) goto loc_0003BDFD; /* jne: not equal / not zero */

loc_0003BD8D:
    eax = MEM32(0x5F9E40);
    if (TEST_NZ(eax, eax)) goto loc_0003BDA2; /* jne: not equal / not zero */

loc_0003BD96:
    PUSH32(esp, 0x10);
    PUSH32(esp, 0); fn_0009E3F2_malloc(); /* call 0x0009E3F2 */

loc_0003BD9D:
    esp = esp + 4;
    goto loc_0003BDBC;

loc_0003BDA2:
    eax = MEM32(0x6135C8);
    { uint32_t _icall_esp = g_esp;
    PUSH32(esp, 0);
    PUSH32(esp, 0x10);
    ecx = 0x6135C8;
    PUSH32(esp, 0); RECOMP_ICALL_SAFE(MEM32(eax), _icall_esp); /* indirect call */
    }

loc_0003BDB2:
    if (TEST_NZ(eax, eax)) goto loc_0003BDC0; /* jne: not equal / not zero */

loc_0003BDB6:
    MEM32(eax) = 0x12345678;

loc_0003BDBC:
    if (TEST_Z(eax, eax)) goto loc_0003BDD9; /* je: equal / zero */

loc_0003BDC0:
    ecx = MEM32(esp + 0xC);
    edx = MEM32(esp + 0x10);
    MEM32(eax + 4) = esi;
    MEM32(eax) = 0x54BF40;
    MEM32(eax + 8) = ecx;
    MEM32(eax + 0xC) = edx;
    goto loc_0003BDDB;

loc_0003BDD9:
    eax = 0; /* xor self */

loc_0003BDDB:
    MEM32(esp + 0x14) = esi;
    MEM32(esp + 4) = eax;
    PUSH32(esp, 0); fn_002047A0_CScriptManager_Get(); /* call 0x002047A0 */

loc_0003BDE8:
    ecx = esp + 0x14;
    PUSH32(esp, ecx);
    edx = esp + 8;
    PUSH32(esp, edx);
    eax = eax + 0x160;
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_000366F0_PAVCUITexture_ZeroTree_Insert(); /* call 0x000366F0 */

loc_0003BDFD:
    MEM32(edi) = esi;
    eax = edi;
    POP32(esp, esi);
    POP32(esp, ecx);
    esp += 4; return; /* ret */

}

/**
 * fn_0039EF10_CChangeMaxSpawn_Setup
 * Symbol: ?Setup@CChangeMaxSpawn@@MAE_NXZ
 * Original: 0x0039EF10 - 0x0039EF13 (3 bytes, 2 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0039EF10_CChangeMaxSpawn_Setup(void)
{

loc_0039EF10:
    SET_LO8(eax, 1);
    esp += 4; return; /* ret */

}

/**
 * fn_0039EF20_CChangeMaxSpawn_ParseLine
 * Symbol: ?ParseLine@CChangeMaxSpawn@@UAEXPBDPAD@Z
 * Original: 0x0039EF20 - 0x0039EF63 (67 bytes, 25 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0039EF20_CChangeMaxSpawn_ParseLine(void)
{
    int _flags = 0; /* fallback flag var */

loc_0039EF20:
    eax = MEM32(esp + 8);
    PUSH32(esp, esi);
    esi = MEM32(esp + 8);
    PUSH32(esp, edi);
    PUSH32(esp, eax);
    PUSH32(esp, esi);
    edi = ecx;
    PUSH32(esp, 0); fn_00214340_CBehavior_ParseLine(); /* call 0x00214340 */

loc_0039EF33:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54BB18);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_0039EF3E:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) { sub_0039EF63(); return; } /* jne: not equal / not zero */

loc_0039EF45:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_0039EF4E:
    ecx = eax;
    eax = 0; /* xor self */
    if (TEST_Z(ecx, ecx)) goto loc_0039EF5B; /* je: equal / zero */

loc_0039EF56:
    PUSH32(esp, 0); fn_00128D90_CalcLowerCRC(); /* call 0x00128D90 */

loc_0039EF5B:
    MEM32(edi + 0x60) = eax;
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

}

/**
 * sub_0039EF63
 * Original: 0x0039EF63 - 0x0039EF8F (44 bytes, 15 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void sub_0039EF63(void)
{
    int _flags = 0; /* fallback flag var */

loc_0039EF63:
    PUSH32(esp, esi);
    PUSH32(esp, 0x54C81C);
    PUSH32(esp, 0); fn_0009D4A0_stricmp(); /* call 0x0009D4A0 */

loc_0039EF6E:
    esp = esp + 8;
    if (TEST_NZ(eax, eax)) goto loc_0039EF8A; /* jne: not equal / not zero */

loc_0039EF75:
    esi = esp + 0x10;
    PUSH32(esp, 0); fn_00204D00_CScript_GetString(); /* call 0x00204D00 */

loc_0039EF7E:
    PUSH32(esp, eax);
    PUSH32(esp, 0); fn_0009BB68_atol(); /* call 0x0009BB68 */

loc_0039EF84:
    esp = esp + 4;
    MEM32(edi + 0x64) = eax;

loc_0039EF8A:
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 12; return; /* ret 8 */

}

/**
 * fn_0039EF90_CChangeMaxSpawn_OnStart
 * Symbol: ?OnStart@CChangeMaxSpawn@@QAE_NXZ
 * Original: 0x0039EF90 - 0x0039EFBD (45 bytes, 19 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0039EF90_CChangeMaxSpawn_OnStart(void)
{
    int _flags = 0; /* fallback flag var */

loc_0039EF90:
    PUSH32(esp, esi);
    PUSH32(esp, ecx);
    esi = ecx;
    ecx = MEM32(esi + 0x60);
    eax = esp;
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_00184970_CSpawnManager_Get(); /* call 0x00184970 */

loc_0039EFA0:
    ecx = eax;
    PUSH32(esp, 0); fn_00182CE0_CSpawnManager_FindEncounter(); /* call 0x00182CE0 */

loc_0039EFA7:
    if (TEST_Z(eax, eax)) goto loc_0039EFB9; /* je: equal / zero */

loc_0039EFAB:
    ecx = MEM32(esi + 0x64);
    (void)0; /* cmp MEM32(eax + 0x6C), ecx - flags set for next jcc */
    MEM32(eax + 0x68) = ecx;
    if (CMP_LE(MEM32(eax + 0x6C), ecx)) goto loc_0039EFB9; /* jle: less or equal (signed <=) */

loc_0039EFB6:
    MEM32(eax + 0x6C) = ecx;

loc_0039EFB9:
    SET_LO8(eax, 0); /* xor self */
    POP32(esp, esi);
    esp += 4; return; /* ret */

}

/**
 * fn_0039EFC0_CChangeMaxSpawn_OnActivate
 * Symbol: ?OnActivate@CChangeMaxSpawn@@MAEX_N@Z
 * Original: 0x0039EFC0 - 0x0039EFF5 (53 bytes, 21 insns)
 * Category: game_vtable
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0039EFC0_CChangeMaxSpawn_OnActivate(void)
{
    int _flags = 0; /* fallback flag var */

loc_0039EFC0:
    SET_LO8(eax, MEM8(esp + 4));
    (void)0; /* test LO8(eax), LO8(eax) - flags set for next jcc */
    PUSH32(esp, esi);
    esi = ecx;
    if (TEST_Z(LO8(eax), LO8(eax))) goto loc_0039EFF1; /* je: equal / zero */

loc_0039EFCB:
    PUSH32(esp, ecx);
    ecx = MEM32(esi + 0x60);
    eax = esp;
    MEM32(eax) = ecx;
    PUSH32(esp, 0); fn_00184970_CSpawnManager_Get(); /* call 0x00184970 */

loc_0039EFD8:
    ecx = eax;
    PUSH32(esp, 0); fn_00182CE0_CSpawnManager_FindEncounter(); /* call 0x00182CE0 */

loc_0039EFDF:
    if (TEST_Z(eax, eax)) goto loc_0039EFF1; /* je: equal / zero */

loc_0039EFE3:
    ecx = MEM32(esi + 0x64);
    (void)0; /* cmp MEM32(eax + 0x6C), ecx - flags set for next jcc */
    MEM32(eax + 0x68) = ecx;
    if (CMP_LE(MEM32(eax + 0x6C), ecx)) goto loc_0039EFF1; /* jle: less or equal (signed <=) */

loc_0039EFEE:
    MEM32(eax + 0x6C) = ecx;

loc_0039EFF1:
    POP32(esp, esi);
    esp += 8; return; /* ret 4 */

}

/**
 * fn_0039F000_0CChangeMaxSpawn_QAE_XZ
 * Symbol: ??0CChangeMaxSpawn@@QAE@XZ
 * Original: 0x0039F000 - 0x0039F017 (23 bytes, 6 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
void fn_0039F000_0CChangeMaxSpawn_QAE_XZ(void)
{

loc_0039F000:
    eax = esi;
    PUSH32(esp, 0); fn_00214550_0CBehavior_QAE_XZ(); /* call 0x00214550 */

loc_0039F007:
    MEM32(esi) = 0x54C7B0;
    MEM32(esi + 0x10) = 0x54C79C;
    eax = esi;
    esp += 4; return; /* ret */

}
